/**
 * Atomic Fact Store — Read-Only TypeScript Layer
 * ==============================================
 * Reads data/atomic-facts.json (generated by scripts/build-atomic-facts.py).
 * Provides type-safe query functions. No extraction logic here.
 */

import fs from "fs";
import path from "path";

// ============================================================================
// Types (mirrors data/schemas/atomic-fact.schema.json)
// ============================================================================

export type Subject = "history" | "planning" | "environment" | "construction";

export type EntityType =
  | "building" | "person" | "style" | "movement" | "term"
  | "formula" | "number" | "material" | "component" | "system"
  | "urban_plan" | "institution";

export type FactConfidence = "high" | "medium" | "low" | "candidate";
export type ReviewStatus = "unreviewed" | "confirmed" | "rejected" | "edited";

export interface AtomicFact {
  id: string;
  subject: Subject;
  entityType: EntityType;
  entityName: string;
  entityNameOriginal?: string;
  relation: string;
  value: string;
  valueType: "text" | "number" | "image_ref" | "html";
  sourceType: "anki" | "notion" | "past_exam" | "textbook";
  sourceId: string;
  sourceField: string;
  evidenceText: string;
  confidence: FactConfidence;
  reviewStatus: ReviewStatus;
  tags: string[];
  usableBlueprints: string[];
}

interface FactStore {
  version: number;
  generatedAt: string;
  totalFacts: number;
  facts: AtomicFact[];
}

// ============================================================================
// Load
// ============================================================================

let _store: FactStore | null = null;

function loadStore(): FactStore {
  if (_store) return _store;
  const p = path.resolve(process.cwd(), "data/atomic-facts.json");
  _store = JSON.parse(fs.readFileSync(p, "utf-8")) as FactStore;
  return _store;
}

// ============================================================================
// Query API
// ============================================================================

/** All confirmed facts (high + medium confidence, ready for question generation) */
export function getConfirmedFacts(subject?: Subject): AtomicFact[] {
  return loadStore().facts.filter((f) =>
    (f.confidence === "high" || f.confidence === "medium") &&
    (!subject || f.subject === subject)
  );
}

/** Facts by entity name (exact match) */
export function getFactsByEntity(name: string, subject?: Subject): AtomicFact[] {
  return loadStore().facts.filter((f) =>
    f.entityName === name && (!subject || f.subject === subject)
  );
}

/** Facts by relation type */
export function getFactsByRelation(relation: string, subject?: Subject): AtomicFact[] {
  return loadStore().facts.filter((f) =>
    f.relation === relation && (!subject || f.subject === subject)
  );
}

/** Facts that can generate a specific blueprint */
export function getFactsForBlueprint(blueprintId: string, subject?: Subject): AtomicFact[] {
  return loadStore().facts.filter((f) =>
    f.usableBlueprints.includes(blueprintId) &&
    f.confidence !== "candidate" &&
    (!subject || f.subject === subject)
  );
}

/** Entity names of a given type */
export function getEntityNames(entityType: EntityType, subject?: Subject): string[] {
  const names = new Set<string>();
  for (const f of loadStore().facts) {
    if (f.entityType === entityType && (!subject || f.subject === subject)) {
      names.add(f.entityName);
    }
  }
  return [...names].sort();
}

/** Facts with exam evidence */
export function getExamVerifiedFacts(subject?: Subject): AtomicFact[] {
  return loadStore().facts.filter((f) =>
    f.relation === "appears_in_exam" &&
    (!subject || f.subject === subject)
  );
}

/** Stats */
export function getFactStats() {
  const facts = loadStore().facts;
  const bySubject: Record<string, number> = {};
  const byConfidence: Record<string, number> = {};
  const byEntityType: Record<string, number> = {};
  const byRelation: Record<string, number> = {};

  for (const f of facts) {
    bySubject[f.subject] = (bySubject[f.subject] || 0) + 1;
    byConfidence[f.confidence] = (byConfidence[f.confidence] || 0) + 1;
    byEntityType[f.entityType] = (byEntityType[f.entityType] || 0) + 1;
    byRelation[f.relation] = (byRelation[f.relation] || 0) + 1;
  }

  return {
    total: facts.length,
    generatedAt: loadStore().generatedAt,
    bySubject,
    byConfidence,
    byEntityType,
    byRelation,
  };
}
