/**
 * Blueprint Registry — Read-Only TypeScript Layer
 * ================================================
 * Reads data/question-blueprints.json (generated by scripts/build-question-blueprints.py).
 * Provides type-safe blueprint queries. No discovery logic here.
 */

import fs from "fs";
import path from "path";

// ============================================================================
// Types
// ============================================================================

export type QuestionAction = "identify" | "match" | "fill_blank" | "select" | "calculate" | "explain";
export type AnswerType = "single_choice" | "multi_choice" | "fill_blank" | "free_recall" | "essay";

export interface BlueprintOccurrence {
  blueprintId: string;
  year: number;
  category: "専門1" | "専門2-2";
  questionNumber: string;
  originalForm: string;
}

export interface QuestionBlueprint {
  id: string;
  subject: string;
  name: string;
  questionAction: QuestionAction;
  requiredFactRelations: string[];
  promptTemplate: string;
  answerType: AnswerType;
  distractorStrategy: string;
  needsImage: boolean;
  validationRules: string[];
  occurrences: BlueprintOccurrence[];
  occurrenceCount: number;
  years: number[];
}

interface BlueprintStore {
  version: number;
  totalBlueprints: number;
  blueprints: QuestionBlueprint[];
}

// ============================================================================
// Load
// ============================================================================

let _store: BlueprintStore | null = null;

function loadStore(): BlueprintStore {
  if (_store) return _store;
  const p = path.resolve(process.cwd(), "data/question-blueprints.json");
  _store = JSON.parse(fs.readFileSync(p, "utf-8")) as BlueprintStore;
  return _store;
}

// ============================================================================
// Query API
// ============================================================================

export function getAllBlueprints(): QuestionBlueprint[] {
  return loadStore().blueprints;
}

export function getBlueprintsBySubject(subject: string): QuestionBlueprint[] {
  return loadStore().blueprints.filter((bp) => bp.subject === subject);
}

export function getBlueprintById(id: string): QuestionBlueprint | undefined {
  return loadStore().blueprints.find((bp) => bp.id === id);
}

/** Blueprints verified by at least one past exam occurrence */
export function getExamVerifiedBlueprints(subject?: string): QuestionBlueprint[] {
  return loadStore().blueprints.filter((bp) =>
    bp.occurrenceCount > 0 && (!subject || bp.subject === subject)
  );
}

/** Blueprints defined but not yet observed in real exams */
export function getUnverifiedBlueprints(subject?: string): QuestionBlueprint[] {
  return loadStore().blueprints.filter((bp) =>
    bp.occurrenceCount === 0 && (!subject || bp.subject === subject)
  );
}

/** Years a specific question action appears */
export function getYearsForAction(action: QuestionAction, subject?: string): number[] {
  const years = new Set<number>();
  for (const bp of loadStore().blueprints) {
    if (bp.questionAction === action && (!subject || bp.subject === subject)) {
      for (const occ of bp.occurrences) {
        years.add(occ.year);
      }
    }
  }
  return [...years].sort();
}

/** Stats */
export function getBlueprintStats() {
  const bps = loadStore().blueprints;
  const bySubject: Record<string, number> = {};
  const byAction: Record<string, number> = {};
  const byAnswerType: Record<string, number> = {};
  let verified = 0;
  let unverified = 0;

  for (const bp of bps) {
    bySubject[bp.subject] = (bySubject[bp.subject] || 0) + 1;
    byAction[bp.questionAction] = (byAction[bp.questionAction] || 0) + 1;
    byAnswerType[bp.answerType] = (byAnswerType[bp.answerType] || 0) + 1;
    if (bp.occurrenceCount > 0) verified++; else unverified++;
  }

  return {
    total: bps.length,
    verified,
    unverified,
    bySubject,
    byAction,
    byAnswerType,
  };
}
