import type{BuildingTypeLearningCard}from"@/types/history-learning-card";
const l=(ja:string,zh:string,en?:string)=>({ja,zh,...(en?{en}:{})});
type EnglishBuildingType={name:string;period:string;purpose:string;structure:string;space:string;evolution:string};
const ENGLISH_BY_ID:Record<string,EnglishBuildingType>={
  "type-machiya":{name:"Machiya",period:"Historical overview",purpose:"A combined shop, workplace, and dwelling lining urban streets.",structure:"Timber framing, a narrow frontage, deep plot, and a through passage",space:"Shop, living rooms, kitchen, and rear garden arranged sequentially from the street",evolution:"Regional forms developed from medieval towns to early-modern castle towns and commercial cities."},
  "type-minka":{name:"Minka",period:"Historical overview",purpose:"Vernacular houses adapted to the lives and productive activities of farming, forestry, and fishing communities.",structure:"Timber frames, earthen walls, and thatched roofs adapted to local materials and climate",space:"Earthen-floored and raised-floor areas organize work, domestic life, family, and livestock according to region.",evolution:"They diversified into regional types such as honmune-zukuri, gassho-zukuri, and magariya."},
  "type-castle":{name:"Castle Architecture",period:"Historical overview",purpose:"A military and political complex integrating defense, governance, residence, and the display of authority.",structure:"Stone ramparts, moats, earthen embankments, turrets, gates, and keeps forming layered defenses",space:"The honmaru, ninomaru, and other baileys are terraced to bend and control movement.",evolution:"It developed from medieval mountain castles into early-modern hirayamajiro, flatland castles, and castle towns."},
  "type-pit-dwelling":{name:"Pit Dwelling",period:"Prehistory–ancient period",purpose:"A dwelling type with a floor excavated below ground level, used widely from prehistory into the ancient period.",structure:"An excavated floor, posts, rafters, a roof of earth or plant material, and a hearth",space:"A single room integrates sleeping, work, and cooking.",evolution:"It developed from the basic dwelling of Jōmon and Yayoi settlements toward ground-level houses."},
  "type-moated-settlement":{name:"Moated Settlement",period:"Primarily the Yayoi period",purpose:"A settlement type enclosed by ditches to define defense, boundaries, and community.",structure:"Ditches, earthen embankments, gates, pit dwellings, and post-in-ground buildings",space:"Dwellings, stores, and ritual spaces are collectively arranged inside the enclosing ditches.",evolution:"It records settlement, defense, and social stratification in agricultural society and leads toward later urbanized settlements."},
  "type-southeast-asian-temple":{name:"Southeast Asian Hindu and Buddhist Temple",period:"Classical and medieval Southeast Asia",purpose:"Monumental religious architecture expressing Hindu cosmology and kingship, later also accommodating Buddhist practice.",structure:"Layered stone platforms, galleries, and gateway towers establish a rising axis toward the central sanctuary.",space:"A pilgrimage sequence advances from moat and outer gallery to the central sanctuary.",evolution:"Religious architecture of Indianized kingdoms fused with local materials and techniques, culminating in the monumental temple cities of the Angkor period."},
};
const c=(id:string,ja:string,zh:string,purpose:[string,string],structure:[string,string],space:[string,string],evolution:[string,string]):BuildingTypeLearningCard=>({id,kind:"building-type",name:l(ja,zh,ENGLISH_BY_ID[id]?.name),aliases:[],period:l("通史","通史",ENGLISH_BY_ID[id]?.period),regions:["japan"],summary:l(purpose[0],purpose[1],ENGLISH_BY_ID[id]?.purpose),functionalPurpose:l(purpose[0],purpose[1],ENGLISH_BY_ID[id]?.purpose),structuralFeatures:[l(structure[0],structure[1],ENGLISH_BY_ID[id]?.structure)],spatialFeatures:[l(space[0],space[1],ENGLISH_BY_ID[id]?.space)],evolution:[l(evolution[0],evolution[1],ENGLISH_BY_ID[id]?.evolution)],comparisonCardIds:[],keywords:[],relatedBuildingIds:[],relatedPersonIds:[],relatedCardIds:[],examEvidence:[],reviewStatus:"draft"});
export const BUILDING_TYPE_LEARNING_CARDS:BuildingTypeLearningCard[]=[
c("type-machiya","町家","町家",["都市の街路沿いで商業・生産と居住を兼ねる職住一体住宅。","沿城市街道兼具商业、生产与居住的职住一体住宅。"],["木造軸組、狭い間口、深い奥行き、通り庭。","木构架、窄面宽、深进深与通庭。"],["店—居室—台所—奥庭を街路から奥へ連ねる。","从街道向内依次组织店面、居室、厨房与后院。"],["中世都市から近世城下町・商業都市へ地域的形式が発達。","由中世城市发展至近世城下町和商业城市的地域形式。"]),
c("type-minka","民家","民居",["農林漁業など地域の生活と生産に対応した庶民住宅。","适应农林渔业等地域生活与生产的普通民众住宅。"],["木造架構、土壁、茅葺などを地域の材料と気候に合わせる。","以木构、土墙、茅葺等适应地方材料与气候。"],["土間と床上、作業と生活、家族と家畜を地域ごとに編成。","按地域组织土间与架高地板、生产与生活、家庭与牲畜空间。"],["本棟造、合掌造、曲家等の地域類型へ分化。","分化为本栋造、合掌造、曲家等地域类型。"]),
c("type-castle","城郭建築","城郭建筑",["防御、統治、居住、権威の表象を統合する軍事・政治的建築群。","整合防御、统治、居住与权威展示的军事政治建筑群。"],["石垣、堀、土塁、櫓、門、天守を多重防御線として構成。","以石垣、壕沟、土垒、橹、门和天守构成多重防线。"],["本丸・二の丸等の曲輪を階層化し、動線を屈曲させる。","分级组织本丸、二之丸等曲轮并使流线曲折。"],["中世山城から近世平山城・平城と城下町へ展開。","由中世山城发展至近世平山城、平城及城下町。"]),
c("type-pit-dwelling","竪穴住居","竖穴住居",["地面を掘り下げた床をもち、先史時代から古代まで広く用いられた住居形式。","通过下挖地面获得热环境和结构稳定的史前、古代住宅。"],["掘り込み床、柱、垂木、土や植物材で葺いた屋根、炉などを組み合わせる。","下挖地面、立柱、椽木、草葺屋顶与中央炉。"],["単室を中心に睡眠・作業・炊事を統合。","以单室整合睡眠、作业与炊事。"],["縄文・弥生集落の基本住居から平地式住居へ移行。","由绳文、弥生聚落基本住宅逐渐转向平地式住宅。"]),
c("type-moated-settlement","環壕集落","环壕聚落",["周囲に壕を巡らせ、防御・境界・共同体を表す弥生期中心の集落類型。","以环绕壕沟表现防御、边界与共同体的弥生时期聚落类型。"],["壕、土塁、門、竪穴住居、掘立柱建物を組み合わせる。","组合壕沟、土垒、门、竖穴住宅和掘立柱建筑。"],["住居・倉庫・祭祀空間を壕内で集団的に配置。","在壕内集中布置住宅、仓库和祭祀空间。"],["農耕社会の定住・防御・階層化を示し、後の都市的集住へ接続。","体现农业社会的定居、防御和阶层化，并连接后续城市性聚居。"]),
c("type-southeast-asian-temple","東南アジアのヒンドゥー・仏教寺院","东南亚印度教与佛教寺院",["ヒンドゥー教の宇宙観と王権を表象し、後に仏教的実践も受け入れた大規模宗教建築。","表现印度教宇宙观与王权、并在后世容纳佛教实践的大型宗教建筑。"],["石造の基壇・回廊・塔門を重層させ、中心祠堂へ上昇する軸線をつくる。","层叠石造台基、回廊和塔门，形成通向中心祠堂的上升轴线。"],["環濠・外周回廊から中心聖所へ段階的に進む巡礼的空間構成。","从环壕、外围回廊逐层进入中心圣所的朝圣式空间构成。"],["インド化した王国の宗教建築が地域の材料・技術と融合し、アンコール期に巨大な寺院都市へ展開。","印度化王国的宗教建筑与本地材料、技术融合，并在吴哥时期发展为巨型寺院城市。"]),
];
