export type ConstructionDistinction = {
  id: string;
  category: "木造" | "RC・PC" | "S造" | "外皮" | "基礎" | "構造" | "組積・材料";
  terms: string[];
  titleZh: string;
  titleJa: string;
  keyZh: string;
  keyJa: string;
  recognitionZh: string;
  recognitionJa: string;
  examForms: string[];
  imageStatus: "notion" | "past-exam" | "diagram-needed";
  notionUrl: string;
};

export type ConstructionExamEvidence = {
  level: "direct" | "related" | "foundation";
  references: string[];
  focusZh: string;
  focusJa: string;
};

export const constructionDistinctions: ConstructionDistinction[] = [
  {
    id: "separator-form-tie", category: "RC・PC", terms: ["セパレーター", "フォームタイ"],
    titleZh: "对拉杆与外侧紧固件", titleJa: "セパレーターとフォームタイ",
    keyZh: "セパレーター贯穿两侧模板并保持墙厚；フォームタイ位于模板外侧，连接端部并抵抗混凝土侧压力。",
    keyJa: "セパレーターは両側型枠の間隔、すなわち壁厚を保持する。フォームタイは型枠外側で端部を締め付け、コンクリート側圧による開きを防ぐ。",
    recognitionZh: "看位置：墙体内部的是セパレーター，模板外侧带紧固头的是フォームタイ。",
    recognitionJa: "位置で判別する。壁体内部を貫通するものがセパレーター、型枠外側の締付け金物がフォームタイ。",
    examForms: ["图解识别", "部材名称", "比较说明"], imageStatus: "notion", notionUrl: "https://app.notion.com/399e961e46908171816aceebecc0f746",
  },
  {
    id: "stirrup-hoop", category: "RC・PC", terms: ["あばら筋", "帯筋"],
    titleZh: "梁箍筋与柱箍筋", titleJa: "あばら筋（スターラップ）と帯筋（フープ）",
    keyZh: "两者都是剪切补强筋；あばら筋围绕梁主筋，帯筋水平围绕柱主筋，并约束主筋屈曲和核心混凝土。",
    keyJa: "ともにせん断補強筋である。あばら筋は梁主筋を囲み、帯筋は柱主筋を水平に囲んで主筋の座屈とコンクリートのはらみ出しを拘束する。",
    recognitionZh: "先判断构件方向：横向的梁用あばら筋，竖向的柱用帯筋。",
    recognitionJa: "部材方向を見る。梁を囲むものがあばら筋、柱を水平に囲むものが帯筋。",
    examForms: ["图解识别", "部材名称", "比较说明"], imageStatus: "notion", notionUrl: "https://app.notion.com/399e961e469081fabf9bfddac7f75e29",
  },
  {
    id: "pc-pca", category: "RC・PC", terms: ["PC", "PCa"],
    titleZh: "预应力与预制的不同分类轴", titleJa: "PCとPCa",
    keyZh: "PC是力学分类：用紧张钢材向混凝土导入预压应力；PCa是生产地点分类：在工厂等处预制构件、现场组装。一个构件可以同时是PC和PCa。",
    keyJa: "PCは力学的区分で、緊張材によりコンクリートへ圧縮力を導入する。PCaは製作場所の区分で、工場等で成形した部材を現場で組み立てる。両者は排他的ではない。",
    recognitionZh: "看到钢材紧张、预压应力是PC；看到工厂制造、现场接合是PCa。",
    recognitionJa: "緊張・プレストレスならPC、工場製作・現場接合ならPCa。",
    examForms: ["用语填空", "比较说明", "论述"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/399e961e4690810ebb1cc28653ec57e6",
  },
  {
    id: "src-cft", category: "RC・PC", terms: ["SRC造", "CFT造"],
    titleZh: "包覆型与钢管填充型复合柱", titleJa: "SRC造とCFT造",
    keyZh: "SRC是在钢骨周围配置钢筋并由混凝土包覆；CFT是在闭合钢管内部填充混凝土，利用钢管约束效应。",
    keyJa: "SRCは鉄骨の周囲に鉄筋を配しコンクリートで包む。CFTは鋼管内部へコンクリートを充填し、鋼管の拘束効果を利用する。",
    recognitionZh: "截面上混凝土在钢材外侧为SRC；混凝土位于钢管内部为CFT。",
    recognitionJa: "断面で、鋼材をコンクリートが包むのがSRC、鋼管内にコンクリートが入るのがCFT。",
    examForms: ["用语填空", "图解识别", "比较说明"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/399e961e4690816790deca6d6de7010e",
  },
  {
    id: "cold-joint-honeycomb", category: "RC・PC", terms: ["コールドジョイント", "豆板（ジャンカ）"],
    titleZh: "浇筑间断与局部空洞", titleJa: "コールドジョイントと豆板（ジャンカ）",
    keyZh: "コールドジョイント是前后两次浇筑间隔过长形成的非一体化界面；豆板是砂浆不足或振捣不良造成粗骨料外露和空隙。",
    keyJa: "コールドジョイントは打重ね時間が長く新旧コンクリートが一体化しない界面。豆板はモルタル不足や締固め不良で粗骨材が露出した空隙。",
    recognitionZh: "线状接缝看コールドジョイント；蜂窝状孔洞、骨料外露看豆板。",
    recognitionJa: "線状の打継ぎ面はコールドジョイント、蜂の巣状の空隙と粗骨材露出は豆板。",
    examForms: ["选择题", "图解识别", "比较说明"], imageStatus: "notion", notionUrl: "https://app.notion.com/399e961e469081f7bbbfc4412344037f",
  },
  {
    id: "wa-goya-yo-goya", category: "木造", terms: ["和小屋", "洋小屋"],
    titleZh: "竖向支承式与三角桁架式屋架", titleJa: "和小屋と洋小屋",
    keyZh: "和小屋以小屋束竖向支承母屋、棟木；洋小屋以合掌、陸梁等构成三角形桁架，主要通过轴力传递荷载，较适合较大跨度。",
    keyJa: "和小屋は小屋束で母屋・棟木を鉛直支持する。洋小屋は合掌・陸梁等による三角形トラスで主に軸力として荷重を伝え、比較的大きなスパンに対応しやすい。",
    recognitionZh: "内部有多根竖向小屋束的是和小屋；明显三角桁架的是洋小屋。",
    recognitionJa: "多数の小屋束が立つものは和小屋、明瞭な三角トラスは洋小屋。",
    examForms: ["图解识别", "部材名称", "比较说明"], imageStatus: "past-exam", notionUrl: "https://app.notion.com/399e961e4690815aa40df25487f155e1",
  },
  {
    id: "king-queen-post", category: "木造", terms: ["真束小屋", "対束小屋"],
    titleZh: "中央单吊杆与左右双吊杆", titleJa: "真束小屋と対束小屋",
    keyZh: "真束小屋在桁架中央设置一根真束；対束小屋设置左右两根对束。两者都属于洋小屋，应连同陸梁、合掌的位置判断。",
    keyJa: "真束小屋は中央に一本の真束を置き、対束小屋は左右二本の対束を置く。ともに洋小屋で、陸梁・合掌との位置関係で判別する。",
    recognitionZh: "数竖杆：中央1根为真束，左右2根为対束。",
    recognitionJa: "鉛直材を数える。中央一本が真束、左右二本が対束。",
    examForms: ["图解识别", "部材名称"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/394e961e469080a8a4abf3d691869ab6",
  },
  {
    id: "makabe-okabe", category: "木造", terms: ["真壁", "大壁"],
    titleZh: "柱外露与柱被墙面覆盖", titleJa: "真壁と大壁",
    keyZh: "真壁让柱梁显露，利于检查与干燥但墙内不易配置筋かい；大壁用墙面覆盖柱，施工和室内完成面整齐，但必须注意壁体内部结露。",
    keyJa: "真壁は柱を現し、防腐・点検上有利だが筋かいを納めにくい。大壁は柱を壁内に隠し平滑な面を得やすいが、壁体内結露に注意する。",
    recognitionZh: "立面上能看见柱框架为真壁，看不见柱为大壁。",
    recognitionJa: "柱が見えるものが真壁、仕上げ面に隠れるものが大壁。",
    examForms: ["图解识别", "比较说明"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/394e961e469080ab9bcbfdb3115a5358",
  },
  {
    id: "ordinary-high-strength-bolt", category: "S造", terms: ["普通ボルト", "高力ボルト"],
    titleZh: "承压剪切传力与摩擦传力", titleJa: "普通ボルト接合と高力ボルト接合",
    keyZh: "普通螺栓主要依靠螺栓杆与孔壁的承压、剪切传力；高力螺栓强力夹紧接合板，主要依靠接触面摩擦力传力。",
    keyJa: "普通ボルトは主にボルト軸と孔の支圧・せん断で力を伝える。高力ボルトは接合材を強く圧着し、主に接触面の摩擦力で伝える。",
    recognitionZh: "不要只看外形；答题必须写出夹紧力与摩擦传力原理。",
    recognitionJa: "外観だけでなく伝力原理を書く。強い締付けと摩擦力が高力ボルトの要点。",
    examForms: ["用语填空", "比较说明"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/382e961e46908065baa9f3088ae3b817",
  },
  {
    id: "butt-fillet-weld", category: "S造", terms: ["突合せ溶接", "隅肉溶接"],
    titleZh: "同面端接与角部三角焊缝", titleJa: "突合せ溶接と隅肉溶接",
    keyZh: "突合せ溶接将同一平面上的材端开坡口后连接；隅肉溶接用于搭接或直交部，在角部形成近似三角形焊缝。",
    keyJa: "突合せ溶接は同一面の材端を開先加工して接合する。隅肉溶接は重ね部や直交部の隅に三角形状の溶接部をつくる。",
    recognitionZh: "看接合几何：端面对端面为突合せ；角部三角焊道为隅肉。",
    recognitionJa: "材端同士なら突合せ、重ね・直交部の三角形状溶接なら隅肉。",
    examForms: ["图解识别", "比较说明"], imageStatus: "past-exam", notionUrl: "https://app.notion.com/382e961e4690802d9fb1fb14ccd3beea",
  },
  {
    id: "curtain-wall-movement", category: "外皮", terms: ["ロッキング方式", "スウェイ方式"],
    titleZh: "面板转动追随与滑移追随", titleJa: "ロッキング方式とスウェイ方式",
    keyZh: "ロッキング方式通过面板绕支点微转动吸收层间位移；スウェイ方式通过安装部或接缝的滑移、伸缩追随变形。",
    keyJa: "ロッキング方式はパネルの微小回転で層間変位を逃がす。スウェイ方式は取付部や目地の滑り・伸縮で変位に追従する。",
    recognitionZh: "题图有转角箭头看ロッキング；有水平相对滑移箭头看スウェイ。",
    recognitionJa: "回転矢印ならロッキング、水平の相対滑りならスウェイ。",
    examForms: ["图解识别", "比较说明"], imageStatus: "past-exam", notionUrl: "https://app.notion.com/399e961e46908132bfc1e91dcba5a1d1",
  },
  {
    id: "glass-types", category: "外皮", terms: ["合わせガラス", "強化ガラス", "複層ガラス"],
    titleZh: "防飞散、提高强度与提高隔热", titleJa: "合わせガラス・強化ガラス・複層ガラス",
    keyZh: "合わせガラス以中间膜保持破片；強化ガラス经热处理提高强度，破坏时粒状化；複層ガラス以密闭中空层提高隔热性能。",
    keyJa: "合わせガラスは中間膜で破片を保持する。強化ガラスは熱処理で強度を高め破損時に粒状化する。複層ガラスは密閉中空層で断熱性を高める。",
    recognitionZh: "中间膜、粒状破碎、中空层分别对应三者；它们解决的问题不同。",
    recognitionJa: "中間膜・粒状破壊・中空層をそれぞれ対応させ、目的の違いまで答える。",
    examForms: ["用语填空", "比较说明"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/399e961e4690817eb7e3f902131c2c87",
  },
  {
    id: "foundation-types", category: "基礎", terms: ["独立基礎", "布基礎", "べた基礎"],
    titleZh: "点支承、线支承与面支承", titleJa: "独立基礎・布基礎・べた基礎",
    keyZh: "独立基础分别承托各柱；布基础沿承重墙或柱列连续；筏板基础以建筑底面整体承托。接地面积依次从点状、带状到整面。",
    keyJa: "独立基礎は各柱を個別に、布基礎は壁・柱列下を連続して、べた基礎は建物底面全体で支持する。",
    recognitionZh: "看基础平面连续范围，而不是只看剖面上的扩底形状。",
    recognitionJa: "断面のフーチング形状だけでなく、平面上の連続範囲で判別する。",
    examForms: ["用语填空", "图解识别", "比较说明"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/399e961e469081f5ac45c3f8dff14c7f",
  },
  {
    id: "survey-improvement-retaining", category: "基礎", terms: ["地盤調査", "地盤改良", "山留め"],
    titleZh: "调查、改善与开挖支护", titleJa: "地盤調査・地盤改良・山留め",
    keyZh: "地盘调查是确认地层与承载力；地盘改良是改变软弱地基性质；山留め是在地下开挖时临时抵抗土压、水压。",
    keyJa: "地盤調査は地層・支持力を確認し、地盤改良は軟弱地盤の性質を改善する。山留めは地下掘削時に土圧・水圧を支える仮設である。",
    recognitionZh: "按施工目的辨别：测什么、改什么、撑什么。",
    recognitionJa: "目的で分ける。測るのが調査、性質を変えるのが改良、掘削面を支えるのが山留め。",
    examForms: ["用语填空", "施工手顺", "比较说明"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/399e961e469081248f35e8390bd8a296",
  },
  {
    id: "seismic-systems", category: "構造", terms: ["耐震", "制震", "免震"],
    titleZh: "承受、吸收与隔离地震作用", titleJa: "耐震・制震・免震",
    keyZh: "耐震依靠结构强度与延性承受地震力；制震以阻尼器等吸收振动能量；免震在基础或中间层设置免震层，减少地震运动向上部传递。",
    keyJa: "耐震は構造体の強度・靱性で耐え、制震はダンパー等で振動エネルギーを吸収する。免震は免震層により地震動の上部への伝達を抑える。",
    recognitionZh: "加强梁柱是耐震；结构中有阻尼器是制震；建筑底部有柔性隔离层是免震。",
    recognitionJa: "骨組補強は耐震、ダンパーは制震、建物下部の柔らかい分離層は免震。",
    examForms: ["用语填空", "图解识别", "比较说明"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/399e961e4690810189b6d08187ee8a98",
  },
  {
    id: "shell-truss-space", category: "構造", terms: ["シェル", "平面トラス", "スペースフレーム"],
    titleZh: "曲面、平面三角桁架与立体网格", titleJa: "シェル・平面トラス・スペースフレーム",
    keyZh: "シェル以薄曲面的面内力传递荷载；平面トラス以同一平面内三角形杆件的轴力传力；スペースフレーム以立体三角网格向多方向分散荷载。",
    keyJa: "シェルは薄い曲面の面内力、平面トラスは同一平面の三角形部材の軸力、スペースフレームは立体三角格子で多方向へ荷重を分散する。",
    recognitionZh: "连续曲面、二维三角杆系、三维网格分别对应三者。",
    recognitionJa: "連続曲面・二次元三角骨組・三次元格子の順に判別する。",
    examForms: ["用语填空", "图解识别", "比较说明"], imageStatus: "past-exam", notionUrl: "https://app.notion.com/399e961e4690816ba74ef204a45eb0cb",
  },
  {
    id: "brick-bonds", category: "組積・材料", terms: ["イギリス積み", "フランス積み"],
    titleZh: "分层交替与同层交替", titleJa: "イギリス積みとフランス積み",
    keyZh: "英国式是一层全为长面、下一层全为短面，逐层交替；法国式在同一层中让长面与短面交替排列。",
    keyJa: "イギリス積みは長手だけの段と小口だけの段を交互に積む。フランス積みは各段の中で長手と小口を交互に並べる。",
    recognitionZh: "看同一层是否混合长面和短面：混合的是法国式。",
    recognitionJa: "同じ段に長手と小口が混在すればフランス積み。段ごとに揃えばイギリス積み。",
    examForms: ["用语填空", "图解识别", "比较说明"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/399e961e4690811eae45ea35b4434ed2",
  },
  {
    id: "joints", category: "組積・材料", terms: ["芋目地", "馬目地"],
    titleZh: "竖缝贯通与错缝", titleJa: "芋目地と馬目地",
    keyZh: "芋目地的上下竖缝连续贯通；馬目地让上下层竖缝错开。前者图形整齐但整体性较差，砌体通常采用错缝。",
    keyJa: "芋目地は上下段の縦目地が連続し、馬目地は上下で縦目地をずらす。組積体では一般に目地をずらして一体性を高める。",
    recognitionZh: "只追踪一条竖缝：能贯穿多层是芋目地，逐层错开是馬目地。",
    recognitionJa: "一本の縦目地を追う。上下に通れば芋目地、段ごとにずれれば馬目地。",
    examForms: ["图解识别", "比较说明"], imageStatus: "past-exam", notionUrl: "https://app.notion.com/399e961e469081e29671d92f6ca2f4cc",
  },
  {
    id: "wet-dry", category: "組積・材料", terms: ["湿式工法", "乾式工法"],
    titleZh: "现场湿作硬化与部件机械组装", titleJa: "湿式工法と乾式工法",
    keyZh: "湿式工法使用砂浆、混凝土、抹灰等含水材料现场硬化；乾式工法用板材、面板、金属下地等通过钉、螺钉或金物组装。",
    keyJa: "湿式工法はモルタル・コンクリート等を現場で硬化させる。乾式工法はボード・パネル等を釘・ビス・金物で組み立てる。",
    recognitionZh: "需要养护、干燥的是湿式；可拆装、接缝明确的是乾式。",
    recognitionJa: "養生・乾燥を要するものは湿式、機械的接合で組立・交換しやすいものは乾式。",
    examForms: ["用语填空", "比较说明"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/399e961e469081d99dcaf6cb4ff022ab",
  },
  {
    id: "wood-products", category: "木造", terms: ["合板", "LVL", "CLT", "集成材", "OSB"],
    titleZh: "木质材料按原料形态与纤维方向区分", titleJa: "合板・LVL・CLT・集成材・OSB",
    keyZh: "合板是单板交错层积；LVL是单板平行层积；CLT是ラミナ交错层积；集成材是ラミナ平行层积；OSB以定向ストランド压制。",
    keyJa: "合板は単板を直交、LVLは単板を平行、CLTはラミナを直交、集成材はラミナを平行に積層する。OSBはストランドを配向して成形する。",
    recognitionZh: "先看构成单元，再看纤维方向：単板／ラミナ／ストランド × 直交／平行。",
    recognitionJa: "構成単位と繊維方向を見る。単板・ラミナ・ストランド、直交・平行の二軸で判別する。",
    examForms: ["用语联系", "图解识别", "比较说明"], imageStatus: "past-exam", notionUrl: "https://app.notion.com/382e961e469080fa86c8c5836b44ed6b",
  },
  {
    id: "base-cornice", category: "外皮", terms: ["巾木", "回り縁"],
    titleZh: "墙脚收边与墙顶收边", titleJa: "巾木と回り縁",
    keyZh: "巾木设在墙与地板交界，保护墙脚并收边；回り縁设在墙与天花交界，收住天花与墙面的边界。",
    keyJa: "巾木は壁と床の取合いで壁下端を保護する。回り縁は壁と天井の取合いを納める見切り材である。",
    recognitionZh: "只看高度：地面边是巾木，天花边是回り縁。", recognitionJa: "高さで判別する。床際が巾木、天井際が回り縁。",
    examForms: ["用语填空", "图解比较"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/382e961e469080fa86c8c5836b44ed6b",
  },
  {
    id: "ari-kama", category: "木造", terms: ["あり継ぎ", "かま継ぎ"],
    titleZh: "燕尾防拔与钩形防错动", titleJa: "あり継ぎとかま継ぎ",
    keyZh: "あり継ぎ以燕尾形防止轴向拔出；かま継ぎ以互相咬合的钩形缺口抑制材轴方向错动。",
    keyJa: "あり継ぎは燕尾形で引抜けを防ぎ、かま継ぎは鉤形の欠込みをかみ合わせて材軸方向のずれを抑える。",
    recognitionZh: "梯形扩口看あり；相互钩形看かま。", recognitionJa: "台形の広がりがあり、鉤形のかみ合わせがかま。",
    examForms: ["图解比较"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/382e961e469080fa86c8c5836b44ed6b",
  },
  {
    id: "roof-tiles", category: "木造", terms: ["本瓦葺き", "桟瓦葺き"],
    titleZh: "丸瓦＋平瓦与一体化桟瓦", titleJa: "本瓦葺きと桟瓦葺き",
    keyZh: "本瓦葺将平瓦与丸瓦组合，传统但较重；桟瓦葺使用兼具平瓦与丸瓦作用的桟瓦挂在瓦桟上，施工较简便。",
    keyJa: "本瓦葺きは平瓦と丸瓦を組み合わせる。桟瓦葺きは両者の役割を一体化した桟瓦を瓦桟に掛けて葺く。",
    recognitionZh: "看到两种瓦交替是本瓦；单一波形瓦挂桟是桟瓦。", recognitionJa: "平瓦と丸瓦の二種なら本瓦、単一の桟瓦なら桟瓦葺き。",
    examForms: ["用语填空", "图解比较"], imageStatus: "past-exam", notionUrl: "https://app.notion.com/382e961e469080fa86c8c5836b44ed6b",
  },
  {
    id: "kyoro-orioki", category: "木造", terms: ["京呂組", "折置組"],
    titleZh: "小屋梁在桁下或桁上", titleJa: "京呂組と折置組",
    keyZh: "京呂組在柱顶先放小屋梁，再在其上架桁；折置組先在柱上架桁，再把小屋梁放在桁上。",
    keyJa: "京呂組は柱上に小屋梁、その上に軒桁を置く。折置組は柱上に軒桁、その上に小屋梁を置く。",
    recognitionZh: "记住上下顺序：京呂是梁下桁上；折置是桁下梁上。", recognitionJa: "上下関係で判別する。京呂は小屋梁が下、折置は軒桁が下。",
    examForms: ["定义填空", "图解识别"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/382e961e469080fa86c8c5836b44ed6b",
  },
  {
    id: "concrete-workability", category: "RC・PC", terms: ["ワーカビリティ", "スランプ", "スランプフロー"],
    titleZh: "施工性能、稠度指标与流动扩展", titleJa: "ワーカビリティ・スランプ・スランプフロー",
    keyZh: "ワーカビリティ是混凝土易于浇筑、振捣和收面的综合施工性能；スランプ测脱模后的下沉量；スランプフロー测底面扩展直径。",
    keyJa: "ワーカビリティは施工のしやすさ。スランプはコーン引上げ後の沈下量、スランプフローは試料の広がり径を測る。",
    recognitionZh: "概念问施工难易选ワーカビリティ；测高度差选スランプ；测扩展直径选スランプフロー。",
    recognitionJa: "施工性はワーカビリティ、沈下量はスランプ、広がり径はスランプフロー。",
    examForms: ["定义填空", "数值判断"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/382e961e469080fa86c8c5836b44ed6b",
  },
  {
    id: "mullion-transom", category: "外皮", terms: ["マリオン", "無目"],
    titleZh: "幕墙竖框与横框", titleJa: "マリオンと無目",
    keyZh: "マリオン是幕墙或窗中的竖向框材；無目是横向框材。两者共同分格并支承玻璃或面板。",
    keyJa: "マリオンは縦枠、無目は横枠であり、ガラス・パネルを分割して支持する。",
    recognitionZh: "竖向是マリオン，横向是無目。", recognitionJa: "縦がマリオン、横が無目。",
    examForms: ["用语填空", "图解识别"], imageStatus: "past-exam", notionUrl: "https://app.notion.com/382e961e469080fa86c8c5836b44ed6b",
  },
  {
    id: "flange-web", category: "S造", terms: ["フランジ", "ウェブ"],
    titleZh: "H形钢翼缘与腹板", titleJa: "フランジとウェブ",
    keyZh: "フランジ是上下展开的板，主要承担弯曲正应力；ウェブ是连接上下翼缘的中间板，主要承担剪力。",
    keyJa: "フランジは上下の張出し板で主に曲げ応力を、ウェブは両者をつなぐ中央板で主にせん断力を負担する。",
    recognitionZh: "H形截面上下横板是フランジ，中间竖板是ウェブ。", recognitionJa: "H形断面の上下板がフランジ、中央板がウェブ。",
    examForms: ["定义填空", "用语联系", "图解识别"], imageStatus: "diagram-needed", notionUrl: "https://app.notion.com/382e961e469080fa86c8c5836b44ed6b",
  },
];

export const constructionExamEvidence: Record<string, ConstructionExamEvidence> = {
  "separator-form-tie": { level: "direct", references: ["2019 専門1 Q3", "2026 専門1 Q3"], focusZh: "位置识别＋功能比较", focusJa: "位置識別と機能比較" },
  "stirrup-hoop": { level: "direct", references: ["2017 専門1 Q3", "2023 専門1 Q3"], focusZh: "用语联系＋RC断面识别", focusJa: "用語対応とRC断面識別" },
  "pc-pca": { level: "foundation", references: [], focusZh: "基础辨析，専門1暂未确认直接对比", focusJa: "基礎整理。専門1の直接比較は未確認" },
  "src-cft": { level: "related", references: ["2022 専門1 Q3（CFT）"], focusZh: "CFT直接出现，SRC用于比较理解", focusJa: "CFTが直接出題、SRCは比較理解" },
  "cold-joint-honeycomb": { level: "related", references: ["2024 専門1 Q3（豆板）"], focusZh: "豆板直接出现，施工缺陷辨析", focusJa: "豆板が直接出題、施工欠陥の区別" },
  "wa-goya-yo-goya": { level: "direct", references: ["2013 専門1 Q2", "2016 専門1 Q2", "2018 専門1 Q3"], focusZh: "小屋组类型与部材图", focusJa: "小屋組形式と部材図" },
  "king-queen-post": { level: "direct", references: ["2016 専門1 Q2", "2017 専門1 Q3"], focusZh: "真束位置＋クイーンポスト联系", focusJa: "真束位置とクイーンポスト対応" },
  "makabe-okabe": { level: "foundation", references: [], focusZh: "木造墙体基础辨析", focusJa: "木造壁の基礎的区別" },
  "ordinary-high-strength-bolt": { level: "direct", references: ["2013 専門1 Q2"], focusZh: "传力机制填空", focusJa: "伝力機構の穴埋め" },
  "butt-fillet-weld": { level: "direct", references: ["2023 専門1 Q3"], focusZh: "焊缝形状图解识别", focusJa: "溶接形状の図解識別" },
  "curtain-wall-movement": { level: "direct", references: ["2019 専門1 Q3", "2026 専門1 Q3例题"], focusZh: "层间变位追随方式", focusJa: "層間変位追従方式" },
  "glass-types": { level: "direct", references: ["2026 専門1 Q3"], focusZh: "构成层与性能比较", focusJa: "層構成と性能比較" },
  "foundation-types": { level: "direct", references: ["2018 専門1 Q3", "2022 専門1 Q3"], focusZh: "图中位置＋基础部材", focusJa: "図中位置と基礎部材" },
  "survey-improvement-retaining": { level: "direct", references: ["2014 専門1 Q3", "2022 専門1 Q3", "2026 専門1 Q3"], focusZh: "调查、支护的目的辨析", focusJa: "調査・山留めの目的区別" },
  "seismic-systems": { level: "related", references: ["2015 専門1 Q12", "2024 専門1 Q3（免震レトロフィット）"], focusZh: "耐震改修与免震概念", focusJa: "耐震改修と免震概念" },
  "shell-truss-space": { level: "direct", references: ["2013 専門1 Q2", "2020 専門1 Q3"], focusZh: "传力形式＋结构家联系", focusJa: "伝力形式と構造家対応" },
  "brick-bonds": { level: "direct", references: ["2015 専門1 Q2", "2022 専門1 Q3"], focusZh: "砌筑排列与名称联系", focusJa: "積み方と名称対応" },
  "joints": { level: "direct", references: ["2026 専門1 Q3"], focusZh: "目地位置的单线图比较", focusJa: "目地位置の単線図比較" },
  "wet-dry": { level: "direct", references: ["2016 専門1 Q2"], focusZh: "施工方式填空", focusJa: "施工方式の穴埋め" },
  "wood-products": { level: "direct", references: ["2014 専門1 Q3", "2017 専門1 Q3", "2025 専門1 Q3", "2026 専門1 Q3"], focusZh: "构成单元＋纤维方向", focusJa: "構成単位と繊維方向" },
  "base-cornice": { level: "direct", references: ["2024 専門1 Q3", "2026 専門1 Q3"], focusZh: "安装高度与功能", focusJa: "取付位置と機能" },
  "ari-kama": { level: "direct", references: ["2026 専門1 Q3"], focusZh: "形状与防拔方向", focusJa: "形状と引抜け方向" },
  "roof-tiles": { level: "direct", references: ["2014 専門1 Q3", "2026 専門1 Q3"], focusZh: "瓦的组合方式图解", focusJa: "瓦の組合せの図解" },
  "kyoro-orioki": { level: "direct", references: ["2014 専門1 Q3"], focusZh: "梁与桁的上下顺序", focusJa: "小屋梁と軒桁の上下関係" },
  "concrete-workability": { level: "direct", references: ["2013 専門1 Q2", "2014 専門1 Q3", "2022 専門1 Q3"], focusZh: "定义与测量对象", focusJa: "定義と測定対象" },
  "mullion-transom": { level: "direct", references: ["2019 専門1 Q3", "2022 専門1 Q3"], focusZh: "竖框／横框图解识别", focusJa: "縦枠・横枠の図解識別" },
  "flange-web": { level: "direct", references: ["2014 専門1 Q3", "2017 専門1 Q3"], focusZh: "截面位置＋主要应力", focusJa: "断面位置と主要応力" },
};
