export type EnvironmentKnowledgeTopic = {
  id: string;
  number: string;
  title: string;
  shortTitle: string;
  accent: "amber" | "sky" | "violet" | "rose" | "orange" | "teal" | "slate";
  frequency: string;
  focus: string[];
  traps: string[];
  years: string;
};

export type FormulaCard = {
  topic: string;
  title: string;
  formula: string;
  use: string;
  condition: string;
  referenceYears?: number[];
};

export const ENVIRONMENT_KNOWLEDGE_TOPICS: EnvironmentKnowledgeTopic[] = [
  {
    id: "heat",
    number: "01",
    title: "建築伝熱・放射",
    shortTitle: "伝熱",
    accent: "amber",
    frequency: "毎年級",
    focus: [
      "熱抵抗を直列に足す",
      "U値・表面温度・熱流",
      "黒体放射と平行二面間放射",
    ],
    traps: ["U値は壁厚に単純反比例しない", "放射式は絶対温度[K]を使う"],
    years: "2014–2026",
  },
  {
    id: "ventilation",
    number: "02",
    title: "換気・室内空気質",
    shortTitle: "換気",
    accent: "sky",
    frequency: "毎年級",
    focus: [
      "CO₂の定常・非定常収支",
      "風力・温度差換気",
      "第1〜3種、空気齢・余命",
    ],
    traps: ["濃度のppmと小数を混ぜない", "開口流量はΔpに比例ではなく√Δp"],
    years: "2013–2026",
  },
  {
    id: "light",
    number: "03",
    title: "採光・照明・色彩",
    shortTitle: "光",
    accent: "violet",
    frequency: "高頻度",
    focus: ["測光量の関係", "点光源・昼光率・光束法", "マンセル、順応、混色"],
    traps: ["光度[cd]と輝度[cd/m²]を混同しない", "加法混色はRGB"],
    years: "2013–2026",
  },
  {
    id: "acoustics",
    number: "04",
    title: "建築音響",
    shortTitle: "音",
    accent: "rose",
    frequency: "高頻度",
    focus: ["音圧レベルとdB合成", "残響・吸音・遮音", "距離減衰と心理音響"],
    traps: ["音圧60dB低下=エネルギー10⁻⁶", "2音源合成は+3dB"],
    years: "2013–2026",
  },
  {
    id: "sun",
    number: "05",
    title: "日照・日射",
    shortTitle: "日射",
    accent: "orange",
    frequency: "中頻度",
    focus: [
      "日照・日影の定義",
      "太陽位置と相当外気温度",
      "SC・日射透過・Low-E",
    ],
    traps: ["永久日影と終日日影を区別", "SCは小さいほど遮蔽が強い"],
    years: "2013–2024",
  },
  {
    id: "thermal",
    number: "06",
    title: "温熱・湿気・結露",
    shortTitle: "温湿度",
    accent: "teal",
    frequency: "中頻度",
    focus: [
      "温熱6要素、met・clo・PMV",
      "露点・湿り空気・エンタルピー",
      "表面・内部結露",
    ],
    traps: ["PMVの放射要素は平均放射温度", "防湿層は冬期に室内側"],
    years: "2013–2026",
  },
  {
    id: "systems",
    number: "07",
    title: "設備・省エネルギー",
    shortTitle: "設備",
    accent: "slate",
    frequency: "補強",
    focus: [
      "VAV・冷凍サイクル・熱回収",
      "COP・APF・UA・一次エネルギー",
      "給排水・電気の基本現象",
    ],
    traps: ["COP/APFは大きいほど高効率", "UAの除数は外皮面積"],
    years: "2014–2025",
  },
];

const FORMULA_REFERENCE_YEARS: Record<string, number[]> = {
  日射: [2013, 2014, 2015, 2020, 2024],
  伝熱: [2018, 2023, 2024, 2025],
  換気: [2013, 2017, 2018, 2024, 2025],
  照明: [2018, 2020, 2023, 2024],
  音響: [2017, 2018, 2019, 2023, 2025],
  湿気: [2019, 2020, 2022, 2024],
  温熱: [2013, 2015, 2018, 2019, 2020, 2026],
  設備: [2016, 2020, 2025, 2026],
};

const FORMULA_CARDS: FormulaCard[] = [
  {
    topic: "伝熱",
    title: "多層壁の熱貫流率",
    formula: "U = 1 / (1/hᵢ + Σd/λ + 1/hₒ)",
    use: "壁のU値、熱流、表面温度",
    condition: "d[m]・λ[W/(m·K)]・h[W/(m²·K)]を統一",
  },
  {
    topic: "伝熱",
    title: "放射熱流",
    formula: "q = ε₁₂σ(T₁⁴ − T₂⁴)",
    use: "無限平行二面間の放射",
    condition: "Tは必ず絶対温度[K]",
  },
  {
    topic: "換気",
    title: "CO₂必要換気量",
    formula: "Q = G / (Cᵢ − Cₒ)",
    use: "許容濃度から換気量を求める",
    condition: "ppmを小数へ：1000 ppm = 0.001",
  },
  {
    topic: "換気",
    title: "開口流量",
    formula: "Q = αA√(2Δp/ρ)",
    use: "風力・温度差換気",
    condition: "有効開口面積と圧力差を使う",
  },
  {
    topic: "照明",
    title: "点光源の照度",
    formula: "E = I cosθ / r²",
    use: "点光源の直接照度",
    condition: "直下ではcosθ=1",
  },
  {
    topic: "照明",
    title: "光束法",
    formula: "E = NFUM / A",
    use: "平均照度・必要器具数",
    condition: "Nは灯数か器具数かを確認",
  },
  {
    topic: "音響",
    title: "音圧レベル",
    formula: "Lₚ = 20log₁₀(p/p₀)",
    use: "音圧比をdBへ変換",
    condition: "音の強さはp²に比例",
  },
  {
    topic: "音響",
    title: "残響時間",
    formula: "T₆₀ = 0.161V / A",
    use: "Sabineの残響式",
    condition: "Aは等価吸音面積",
  },
  {
    topic: "湿気",
    title: "湿り空気の比エンタルピー",
    formula: "h ≈ 1.005θ + x(2501 + 1.86θ)",
    use: "空気線図・湿り空気",
    condition: "h[kJ/kg(DA)]、x[kg/kg(DA)]",
  },
  {
    topic: "設備",
    title: "動圧",
    formula: "q = ρv² / 2",
    use: "配管・ダクト・Bernoulli",
    condition: "断面半減→流速2倍→動圧4倍",
  },
  {
    topic: "伝熱",
    title: "単層壁の伝導熱流",
    formula: "q = λ(θ₁ − θ₂) / d",
    use: "壁体内の定常一次元伝導",
    condition: "表面熱伝達抵抗を含める問題ではR法を使う",
  },
  {
    topic: "伝熱",
    title: "熱流・表面温度",
    formula: "q = U(θᵢ − θₒ),  θₛᵢ = θᵢ − (U/hᵢ)(θᵢ − θₒ)",
    use: "熱流と室内側表面温度",
    condition: "結露判定では室内側表面温度と露点を比較",
  },
  {
    topic: "伝熱",
    title: "黒体放射",
    formula: "q = σT⁴",
    use: "黒体の全放射熱流束",
    condition: "絶対温度[K]、σ=5.67×10⁻⁸ W/(m²·K⁴)",
  },
  {
    topic: "伝熱",
    title: "複層ガラスの総合透過率",
    formula: "τₜ = τ² / (1 − ρ²)",
    use: "同一ガラス2枚・中空層の多重反射",
    condition: "単板は τ=1−α−ρ",
  },
  {
    topic: "換気",
    title: "温度差換気の圧力差",
    formula: "Δp = ρgH(1/Tₒ − 1/Tᵢ)",
    use: "煙突効果による自然換気",
    condition: "Tは絶対温度[K]、高低差Hを使う",
  },
  {
    topic: "換気",
    title: "風圧差",
    formula: "Δp = (Cₚ₁ − Cₚ₂)ρv² / 2",
    use: "風力換気の圧力差",
    condition: "風上・風下の風圧係数差を使う",
  },
  {
    topic: "換気",
    title: "非定常濃度減衰",
    formula: "C(t) − Cₒ = (C₀ − Cₒ)e⁻Qᵗ⁄ⱽ",
    use: "換気による汚染物質の希釈",
    condition: "発生なし・完全混合。e⁻²までならt=2V/Q",
  },
  {
    topic: "換気",
    title: "定常温度差",
    formula: "ΔT = q / (ρcₚQ)",
    use: "換気だけで熱を排出する室",
    condition: "q[W]、Q[m³/s]で単位を合わせる",
  },
  {
    topic: "照明",
    title: "昼光率",
    formula: "DF = (Eᵢ / Eₒ) × 100",
    use: "室内照度と屋外全天空照度",
    condition: "直接昼光率と間接昼光率は加算",
  },
  {
    topic: "照明",
    title: "測光量の関係",
    formula: "I = dΦ/dΩ,  L = dI/(dA cosθ)",
    use: "光束・光度・輝度の定義整理",
    condition: "光束[lm]、光度[cd]、輝度[cd/m²]",
  },
  {
    topic: "音響",
    title: "複数音源の合成",
    formula: "L = 10log₁₀(Σ10ᴸⁱ⁄¹⁰)",
    use: "複数の独立音源のレベル合成",
    condition: "同レベル2音源は+3 dB、4音源は+6 dB",
  },
  {
    topic: "音響",
    title: "自由音場の距離減衰",
    formula: "I = W/(4πr²),  ΔLₚ = −20log₁₀(r₂/r₁)",
    use: "点音源の距離変化",
    condition: "距離2倍で音圧レベルは約−6 dB",
  },
  {
    topic: "音響",
    title: "質量則",
    formula: "TL ≈ 20log₁₀(mf) − 47",
    use: "単層壁の透過損失の概算",
    condition: "面密度m又は周波数fが2倍で約+6 dB",
  },
  {
    topic: "音響",
    title: "室間音圧レベル差",
    formula: "R = L₁ − L₂ + 10log₁₀(S/A₂)",
    use: "遮音性能・隣室音圧レベル",
    condition: "S=隔壁面積、A₂=受音室等価吸音面積",
  },
  {
    topic: "湿気",
    title: "相対湿度",
    formula: "RH = (f/fₛ) × 100",
    use: "水蒸気分圧と飽和水蒸気分圧",
    condition: "RH[%]、fとfₛは同じ温度で比較",
  },
  {
    topic: "湿気",
    title: "表面結露判定",
    formula: "θₛᵢ < θdp → 結露",
    use: "室内側表面の結露判定",
    condition: "θdpは室内空気の露点温度",
  },
  {
    topic: "湿気",
    title: "透湿量",
    formula: "W = K′A(fᵢ − fₒ)",
    use: "壁体を通る定常透湿",
    condition: "K′は各層・表面湿気抵抗から求める",
  },
  {
    topic: "設備",
    title: "COP・APF",
    formula: "COP = 能力 / 消費電力",
    use: "冷凍機・空調の効率比較",
    condition: "COPもAPFも大きいほど高効率",
  },
  {
    topic: "設備",
    title: "連続の式",
    formula: "A₁v₁ = A₂v₂",
    use: "配管・ダクトの断面変化",
    condition: "断面積半減→流速2倍。動圧式とセットで使う",
  },
  {
    topic: "日射",
    title: "南中時太陽高度",
    formula: "h = 90° − |φ − δ|",
    use: "緯度と太陽赤緯から南中高度を求める",
    condition: "夏至δ≈+23.4°、冬至δ≈−23.4°、春秋分δ=0°",
  },
  {
    topic: "日射",
    title: "Bouguerの式",
    formula: "Iᴅ = I₀Pᵐ",
    use: "法線面直達日射量の近似",
    condition: "P=大気透過率、m=光路長に対応するair mass",
  },
  {
    topic: "日射",
    title: "相当外気温度",
    formula: "SAT = θₒ + (aI − εRₙ)/αₒ",
    use: "日射と夜間放射を外気温へ換算",
    condition: "外表面の吸収率aと総合熱伝達率αₒを使う",
  },
  {
    topic: "照明",
    title: "室指数",
    formula: "K = LW / [Hₘ(L + W)]",
    use: "照明率を決める室形状指標",
    condition: "Hₘ=照明器具から作業面までの高さ",
  },
  {
    topic: "照明",
    title: "必要ランプ・器具数",
    formula: "N = EA / (FUM)",
    use: "目標平均照度から必要数を逆算",
    condition: "Fは1灯当たり光束か1器具当たり光束か確認",
  },
  {
    topic: "換気",
    title: "換気回数",
    formula: "n = Q / V",
    use: "換気量と室容積から毎時換気回数",
    condition: "Q[m³/h]、V[m³]ならn[回/h]",
  },
  {
    topic: "換気",
    title: "直列開口の有効開口面積",
    formula: "1/(αA)² = Σ1/(αᵢAᵢ)²",
    use: "複数開口を通る自然換気",
    condition: "最小開口の影響が大きい",
  },
  {
    topic: "換気",
    title: "ダクト摩擦・局部損失",
    formula: "Δp = λ(L/D)(ρv²/2) + ζ(ρv²/2)",
    use: "直管部と曲がり・分岐の圧力損失",
    condition: "損失は概ね風速の2乗に比例",
  },
  {
    topic: "設備",
    title: "Bernoulliの式",
    formula: "p/ρg + v²/2g + z = constant",
    use: "流体の圧力・速度・高さの関係",
    condition: "定常・非圧縮・損失なしの基本形",
  },
  {
    topic: "伝熱",
    title: "Newtonの冷却則",
    formula: "q𝚌 = α𝚌(θₛ − θ𝒇)",
    use: "表面と流体間の対流熱伝達",
    condition: "α𝚌は対流熱伝達率",
  },
  {
    topic: "伝熱",
    title: "線形化放射熱伝達率",
    formula: "αᵣ = εσ(T₁+T₂)(T₁²+T₂²)",
    use: "放射を温度差×熱伝達率で扱う",
    condition: "Tは絶対温度[K]",
  },
  {
    topic: "伝熱",
    title: "形態係数",
    formula: "AᵢFᵢⱼ = AⱼFⱼᵢ,  ΣFᵢⱼ = 1",
    use: "面間放射交換の幾何学的関係",
    condition: "相反則と総和則をセットで使う",
  },
  {
    topic: "湿気",
    title: "内部結露判定",
    formula: "f(x) > fₛ[θ(x)] → 内部結露",
    use: "壁体内部の水蒸気分圧線と飽和分圧線",
    condition: "各層境界の温度と分圧を比較",
  },
  {
    topic: "音響",
    title: "空気中の音速",
    formula: "c ≈ 331 + 0.6θ",
    use: "気温から音速を近似",
    condition: "θ[℃]、c[m/s]",
  },
  {
    topic: "音響",
    title: "比音響インピーダンス",
    formula: "z = p/u = ρc",
    use: "平面進行波の音圧と粒子速度",
    condition: "ρcは平面進行波の場合",
  },
  {
    topic: "音響",
    title: "音響エネルギー密度",
    formula: "E = pᵣₘₛ²/(ρc²)",
    use: "残響時間後のエネルギー比",
    condition: "音圧60 dB低下でエネルギーは10⁻⁶",
  },
  {
    topic: "音響",
    title: "等価吸音面積",
    formula: "A = ΣαᵢSᵢ + ΣAⱼ",
    use: "残響式に用いる吸音力",
    condition: "人・家具の等価吸音面積も加算",
  },
  {
    topic: "音響",
    title: "Eyringの残響式",
    formula: "T₆₀ = 0.161V / [−S ln(1−ᾱ)]",
    use: "平均吸音率が大きい室の残響",
    condition: "低吸音率ではSabine式に近づく",
  },
  {
    topic: "音響",
    title: "音響パワーレベル",
    formula: "Lᴡ = 10log₁₀(W/W₀)",
    use: "音源の音響パワーをdB表示",
    condition: "W₀=10⁻¹² W",
  },
  {
    topic: "設備",
    title: "UA値",
    formula: "UA = Σ(UᵢAᵢ + ΨⱼLⱼ) / Aₑₙᵥ",
    use: "外皮平均熱貫流率",
    condition: "除数は床面積ではなく外皮面積",
  },
  {
    topic: "設備",
    title: "APF",
    formula: "APF = 年間冷暖房能力の総和 / 年間消費電力量",
    use: "年間を通じたエアコン効率",
    condition: "COPと同様、大きいほど高効率",
  },
  {
    topic: "温熱",
    title: "代謝量met",
    formula: "1 met = 58.2 W/m²",
    use: "人体の活動量を熱流束へ換算",
    condition: "歩行・立位など設問の活動状態を確認",
  },
  {
    topic: "温熱",
    title: "着衣量clo",
    formula: "1 clo = 0.155 m²·K/W",
    use: "着衣の熱抵抗換算",
    condition: "metは代謝量、cloは熱抵抗で単位が異なる",
  },
  {
    topic: "温熱",
    title: "作用温度の近似",
    formula: "OT ≈ (θₐ + MRT)/2",
    use: "低風速時の空気温度と放射温度の統合",
    condition: "湿度を直接含む式ではない",
  },
  {
    topic: "伝熱",
    title: "Kirchhoffの法則",
    formula: "ε(λ,T) = α(λ,T)",
    use: "熱平衡時の放射率と吸収率",
    condition: "同一波長・方向・温度で比較",
  },
  {
    topic: "日射",
    title: "放射の収支",
    formula: "α + ρ + τ = 1",
    use: "吸収率・反射率・透過率の関係",
    condition: "不透明体ではτ=0",
  },
  {
    topic: "日射",
    title: "Wienの変位則",
    formula: "λₘₐₓT = 2.898×10⁻³ m·K",
    use: "放射ピーク波長と温度",
    condition: "低温ほどピークは長波長側",
  },
  {
    topic: "音響",
    title: "octaveと周波数",
    formula: "f₂ = 2ⁿf₁",
    use: "n octave上・下の周波数",
    condition: "3 octave上は8倍",
  },
  {
    topic: "設備",
    title: "熱損失係数（旧Q値）",
    formula: "Q旧 = (貫流熱損失 + 換気熱損失) / 床面積",
    use: "旧来の住宅断熱性能指標",
    condition: "現行UA値とは除数・対象が異なる",
  },
];

export const ENVIRONMENT_FORMULAS = FORMULA_CARDS.map((card) => ({
  ...card,
  referenceYears: FORMULA_REFERENCE_YEARS[card.topic] ?? [],
}));
