import type { ArchitectLearningCard } from "@/types/history-learning-card";
const l = (ja: string, zh: string, en: string) => ({ ja, zh, en });
type Seed = [string, string, string, string, string, string, string[] , string[], string[]?];

type BatchFourEnglish = { name: string; period: string; summary: string; principle: string; feature: string; phaseDescription: string };

const BATCH_FOUR_ENGLISH: Record<string, BatchFourEnglish> = {
  "architect-cfa-voysey": { name: "C. F. A. Voysey", period: "1857–1941", summary: "English architect and designer who developed Arts and Crafts houses through plain materials, low-pitched roofs, and plans closely attuned to domestic life.", principle: "Let construction, everyday use, and local materials generate a calm, unified dwelling.", feature: "Roughcast walls, sweeping roofs, deep eaves, simple openings, built-in furnishings, and restrained decorative motifs.", phaseDescription: "Moor Crag exemplifies Voysey's quiet, site-responsive Arts and Crafts domestic architecture and his integration of house, furniture, and landscape." },
  "architect-jjp-oud": { name: "J. J. P. Oud", period: "1890–1963", summary: "Dutch architect who extended De Stijl abstraction into urban housing and public architecture while pursuing the social and technical rationality of modernism.", principle: "Use abstract composition, standardized construction, and clear circulation to give collective housing a civic order.", feature: "Orthogonal planes, white volumes, primary-color accents, economical detailing, and rational street fronts.", phaseDescription: "Cafe De Unie in Rotterdam transformed De Stijl composition into an urban facade; Oud's municipal housing helped connect the movement to social modernism." },
  "architect-louis-charles-boileau": { name: "Louis-Charles Boileau", period: "1837–1914", summary: "French architect who introduced iron-and-glass construction to department-store architecture and contributed to the enlargement of commercial interiors.", principle: "Use modern structural and service systems to produce large, luminous, adaptable spaces for retail.", feature: "Iron framing, glass roofs, broad retail floors, light-filled atria, and facades reconciling engineering with urban decorum.", phaseDescription: "The Bon Marche department store, developed with Aristide Boucicaut and engineer Gustave Eiffel, helped establish the spatial and technical model of the modern department store." },
  "architect-mh-baillie-scott": { name: "M. H. Baillie Scott", period: "1865–1945", summary: "British architect and designer who integrated house, furniture, garden, and craft to shape Arts and Crafts domestic environments.", principle: "Treat the home as a coordinated setting for daily life, made through material honesty and craft.", feature: "Informal plans, built-in furniture, inglenooks, handcrafted finishes, garden rooms, and a close relation between interior and site.", phaseDescription: "Blackwell, often known as Blackwell: The Arts and Crafts House, demonstrates Baillie Scott's complete design approach to interiors, furnishings, and landscape." },
  "architect-robert-mallet-stevens": { name: "Robert Mallet-Stevens", period: "1886–1945", summary: "French modernist architect who represented interwar architecture through white geometric volumes, cinematic imagery, and carefully staged urban compositions.", principle: "Use abstract massing and technological precision to give contemporary life a clear visual identity.", feature: "White cubic volumes, roof terraces, ribbon windows, streamlined details, and scenographic approaches to streets and interiors.", phaseDescription: "Mallet-Stevens's own house and the Rue Mallet-Stevens ensemble made a powerful case for the French modernist domestic city." },
  "architect-thomas-farnolls-pritchard": { name: "Thomas Farnolls Pritchard", period: "1723–1777", summary: "English architect and designer associated with the early application of cast iron to bridge construction through the design of the Iron Bridge at Coalbrookdale.", principle: "Adapt the logic of timber joinery and arch construction to the possibilities of cast-iron members.", feature: "Segmental cast-iron arches, repeated ribs, bolted and wedged connections, and a structural language derived from carpentry.", phaseDescription: "The Iron Bridge at Coalbrookdale, executed with Abraham Darby III, was the first major cast-iron bridge and a landmark of industrial-age engineering." },
  "architect-thomas-james-waters": { name: "Thomas James Waters", period: "1842–1898", summary: "British engineer and architect who introduced Western construction methods and institutional building types to early Meiji Japan through the Osaka Mint and foreign-settlement work.", principle: "Adapt Western structural practice and institutional planning to new Japanese governmental and industrial programs.", feature: "Brick construction, classical facades, regular structural bays, industrial planning, and hybrid adaptation to local construction conditions.", phaseDescription: "The Osaka Mint Foundry entrance and Senpukan in Osaka are major early Meiji works linking imported engineering practice to Japan's modernization of industry and institutions." },
  "architect-august-endell": { name: "August Endell", period: "1871–1925", summary: "German architect and designer who developed Art Nouveau in the German-speaking world through curving ornament and immersive interior effects.", principle: "Make surface, line, color, and atmosphere active agents of spatial experience.", feature: "Abstract flowing reliefs, sinuous facades, colored interiors, highly integrated decoration, and theatrical sensory effects.", phaseDescription: "The Elvira Photography Studio in Munich was an early and radical German Art Nouveau facade, extending Jugendstil ornament into an abstract architectural language." },
  "architect-ivan-leonidov": { name: "Ivan Leonidov", period: "1902–1959", summary: "Russian Constructivist architect who imagined large public institutions as transparent structures connected by networks of communication, transport, and collective life.", principle: "Organize social programs as infrastructural systems rather than enclosed monumental masses.", feature: "Glass towers, cable-supported elements, elevated walkways, spheres, technical diagrams, and vast networked campuses.", phaseDescription: "The Lenin Institute project proposed an apparatus of libraries, auditoria, communications, and transport, becoming an iconic unbuilt image of Soviet Constructivism." },
  "architect-vladimir-tatlin": { name: "Vladimir Tatlin", period: "1885–1953", summary: "Russian artist and designer who joined spiral structure and revolutionary social program in the Monument to the Third International project.", principle: "Make dynamic structure and collective political communication inseparable.", feature: "Spiraling iron frameworks, inclined towers, transparent volumes, kinetic imagery, and a fusion of sculpture, engineering, and propaganda.", phaseDescription: "The Monument to the Third International, also known as Tatlin's Tower, became the best-known emblem of Constructivist ambition despite never being built." },
  "architect-el-lissitzky": { name: "El Lissitzky", period: "1890–1941", summary: "Russian artist, architect, and designer who connected horizontal and vertical composition with urban infrastructure, extending Constructivist expression across architecture and graphics.", principle: "Translate abstract spatial composition into instruments of collective urban and technological transformation.", feature: "Proun geometry, cantilevered horizontal elements, vertical supports, photomontage, graphic clarity, and infrastructural imagery.", phaseDescription: "The Wolkenbugel, or Horizontal Skyscraper, reimagined the high-rise as a cantilevered urban infrastructure and expanded Constructivist thinking beyond conventional towers." },
  "architect-hans-poelzig": { name: "Hans Poelzig", period: "1869–1936", summary: "German architect who used light and organic form to envelop immense theater interiors, becoming a leading figure of architectural Expressionism.", principle: "Shape collective interior experience through light, acoustics, and sculptural enclosure.", feature: "Cavernous auditoria, stalactite-like plaster forms, dramatic lighting, curved surfaces, and expressive massing.", phaseDescription: "The Grosses Schauspielhaus in Berlin transformed a former market hall into an immersive Expressionist theater and remains a canonical interwar interior." },
  "architect-philip-webb": { name: "Philip Webb", period: "1831–1915", summary: "English architect who established Arts and Crafts domestic principles by valuing materials, craft labor, and ordinary life.", principle: "Build from local material, honest workmanship, and the practical rituals of daily habitation.", feature: "Asymmetrical plans, red brick, steep roofs, vernacular references, handcrafted details, and close coordination of house and garden.", phaseDescription: "Standen House demonstrates Webb's mature Arts and Crafts approach, while the earlier Red House with William Morris established the movement's domestic ideal." },
  "architect-frank-gehry": { name: "Frank O. Gehry", period: "1929–", summary: "Canadian-American architect who expanded contemporary architectural expression through fragmented masses, material contrasts, and digital form-making.", principle: "Use construction, material collision, and digital modeling to turn ordinary programs into spatially charged compositions.", feature: "Fragmented volumes, exposed framing, corrugated metal, chain-link, titanium cladding, and complex digitally modeled surfaces.", phaseDescription: "Gehry's own house in Santa Monica established his strategy of transforming an existing suburban house through layered, deliberately unfinished-looking additions; later projects brought this language to major cultural buildings." },
  "architect-josiah-conder": { name: "Josiah Conder", period: "1852–1920", summary: "British architect and educator who trained Japanese architects at the Imperial College of Engineering and shaped Meiji institutional architecture and architectural education.", principle: "Adapt Western historical styles and professional education to Japan's new governmental, commercial, and religious institutions.", feature: "Brick and stone construction, historicist facades, formal planning, eclectic details, and teaching that connected design with modern professional practice.", phaseDescription: "Nikolai-do, or Holy Resurrection Cathedral in Tokyo, is a landmark of Conder's Meiji work; his teaching influenced Tatsuno Kingo and many later Japanese architects." },
  "architect-robert-smirke": { name: "Robert Smirke", period: "1780–1867", summary: "British Neoclassical architect who joined the colonnade of the Greek temple to the institutional authority of the modern museum at the British Museum.", principle: "Give new public institutions monumental clarity through archaeologically informed classical form.", feature: "Grand Ionic colonnades, symmetrical facades, temple fronts, restrained stone massing, and ordered museum planning.", phaseDescription: "The British Museum's Greek Revival facade became an enduring image of the national museum and a principal monument of British Neoclassicism." },
};
const make = ([id, ja, zh, years, summaryJa, summaryZh, buildingIds, related, regions = ["western"]]: Seed): ArchitectLearningCard => {
  const english = BATCH_FOUR_ENGLISH[id];
  return {
    id, kind: "architect", name: l(ja, zh, english.name), aliases: [], period: l(years, years, english.period), regions,
    summary: l(summaryJa, summaryZh, english.summary), lifeSummary: l(summaryJa, summaryZh, english.summary),
    designPrinciples: [l("技術・用途・表現を代表作の空間構成へ統合する。", "将技术、用途与表达整合进代表作的空间构成。", english.principle)],
    recurringFeatures: [l("時代の素材と社会的な要請に応答する設計。", "回应时代材料与社会需求的设计。", english.feature)],
    careerPhases: [{ label: l("代表作", "代表作", "Representative works and influence"), description: l(summaryJa, summaryZh, english.phaseDescription), buildingIds }],
    keywords: [], relatedBuildingIds: buildingIds, relatedPersonIds: [], relatedCardIds: related,
    influencedByIds: [], influencedIds: [], examEvidence: [], reviewStatus: "draft",
  };
};
const SEEDS: Seed[] = [
  ["architect-cfa-voysey", "C・F・A・ヴォイジー", "C. F. A. 沃伊西", "1857–1941", "素朴な材料、緩やかな屋根、生活に即した平面でアーツ・アンド・クラフツ住宅を展開した建築家。", "以朴素材料、缓坡屋顶和贴近生活的平面发展工艺美术住宅的建筑师。", ["building-4cdd0314017d"], ["movement-arts-crafts"]],
  ["architect-jjp-oud", "J・J・P・アウト", "J. J. P. 奥德", "1890–1963", "デ・ステイルの抽象性を都市住宅と公共建築へ展開し、近代建築の合理性を追求した建築家。", "将风格派抽象性发展至城市住宅和公共建筑、追求现代建筑理性的建筑师。", ["building-ab51368ef548"], ["movement-de-stijl", "movement-modernism"]],
  ["architect-louis-charles-boileau", "L・H・ボワロー", "路易-夏尔·布瓦洛", "1837–1914", "百貨店建築に鉄とガラスの技術を導入し、商業空間の大規模化に寄与した建築家。", "将铁和玻璃技术引入百货商店建筑、推动商业空间大规模化的建筑师。", ["building-4dc6e693a30b"], ["style-industrial-iron-glass"]],
  ["architect-mh-baillie-scott", "M・H・ベイリー・スコット", "M. H. 贝利·斯科特", "1865–1945", "住宅・家具・庭園を総合し、英国アーツ・アンド・クラフツの生活空間を形づくった建築家。", "综合住宅、家具和庭园，塑造英国工艺美术生活空间的建筑师。", ["building-5a0d1344f6ae"], ["movement-arts-crafts"]],
  ["architect-robert-mallet-stevens", "R・マレ＝ステヴァン", "罗贝尔·马莱-史蒂文斯", "1886–1945", "白い幾何学的量塊と映画的な都市イメージでフランス近代建築を代表した建築家。", "以白色几何体量和电影般城市意象代表法国现代建筑的建筑师。", ["building-e9b78591ea33"], ["movement-modernism", "style-international"]],
  ["architect-thomas-farnolls-pritchard", "T・F・プリチャード", "托马斯·法诺尔斯·普里查德", "1723–1777", "コールブルックデール橋の設計に関わり、鋳鉄を橋梁構造へ用いた初期の設計者。", "参与科尔布鲁克代尔桥设计，早期将铸铁用于桥梁结构的设计者。", ["building-f09e9fd36d8e"], ["style-industrial-iron-glass"]],
  ["architect-thomas-james-waters", "T・J・ウォートルス", "T. J. 沃特斯", "1842–1898", "明治初期の大阪造幣寮建築と居留地建築を通じ、西洋の構法と制度建築を日本へ導入した技師・設計者。", "通过明治初期大阪造币寮与居留地建筑，将西方构法和制度建筑引入日本的技师、设计者。", ["building-502b2e0291ba", "building-175c47d31146"], ["style-historicism"], ["japan"]],
  ["architect-august-endell", "アウグスト・エンデル", "奥古斯特·恩德尔", "1871–1925", "曲線的な装飾と室内の没入感によって、ドイツ語圏アール・ヌーヴォーを展開した建築家。", "以曲线装饰和沉浸式室内发展德语地区新艺术运动的建筑师。", ["building-64593260cffe"], ["movement-art-nouveau"]],
  ["architect-ivan-leonidov", "イワン・レオニドフ", "伊万·列昂尼多夫", "1902–1959", "大規模な公共施設を透明な構造と通信・交通のネットワークとして構想した構成主義の建築家。", "将大型公共设施构想为透明结构及通信、交通网络的构成主义建筑师。", ["building-1258b29b9ae4"], ["movement-constructivism"]],
  ["architect-vladimir-tatlin", "ウラジーミル・タトリン", "弗拉基米尔·塔特林", "1885–1953", "第三インターナショナル記念塔案で、螺旋構造と社会的プログラムを結びつけた芸術家・設計者。", "在第三国际纪念塔方案中结合螺旋结构与社会项目的艺术家、设计者。", ["building-8e7427eb86b1"], ["movement-constructivism"]],
  ["architect-el-lissitzky", "エル・リシツキー", "埃尔·利西茨基", "1890–1941", "水平・垂直の構成と都市インフラを結び、構成主義の建築的表現を拡張した芸術家・設計者。", "结合水平垂直构成与城市基础设施，扩展构成主义建筑表达的艺术家、设计者。", ["building-50be283146d2"], ["movement-constructivism"]],
  ["architect-hans-poelzig", "ハンス・ペルツィヒ", "汉斯·珀尔齐希", "1869–1936", "劇場の巨大な内部空間を光と有機的な造形で包み、ドイツ表現主義を代表した建築家。", "以光和有机造型包裹剧场巨大内部空间、代表德国表现主义的建筑师。", ["building-567a9fd73321"], ["style-expressionism"]],
  ["architect-philip-webb", "フィリップ・ウェブ", "菲利普·韦布", "1831–1915", "素材、職人仕事、日常生活を重視し、アーツ・アンド・クラフツの住宅原理を確立した建築家。", "重视材料、工匠劳动和日常生活，确立工艺美术住宅原则的建筑师。", ["building-2655faa28b18"], ["movement-arts-crafts"]],
  ["architect-frank-gehry", "フランク・O・ゲーリー", "弗兰克·盖里", "1929–", "断片化した量塊、素材の対比、デジタルな形態操作で現代建築の表現領域を広げた建築家。", "以碎片化体量、材料对比和数字形态操作拓展当代建筑表达领域的建筑师。", ["building-53cc2036fcbb"], ["movement-postmodernism"]],
  ["architect-josiah-conder", "ジョサイア・コンドル", "乔赛亚·康德", "1852–1920", "工部大学校で日本人建築家を育成し、明治期の制度建築と建築教育を形づくった建築家。", "在工部大学校培养日本建筑师，塑造明治时期制度建筑与建筑教育的建筑师。", ["building-cca8ea209149"], ["style-historicism"], ["japan"]],
  ["architect-robert-smirke", "ロバート・スメアーク", "罗伯特·斯默克", "1780–1867", "大英博物館でギリシア神殿の列柱と近代博物館の制度性を結びつけた新古典主義の建築家。", "在大英博物馆中结合希腊神庙柱廊与近代博物馆制度性的新古典主义建筑师。", ["building-983cf5798337"], ["style-neoclassical"]],
];
export const BATCH_FOUR_ARCHITECT_CARDS = SEEDS.map(make);
