import type { HistoryLearningCard } from "@/types/history-learning-card";

const l = (ja: string, zh: string, en: string) => ({ ja, zh, en });

export const HISTORY_LEARNING_CARD_EXAMPLES: HistoryLearningCard[] = [
  {
    id: "style-wayo",
    kind: "style",
    name: l("和様", "和样", "Wayō style"),
    aliases: ["和様建築"],
    period: l("平安時代以降", "平安时代以后", "From the Heian period onward"),
    regions: ["japan"],
    summary: l("大陸系寺院建築を日本の材料・技術・美意識に適応させて成立した寺院建築様式。", "大陆寺院建筑适应日本材料、技术与审美后形成的寺院建筑样式。", "A temple-building style formed by adapting continental Buddhist architecture to Japanese materials, techniques, and aesthetics."),
    formationBackground: l("奈良時代に導入された大陸様式が、平安期以降の国風文化と木材事情の中で日本化した。鎌倉期に大仏様・禅宗様が伝来した後、それらと区別するため和様と呼ばれた。", "奈良时代传入的大陆样式在平安时代以后随国风文化和木材条件逐渐日本化。镰仓时期大佛样、禅宗样传入后，为加以区别而称为和样。", "Continental styles introduced in the Nara period were adapted to the national culture and timber conditions of the Heian period and later. After Daibutsuyō and Zenshūyō arrived in the Kamakura period, this established Japanese tradition came to be called Wayō to distinguish it from them."),
    structuralFeatures: [
      l("柱上に組物を置く疎組を基本とする。", "斗栱主要设置于柱顶，形成疏组。", "It is based on sparse bracket complexes placed above the columns."),
      l("貫より長押を多用し、水平材で柱列を整える。", "较少依赖贯，更多使用长押整理柱列。", "Nageshi horizontal tie beams are used more extensively than penetrating tie beams to organize the column rows."),
      l("小屋組を天井裏に隠し、穏やかな架構表現をつくる。", "将屋架隐藏于天花之上，形成平稳的结构表达。", "The roof framing is concealed above the ceiling, producing a restrained structural expression."),
    ],
    spatialFeatures: [
      l("蔀戸・格子・板扉などによって内外を柔らかく分節する。", "以蔀户、格栅和板门柔和划分内外。", "Shutters, latticework, and board doors gently articulate the boundary between interior and exterior."),
      l("畳や天井を用いた水平性の強い内部空間を発達させた。", "发展出使用榻榻米与天花、强调水平性的室内空间。", "It developed strongly horizontal interiors using tatami and ceilings."),
    ],
    visualClues: [
      l("緩やかな屋根、疎らな組物、水平性の強い外観。", "缓和的屋顶、较疏的斗栱和强调水平线的外观。", "Look for gently pitched roofs, sparse bracket complexes, and an emphatically horizontal exterior."),
      l("禅宗様の花頭窓・詰組、大仏様の貫による力強い架構が前面に出ない。", "不像禅宗样突出花头窗与密集斗栱，也不像大佛样强调贯构成的强劲结构。", "It does not foreground the cusped windows and dense bracket complexes of Zenshūyō, nor the powerful penetrating-tie framing of Daibutsuyō."),
    ],
    keywords: [l("疎組", "疏组", "sparse bracket complex"), l("長押", "长押", "nageshi tie beam"), l("国風化", "日本化", "Japanization")],
    relatedBuildingIds: [],
    relatedPersonIds: [],
    relatedCardIds: ["style-daibutsuyo", "style-zenshuyo"],
    comparisonCardIds: ["style-daibutsuyo", "style-zenshuyo"],
    predecessorCardIds: [],
    successorCardIds: ["style-shinden", "style-shoin"],
    examEvidence: [],
    reviewStatus: "draft",
  },
  {
    id: "movement-arts-crafts",
    kind: "movement",
    name: l("アーツ・アンド・クラフツ運動", "工艺美术运动", "Arts and Crafts movement"),
    aliases: ["Arts and Crafts Movement"],
    period: l("19世紀後半〜20世紀初頭", "19世纪后半至20世纪初", "Late 19th to early 20th century"),
    regions: ["britain", "western"],
    summary: l("産業革命後の粗悪な量産品と労働疎外を批判し、手仕事・素材・生活芸術の統一を目指した運動。", "批判工业革命后粗劣量产品与劳动异化，追求手工艺、材料与生活艺术统一的运动。", "A movement that criticized poor mass-produced goods and alienated labour after the Industrial Revolution, seeking to unite craft, material, and the arts of everyday life."),
    socialBackground: [
      l("機械生産と大量消費の拡大。", "机器生产与大众消费扩张。", "The expansion of machine production and mass consumption."),
      l("職人の分業化と労働の疎外、製品品質の低下。", "工匠劳动被分割、劳动异化及产品质量下降。", "The division and alienation of craftspeople's labour, together with declining product quality."),
    ],
    reactionAgainst: [
      l("表面的な歴史様式の模倣。", "表面化的历史样式模仿。", "Superficial imitation of historical styles."),
      l("材料と構法を隠す粗悪な工業製品。", "掩盖材料和构造的粗劣工业产品。", "Poor industrial goods that conceal their materials and construction."),
    ],
    development: [
      l("ラスキンの中世職人社会への評価が思想的基盤となった。", "拉斯金对中世纪工匠社会的评价成为思想基础。", "John Ruskin's esteem for medieval craft society provided an intellectual foundation."),
      l("ウィリアム・モリスが制作・出版・住宅・室内を横断して実践した。", "威廉·莫里斯通过制作、出版、住宅与室内设计展开实践。", "William Morris put its principles into practice across making, publishing, houses, and interiors."),
      l("イギリスから欧米へ広がり、地域ごとの工芸復興を促した。", "从英国传播至欧美，推动各地工艺复兴。", "It spread from Britain through Europe and North America, encouraging local craft revivals."),
    ],
    principles: [
      l("素材と構法に対する誠実さ。", "忠实于材料与构造。", "Truthfulness to materials and construction."),
      l("芸術と日常生活の統一。", "艺术与日常生活统一。", "The unity of art and everyday life."),
      l("設計者と職人の協働。", "设计者与工匠协作。", "Collaboration between designers and craftspeople."),
    ],
    results: [
      l("住宅・家具・印刷を含む総合デザイン思想を確立した。", "确立涵盖住宅、家具和印刷的整体设计思想。", "It established an integrated design philosophy encompassing houses, furniture, and printing."),
      l("アール・ヌーヴォー、分離派、近代デザイン教育に影響した。", "影响新艺术、分离派与现代设计教育。", "It influenced Art Nouveau, the Secession movements, and modern design education."),
      l("手仕事重視と大衆への普及という理想の間に矛盾を残した。", "在重视手工与面向大众普及之间留下矛盾。", "It left an unresolved tension between valuing handwork and reaching a broad public."),
    ],
    keywords: [l("ジョン・ラスキン", "约翰·拉斯金", "John Ruskin"), l("ウィリアム・モリス", "威廉·莫里斯", "William Morris"), l("手工芸", "手工艺", "craftsmanship")],
    relatedBuildingIds: [],
    relatedPersonIds: ["person-john-ruskin", "person-william-morris"],
    relatedCardIds: ["movement-art-nouveau", "movement-vienna-secession", "movement-bauhaus"],
    influencedStyleIds: ["movement-art-nouveau"],
    influencedMovementIds: ["movement-vienna-secession", "movement-bauhaus"],
    examEvidence: [],
    reviewStatus: "draft",
  },
  {
    id: "architect-le-corbusier",
    kind: "architect",
    name: l("ル・コルビュジエ", "勒·柯布西耶", "Le Corbusier"),
    aliases: ["Le Corbusier", "シャルル＝エドゥアール・ジャンヌレ"],
    period: l("1887–1965", "1887–1965", "1887–1965"),
    regions: ["france", "global"],
    summary: l("住宅・都市・造形・構造を横断し、近代建築の原則を体系化するとともに、後期には彫塑的空間へ展開した建築家。", "横跨住宅、城市、造型与结构，系统化现代建筑原则，并在后期转向雕塑性空间的建筑师。", "An architect who worked across houses, cities, form, and structure; he systematized the principles of modern architecture before developing sculptural spaces in his later work."),
    lifeSummary: l("スイスに生まれ、パリを拠点に活動した。ピュリスム、住宅研究、都市計画を通じて機械時代の建築を提案し、戦後は粗いコンクリートと彫塑的形態へ展開した。", "生于瑞士，以巴黎为主要据点。通过纯粹主义、住宅研究和城市规划提出机器时代建筑，战后转向粗野混凝土与雕塑性形态。", "Born in Switzerland and active chiefly from Paris, he proposed an architecture for the machine age through Purism, housing research, and urban planning; after the war he turned to rough concrete and sculptural form."),
    designPrinciples: [
      l("近代建築の五原則。", "现代建筑五原则。", "The Five Points of a New Architecture."),
      l("ドミノ・システムによる構造と間仕切りの分離。", "通过多米诺体系分离结构与隔墙。", "The Dom-Ino system's separation of structure and partitions."),
      l("モデュロールによる人体寸法と比例の体系化。", "以模度体系化人体尺度与比例。", "The Modulor's systematization of human dimensions and proportion."),
    ],
    recurringFeatures: [
      l("自由な平面と動線による建築的プロムナード。", "以自由平面和流线形成建筑漫步。", "The architectural promenade created through the free plan and movement paths."),
      l("光を空間構成の中心に置く。", "将光置于空间构成中心。", "Light placed at the centre of spatial composition."),
      l("個別建築と都市モデルを一体として考える。", "将单体建筑与城市模型整体思考。", "Individual buildings and urban models conceived as one integrated problem."),
    ],
    careerPhases: [
      { label: l("初期近代主義", "早期现代主义", "Early modernism"), description: l("白い幾何学的ヴォリュームと五原則を実験。", "实验白色几何体量与五原则。", "Experiments with white geometric volumes and the Five Points."), buildingIds: [] },
      { label: l("集合住宅・都市", "集合住宅与城市", "Collective housing and the city"), description: l("標準化住戸と共同施設を垂直都市として統合。", "将标准化住宅和公共设施整合为垂直城市。", "Integration of standardized dwellings and collective facilities as a vertical city."), buildingIds: [] },
      { label: l("後期の彫塑性", "后期雕塑性", "Late sculptural work"), description: l("打放しコンクリート、曲面、象徴的な光を展開。", "发展清水混凝土、曲面和象征性光线。", "Development of exposed concrete, curved surfaces, and symbolic light."), buildingIds: [] },
    ],
    keywords: [l("五原則", "五原则", "Five Points"), l("ドミノ・システム", "多米诺体系", "Dom-Ino system"), l("モデュロール", "模度", "Modulor")],
    relatedBuildingIds: [],
    relatedPersonIds: [],
    relatedCardIds: ["movement-modernism", "style-international", "theory-five-points"],
    influencedByIds: ["person-auguste-perret", "person-peter-behrens"],
    influencedIds: [],
    examEvidence: [],
    reviewStatus: "draft",
  },
];
