import type { ArchitectLearningCard } from "@/types/history-learning-card";

type WesternEnglish = { name:string; period:string; summary:string; designPrinciples:string[]; recurringFeatures:string[]; careerPhases:[string,string][] };
const l = (ja: string, zh: string, en?: string) => ({ ja, zh, ...(en ? { en } : {}) });
const make = (id: string, ja: string, zh: string, years: string, summary: [string,string], principles: [string,string][], features: [string,string][], phases: [string,string,string,string][], related: string[], influencedBy: string[] = [], influenced: string[] = [], english?: WesternEnglish): ArchitectLearningCard => ({
  id, kind:"architect", name:l(ja,zh,english?.name), aliases:[], period:l(years,years,english?.period), regions:["western"], summary:l(summary[0],summary[1],english?.summary), lifeSummary:l(summary[0],summary[1],english?.summary),
  designPrinciples:principles.map((x,index)=>l(x[0],x[1],english?.designPrinciples[index])), recurringFeatures:features.map((x,index)=>l(x[0],x[1],english?.recurringFeatures[index])),
  careerPhases:phases.map(([a,b,c,d],index)=>({label:l(a,b,english?.careerPhases[index]?.[0]),description:l(c,d,english?.careerPhases[index]?.[1]),buildingIds:[]})),
  keywords:[], relatedBuildingIds:[], relatedPersonIds:[], relatedCardIds:related, influencedByIds:influencedBy, influencedIds:influenced,
  examEvidence:[], reviewStatus:"draft",
});

export const WESTERN_ARCHITECT_CARDS_2: ArchitectLearningCard[] = [
  make("architect-leon-battista-alberti","レオン・バッティスタ・アルベルティ","莱昂·巴蒂斯塔·阿尔伯蒂","1404–1472",
    ["人文主義、数学、古代研究を建築理論とファサード設計へ統合し、ルネサンス建築を言語化した建築家・理論家。","将人文主义、数学和古代研究整合进建筑理论与立面设计，并将文艺复兴建筑系统化的建筑师、理论家。"],
    [["美・用・強の統合と比例秩序。","整合美、用、坚固与比例秩序。"],["既存建築へ古典的ファサードを重ねる。","在既有建筑上叠加古典立面。"]],
    [["オーダーと幾何学で異なる部分を統一。","以柱式与几何统一不同部分。"],["著作と実作を相互に補完。","理论著作与实践相互补充。"]],
    [["人文主義理論","人文主义理论","『建築論』で古代建築を同時代へ翻訳。","以《建筑论》将古代建筑转译至当代。"],["宮殿と教会","宫殿与教堂","都市ファサードに古典秩序を導入。","向城市立面引入古典秩序。"]],
    ["style-renaissance"],["architect-filippo-brunelleschi","style-roman"],["architect-andrea-palladio"],
    { name:"Leon Battista Alberti", period:"1404-1472", summary:"An architect and theorist who integrated humanism, mathematics, and the study of antiquity into architectural theory and facade design, systematizing Renaissance architecture.", designPrinciples:["A proportional order uniting beauty, utility, and firmness.","Classical facades layered onto existing buildings."], recurringFeatures:["Orders and geometry unify diverse parts.","Theoretical writing and built work mutually reinforce one another."], careerPhases:[["Humanist theory","De re aedificatoria translated ancient architecture for the contemporary world."],["Palaces and churches","Classical order was introduced into urban facades."]] }),
  make("architect-francesco-borromini","フランチェスコ・ボッロミーニ","弗朗切斯科·博罗米尼","1599–1667",
    ["複雑な幾何学、波動する壁面、光によってバロック空間を内側から生成した建築家。","以复杂几何、波动墙面和光线从内部生成巴洛克空间的建筑师。"],
    [["円・楕円・三角形を重ねる生成的幾何学。","叠加圆、椭圆与三角形的生成性几何。"],["装飾を貼るのでなく構造面そのものを動かす。","不附加装饰，而使结构表面本身运动。"]],
    [["凹凸が連続するファサード。","连续凹凸的立面。"],["小敷地でも光と曲面で伸縮する内部。","在狭小场地以光与曲面形成伸缩内部。"]],
    [["修業期","学习期","マデルノのもとで石工・製図・施工を修得。","在马代尔诺手下掌握石工、制图和施工。"],["独自の教会空間","独特教堂空间","サン・カルロ、サンティーヴォで幾何学を展開。","在圣卡洛与圣伊沃发展几何空间。"]],
    ["style-baroque"],["style-baroque"],[],
    { name:"Francesco Borromini", period:"1599-1667", summary:"An architect who generated Baroque space from complex geometry, undulating walls, and light.", designPrinciples:["Generative geometry layering circles, ellipses, and triangles.","Structural surfaces set in motion rather than applied ornament."], recurringFeatures:["Continuously concave and convex facades.","Interiors expanded and compressed by light and curved surfaces on small sites."], careerPhases:[["Training","Learned stonework, drawing, and construction under Carlo Maderno in Rome."],["Independent churches","Developed geometric church spaces at San Carlo alle Quattro Fontane and Sant'Ivo alla Sapienza."]] }),
  make("architect-otto-wagner","オットー・ワーグナー","奥托·瓦格纳","1841–1918",
    ["歴史主義から分離派・近代建築へ移行し、都市交通、材料、機能に対応する『現代建築』を唱えた建築家。","从历史主义转向分离派与现代建筑，倡导适应城市交通、材料和功能的‘现代建筑’的建筑师。"],
    [["現代生活と実用から形態を導く。","从现代生活和实用性导出形式。"],["新材料と接合部を意匠として可視化。","将新材料及节点作为设计显现。"]],
    [["軸線的で明快な平面。","轴线明确的平面。"],["石板留め金具、アルミ、ガラスなど表皮の技術表現。","以石板固定件、铝和玻璃表现表皮技术。"]],
    [["歴史主義期","历史主义时期","都市住宅と記念建築で折衷様式を使用。","在城市住宅与纪念建筑中使用折衷样式。"],["都市鉄道と分離派","城市铁路与分离派","交通施設と集合住宅を近代化。","推动交通设施与集合住宅现代化。"],["成熟した現代建築","成熟现代建筑","郵便貯金局で機能・材料・表現を統合。","在邮政储蓄银行整合功能、材料与表达。"]],
    ["movement-vienna-secession","movement-modernism"],["style-historicism"],["movement-vienna-secession"],
    { name:"Otto Wagner", period:"1841-1918", summary:"An architect who moved from historicism toward the Vienna Secession and modern architecture, advocating forms responsive to urban transport, materials, and function.", designPrinciples:["Form derived from modern life and utility.","New materials and joints made visible as design expression."], recurringFeatures:["Axial, lucid plans.","Technical expression in stone panels, aluminium, glass, and ceramic surfaces."], careerPhases:[["Historicism","Eclectic styles in urban housing and commemorative buildings."],["Urban railway and Secession","Modernized transport facilities and collective housing."],["Mature modern architecture","The Postal Savings Bank united function, material, and expression."]] }),
  make("architect-mies-van-der-rohe","ミース・ファン・デル・ローエ","路德维希·密斯·凡·德·罗","1886–1969",
    ["最小限の構造、自由な平面、精密なディテールによって普遍的空間を追求した近代建築家。","以最少结构、自由平面和精密细部追求普遍空间的现代建筑师。"],
    [["少ないことは豊かなこと。","少即是多。"],["構造フレームと非耐力壁を分離する。","分离结构框架与非承重墙。"]],
    [["十字柱、薄い屋根、連続ガラス面。","十字柱、薄屋面与连续玻璃面。"],["石・金属・ガラスを極端に精密に納める。","以极高精度处理石材、金属和玻璃。"]],
    [["欧州前衛期","欧洲先锋时期","住宅案と展覧会で流動空間を確立。","通过住宅方案与展览确立流动空间。"],["バウハウス末期","包豪斯末期","教育と近代建築運動を統率。","领导教育与现代建筑运动。"],["米国高層期","美国高层时期","普遍的グリッドとガラス高層を体系化。","系统化通用网格与玻璃高层。"]],
    ["movement-bauhaus","movement-modernism","style-international"],["person-peter-behrens","movement-de-stijl"],[],
    { name:"Ludwig Mies van der Rohe", period:"1886-1969", summary:"A modern architect who pursued universal space through minimal structure, free plans, and exacting detail.", designPrinciples:["Less is more.","Structural frame separated from non-load-bearing walls."], recurringFeatures:["Cruciform columns, thin roof planes, and continuous glass.", "Stone, metal, and glass finished with exceptional precision."], careerPhases:[["European avant-garde","Houses and exhibition projects established flowing space."],["Late Bauhaus","Led architectural education and the modern movement."],["American high-rise period","Systematized the universal grid and glass tower."]] }),
  make("architect-louis-kahn","ルイス・カーン","路易·康","1901–1974",
    ["近代建築の構造合理性に記念性、光、制度の原型を重ね、重厚な空間秩序を再構築した建築家。","在现代建筑结构理性上叠加纪念性、光线和制度原型，重构厚重空间秩序的建筑师。"],
    [["建物が何になりたいかを問う。","追问建筑想成为什么。"],["サーブド・スペースとサーバント・スペースを分離。","分离被服务空间与服务空间。"]],
    [["幾何学的な室群と厚い壁。","几何房间群与厚墙。"],["構造体と光の入口を一致させる。","使结构体与采光入口一致。"]],
    [["近代主義的形成期","现代主义形成期","都市計画と共同設計を経験。","经历城市规划与协作设计。"],["研究施設","研究设施","リチャーズ研究所で機能単位を外部化。","在理查兹研究所中外显功能单元。"],["記念的成熟期","纪念性成熟期","議会・美術館・研究所で光と秩序を深化。","在议会、美术馆和研究所中深化光与秩序。"]],
    ["movement-modernism"],["architect-le-corbusier","ancient-monumentality"],[],
    { name:"Louis I. Kahn", period:"1901-1974", summary:"An architect who reconstituted a weighty spatial order by joining modern structural rationality with monumentality, light, and institutional archetypes.", designPrinciples:["Ask what a building wants to be.","Separate served spaces from servant spaces."], recurringFeatures:["Geometric room groups and thick walls.","Structural bodies aligned with openings for light."], careerPhases:[["Formation in modernism","Work in urban planning and collaborative practice."],["Research facilities","The Salk Institute externalized functional units."],["Mature monumentality","Assemblies, museums, and laboratories deepened his use of light and order."]] }),
  make("architect-adolf-loos","アドルフ・ロース","阿道夫·路斯","1870–1933",
    ["装飾批判とラウムプランによって、外観の静けさと内部の複雑な生活空間を対置した近代建築家。","以装饰批判和空间体量规划，将安静外观与复杂生活内部并置的现代建筑师。"],
    [["装飾を文化的浪費として批判。","批判装饰为文化浪费。"],["床レベルと室高を用途ごとに組むラウムプラン。","按用途组合楼层标高与层高的空间体量规划。"]],
    [["街路側は平滑で抑制された外観。","临街面平滑克制。"],["内部は大理石・木材と段差で豊かな空間を形成。","内部以大理石、木材和高差形成丰富空间。"]],
    [["文化批評期","文化批评期","文章と店舗改装で装飾と近代生活を論じる。","通过文章和店铺改造讨论装饰与现代生活。"],["ラウムプラン住宅","空间体量住宅","ミュラー邸などで立体的生活空間を完成。","在米勒住宅等作品中完成立体生活空间。"]],
    ["movement-modernism"],["person-otto-wagner","english-domestic-architecture"],[],
    { name:"Adolf Loos", period:"1870-1933", summary:"A modern architect who juxtaposed restrained exteriors with richly articulated interiors through his critique of ornament and the Raumplan.", designPrinciples:["Ornament criticized as cultural waste.","Spatial volumes organized by use through varied floor and ceiling levels."], recurringFeatures:["Smooth, restrained street facades.","Rich interiors of marble, timber, and interlocking levels."], careerPhases:[["Cultural criticism","Essays and shop interiors debated ornament and modern life."],["Raumplan houses","Houses such as the Muller House developed three-dimensional living space."]] }),
];
