import type { MovementLearningCard } from "@/types/history-learning-card";

type MovementEnglish = {
  name: string; period: string; summary: string; socialBackground: string[];
  reactionAgainst: string[]; development: string[]; principles: string[]; results: string[];
};
const l = (ja: string, zh: string, en?: string) => ({ ja, zh, ...(en ? { en } : {}) });
const ls = (items: [string, string][], english?: string[]) => items.map(([ja, zh], index) => l(ja, zh, english?.[index]));
const movement = (
  id: string, ja: string, zh: string, periodJa: string, periodZh: string,
  summary: [string, string], background: [string, string][], against: [string, string][],
  development: [string, string][], principles: [string, string][], results: [string, string][],
  people: string[], buildings: string[], related: string[], styles: string[], movements: string[], english?: MovementEnglish,
): MovementLearningCard => ({
  id, kind: "movement", name: l(ja, zh, english?.name), aliases: [], period: l(periodJa, periodZh, english?.period), regions: ["western", "global"],
  summary: l(summary[0], summary[1], english?.summary), socialBackground: ls(background, english?.socialBackground), reactionAgainst: ls(against, english?.reactionAgainst), development: ls(development, english?.development),
  principles: ls(principles, english?.principles), results: ls(results, english?.results), keywords: [], relatedPersonIds: people,
  relatedBuildingIds: buildings, relatedCardIds: related, influencedStyleIds: styles,
  influencedMovementIds: movements, examEvidence: [], reviewStatus: "draft",
});

export const HISTORY_MOVEMENT_CARDS: MovementLearningCard[] = [
  movement(
    "movement-art-nouveau", "アール・ヌーヴォー", "新艺术运动", "1890年代〜1910年代", "19世纪90年代至20世纪10年代",
    ["植物的曲線、新材料、工芸を統合し、歴史様式に依存しない近代生活の総合芸術を目指した国際的運動。", "以植物曲线、新材料和工艺为基础，追求不依赖历史样式的现代生活总体艺术。"],
    [["産業化した都市と新しい中産階級の成長。", "工业化城市和新中产阶级成长。"], ["鉄・ガラス・鋳鉄など新材料の普及。", "铁、玻璃和铸铁等新材料普及。"]],
    [["歴史主義による過去様式の反復。", "历史主义对过去样式的重复。"], ["芸術、工芸、家具、建築の分離。", "艺术、工艺、家具和建筑彼此分离。"]],
    [["ブリュッセル、パリ、バルセロナ、ウィーンなどで地域的展開。", "在布鲁塞尔、巴黎、巴塞罗那和维也纳等地形成地域性发展。"], ["建築から家具・ポスター・地下鉄入口まで一体的に設計。", "从建筑到家具、海报和地铁入口进行整体设计。"]],
    [["自然形態を抽象化した連続曲線。", "抽象自然形态的连续曲线。"], ["構造材を装飾と空間表現に用いる。", "将结构材料用于装饰和空间表达。"]],
    [["近代的な総合デザインを普及させた。", "普及现代总体设计。"], ["分離派、初期モダニズム、装飾芸術へ展開した。", "发展并影响分离派、早期现代主义和装饰艺术。"]],
    [], [],
    ["movement-arts-crafts", "movement-vienna-secession", "movement-modernism"], ["style-art-deco"], ["movement-vienna-secession", "movement-modernism"],
    {
      name: "Art Nouveau", period: "1890s to 1910s",
      summary: "An international movement that sought a total art for modern life, combining plant-like curves, new materials, and craft without dependence on historical styles.",
      socialBackground: ["Industrializing cities and the growth of a new middle class.", "The widespread availability of new materials such as iron, glass, and cast iron."],
      reactionAgainst: ["Historicist repetition of styles from the past.", "The separation of art, craft, furniture, and architecture."],
      development: ["Regional variants developed in Brussels, Paris, Barcelona, Vienna, and elsewhere.", "It pursued integrated design from buildings to furniture, posters, and underground-station entrances."],
      principles: ["Continuous curves abstracted from natural forms.", "Structural materials used as ornament and spatial expression."],
      results: ["It disseminated the modern ideal of total design.", "It developed into the Secession, early modernism, and Art Deco."],
    }),
  movement(
    "movement-vienna-secession", "ウィーン分離派", "维也纳分离派", "1897年以降", "1897年以后",
    ["保守的な美術制度から離脱し、建築・美術・工芸を統合して時代にふさわしい芸術をつくろうとした運動。", "脱离保守艺术制度，整合建筑、美术与工艺，创造符合时代精神的艺术运动。"],
    [["世紀末ウィーンの都市文化と環状道路建設後の歴史主義。", "世纪末维也纳城市文化及环城大道建成后的历史主义。"], ["新しい市民文化と芸術家組織の台頭。", "新市民文化与艺术家组织兴起。"]],
    [["官展とアカデミーの保守性。", "官方展览与学院体系的保守性。"], ["無批判な歴史様式の模倣。", "无批判的历史样式模仿。"]],
    [["クリムト、オルブリヒらが分離派を結成。", "克里姆特、奥尔布里希等成立分离派。"], ["ワーグナーとホフマンが建築・都市・家具を近代化。", "瓦格纳和霍夫曼推动建筑、城市与家具现代化。"]],
    [["『時代にはその芸術を、芸術にはその自由を』。", "‘时代有其艺术，艺术有其自由。’"], ["幾何学化した装飾と材料に即した表現。", "几何化装饰与符合材料特性的表达。"]],
    [["新艺术的曲线を幾何学化し、近代デザインへ接続した。", "将新艺术曲线几何化，并连接到现代设计。"], ["ウィーン工房と近代的総合デザインに影響した。", "影响维也纳工坊与现代总体设计。"]],
    ["architect-otto-wagner"], [],
    ["movement-art-nouveau", "movement-modernism"], ["style-art-deco"], ["movement-modernism", "movement-bauhaus"],
    {
      name: "Vienna Secession", period: "From 1897",
      summary: "A movement that broke from conservative art institutions to unite architecture, fine art, and craft in an art appropriate to its age.",
      socialBackground: ["Fin-de-siecle Viennese urban culture and the historicism of the Ringstrasse era.", "The rise of a new bourgeois culture and artists' organizations."],
      reactionAgainst: ["The conservatism of official exhibitions and the academy.", "Uncritical imitation of historical styles."],
      development: ["Gustav Klimt, Joseph Maria Olbrich, and others founded the Secession.", "Otto Wagner and Josef Hoffmann modernized architecture, urban design, and furniture."],
      principles: ["To every age its art; to art its freedom.", "Geometrized ornament and expression appropriate to materials."],
      results: ["It geometrized Art Nouveau curves and connected them to modern design.", "It influenced the Wiener Werkstatte and modern total design."],
    }),
  movement(
    "movement-de-stijl", "デ・ステイル", "风格派", "1917〜1930年代", "1917年至20世纪30年代",
    ["垂直・水平、三原色、非対称な均衡によって普遍的な造形秩序を追求したオランダの運動。", "通过垂直水平、三原色与非对称平衡追求普遍造型秩序的荷兰运动。"],
    [["第一次世界大戦下での普遍的秩序への希求。", "第一次世界大战时期对普遍秩序的追求。"], ["抽象絵画と近代建築の接近。", "抽象绘画与现代建筑相互接近。"]],
    [["自然形態の再現と個人的表現。", "对自然形态的再现和个人化表达。"], ["閉じた箱としての伝統的建築。", "作为封闭盒子的传统建筑。"]],
    [["モンドリアン、ドゥースブルフ、リートフェルトらが雑誌を中心に活動。", "蒙德里安、杜斯堡和里特维尔德等围绕杂志展开活动。"], ["絵画の原理を家具・住宅・都市へ展開。", "将绘画原则扩展至家具、住宅与城市。"]],
    [["直交する線と面、三原色と無彩色。", "正交线面、三原色与无彩色。"], ["面を分解し、内外が浸透する非対称空間。", "分解平面，形成内外渗透的非对称空间。"]],
    [["近代建築の抽象的構成に強い影響を与えた。", "强烈影响现代建筑的抽象构成。"], ["バウハウス、ミース、構成主義との交流を生んだ。", "促进与包豪斯、密斯和构成主义的交流。"]],
    [], [],
    ["movement-modernism", "movement-bauhaus"], ["style-international"], ["movement-bauhaus", "movement-modernism"],
    {
      name: "De Stijl", period: "1917 to the 1930s",
      summary: "A Dutch movement that sought a universal visual order through vertical and horizontal lines, primary colours, and asymmetrical balance.",
      socialBackground: ["A search for universal order during the First World War.", "The convergence of abstract painting and modern architecture."],
      reactionAgainst: ["Representation of natural forms and individual expression.", "Traditional architecture conceived as a closed box."],
      development: ["Piet Mondrian, Theo van Doesburg, Gerrit Rietveld, and others worked around the journal De Stijl.", "Its pictorial principles were extended to furniture, houses, and the city."],
      principles: ["Orthogonal lines and planes, primary colours, and non-colours.", "Decomposed planes and asymmetrical space in which interior and exterior interpenetrate."],
      results: ["It strongly influenced abstract composition in modern architecture.", "It fostered exchanges with the Bauhaus, Mies van der Rohe, and Constructivism."],
    }),
  movement(
    "movement-constructivism", "ロシア構成主義", "俄国构成主义", "1910年代後半〜1930年代初頭", "20世纪10年代后半至30年代初",
    ["革命後の新社会を、工業材料、動的構成、集団生活の新しいプログラムによって可視化しようとした前衛運動。", "以工业材料、动态构成和集体生活新功能将革命后新社会可视化的先锋运动。"],
    [["ロシア革命と社会制度の再編。", "俄国革命与社会制度重组。"], ["工業化、宣伝媒体、集団生活施設への需要。", "工业化、宣传媒介和集体生活设施需求。"]],
    [["ブルジョワ的な芸術作品と歴史装飾。", "资产阶级艺术品与历史装饰。"], ["芸術を自律的対象とする考え。", "将艺术视为自治对象的观念。"]],
    [["タトリンらが材料の構成そのものを芸術とした。", "塔特林等将材料构成本身视为艺术。"], ["ヴェスニン兄弟、メーリニコフらがクラブ・集合住宅・行政施設を提案。", "维斯宁兄弟、梅尔尼科夫等设计俱乐部、集合住宅和行政设施。"]],
    [["機能、構造、工業生産の統合。", "功能、结构与工业生产整合。"], ["斜線、片持ち、交差体による動的形態。", "以斜线、悬挑和交叉体形成动态形态。"]],
    [["短期間で国家的古典主義に置き換えられた。", "短期内被国家古典主义取代。"], ["後のハイテク、脱構築、視覚文化に再評価された。", "后来被高技派、解构主义和视觉文化重新评价。"]],
    [], [],
    ["movement-modernism", "movement-bauhaus"], ["style-expressionism"], ["movement-modernism"],
    { name: "Russian Constructivism", period: "Late 1910s to early 1930s", summary: "An avant-garde movement that sought to visualize the new post-revolutionary society through industrial materials, dynamic composition, and programmes for collective life.", socialBackground: ["The Russian Revolution and the reorganization of social institutions.", "Industrialization, propaganda media, and demand for collective facilities."], reactionAgainst: ["Bourgeois art objects and historical ornament.", "The idea of art as an autonomous object."], development: ["Vladimir Tatlin and others treated material construction itself as art.", "The Vesnin brothers and Konstantin Melnikov proposed clubs, collective housing, and administrative buildings."], principles: ["Integration of function, structure, and industrial production.", "Dynamic forms using diagonals, cantilevers, and intersecting volumes."], results: ["It was rapidly displaced by state classicism.", "It was later reappraised by High Tech, Deconstructivism, and visual culture."] }),
  movement(
    "movement-bauhaus", "バウハウス", "包豪斯", "1919〜1933年", "1919至1933年",
    ["芸術・工芸・建築教育を統合し、工業生産と生活環境の近代化を担う設計者を育成した学校・運動。", "整合艺术、工艺与建筑教育，培养推动工业生产和生活环境现代化设计者的学校与运动。"],
    [["第一次世界大戦後の社会再建と住宅不足。", "第一次世界大战后的社会重建与住宅短缺。"], ["工芸教育と工業生産を結びつける必要。", "需要连接工艺教育与工业生产。"]],
    [["アカデミックな美術教育。", "学院式美术教育。"], ["芸術、工芸、建築の専門分離。", "艺术、工艺和建筑的专业分离。"]],
    [["グロピウスがワイマールで創設。", "格罗皮乌斯在魏玛创立。"], ["デッサウ移転後、工業デザインと建築教育を強化。", "迁至德绍后强化工业设计与建筑教育。"], ["ナチスの圧力で閉鎖され、教師・学生が各国へ移住。", "因纳粹压力关闭，师生迁往各国。"]],
    [["基礎教育、工房、建築の統合。", "基础教育、工坊与建筑整合。"], ["標準化と量産を通じた良質な生活環境。", "通过标准化与量产创造优质生活环境。"]],
    [["近代デザイン教育の国際的モデルとなった。", "成为国际现代设计教育模式。"], ["国際様式、企業デザイン、戦後教育へ広がった。", "扩展至国际主义、企业设计和战后教育。"]],
    ["architect-walter-gropius", "architect-mies-van-der-rohe"], [],
    ["movement-arts-crafts", "movement-de-stijl", "movement-modernism"], ["style-international"], ["movement-modernism"],
    { name: "Bauhaus", period: "1919 to 1933", summary: "A school and movement that integrated art, craft, and architectural education to train designers for industrial production and modern life.", socialBackground: ["Post-First World War reconstruction and housing shortages.", "The need to connect craft education with industrial production."], reactionAgainst: ["Academic fine-art education.", "The specialization that separated art, craft, and architecture."], development: ["Walter Gropius founded the school in Weimar.", "After moving to Dessau, it strengthened industrial design and architectural education.", "Nazi pressure closed the school, dispersing its teachers and students internationally."], principles: ["Integration of foundation instruction, workshops, and architecture.", "A high-quality living environment through standardization and mass production."], results: ["It became an international model for modern design education.", "Its influence extended to the International Style, corporate design, and postwar education."] }),
  movement(
    "movement-modernism", "近代建築運動・モダニズム", "现代建筑运动与现代主义", "1910年代〜1960年代", "20世纪10年代至60年代",
    ["工業化社会に対応し、機能・構造・標準化・普遍的空間によって建築を再編した国際的運動。", "为回应工业社会，以功能、结构、标准化和普遍空间重组建筑的国际运动。"],
    [["鉄・ガラス・鉄筋コンクリートと大量生産。", "钢铁、玻璃、钢筋混凝土与大规模生产。"], ["都市人口増加、住宅不足、衛生問題。", "城市人口增长、住宅短缺和卫生问题。"]],
    [["歴史様式の模倣と表面的装飾。", "历史样式模仿与表面装饰。"], ["職人的一品生産だけに依存する建築。", "只依赖手工单件生产的建筑。"]],
    [["欧州各地の前衛運動、バウハウス、ル・コルビュジエ、CIAMが理論と実践を共有。", "欧洲各先锋运动、包豪斯、勒·柯布西耶和CIAM共享理论与实践。"], ["戦後復興と企業・公共建築を通じて世界化。", "通过战后重建、企业和公共建筑走向全球。"]],
    [["形態は機能・構造から導く。", "形式由功能和结构导出。"], ["自由な平面、均質空間、標準化、装飾の抑制。", "自由平面、均质空间、标准化和装饰抑制。"]],
    [["住宅・都市・デザインの共通言語を形成。", "形成住宅、城市和设计的共同语言。"], ["画一性や地域性の喪失への批判から、地域主義・ポストモダンなどを生んだ。", "对单一化和地域性丧失的批评催生地域主义与后现代。"]],
    ["architect-le-corbusier", "architect-walter-gropius", "architect-mies-van-der-rohe"], [],
    ["movement-bauhaus", "movement-de-stijl", "movement-constructivism", "movement-metabolism", "movement-postmodernism"],
    ["style-international"], ["movement-metabolism", "movement-postmodernism"],
    { name: "Modern Movement", period: "1910s to 1960s", summary: "An international movement that reorganized architecture for industrial society through function, structure, standardization, and universal space.", socialBackground: ["Steel, glass, reinforced concrete, and mass production.", "Urban population growth, housing shortages, and sanitary problems."], reactionAgainst: ["Imitation of historical styles and applied ornament.", "Architecture dependent solely on handcrafted one-off production."], development: ["European avant-gardes, the Bauhaus, Le Corbusier, and CIAM shared theory and practice.", "It became global through postwar reconstruction and corporate and public building."], principles: ["Form is derived from function and structure.", "Free plans, homogeneous space, standardization, and restraint of ornament."], results: ["It created a common language for housing, cities, and design.", "Criticism of uniformity and lost regional identity generated regionalism and postmodernism."] }),
  {
    ...movement(
      "movement-metabolism", "メタボリズム", "新陈代谢派", "1960年代〜1970年代", "20世纪60至70年代",
      ["都市と建築を成長・交換・更新する生命体として捉え、恒久的な基盤と交換可能な単位を組み合わせた日本の運動。", "将城市和建筑视为成长、交换、更新的生命体，组合永久基础设施与可替换单元的日本运动。"],
      [["戦後復興、高度経済成長、人口の都市集中。", "战后重建、高速经济增长与人口城市集中。"], ["急速に変化する日本社会と大規模国土開発。", "快速变化的日本社会与大规模国土开发。"]],
      [["固定的で完成形を前提とする近代都市計画。", "以固定完成形为前提的现代城市规划。"], ["均質な国際様式と西欧中心の近代主義。", "均质国际主义及西欧中心现代主义。"]],
      [["1960年世界デザイン会議で宣言を発表。", "在1960年世界设计会议上发表宣言。"], ["海上都市、空中都市、カプセルなどの計画を提案。", "提出海上城市、空中城市和胶囊等计划。"], ["大阪万博で実験的構造と都市像を実現。", "在大阪世博会中实现实验性结构与城市图景。"]],
      [["成長、変化、交換可能性。", "成长、变化和可替换性。"], ["メガストラクチャーと小単位の階層。", "巨型结构与小单元的层级。"]],
      [["実現例は限定されたが、日本建築を国際的議論へ押し上げた。", "虽实现案例有限，但将日本建筑推向国际讨论。"], ["可変建築、メガストラクチャー、持続可能性の議論へ影響。", "影响可变建筑、巨型结构和可持续性讨论。"]],
      ["architect-kenzo-tange", "architect-kisho-kurokawa", "architect-kiyonori-kikutake"], [],
      ["movement-modernism", "movement-postmodernism"], [], ["movement-postmodernism"],
      { name: "Metabolism", period: "1960s to 1970s", summary: "A Japanese movement that conceived cities and architecture as living systems of growth, replacement, and renewal, combining permanent infrastructure with replaceable units.", socialBackground: ["Postwar reconstruction, rapid economic growth, and urban concentration.", "Rapid social change in Japan and large-scale national development."], reactionAgainst: ["Modern urban planning premised on a fixed finished form.", "Homogeneous International Style modernism centred on Western Europe."], development: ["It issued its manifesto at the 1960 World Design Conference.", "It proposed marine cities, aerial cities, and capsule systems.", "Experimental structures and urban images were realized at Expo '70 in Osaka."], principles: ["Growth, change, and replaceability.", "A hierarchy of megastructures and small units."], results: ["Built examples were limited, but it brought Japanese architecture into international debate.", "It influenced discussions of adaptable architecture, megastructures, and sustainability."] }),
    regions: ["japan", "global"],
  },
  movement(
    "movement-postmodernism", "ポストモダニズム", "后现代主义", "1960年代後半〜1990年代", "20世纪60年代后半至90年代",
    ["近代主義の単一性と無装飾を批判し、歴史的引用、記号、文脈、多義性を建築へ回復した運動。", "批判现代主义的单一性和无装饰，将历史引用、符号、语境与多义性重新带回建筑。"],
    [["戦後モダニズムの国際的普及と画一化。", "战后现代主义全球普及与趋同。"], ["都市更新による歴史的環境と地域性の喪失。", "城市更新造成历史环境和地域性丧失。"]],
    [["『形態は機能に従う』という単線的合理主義。", "‘形式追随功能’的单线理性主义。"], ["装飾・歴史・大衆文化の排除。", "排斥装饰、历史和大众文化。"]],
    [["ヴェンチューリが複雑性と矛盾を評価。", "文丘里肯定复杂性与矛盾。"], ["ジェンクスらが理論化し、公共・商業建築へ拡大。", "詹克斯等加以理论化，并扩展至公共与商业建筑。"]],
    [["歴史様式を記号として引用。", "将历史样式作为符号引用。"], ["文脈、多義性、装飾、利用者とのコミュニケーション。", "重视语境、多义性、装饰及与使用者沟通。"]],
    [["建築表現の多様性を回復した。", "恢复建筑表达多样性。"], ["表層的引用や商品化への批判を受け、脱構築や新しいモダニズムへ移行。", "因表层引用和商品化受到批评，并转向解构主义及新现代主义。"]],
    ["person-robert-venturi", "person-denise-scott-brown", "person-charles-moore"], [],
    ["movement-modernism", "movement-metabolism"], ["style-postmodern"], [],
    { name: "Postmodernism", period: "Late 1960s to 1990s", summary: "A movement that criticized modernism's uniformity and lack of ornament, restoring historical reference, signs, context, and ambiguity to architecture.", socialBackground: ["The global spread and homogenization of postwar modernism.", "Loss of historic environments and regional identity through urban renewal."], reactionAgainst: ["The linear rationalism of form follows function.", "Exclusion of ornament, history, and popular culture."], development: ["Robert Venturi valued complexity and contradiction.", "Charles Jencks and others theorized the movement and extended it to public and commercial architecture."], principles: ["Historical styles cited as signs.", "Context, ambiguity, ornament, and communication with users."], results: ["It restored diversity to architectural expression.", "Criticism of superficial quotation and commodification led toward Deconstructivism and new modernism."] }),
  {
    ...movement(
      "movement-critical-regionalism", "地域主義・批判的地域主義", "地域主义与批判地域主义", "1980年代以降", "20世纪80年代以后",
      ["近代建築の普遍的技術を地域の気候・風土・文化で批判的に濾過し、場所に根ざした現代建築を追求する思想的立場。", "以地域气候、风土和文化批判性地过滤现代建筑普遍技术，追求扎根于场所的现代建筑。"],
      [["モダニズムの国際的普及による地域性の喪失と空間の均質化。", "现代主义国际普及导致地域性丧失与空间均质化。"], ["ポストモダンの表層的歴史引用への批判。", "对后现代表层历史引用的批判。"]],
      [["場所性を無視した画一的なインターナショナル・スタイル。", "无视场所性的均质化国际风格。"], ["郷愁に基づく単なる伝統様式の外部模倣。", "对传统外观的简单怀旧式模仿。"]],
      [["アレグザンダー・ツォニスとリアーヌ・ルフェーヴルが「批判的地域主義」の用語を提唱。", "Alexander Tzonis与Liane Lefaivre提出'批判地域主义'概念。"], ["ケネス・フランプトンが理論的枠組みを構築し国際的に普及。", "Kenneth Frampton构建理论框架并推广至国际。"], ["安藤忠雄、アルヴァ・アアルト、バルクリシュナ・ドーシら各地の建築家が実践。", "安藤忠雄、Alvar Aalto、Balkrishna Doshi等各地建筑师付诸实践。"]],
      [["普遍的近代技術を地域の気候・地形・材料・文化で批判的に調整する。", "以地域气候、地形、材料和文化批判性调整普遍现代技术。"], ["視覚的イメージより触覚的・身体的な場所経験を重視する。", "重视触觉性身体性场所经历甚于视觉图像。"], ["伝統の外面的模倣ではなく、背後にある空間論理を現代的に再解釈する。", "不模仿传统外观，而对其空间逻辑进行现代再诠释。"]],
      [["アジア・中南米・北欧などで地域性と近代性を融合した作品が多数生まれた。", "诞生大量融合地域性与现代性的作品于亚、拉美、北欧等地。"], ["持続可能な建築・場所論・ポストコロニアル建築論へ理論的影響を与えた。", "对可持续建筑、场所论、后殖民建筑理论产生理论影响。"]],
      ["architect-tadao-ando"], [],
      ["movement-modernism", "movement-postmodernism"], [], [],
      { name: "Critical Regionalism", period: "From the 1980s", summary: "A theoretical position that critically filters universal modern techniques through regional climate, topography, materials, and culture to pursue contemporary architecture rooted in place.", socialBackground: ["Loss of regional identity and spatial homogenization through the international spread of modernism.", "Criticism of postmodernism's superficial historical quotation."], reactionAgainst: ["Placeless, homogeneous International Style architecture.", "Nostalgic imitation of traditional appearances."], development: ["Alexander Tzonis and Liane Lefaivre introduced the term critical regionalism.", "Kenneth Frampton developed and internationalized its theoretical framework.", "Architects including Tadao Ando, Alvar Aalto, and Balkrishna Doshi developed related practices."], principles: ["Universal modern techniques critically adjusted to regional climate, terrain, materials, and culture.", "Tactile and embodied experience of place valued over visual imagery.", "Contemporary reinterpretation of spatial logic rather than imitation of traditional appearance."], results: ["Many works combining regional identity and modernity emerged in Asia, Latin America, and Northern Europe.", "It influenced sustainable architecture, theories of place, and postcolonial architectural discourse."] }),
    regions: ["global"],
  },
];
