import type { ArchitectLearningCard } from "@/types/history-learning-card";

const l = (ja: string, zh: string, en: string) => ({ ja, zh, en });
type Seed = [string, string, string, string, string, string, string, string, string[], string[]];

type BatchThreeEnglish = { name: string; period: string; summary: string; principle: string; feature: string; phaseDescription: string };

const BATCH_THREE_ENGLISH: Record<string, BatchThreeEnglish> = {
  "architect-ictinus": { name: "Ictinus", period: "5th century BCE", summary: "Ancient Greek architect associated with the Parthenon, where the Doric order and subtle visual refinements were integrated with exceptional precision.", principle: "Unite proportion, curvature, optical correction, and structure to achieve classical harmony.", feature: "Refined Doric proportions, entasis, stylobate curvature, inward column inclination, and tightly coordinated structural rhythm.", phaseDescription: "The Parthenon, designed with Callicrates and enriched by Phidias's sculptural program, became the canonical expression of High Classical Greek temple architecture." },
  "architect-callicrates": { name: "Callicrates", period: "5th century BCE", summary: "Ancient Greek architect who worked with Ictinus on the Parthenon and represented the exacting order of Athenian Classical temple architecture.", principle: "Achieve unity through disciplined order, proportion, and precision in architectural detail.", feature: "Doric clarity, rigorous column spacing, calibrated entablatures, and refined visual corrections.", phaseDescription: "The Parthenon, attributed jointly to Ictinus and Callicrates, established a lasting model for the proportion and refinement of the Greek Doric temple." },
  "architect-mnesicles": { name: "Mnesicles", period: "5th century BCE", summary: "Ancient Greek architect who designed the Propylaea, transforming the Acropolis's difficult terrain and ceremonial approach into a complex monumental gateway.", principle: "Translate irregular topography into an ordered experience of axis, level change, colonnade, and ritual passage.", feature: "Split-level planning, intersecting colonnades, carefully staged ascent, and an adaptation of Doric and Ionic orders to uneven ground.", phaseDescription: "The Propylaea made arrival at the Acropolis into an architectural sequence and remains a principal example of Classical Greek planning shaped by terrain and procession." },
  "architect-isidore-of-miletus": { name: "Isidore of Miletus", period: "6th century CE", summary: "Byzantine mathematician and architect who, with Anthemius of Tralles, realized the great dome of Hagia Sophia and united centralized space with the basilican tradition.", principle: "Transfer dome loads through pendentives, piers, and cascading semi-domes to create a continuous centralized interior.", feature: "Pendentive dome construction, massive piers, semi-domes, ring windows, and a luminous spatial hierarchy.", phaseDescription: "Hagia Sophia in Constantinople became the defining monument of Byzantine architecture and a foundational precedent for later domed sacred architecture in East and West." },
  "architect-antonio-da-sangallo-younger": { name: "Antonio da Sangallo the Younger", period: "1484–1546", summary: "Italian Renaissance architect who developed a mature classical order for Roman palaces, fortifications, and religious architecture and directed work on the Palazzo Farnese.", principle: "Combine classical orders with practical construction and urban scale in robust, legible architectural compositions.", feature: "Rusticated bases, superimposed orders, strongly articulated cornices, disciplined palace facades, and technical mastery of fortification.", phaseDescription: "The Palazzo Farnese established a benchmark for the Roman High Renaissance palazzo; Michelangelo later completed and transformed key elements of its design." },
  "architect-inigo-jones": { name: "Inigo Jones", period: "1573–1652", summary: "English architect who introduced Palladian principles to royal and civic architecture, establishing a durable classical tradition in Britain.", principle: "Apply proportion, symmetry, and lucid classical orders to institutional architecture.", feature: "Palladian facades, measured symmetry, restrained ornament, clear axial planning, and disciplined proportional systems.", phaseDescription: "The Banqueting House at Whitehall brought Palladian classicism to the English court and became a decisive precedent for later British Neoclassicism." },
  "architect-juan-de-herrera": { name: "Juan de Herrera", period: "1530–1597", summary: "Spanish architect who completed El Escorial with severe geometry and monumental restraint, binding royal authority and religious purpose into a distinctive Spanish classicism.", principle: "Create institutional monumentality through stripped ornament, clear geometry, and vast, ordered composition.", feature: "Austere granite planes, repetitive windows, pyramidal roofs, long axial courts, and highly controlled geometric massing.", phaseDescription: "The Royal Site of San Lorenzo de El Escorial defined the Herrerian style and gave architectural form to the political and religious program of Philip II of Spain." },
  "architect-juan-bautista-de-toledo": { name: "Juan Bautista de Toledo", period: "1515–1567", summary: "Spanish architect who prepared the early design of El Escorial, establishing the basis for its unprecedented union of palace, monastery, church, and royal mausoleum.", principle: "Organize multiple institutions and rituals within an axial, courtyard-based architectural complex.", feature: "Gridded courts, hierarchical axes, monumental enclosure, and a rational integration of secular and sacred programs.", phaseDescription: "Juan Bautista de Toledo laid out the initial scheme for El Escorial; Juan de Herrera subsequently developed it into the austere monument completed under Philip II." },
  "architect-pierre-lescot": { name: "Pierre Lescot", period: "1515–1578", summary: "French Renaissance architect who established a new courtly classicism at the Louvre by fusing Italian orders with French roofs, sculpture, and facade hierarchy.", principle: "Integrate classical orders with French building traditions to produce a layered and ceremonial royal facade.", feature: "Superimposed orders, steep roofs, sculptural reliefs, rhythmic bays, and carefully graduated facade composition.", phaseDescription: "The Lescot Wing of the Louvre, developed with sculptor Jean Goujon, became the formative statement of French Renaissance palace architecture." },
  "architect-john-vanbrugh": { name: "John Vanbrugh", period: "1664–1726", summary: "English Baroque architect who used colossal massing and landscape composition to give aristocratic houses theatrical, military, and dynastic force.", principle: "Compose architecture and landscape through dramatic axes and contrasts of monumental mass.", feature: "Colossal blocks, emphatic towers, deep shadows, ceremonial approaches, and picturesque coordination with parkland.", phaseDescription: "Blenheim Palace translated a national military commemoration into an English Baroque country house; Vanbrugh's work at Castle Howard further shaped the genre." },
  "architect-james-gibbs": { name: "James Gibbs", period: "1682–1754", summary: "British architect who combined classical porticoes and steeples to give Anglican urban churches a lucid ceremonial and civic presence.", principle: "Balance a dignified liturgical front with a conspicuous urban landmark.", feature: "Temple fronts, steeples, restrained Baroque detail, clear interiors, and compositions calibrated to the city street.", phaseDescription: "St Martin-in-the-Fields united a classical portico with a prominent spire, creating a prototype for Anglican church architecture in Britain and North America." },
  "architect-balthasar-neumann": { name: "Balthasar Neumann", period: "1687–1753", summary: "German architect and military engineer who used ovals, curves, and light to create fluid ceremonial spaces in the late Baroque and Rococo.", principle: "Integrate structure and ornament as a continuous curving spatial field.", feature: "Interlocking ovals, undulating walls, complex vaults, painted ceilings, controlled daylight, and theatrical processional movement.", phaseDescription: "The Pilgrimage Church of Vierzehnheiligen demonstrates Neumann's synthesis of oval planning, Rococo ornament, and pilgrimage ritual; the Wurzburg Residence extended this spatial drama to a princely court." },
  "architect-francois-de-cuvillies": { name: "Francois de Cuvillies", period: "1695–1768", summary: "Flemish-born Bavarian architect and decorator who developed highly refined Rococo interiors for court architecture in Munich.", principle: "Use ornament, mirrors, and light to create rich depth and movement in intimate interiors.", feature: "Rocaille carving, gilded stucco, mirrored surfaces, delicate color, asymmetrical ornament, and intimate salon-scale rooms.", phaseDescription: "The Hall of Mirrors in the Amalienburg hunting lodge is a consummate Bavarian Rococo interior, where ornament and reflection dissolve the limits of the room." },
  "architect-elias-holl": { name: "Elias Holl", period: "1573–1646", summary: "German architect who used Renaissance symmetry at Augsburg Town Hall to represent civic autonomy and municipal authority.", principle: "Translate civic institutions into an orderly composition of facade, hall, and tower.", feature: "Symmetrical facades, clear story divisions, gabled rooflines, towers, and large ceremonial halls.", phaseDescription: "Augsburg Town Hall gave architectural form to the power of the imperial free city and remains a major example of German Renaissance civic architecture." },
  "architect-william-chambers": { name: "William Chambers", period: "1723–1796", summary: "British architect who advanced Palladianism and Neoclassicism in country houses and public architecture while bringing international references into English garden design.", principle: "Adapt classical proportion to the connected scales of house, garden, and urban landscape.", feature: "Measured Palladian composition, archaeological classicism, garden follies, controlled picturesque views, and refined interior detail.", phaseDescription: "Chambers's Somerset House and the Great Pagoda at Kew Gardens reveal his command of civic classicism and cosmopolitan garden architecture, influencing late Georgian design." },
  "architect-francisco-de-herrera-younger": { name: "Francisco de Herrera the Younger", period: "1627–1685", summary: "Spanish architect and painter who developed sculptural facades and emphatic massing in Seville's religious architecture, becoming a key figure of Spanish Baroque.", principle: "Intensify the drama of religious architecture through facades modeled by forceful light and shadow.", feature: "Deeply modeled portals, emphatic volumes, broken silhouettes, strong chiaroscuro, and painterly Baroque composition.", phaseDescription: "The facade of the Hospital of San Fernando exemplifies Herrera's sculptural approach to religious and charitable architecture in the Spanish Baroque." },
  "architect-jean-francois-chalgrin": { name: "Jean-Francois Chalgrin", period: "1739–1811", summary: "French architect who designed the Arc de Triomphe and adapted the Roman triumphal-arch type to the national urban monument of modern Paris.", principle: "Connect classical archetypes to metropolitan axes and collective national memory.", feature: "Monumental single arch, severe Neoclassical massing, sculptural reliefs, axial siting, and an urban-scale commemorative presence.", phaseDescription: "The Arc de Triomphe at Place Charles de Gaulle turned the Roman triumphal arch into an emblem of French national commemoration and a focal point of Parisian urban planning." },
  "architect-pierre-alexandre-vignon": { name: "Pierre-Alexandre Vignon", period: "1763–1828", summary: "French Neoclassical architect who transformed the ancient temple type into a monumental Parisian church at La Madeleine.", principle: "Use the clear mass of a peripteral temple as a civic and religious urban facade.", feature: "Corinthian colonnades, temple-front composition, austere stone massing, deep porticoes, and a strongly isolated urban volume.", phaseDescription: "La Madeleine applied the image of an ancient temple to nineteenth-century Paris and became a conspicuous monument of French Neoclassicism." },
  "architect-george-edmund-street": { name: "George Edmund Street", period: "1824–1881", summary: "English architect who used Gothic Revival construction and verticality to give modern judicial institutions a monumental expression.", principle: "Link historical style to program, construction, and urban authority.", feature: "Polychrome masonry, pointed arches, steep roofs, vertical accents, long institutional facades, and carefully articulated courtrooms.", phaseDescription: "The Royal Courts of Justice in London made Gothic Revival architecture the public image of the Victorian legal system and a major landmark of nineteenth-century institutional design." },
};

const make = ([id, ja, zh, years, summaryJa, summaryZh, principleJa, principleZh, buildingIds, related]: Seed): ArchitectLearningCard => {
  const english = BATCH_THREE_ENGLISH[id];
  return {
    id, kind: "architect", name: l(ja, zh, english.name), aliases: [], period: l(years, years, english.period), regions: ["western"],
    summary: l(summaryJa, summaryZh, english.summary), lifeSummary: l(summaryJa, summaryZh, english.summary),
    designPrinciples: [l(principleJa, principleZh, english.principle)],
    recurringFeatures: [l("構法・比例・儀礼に対応する空間構成。", "与构造、比例和仪礼相对应的空间构成。", english.feature)],
    careerPhases: [{ label: l("代表作", "代表作", "Representative works and influence"), description: l(summaryJa, summaryZh, english.phaseDescription), buildingIds }],
    keywords: [], relatedBuildingIds: buildingIds, relatedPersonIds: [], relatedCardIds: related,
    influencedByIds: [], influencedIds: [], examEvidence: [], reviewStatus: "draft",
  };
};

const SEEDS: Seed[] = [
  ["architect-ictinus", "イクティノス", "伊克提诺斯", "紀元前5世紀", "パルテノン神殿の設計に関わり、古代ギリシアのドーリア式と視覚的補正を高度に統合した建築家。", "参与帕特农神庙设计，高度整合古希腊多立克柱式与视觉校正的建筑师。", "比例・曲線補正・構造を一体として古典的調和をつくる。", "将比例、曲线校正和结构合为一体，建立古典和谐。", ["building-e103164c6ab5"], ["style-greek"]],
  ["architect-callicrates", "カリクラテス", "卡利克拉特斯", "紀元前5世紀", "イクティノスとともにパルテノン神殿に関わり、アテネ古典期の神殿建築を代表する建築家。", "与伊克提诺斯共同参与帕特农神庙，代表雅典古典时期神庙建筑的建筑师。", "秩序・比例・細部の精度を通じて神殿の統一性をつくる。", "通过秩序、比例和细部精度建立神庙统一性。", ["building-e103164c6ab5"], ["style-greek", "architect-ictinus"]],
  ["architect-mnesicles", "ムネシクレス", "姆内西克利斯", "紀元前5世紀", "アクロポリスの地形と儀礼的な通過を統合し、プロピュライアの複雑な門空間を設計した建築家。", "整合卫城地形与仪礼性通行，设计山门复杂门厅空间的建筑师。", "不整形の地形を軸線・段差・柱廊の経験へ変換する。", "将不规则地形转化为轴线、高差与柱廊体验。", ["building-28369e885450"], ["style-greek"]],
  ["architect-isidore-of-miletus", "イシドロス・ミレトス", "米利都的伊西多尔", "6世紀", "ハギア・ソフィアの大ドームを実現し、集中式空間とバシリカを統合した東ローマの数学者・建築家。", "实现圣索菲亚大穹顶、整合集中式空间与巴西利卡的东罗马数学家、建筑师。", "ドーム荷重をペンデンティブと半ドームへ段階的に伝える。", "将穹顶荷载通过帆拱和半穹顶分级传递。", ["building-ad7b5b62435c"], ["style-byzantine"]],
  ["architect-antonio-da-sangallo-younger", "アントニオ・ダ・サンガッロ・イル・ジョヴァネ", "小安东尼奥·达·桑加洛", "1484–1546", "ローマの宮殿・要塞・宗教建築で盛期ルネサンスの秩序を発展させ、ファルネーゼ宮の計画を主導した建築家。", "在罗马宫殿、堡垒和宗教建筑中发展盛期文艺复兴秩序，主导法尔内塞宫规划的建筑师。", "古典オーダーと実用的な構成を大規模な都市建築へ統合する。", "将古典柱式与实用构成整合进大型城市建筑。", ["building-471497368549"], ["style-renaissance", "architect-michelangelo"]],
  ["architect-inigo-jones", "イニゴ・ジョーンズ", "伊尼戈·琼斯", "1573–1652", "パラーディオ主義を英国の王室・都市建築へ導入し、古典主義を定着させた建築家。", "将帕拉第奥主义引入英国王室和城市建筑，并使古典主义扎根的建筑师。", "比例、対称、明快な古典オーダーを英国の制度建築へ用いる。", "将比例、对称与清晰古典柱式用于英国制度建筑。", ["building-1696048b2333"], ["style-renaissance", "style-neoclassical"]],
  ["architect-juan-de-herrera", "フアン・デ・エレーラ", "胡安·德·埃雷拉", "1530–1597", "エル・エスコリアルを通じて、厳格な幾何学と王権・宗教の象徴性を統合したスペインの建築家。", "通过埃斯科里亚尔整合严谨几何与王权、宗教象征的西班牙建筑师。", "装飾を抑えた幾何学と巨大な構成で制度的記念性をつくる。", "以克制装饰的几何和巨大构成建立制度性纪念性。", ["building-5d5e175cdf7c"], ["style-renaissance", "style-historicism"]],
  ["architect-juan-bautista-de-toledo", "フアン・バウティスタ・デ・トレド", "胡安·包蒂斯塔·德·托莱多", "1515–1567", "エル・エスコリアル初期計画を担い、王宮・修道院・霊廟を統合する巨大複合施設の基礎を築いた建築家。", "负责埃斯科里亚尔早期规划，为整合王宫、修道院和陵墓的巨型综合体奠定基础的建筑师。", "複数の制度・儀礼を軸線的な中庭型複合施設へ組織する。", "将多个制度和仪礼组织为轴线式庭院综合体。", ["building-5d5e175cdf7c"], ["style-renaissance", "architect-juan-de-herrera"]],
  ["architect-pierre-lescot", "ピエール・レスコー", "皮埃尔·莱斯科", "1515–1578", "ルーヴル宮でフランス的な古典主義のファサードを形づくり、王宮建築の新しい基準をつくった建築家。", "在卢浮宫塑造法国古典主义立面，为王宫建筑建立新基准的建筑师。", "古典オーダーとフランスの屋根・装飾を立面の階層へ統合する。", "将古典柱式与法国屋顶、装饰整合为立面层级。", ["building-de19b3495e1d"], ["style-renaissance", "style-historicism"]],
  ["architect-john-vanbrugh", "ジョン・ヴァンブラ", "约翰·范布勒", "1664–1726", "英国バロックの大規模な量塊と景観構成を用い、ブレニム宮に軍事的・王侯的記念性を与えた建築家。", "运用英国巴洛克的大尺度体量与景观构成，赋予布伦海姆宫军事性、王侯纪念性的建筑师。", "建築と庭園を劇的な軸線と量塊の対比で組織する。", "以戏剧性轴线和体量对比组织建筑与园林。", ["building-602705adaa8d"], ["style-baroque"]],
  ["architect-james-gibbs", "ジェームズ・ギブス", "詹姆斯·吉布斯", "1682–1754", "古典的ポルティコと尖塔を組み合わせ、英国国教会の都市教会に明快な顔を与えた建築家。", "结合古典门廊与尖塔，为英国国教会城市教堂赋予清晰形象的建筑师。", "儀礼的な正面性と都市のランドマーク性を両立する。", "兼顾仪礼性正面与城市地标性。", ["building-18161ddc56bc"], ["style-baroque", "style-neoclassical"]],
  ["architect-balthasar-neumann", "バルタザール・ノイマン", "巴尔塔萨·诺伊曼", "1687–1753", "楕円・曲面・光を用いてロココ期の巡礼教会に流動的な空間を与えた建築家・技術者。", "运用椭圆、曲面和光，为洛可可时期朝圣教堂赋予流动空间的建筑师、工程师。", "構造と装飾を連続する曲面空間として統合する。", "将结构与装饰整合为连续的曲面空间。", ["building-e6a60a9bd70a"], ["style-rococo", "style-baroque"]],
  ["architect-francois-de-cuvillies", "フランソワ・ド・キュヴィリエ", "弗朗索瓦·德·居维利埃", "1695–1768", "バイエルンの宮廷建築に精緻なロココ装飾と室内空間を展開した建築家・装飾家。", "在巴伐利亚宫廷建筑中发展精致洛可可装饰和室内空间的建筑师、装饰家。", "装飾・鏡・光を用いて小規模な室内に豊かな奥行きをつくる。", "以装饰、镜面和光在线性小尺度室内中营造丰富纵深。", ["building-955f9da228d5"], ["style-rococo"]],
  ["architect-elias-holl", "エリアス・ホル", "埃利亚斯·霍尔", "1573–1646", "アウクスブルク市庁舎で都市の自治と威信をルネサンス的な対称構成へ表した建築家。", "在奥格斯堡市政厅中以文艺复兴对称构成表达城市自治与威信的建筑师。", "市民制度を明快な立面、広間、塔屋の秩序へ変換する。", "将市民制度转化为清晰立面、大厅和塔楼秩序。", ["building-1943de51af0c"], ["style-renaissance", "style-historicism"]],
  ["architect-william-chambers", "ウィリアム・チェンバーズ", "威廉·钱伯斯", "1723–1796", "英国の邸宅建築にパラーディオ主義と新古典主義を展開し、庭園建築にも国際的な趣味を導入した建築家。", "在英国宅邸建筑中发展帕拉第奥主义和新古典主义，并向园林建筑引入国际化趣味的建筑师。", "古典的な比例を住宅・庭園・都市景観の連続へ適用する。", "将古典比例用于住宅、园林和城市景观的连续关系。", ["building-5fc0fd11794f"], ["style-neoclassical", "architect-andrea-palladio"]],
  ["architect-francisco-de-herrera-younger", "フランシスコ・デ・エレーラ（子）", "小弗朗西斯科·德·埃雷拉", "1627–1685", "セビリアの宗教建築で彫刻的な正面と強い量塊を展開し、スペイン・バロックを代表した建築家・画家。", "在塞维利亚宗教建筑中发展雕塑性正面和强烈体量，代表西班牙巴洛克的建筑师、画家。", "光と陰影を強調する立面で宗教建築の劇性を高める。", "以强调光影的立面强化宗教建筑戏剧性。", ["building-9b71f0328835"], ["style-baroque"]],
  ["architect-jean-francois-chalgrin", "ジャン＝フランソワ・シャルグラン", "让-弗朗索瓦·沙尔格兰", "1739–1811", "エトワール凱旋門を設計し、ローマの凱旋門原型を近代フランスの都市的記念碑へ転用した建築家。", "设计星形广场凯旋门，将罗马凯旋门原型转用于近代法国城市纪念碑的建筑师。", "古典的な原型を大都市の軸線と国家記憶へ結びつける。", "将古典原型连接到大城市轴线与国家记忆。", ["building-965ddbdcdb3f"], ["style-neoclassical"]],
  ["architect-pierre-alexandre-vignon", "ピエール＝アレクサンドル・ヴィニョン", "皮埃尔-亚历山大·维尼翁", "1763–1828", "ラ・マドレーヌ教会で古代神殿の原型を近代パリの宗教建築へ転用した建築家。", "在马德莱娜教堂中将古代神庙原型转用于近代巴黎宗教建筑的建筑师。", "周柱式神殿の明快な量塊を都市の記念的正面として用いる。", "将周柱式神庙的清晰体量作为城市纪念性正面。", ["building-c33aa1f04ae0"], ["style-neoclassical"]],
  ["architect-george-edmund-street", "ジョージ・エドマンド・ストリート", "乔治·埃德蒙·斯特里特", "1824–1881", "ゴシック・リヴァイヴァルの構法と垂直性を王立裁判所へ用い、近代司法制度を記念的に表現した建築家。", "将哥特复兴的构法和垂直性用于皇家法院，以纪念性表达近代司法制度的建筑师。", "歴史様式を用途・構造・都市的威厳へ結びつける。", "将历史样式连接到用途、结构和城市威严。", ["building-8d513d2d5203"], ["style-gothic", "style-historicism"]],
];

export const BATCH_THREE_ARCHITECT_CARDS = SEEDS.map(make);
