import type { StyleLearningCard } from "@/types/history-learning-card";

const l = (ja: string, zh: string, en = "") => ({ ja, zh, en });
const base = (id: string, ja: string, zh: string, en: string, periodJa: string, periodZh: string, periodEn: string): Omit<StyleLearningCard, "summary" | "formationBackground" | "structuralFeatures" | "spatialFeatures" | "visualClues"> => ({
  id, kind: "style", name: l(ja, zh, en), aliases: [], period: l(periodJa, periodZh, periodEn), regions: ["japan"],
  keywords: [], relatedBuildingIds: [], relatedPersonIds: [], relatedCardIds: [], comparisonCardIds: [],
  predecessorCardIds: [], successorCardIds: [], examEvidence: [], reviewStatus: "draft",
});

export const JAPANESE_STYLE_CARDS: StyleLearningCard[] = [
  {
    ...base("style-daibutsuyo", "大仏様", "大佛样", "Daibutsuyō style", "鎌倉時代初期", "镰仓时代初期", "Early Kamakura period"),
    aliases: ["天竺様"],
    summary: l("東大寺再建のため重源が宋から導入した、巨大木造建築を合理的に構築する力強い様式。", "重源为重建东大寺从宋引入，以合理结构建造大型木构建筑的强劲样式。", "A powerful style introduced from Song China by Chōgen for the rebuilding of Tōdai-ji, enabling the rational construction of monumental timber buildings."),
    formationBackground: l("治承4年の兵火で焼失した東大寺を短期間で再建するため、重源が宋代中国の建築技術と工人組織を導入した。", "为迅速重建治承四年兵火烧毁的东大寺，重源引入宋代中国的建筑技术和工匠组织。", "To rebuild Tōdai-ji swiftly after it was destroyed in the 1180 conflict, Chōgen introduced Song-dynasty Chinese building techniques and systems of craft organization."),
    structuralFeatures: [l("柱を貫通する貫で軸部を固める。", "以贯穿柱身的贯加强轴部。", "Penetrating tie beams running through the columns stiffen the frame."), l("挿肘木を柱に直接差し込み、深い軒を支える。", "将插肘木直接插入柱中支撑深远屋檐。", "Inserted bracket arms are driven directly into columns to support deep eaves."), l("部材を規格化し、構造を外部に明快に表す。", "构件规格化，并将结构清晰表现于外部。", "Members are standardized and the structure is clearly expressed on the exterior.")],
    spatialFeatures: [l("天井を張らず架構を見せ、巨大な一室空間をつくる。", "不设吊顶、显露结构，形成巨大的单室空间。", "Unceiled interiors expose the roof structure and create vast single-volume spaces."), l("構造と意匠が一致した、垂直性と力強さのある内部。", "结构与设计一致，内部具有垂直感与力量感。", "Structure and design coincide in interiors of marked verticality and force.")],
    visualClues: [l("太い貫、挿肘木、皿斗、構造材が反復する外観。", "粗大的贯、插肘木、皿斗及结构构件反复出现。", "Look for heavy penetrating ties, inserted bracket arms, dish-shaped blocks, and repeated structural members."), l("和様より構造表現が強く、禅宗様より装飾が少ない。", "比和样更强调结构，比禅宗样装饰更少。", "It expresses structure more strongly than Wayō and is less ornamental than Zenshūyō.")],
    keywords: [l("重源", "重源", "Chōgen"), l("貫", "贯", "penetrating tie beam"), l("挿肘木", "插肘木", "inserted bracket arm")],
    relatedPersonIds: ["person-chogen"], relatedCardIds: ["style-wayo", "style-zenshuyo"],
    comparisonCardIds: ["style-wayo", "style-zenshuyo"], successorCardIds: ["style-setchuyo"],
  },
  {
    ...base("style-zenshuyo", "禅宗様", "禅宗样", "Zenshūyō style", "鎌倉時代以降", "镰仓时代以后", "From the Kamakura period onward"),
    aliases: ["唐様"],
    summary: l("禅宗の伝来とともに宋から導入され、細部まで体系化された装飾性と構造性をもつ寺院建築様式。", "随禅宗从宋传入，兼具细部体系化、装饰性与结构性的寺院建筑样式。", "A temple-building style introduced from Song China with Zen Buddhism, combining a systematic vocabulary of details with ornament and structural expression."),
    formationBackground: l("鎌倉期に栄西らが禅宗と宋代寺院制度を導入し、禅院の伽藍・仏殿・山門に新しい建築技術が用いられた。", "镰仓时期荣西等人引入禅宗及宋代寺院制度，新技术用于禅院伽蓝、佛殿和山门。", "In the Kamakura period, Eisai and others introduced Zen Buddhism and Song temple institutions; new techniques were used in Zen monastery precincts, Buddha halls, and gates."),
    structuralFeatures: [l("柱間にも組物を置く詰組。", "柱间也设置斗栱的诘组。", "Dense bracket complexes are placed between as well as above columns."), l("貫、挿肘木、扇垂木を用いる。", "使用贯、插肘木与扇椽。", "It uses penetrating ties, inserted bracket arms, and fan rafters."), l("礎盤上に柱を立て、木鼻や尾垂木を精緻に加工する。", "柱立于础盘，木鼻和尾垂木加工精细。", "Columns stand on plinth blocks, while projecting beam ends and tail rafters are finely worked.")],
    spatialFeatures: [l("仏殿は方形平面と高い内部空間をもち、化粧屋根裏を見せる。", "佛殿常为方形平面和较高内部空间，显露化妆屋架。", "Buddha halls have square plans and tall interiors with exposed decorative roof framing."), l("禅院全体は山門・仏殿・法堂を軸線上に配置する。", "禅院整体将山门、佛殿、法堂布置于轴线上。", "The monastery aligns its gate, Buddha hall, and dharma hall along a principal axis.")],
    visualClues: [l("花頭窓、桟唐戸、詰組、扇垂木。", "花头窗、栈唐户、诘组和扇椽。", "Key clues are cusped windows, paneled Chinese-style doors, dense brackets, and fan rafters."), l("反りの強い屋根と精密で密度の高い細部。", "起翘明显的屋顶与精密、密集的细部。", "Look for strongly curved roofs and precise, densely articulated details.")],
    keywords: [l("詰組", "诘组", "dense bracket complex"), l("花頭窓", "花头窗", "cusped window"), l("扇垂木", "扇椽", "fan rafter")],
    relatedPersonIds: ["person-eisai"], relatedCardIds: ["style-wayo", "style-daibutsuyo"],
    comparisonCardIds: ["style-wayo", "style-daibutsuyo"], successorCardIds: ["style-setchuyo"],
  },
  {
    ...base("style-shinden", "寝殿造", "寝殿造", "Shinden-zukuri", "平安時代中期〜後期", "平安时代中后期", "Middle to late Heian period"),
    summary: l("平安京の貴族住宅に成立した、寝殿を中心に対屋・渡殿・庭園を組織する住宅形式。", "形成于平安京贵族住宅，以寝殿为中心组织对屋、渡殿和庭园的住宅形式。", "An aristocratic residential form developed in Heian-kyō, organized around a central shinden hall with paired subsidiary halls, connecting corridors, and gardens."),
    formationBackground: l("摂関政治と国風文化の発達のもと、貴族の儀礼・饗宴・日常生活を受け入れる都市邸宅として成立した。", "在摄关政治与国风文化发展下，作为容纳贵族仪式、宴会和日常生活的城市宅邸形成。", "It developed under regency government and the flourishing of indigenous court culture as an urban residence for aristocratic ceremony, banquets, and everyday life."),
    structuralFeatures: [l("左右対称を基本に寝殿と対屋を渡殿で結ぶ。", "原则上左右对称，以渡殿连接寝殿和对屋。", "A basically symmetrical arrangement links the shinden hall and subsidiary halls by corridors."), l("柱と建具で柔軟に仕切る開放的な木造架構。", "以柱和活动隔扇灵活分隔的开放木构。", "An open timber frame is flexibly divided by columns and movable fittings.")],
    spatialFeatures: [l("南庭と池を儀礼・舟遊び・眺望の中心とする。", "以南庭和池塘作为仪式、舟游与观景中心。", "The south garden and pond form the focus for ceremony, boating, and views."), l("母屋・庇・簀子縁が中心から外へ段階的に広がる。", "母屋、庇与簀子缘由中心向外层层展开。", "The core moya, surrounding hisashi, and veranda extend outward in successive layers.")],
    visualClues: [l("寝殿、左右対屋、渡殿、釣殿、南庭の構成。", "寝殿、左右对屋、渡殿、钓殿与南庭的组合。", "Identify the shinden hall, paired halls, corridors, fishing pavilion, and south garden."), l("壁が少なく、蔀戸や御簾で内外を調整する。", "墙体较少，以蔀户和御帘调节内外。", "There are few fixed walls; shutters and bamboo blinds regulate the relationship between interior and exterior.")],
    keywords: [l("寝殿", "寝殿", "shinden hall"), l("対屋", "对屋", "subsidiary hall"), l("南庭", "南庭", "south garden")],
    relatedCardIds: ["style-wayo", "style-shoin"], comparisonCardIds: ["style-shoin"], successorCardIds: ["style-shoin"],
  },
  {
    ...base("style-shoin", "書院造", "书院造", "Shoin-zukuri", "室町時代〜近世", "室町时代至近世", "Muromachi period to early modern era"),
    summary: l("武家・寺院の接客空間から成立し、床・棚・付書院と畳割によって格式と座の秩序を表す住宅様式。", "由武家与寺院接待空间发展而来，以床、棚、付书院和榻榻米布局表达等级与座次秩序的住宅样式。", "A residential style developed from reception rooms in warrior residences and temples, expressing rank and seating order through the tokonoma, shelves, built-in desk, and tatami module."),
    formationBackground: l("寝殿造の開放的空間が中世の武家生活、禅院の書院、対面儀礼に合わせて小室化・固定化した。", "寝殿造的开放空间适应中世武家生活、禅院书院和会面礼仪而逐渐小室化、固定化。", "The open spaces of shinden-zukuri were divided into smaller, fixed rooms to suit medieval warrior life, Zen study halls, and formal audiences."),
    structuralFeatures: [l("角柱、畳敷、舞良戸・明障子などを用いる。", "使用方柱、榻榻米、舞良户和明障子等。", "It uses square posts, tatami flooring, mairado plank doors, and translucent shoji."), l("柱間寸法と畳割を対応させ、室構成を規格化する。", "使柱间尺寸与榻榻米布局对应，规范房间构成。", "Bay dimensions correspond to the tatami layout, standardizing the composition of rooms.")],
    spatialFeatures: [l("床・違棚・付書院・帳台構を備えた座敷を中心とする。", "以设有床、违棚、付书院和帐台构的座敷为中心。", "The principal zashiki reception room is furnished with a tokonoma, staggered shelves, built-in desk, and decorative bed enclosure."), l("上段・下段によって身分と座順を空間化する。", "以升高地面区分身份和座次。", "Raised and lower floors spatially articulate social status and seating order.")],
    visualClues: [l("床の間、違棚、付書院の座敷飾。", "床之间、违棚与付书院的座敷装饰。", "Look for the tokonoma, staggered shelves, and built-in desk as formal zashiki furnishings."), l("畳を基準に整った矩形の室群。", "以榻榻米为基准的规整矩形房间群。", "Rooms form orderly rectangles based on the tatami module.")],
    keywords: [l("床の間", "床之间", "tokonoma alcove"), l("違棚", "违棚", "staggered shelves"), l("付書院", "付书院", "built-in desk")],
    relatedCardIds: ["style-shinden", "style-sukiya"], comparisonCardIds: ["style-shinden", "style-sukiya"],
    predecessorCardIds: ["style-shinden"], successorCardIds: ["style-sukiya"],
  },
  {
    ...base("style-sukiya", "数寄屋造・数寄屋建築", "数寄屋造与数寄屋建筑", "Sukiya-zukuri", "安土桃山時代以降", "安土桃山时代以后", "From the Azuchi-Momoyama period onward"),
    aliases: ["数寄屋造", "数奇屋造"],
    summary: l("茶室の草庵的美意識を住宅・座敷へ展開し、素材の自然さ、非対称、繊細さを重視する建築。", "将茶室草庵审美扩展到住宅和座敷，重视材料自然性、非对称和纤细感的建筑。", "Architecture that extends the rustic tea-room aesthetic to houses and reception rooms, valuing natural materials, asymmetry, and delicacy."),
    formationBackground: l("茶の湯文化と町衆・武家の数寄の精神を背景に、格式化した書院造を崩し、個人的で自由な美意識を表現した。", "以茶汤文化及町众、武家的数寄精神为背景，打破书院造的程式，表达个人而自由的审美。", "Against the background of tea culture and the cultivated taste of townspeople and warriors, it relaxed formalized shoin-zukuri to express a more personal and free aesthetic."),
    structuralFeatures: [l("面皮柱、丸太、竹、土壁など素材の表情を生かす。", "使用带皮柱、原木、竹和土墙，保留材料表情。", "Bark-faced posts, logs, bamboo, and earthen walls retain the character of their materials."), l("細い部材と不整形な納まりで軽快さをつくる。", "以纤细构件和非规整收口形成轻盈感。", "Slender members and deliberately irregular junctions create a light effect.")],
    spatialFeatures: [l("小間茶室の親密な尺度と間接的な動線を取り入れる。", "吸收小间茶室的亲密尺度与间接动线。", "It adopts the intimate scale and indirect circulation of the small tea room."), l("庭・露地・建具を通じて内外を連続させる。", "通过庭园、露地和隔扇连续室内外。", "Gardens, roji paths, and fittings create continuity between inside and outside.")],
    visualClues: [l("非対称、自然素材、繊細な柱、下地窓。", "非对称、自然材料、纤细立柱与下地窗。", "Look for asymmetry, natural materials, slender posts, and shitaji windows."), l("書院造の座敷飾を保ちながら格式を意図的に崩す。", "保留书院造座敷装饰，同时有意弱化其程式感。", "Formal shoin furnishings remain, but their rigidity is deliberately relaxed.")],
    keywords: [l("草庵", "草庵", "rustic tea hut"), l("面皮柱", "带皮柱", "bark-faced post"), l("露地", "露地", "roji tea-garden path")],
    relatedPersonIds: ["person-sen-no-rikyu"], relatedCardIds: ["style-shoin"], comparisonCardIds: ["style-shoin"], predecessorCardIds: ["style-shoin"],
  },
  {
    ...base("style-giyofu", "擬洋風建築", "拟洋风建筑", "Giyōfū architecture", "明治初期", "明治初期", "Early Meiji period"),
    summary: l("日本人大工が伝統技術を用いて西洋建築の外観を模倣・翻案した、明治初期の過渡的建築。", "日本木匠以传统技术模仿、转译西方建筑外观而形成的明治初期过渡性建筑。", "Transitional early-Meiji architecture in which Japanese master carpenters imitated and adapted Western façades using traditional techniques."),
    formationBackground: l("開国・文明開化により官庁、学校、病院などに西洋的威信が求められた一方、西洋建築家と技術者が不足していた。", "开国与文明开化使官厅、学校和医院需要西式权威形象，但当时西方建筑师和技术人员不足。", "Opening the country and the Civilization and Enlightenment movement created demand for Western prestige in government offices, schools, and hospitals, while Western architects and technicians remained scarce."),
    structuralFeatures: [l("木造軸組を基本に、漆喰・木彫・瓦で石造や煉瓦造を模す。", "以木构架为基础，用灰泥、木雕和瓦模仿石造或砖造。", "A timber post-and-beam frame uses plaster, wood carving, and tiles to imitate masonry or brickwork."), l("西洋の細部を在来工法で読み替える。", "以传统工法重新解释西方细部。", "Western details are reinterpreted through indigenous building methods.")],
    spatialFeatures: [l("内部平面は在来建築に近く、外観とのずれが生じることが多い。", "内部平面常接近传统建筑，与西式外观产生错位。", "Interior plans often remain close to indigenous architecture, creating a mismatch with the exterior."), l("学校・役所など新しい公共機能を伝統的空間技術で収容する。", "以传统空间技术容纳学校、官署等新公共功能。", "Traditional spatial techniques accommodate new public functions such as schools and government offices.")],
    visualClues: [l("塔、バルコニー、アーチ窓と瓦屋根の混在。", "塔楼、阳台、拱窗与瓦屋顶并存。", "Towers, balconies, and arched windows appear alongside tiled roofs."), l("西洋風装飾が木造・漆喰で造られている。", "西式装饰由木材和灰泥制作。", "Western-looking decoration is made in timber and plaster.")],
    keywords: [l("文明開化", "文明开化", "Civilization and Enlightenment"), l("棟梁", "栋梁", "master carpenter"), l("和洋混成", "和洋混合", "Japanese-Western hybrid")],
    relatedCardIds: ["style-historicism", "style-teikan"], comparisonCardIds: ["style-historicism"], successorCardIds: ["style-historicism"],
  },
  {
    ...base("style-teikan", "帝冠様式", "帝冠样式", "Imperial Crown Style", "昭和戦前期", "昭和战前期", "Prewar Shōwa period"),
    summary: l("近代的な鉄筋コンクリート建築に日本風の瓦屋根や伝統意匠を載せ、国家的表象をつくる様式。", "在现代钢筋混凝土建筑上加设日式瓦屋顶和传统装饰，以形成国家象征的样式。", "A style that places Japanese tiled roofs and traditional motifs on modern reinforced-concrete buildings to create national representation."),
    formationBackground: l("近代化と国粋主義が併存する昭和戦前期、公共建築に近代技術と日本的・帝国的象徴性の両立が求められた。", "在现代化与国粹主义并存的昭和战前时期，公共建筑被要求兼具现代技术与日本、帝国象征性。", "In the prewar Shōwa period, modernization coexisted with nationalism, and public buildings were expected to combine modern technology with Japanese and imperial symbolism."),
    structuralFeatures: [l("主体は鉄筋コンクリートや鉄骨鉄筋コンクリート。", "主体通常为钢筋混凝土或钢骨钢筋混凝土。", "The main structure is reinforced concrete or steel-reinforced concrete."), l("上部に鉄骨架構の和風瓦屋根を載せる。", "顶部设置钢结构日式瓦屋顶。", "A Japanese-style tiled roof on a steel frame is placed above it.")],
    spatialFeatures: [l("内部は近代的な庁舎・博物館として機能的に計画される。", "内部按现代官厅或博物馆进行功能性规划。", "Interiors are functionally planned as modern government offices or museums."), l("外観の象徴性と内部の機能性が分離しやすい。", "外观象征性与内部功能性往往相互分离。", "The exterior's symbolism is readily separated from the interior's functional organization.")],
    visualClues: [l("洋風・近代的な躯体の上に大きな和風屋根。", "西式、现代结构体上覆盖大型日式屋顶。", "A large Japanese-style roof crowns a Western-looking or modern structural body."), l("左右対称で記念碑的な公共建築。", "左右对称、纪念碑性的公共建筑。", "The public building is symmetrical and monumental.")],
    keywords: [l("和魂洋才", "和魂洋才", "Japanese spirit, Western technique"), l("国粋主義", "国粹主义", "nationalism"), l("RC造", "钢筋混凝土", "reinforced concrete")],
    relatedCardIds: ["style-giyofu", "movement-modernism"], comparisonCardIds: ["style-giyofu", "movement-modernism"], predecessorCardIds: ["style-giyofu", "style-historicism"],
  },
];
