import type{StyleLearningCard}from"@/types/history-learning-card";
const l=(ja:string,zh:string,en?:string)=>({ja,zh,...(en?{en}:{})});
export const JAPANESE_SPECIAL_STYLE_CARDS:StyleLearningCard[]=[
  {
    id:"style-sumiyoshi", kind:"style", name:l("住吉造","住吉造","Sumiyoshi-zukuri"), aliases:["すみよしづくり"],
    period:l("古墳時代〜","古坟时代〜","Kofun period onward"), regions:["japan"],
    summary:l("切妻妻入、直線的屋根と前後二室を特徴とする古式神社本殿形式。","以切妻妻入、直线屋顶和前后两室为特征的古式神社本殿形式。","An archaic shrine main-hall form characterized by a gabled tsumairi roof, straight rooflines, and two chambers arranged front to back."),
    formationBackground:l("神社建築の最も古い形式の一つで、大和朝廷以前の祭祀建築の伝統を引く。住吉大社本殿が代表的。","神社建筑最古老的形式之一，传承大和朝廷以前的祭祀建筑传统。住吉大社本殿为代表。","One of the oldest shrine-building forms, continuing traditions of ritual architecture predating the Yamato court; the main halls of Sumiyoshi Taisha are exemplary."),
    structuralFeatures:[l("切妻造・妻入りで、直線的な屋根形状をもつ。","采用悬山式、山面入口，具有直线型屋顶。","Gabled tsumairi construction with a straight-lined roof profile."),l("柱は丸柱、床は高床式。","柱为圆柱，地板为高床式。","Round posts and a raised floor.")],
    spatialFeatures:[l("正面四間、側面二間、内部を外陣・内陣に分ける二室構成。","正面四间、侧面两间，内部划分外阵与内阵的双室构成。","A four-bay front and two-bay depth, with the interior divided into outer and inner chambers."),l("前室を外陣、後室を内陣とし、神座を最奥に置く。","前室为外阵，后室为内阵，神座置于最深处。","The front chamber serves as the outer sanctuary and the rear as the inner sanctuary, with the sacred seat at the deepest point.")],
    visualClues:[l("切妻の直線的なシルエットと千木・堅魚木。","悬山式直线轮廓与千木、坚鱼木。","A straight gabled silhouette with chigi finials and katsuogi billets."),l("素木造りで装飾を排した簡素な外観。","素木造、排除装饰的简朴外观。","A restrained, unpainted-timber exterior without applied ornament.")],
    keywords:[l("住吉造","住吉造","Sumiyoshi-zukuri"),l("切妻妻入","悬山山面入口","gabled tsumairi")], relatedBuildingIds:[], relatedPersonIds:[], relatedCardIds:["style-shinmei","style-taisha"], comparisonCardIds:["style-shinmei","style-taisha"], predecessorCardIds:[], successorCardIds:[], examEvidence:[], reviewStatus:"draft",
  },
  {
    id:"style-hiyoshi", kind:"style", name:l("日吉造","日吉造","Hiyoshi-zukuri"), aliases:["ひよしづくり","聖帝造"],
    period:l("平安時代後期〜","平安时代后期〜","Late Heian period"), regions:["japan"],
    summary:l("背面屋根を切り上げた複雑な入母屋屋根をもつ日吉大社系の本殿形式。","具有后部屋面截短的复杂入母屋屋顶之日吉大社系本殿形式。","A Hiyoshi Taisha shrine main-hall form with a complex hip-and-gable roof whose rear roof plane is cut away."),
    formationBackground:l("日吉大社（滋賀）を中心に発展した独自の本殿形式。山王信仰と結びつき、比叡山の守護神として発展した。","以日吉大社（滋贺）为中心发展的独特本殿形式。与山王信仰结合，作为比睿山守护神而发展。","A distinctive main-hall form developed at Hiyoshi Taisha in Shiga, associated with Sanno worship and the cult of Mount Hiei."),
    structuralFeatures:[l("正面と側面三面に庇を巡らせ、背面中央部の庇を欠く独特の形式。","正面及三侧面设庇，背面中央部缺失庇的独特形式。","A distinctive configuration with eaves on the front and three sides, but no eave at the centre of the rear elevation."),l("入母屋造を基本とし、背面で屋根を切り上げる。","以入母屋造为基础，背面部截短屋面。","A hip-and-gable form in which the rear portion of the roof is cut away.")],
    spatialFeatures:[l("正面を広く取り、側面に縁を巡らせる。背面中央に神座を置く。","正面开阔，侧面设缘。背面中央设神座。","The front is left open and the side elevations have verandas; the sacred seat is placed at the centre of the rear."),l("三間社の身舎に庇を付加した複合的な平面。","三间社的母屋附加庇的复合型平面。","A composite plan formed by adding eaves to a three-bay shrine core.")],
    visualClues:[l("背面から見たときの庇の欠如が最大の識別点。","从背面看时庇的缺失是最大识别点。","The missing rear eave is the clearest identifying feature when viewed from behind."),l("正面からは通常の入母屋造に見えるが、側面で屋根の切り上げが見える。","从正面看似普通入母屋造，但侧面可见屋顶截短。","From the front it resembles an ordinary hip-and-gable shrine, while the cut-away roof is visible from the side.")],
    keywords:[l("日吉造","日吉造","Hiyoshi-zukuri"),l("日吉大社","日吉大社","Hiyoshi Taisha")], relatedBuildingIds:[], relatedPersonIds:[], relatedCardIds:["style-nagare","style-kasuga"], comparisonCardIds:["style-nagare","style-kasuga"], predecessorCardIds:[], successorCardIds:[], examEvidence:[], reviewStatus:"draft",
  },
  {
    id:"style-asuka", kind:"style", name:l("飛鳥様式","飞鸟样式","Asuka style"), aliases:["飛鳥時代の建築","あすかようしき"],
    period:l("飛鳥時代（6世紀末〜7世紀）","飞鸟时代（6世纪末〜7世纪）","Asuka period (late 6th to 7th centuries)"), regions:["japan"],
    summary:l("仏教伝来初期に朝鮮半島・中国南北朝の影響を受けた日本最初期の寺院建築様式。","佛教传入初期受朝鲜半岛及中国南北朝影响的日本早期寺院建筑样式。","Japan's earliest Buddhist temple architecture, shaped in the initial transmission of Buddhism by influences from the Korean peninsula and China's Northern and Southern Dynasties."),
    formationBackground:l("蘇我氏による仏教導入と、百済からの工人・技術移転を背景に、飛鳥寺を皮切りに本格的な伽藍建築が開始された。","以苏我氏引入佛教和百济工匠技术转移为背景，以飞鸟寺为开端，正式的伽蓝建筑开始建造。","With the introduction of Buddhism by the Soga clan and the transfer of Baekje craftsmen and techniques, full-scale Buddhist construction began with Asuka-dera."),
    structuralFeatures:[l("雲斗・雲肘木など中国的な組物を用いる。","使用云斗、云肘木等中国式斗栱。","Chinese-style bracket forms such as kumogata brackets and cloud-shaped elbow arms."),l("胴張り柱（エンタシス）をもつ柱。","有梭柱（卷杀）。","Entasis columns with a pronounced taper."),l("礎石上に柱を立てる大陸系の基礎構造。","础石上立柱的大陆系基础构造。","A continental-type foundation system of posts set on dressed foundation stones.")],
    spatialFeatures:[l("塔・金堂・講堂などを回廊で囲む四天王寺式または飛鳥寺式伽藍配置。","以回廊环绕塔、金堂、讲堂的四天王寺式或飞鸟寺式伽蓝配置。","A Shitenno-ji or Asuka-dera type compound, in which corridors enclose the pagoda, main hall, and lecture hall."),l("深い軒と高い基壇により、大陸的な荘厳さをもつ。","以深远出檐和高台基表现大陆式的庄严感。","Deep eaves and high platform foundations create a continental sense of monumentality.")],
    visualClues:[l("雲斗・雲肘木、胴張り柱、深い軒。","云斗、云肘木、梭柱、深远出檐。","Kumogata brackets, cloud-shaped elbow arms, entasis columns, and deep eaves."),l("白鳳・天平様式に比べて力強いプロポーション。","与白凤、天平样式相比更具力量感的比例。","More forceful proportions than those of the HakuiM and TenpyM styles.")],
    keywords:[l("飛鳥寺","飞鸟寺","Asuka-dera"),l("雲斗","云斗","Kumogata bracket"),l("胴張り柱","梭柱","Entasis column")], relatedBuildingIds:[], relatedPersonIds:[], relatedCardIds:["style-hakuho","style-wayo"], comparisonCardIds:["style-hakuho"], predecessorCardIds:[], successorCardIds:["style-hakuho","style-wayo"], examEvidence:[], reviewStatus:"draft",
  },
  {
    id:"style-hakuho", kind:"style", name:l("白鳳建築","白凤建筑","HakuhM architecture"), aliases:["白鳳様式","はくほうようしき"],
    period:l("白鳳時代（7世紀後半〜8世紀初頭）","白凤时代（7世纪后半〜8世纪初）","HakuiM period (late 7th to early 8th centuries)"), regions:["japan"],
    summary:l("唐の影響を受けつつ、飛鳥様式より軽快で整った比例へと移行した寺院建築。","在唐代影响下，从飞鸟样式转向更轻盈、规整比例的寺院建筑。","Temple architecture that, under Tang influence, moved from the Asuka style toward lighter and more orderly proportions."),
    formationBackground:l("律令国家の形成に伴い、唐の建築文化が本格的に導入された。遣唐使により最新の唐建築情報がもたらされた。","随律令国家形成，唐代建筑文化正式导入。遣唐使带来了最新的唐建筑信息。","As the ritsuryM state formed, Tang architectural culture was introduced in earnest; missions to Tang China conveyed current architectural knowledge."),
    structuralFeatures:[l("整った組物と均整のとれた柱配置。","规整的斗栱与均衡的柱配置。","More regular bracket sets and evenly spaced columns."),l("礎石・基壇が大型化し、より整然とした架構となる。","础石、台基大型化，构成更整齐的架构。","Larger dressed-stone and platform foundations, with a more orderly structural frame.")],
    spatialFeatures:[l("薬師寺式伽藍配置に代表される、より計画的で均整のとれた伽藍。","以药师寺式伽蓝配置为代表，更具计划性和均整感的伽蓝。","A more planned and regular Buddhist compound, exemplified by the Yakushi-ji layout."),l("塔の比例（高さと幅の比）が穏やかになる。","塔的比例（高宽比）趋于平缓。","Pagoda proportions become more restrained, with a lower height-to-width ratio.")],
    visualClues:[l("飛鳥様式より軽やかで優美なプロポーション。","比飞鸟样式更轻盈优雅的比例。","Lighter, more graceful proportions than in the Asuka style."),l("緩やかな屋根勾配と均衡ある塔身。","平缓的屋顶坡度和均衡的塔身。","Gentler roof slopes and a more balanced pagoda body.")],
    keywords:[l("薬師寺","药师寺","Yakushi-ji"),l("均整","均整","Regularity")], relatedBuildingIds:[], relatedPersonIds:[], relatedCardIds:["style-asuka","style-wayo"], comparisonCardIds:["style-asuka","style-wayo"], predecessorCardIds:["style-asuka"], successorCardIds:["style-wayo"], examEvidence:[], reviewStatus:"draft",
  },
  {
    id:"style-momoyama", kind:"style", name:l("桃山様式","桃山样式","Momoyama style"), aliases:["桃山建築","ももやまようしき"],
    period:l("安土桃山時代（16世紀後半〜17世紀初頭）","安土桃山时代（16世纪后半〜17世纪初）","Azuchi-Momoyama period (late 16th to early 17th centuries)"), regions:["japan"],
    summary:l("統一政権と城郭・殿舎文化を背景に、壮大な空間と華麗な装飾を発達させた近世初頭の様式。","以统一政权和城郭殿舍文化为背景，发展出宏大空间与华丽装饰的近世初期样式。","An early-modern style of monumental spaces and sumptuous decoration, shaped by political unification and castle-and-palace culture."),
    formationBackground:l("織田信長・豊臣秀吉による天下統一の過程で、権力誇示のための城郭建築と豪華な殿舎が競って建てられた。","织田信长和丰臣秀吉统一天下的过程中，为炫耀权力而竞相建造城郭建筑和豪华殿舍。","During the unification campaigns of Oda Nobunaga and Toyotomi Hideyoshi, castles and lavish palaces were competitively built as displays of authority."),
    structuralFeatures:[l("大規模な城郭石垣と天守閣の多層構造。","大规模的城郭石墙和天守阁多层结构。","Large-scale castle stone walls and the multistorey construction of castle keeps."),l("書院造の大規模化：大広間、違棚、付書院、帳台構え。","书院造的大规模化：大厅、错棚、付书院、帐台构。","The expansion of shoin-zukuri: grand halls, staggered shelves, attached writing alcoves, and reception counters.")],
    spatialFeatures:[l("対面儀礼のための大規模な書院空間と、狩野派による金碧障壁画が一体となった室内。","用于会面礼仪的大型书院空间，与狩野派的金碧障壁画融为一体的室内。","Large shoin spaces for formal audiences, integrated with KanM-school gold-leaf screen paintings."),l("城郭・殿舎・茶室が併存する多様な空間構成。","城郭、殿舍与茶室并存的多样的空间构成。","A varied spatial composition in which castles, palaces, and tea houses coexist.")],
    visualClues:[l("金碧障壁画、豪華な彫刻装飾、複雑な屋根形状。","金碧障壁画、豪华雕刻装饰、复杂的屋顶形状。","Gold-leaf screen paintings, sumptuous carved decoration, and complex roof forms."),l("天守閣の多層なシルエットと黒漆・金具のコントラスト。","天守阁的多层轮廓与黑漆、金属件的对比。","The multistorey silhouette of the castle keep, contrasted with black lacquer and gilded metal fittings.")],
    keywords:[l("城郭","城郭","Castle"),l("天守","天守","Castle keep"),l("障壁画","障壁画","Screen painting")], relatedBuildingIds:[], relatedPersonIds:[], relatedCardIds:["style-shoin","style-sukiya"], comparisonCardIds:["style-shoin","style-sukiya"], predecessorCardIds:["style-shoin"], successorCardIds:["style-sukiya"], examEvidence:[], reviewStatus:"draft",
  },
];
