export type OriginalLanguage = "en" | "fr" | "de" | "it" | "es" | "nl" | "el" | "la" | "ca" | "cs" | "tr" | "da";

export interface OriginalLanguageTerm {
  ja: string;
  original: string;
  language: OriginalLanguage;
  aliases?: string[];
}

const terms: OriginalLanguageTerm[] = [
  { ja: "パルテノン神殿", original: "Parthenon", language: "el" },
  { ja: "パンテオン", original: "Pantheon", language: "la" },
  { ja: "サンタ・コスタンツァ廟堂", original: "Mausoleo di Santa Costanza", language: "it" },
  { ja: "ハギア・ソフィア大聖堂", original: "Ἁγία Σοφία (Hagia Sophia)", language: "el", aliases: ["ハギア・ソフィア"] },
  { ja: "アーヘン宮廷礼拝堂", original: "Pfalzkapelle Aachen", language: "de", aliases: ["エクス・ラ・シャペル"] },
  { ja: "サン・ドニ大聖堂", original: "Basilique Saint-Denis", language: "fr", aliases: ["サン・ドニ修道院付属教会"] },
  { ja: "シャルトル大聖堂", original: "Cathédrale Notre-Dame de Chartres", language: "fr" },
  { ja: "サント・シャペル", original: "Sainte-Chapelle", language: "fr" },
  { ja: "サンタ・マリア・デル・フィオーレ大聖堂", original: "Cattedrale di Santa Maria del Fiore", language: "it", aliases: ["サンタ・マリア・デル・フィオーレ"] },
  { ja: "テンピエット", original: "Tempietto del Bramante", language: "it" },
  { ja: "ラウレンツィアーナ図書館", original: "Biblioteca Medicea Laurenziana", language: "it" },
  { ja: "サンティーヴォ・アッラ・サピエンツァ聖堂", original: "Sant'Ivo alla Sapienza", language: "it", aliases: ["サンティーヴォ・アッラ・サピエンツァ"] },
  { ja: "サント＝ジュヌヴィエーヴ聖堂", original: "Panthéon", language: "fr", aliases: ["パンテオン（サント＝ジュヌヴィエーヴ聖堂）"] },
  { ja: "アルテス・ムゼウム", original: "Altes Museum", language: "de" },
  { ja: "水晶宮（クリスタル・パレス）", original: "Crystal Palace", language: "en", aliases: ["水晶宮", "クリスタル・パレス"] },
  { ja: "ファグス靴工場", original: "Fagus-Werk", language: "de", aliases: ["ファグス工場"] },
  { ja: "バウハウス校舎", original: "Bauhaus Dessau", language: "de" },
  { ja: "サヴォア邸", original: "Villa Savoye", language: "fr" },
  { ja: "ロンシャン礼拝堂", original: "Chapelle Notre-Dame-du-Haut", language: "fr", aliases: ["ロンシャンのノートル＝ダム・デュ・オー巡礼堂"] },
  { ja: "シドニー・オペラハウス", original: "Sydney Opera House", language: "en" },
  { ja: "コロッセオ", original: "Colosseo", language: "it" },
  { ja: "サン・マルコ大聖堂", original: "Basilica di San Marco", language: "it" },
  { ja: "クリュニー第三修道院", original: "Abbaye de Cluny III", language: "fr", aliases: ["クリュニー修道院"] },
  { ja: "アミアン大聖堂", original: "Cathédrale Notre-Dame d'Amiens", language: "fr" },
  { ja: "メスキータ", original: "Mezquita-Catedral de Córdoba", language: "es" },
  { ja: "サンタ・マリア・ノヴェッラ教会", original: "Basilica di Santa Maria Novella", language: "it", aliases: ["サンタ・マリア・ノヴェッラ"] },
  { ja: "ヴィラ・ロトンダ", original: "Villa Almerico Capra (La Rotonda)", language: "it" },
  { ja: "ヴェルサイユ宮殿", original: "Château de Versailles", language: "fr" },
  { ja: "サント＝ジュヌヴィエーヴ図書館", original: "Bibliothèque Sainte-Geneviève", language: "fr" },
  { ja: "オックスフォード大学自然史博物館", original: "Oxford University Museum of Natural History", language: "en", aliases: ["オックスフォード自然史博物館"] },
  { ja: "エッフェル塔", original: "Tour Eiffel", language: "fr" },
  { ja: "ル・ランシーのノートル＝ダム聖堂", original: "Église Notre-Dame du Raincy", language: "fr" },
  { ja: "落水荘（カウフマン邸）", original: "Fallingwater", language: "en", aliases: ["落水荘", "カウフマン邸"] },
  { ja: "グッゲンハイム美術館", original: "Solomon R. Guggenheim Museum", language: "en" },
  { ja: "ポンピドゥー・センター", original: "Centre Pompidou", language: "fr", aliases: ["ポンピドゥーセンター"] },
  { ja: "キンベル美術館", original: "Kimbell Art Museum", language: "en" },
  { ja: "大英博物館", original: "British Museum", language: "en" },
  { ja: "バイエルン国立図書館", original: "Bayerische Staatsbibliothek", language: "de" },
  { ja: "フランス国立図書館", original: "Bibliothèque nationale de France", language: "fr" },
  { ja: "ウィーン王立劇場ブルク劇場", original: "Burgtheater", language: "de", aliases: ["ブルク劇場"] },
  { ja: "オペラ座", original: "Palais Garnier", language: "fr", aliases: ["オべラ座", "ガルニエ宮"] },
  { ja: "英国国会議事堂", original: "Palace of Westminster", language: "en" },
  { ja: "ロイヤル・パヴィリオン", original: "Royal Pavilion", language: "en" },
  { ja: "ストロベリー・ヒル・ハウス", original: "Strawberry Hill House", language: "en" },
  { ja: "サー・ジョン・ソーン自邸", original: "Sir John Soane's Museum", language: "en", aliases: ["サー・ジョン・ソーンズ博物館"] },
  { ja: "ブランデンブルク門", original: "Brandenburger Tor", language: "de" },
  { ja: "エトワール凱旋門", original: "Arc de triomphe de l'Étoile", language: "fr", aliases: ["エトワ一ル凱旋門"] },
  { ja: "ラ・マドレーヌ教会", original: "Église de la Madeleine", language: "fr" },
  { ja: "サン・カルロ・アッレ・クワトロ・フォンターネ聖堂", original: "San Carlo alle Quattro Fontane", language: "it" },
  { ja: "カールス教会", original: "Karlskirche", language: "de" },
  { ja: "フィアツェーンハイリゲン巡礼教会堂", original: "Basilika Vierzehnheiligen", language: "de" },
  { ja: "アマリーエンブルク", original: "Amalienburg", language: "de" },
  { ja: "ヴェルサイユ宮殿礼拝堂", original: "Chapelle royale de Versailles", language: "fr", aliases: ["ヴェルサイユ宮扎拝堂"] },
  { ja: "オテル・ド・スービーズ", original: "Hôtel de Soubise", language: "fr" },
  { ja: "チズウィック・ハウス", original: "Chiswick House", language: "en" },
  { ja: "ブレナム宮殿", original: "Blenheim Palace", language: "en", aliases: ["ブレニム宮"] },
  { ja: "セント・マーティン・イン・ザ・フィールズ教会", original: "St Martin-in-the-Fields", language: "en" },
  { ja: "セント・ポール大聖堂", original: "St Paul's Cathedral", language: "en" },
  { ja: "サン・アンドレア・アル・クイリナーレ教会", original: "Sant'Andrea al Quirinale", language: "it" },
  { ja: "サン・ピエトロ大聖堂", original: "Basilica di San Pietro in Vaticano", language: "it" },
  { ja: "パラッツォ・デル・テ", original: "Palazzo Te", language: "it" },
  { ja: "アウグスブルク市庁舎", original: "Augsburger Rathaus", language: "de" },
  { ja: "エル・エスコリアル", original: "Real Monasterio de San Lorenzo de El Escorial", language: "es" },
  { ja: "サラマンカ大学図書館正面", original: "Universidad de Salamanca", language: "es" },
  { ja: "アネの城館", original: "Château d'Anet", language: "fr" },
  { ja: "バンケッティング・ハウス", original: "Banqueting House", language: "en" },
  { ja: "ブロワ城", original: "Château royal de Blois", language: "fr" },
  { ja: "ルーヴル宮", original: "Palais du Louvre", language: "fr" },
  { ja: "カンピドリオ広場", original: "Piazza del Campidoglio", language: "it" },
  { ja: "パラッツォ・ファルネーゼ", original: "Palazzo Farnese", language: "it" },
  { ja: "サンタ・マリア・デル・ポポロ教会", original: "Santa Maria del Popolo", language: "it" },
  { ja: "パラッツォ・ルチェッライ", original: "Palazzo Rucellai", language: "it" },
  { ja: "サンタンドレア教会堂", original: "Basilica di Sant'Andrea", language: "it" },
  { ja: "サント・スピリト教会堂", original: "Basilica di Santo Spirito", language: "it" },
  { ja: "孤児養育院", original: "Ospedale degli Innocenti", language: "it" },
  { ja: "ミラノ大聖堂", original: "Duomo di Milano", language: "it" },
  { ja: "ウィーンのシュテファン大聖堂", original: "Stephansdom", language: "de" },
  { ja: "ウルム大聖堂", original: "Ulmer Münster", language: "de" },
  { ja: "ケルン大聖堂", original: "Kölner Dom", language: "de" },
  { ja: "ソールズベリ大聖堂", original: "Salisbury Cathedral", language: "en" },
  { ja: "パリのノートル＝ダム大聖堂", original: "Cathédrale Notre-Dame de Paris", language: "fr", aliases: ["パリのナートル＝ダム大聖堂"] },
  { ja: "ピサ大聖堂", original: "Cattedrale di Santa Maria Assunta", language: "it" },
  { ja: "シュパイヤー大聖堂", original: "Kaiserdom zu Speyer", language: "de" },
  { ja: "ザンクト・ガレン修道院", original: "Stiftsbezirk St. Gallen", language: "de" },
  { ja: "フォントネ修道院教会堂", original: "Abbaye de Fontenay", language: "fr" },
  { ja: "ル・トロネ修道院", original: "Abbaye du Thoronet", language: "fr" },
  { ja: "ヴェズレーのラ・マドレーヌ教会堂", original: "Basilique Sainte-Marie-Madeleine de Vézelay", language: "fr" },
  { ja: "サン・ミニアート・アル・モンテ教会堂", original: "Basilica di San Miniato al Monte", language: "it" },
  { ja: "アインシュタイン塔", original: "Einsteinturm", language: "de" },
  { ja: "リチャーズ医学研究所", original: "Richards Medical Research Laboratories", language: "en" },
  { ja: "スカイハウス", original: "Sky House", language: "en" },
  { ja: "中銀カプセルタワー", original: "Nakagin Capsule Tower", language: "en" },
  { ja: "神奈川県立近代美術館", original: "Museum of Modern Art, Kamakura", language: "en" },
  { ja: "王立製塩所", original: "Saline royale d'Arc-et-Senans", language: "fr", aliases: ["ショ一の王立製塩所監督官館"] },
  { ja: "ニュートン記念堂設計案", original: "Cénotaphe à Newton", language: "fr" },
  { ja: "サント＝ジュヌヴィエーヴ教会堂", original: "Panthéon", language: "fr" },
  { ja: "サン・フェルナンド施療院", original: "Real Hospicio de San Fernando", language: "es" },
  { ja: "ザンクト・ヨハネス・ネポムク教会堂", original: "Kostel svatého Jana Nepomuckého na Zelené hoře", language: "cs" },
  { ja: "カールス・キルヒェ", original: "Karlskirche", language: "de" },
  { ja: "アマリーエンブルク「鏡の間」", original: "Amalienburg", language: "de" },
  { ja: "オテル・ド・スービーズ「夏の間」", original: "Hôtel de Soubise", language: "fr" },
  { ja: "セント・マーティン＝イン＝ザ＝フィールズ教会堂", original: "St Martin-in-the-Fields", language: "en" },
  { ja: "サン・アンドレア・アル・クイリナーレ教会堂", original: "Sant'Andrea al Quirinale", language: "it" },
  { ja: "サンタ・マリア・ノヴェッラ教会堂ファサード", original: "Basilica di Santa Maria Novella", language: "it" },
  { ja: "フィレンツェのサンタ・マリア・デル・フィオーレ大聖堂", original: "Cattedrale di Santa Maria del Fiore", language: "it" },
  { ja: "バルセロナ大聖堂", original: "Catedral de la Santa Creu i Santa Eulàlia", language: "ca" },
  { ja: "ルアンのサン＝マクルー教会堂", original: "Église Saint-Maclou de Rouen", language: "fr" },
  { ja: "シャルトルのノートル＝ダム大聖堂", original: "Cathédrale Notre-Dame de Chartres", language: "fr" },
  { ja: "ピエルフォン城", original: "Château de Pierrefonds", language: "fr" },
  { ja: "アミアンのノートル＝ダム大聖堂", original: "Cathédrale Notre-Dame d'Amiens", language: "fr" },
  { ja: "フィレンツェのサン・ミニアート・アル・モンテ教会堂", original: "Basilica di San Miniato al Monte", language: "it" },
  { ja: "オルシヴァルのノートル＝ダム教会堂", original: "Basilique Notre-Dame d'Orcival", language: "fr" },
  { ja: "カルドナのサン・ヴィセンス参事会教会堂", original: "Col·legiata de Sant Vicenç de Cardona", language: "ca" },
  { ja: "スイヤックのサント＝マリー教会堂", original: "Abbaye Sainte-Marie de Souillac", language: "fr" },
  { ja: "モンマジュール修道会教会堂", original: "Abbaye de Montmajour", language: "fr" },
  { ja: "ポワティエのノートル＝ダム＝ラ＝グランド教会堂", original: "Église Notre-Dame-la-Grande", language: "fr" },
  { ja: "カンのサン＝テチエンヌ男子修道院教会堂", original: "Abbaye aux Hommes", language: "fr" },
  { ja: "コンクのサント＝フォワ修道院教会堂", original: "Abbatiale Sainte-Foy de Conques", language: "fr" },
  { ja: "オシオス・ルカス修道院", original: "Ὅσιος Λουκᾶς", language: "el" },
  { ja: "カレンデルハネ・ジャミイ", original: "Kalendarhane Camii", language: "tr" },
  { ja: "ダフニ修道院", original: "Μονή Δαφνίου", language: "el" },
  { ja: "サン・ヴィターレ教会堂", original: "Basilica di San Vitale", language: "it" },
  { ja: "サンタポリナーレ・ヌオーヴォ教会堂", original: "Basilica di Sant'Apollinare Nuovo", language: "it" },
  { ja: "サン・ロレンツォ・マッジョーレ教会堂", original: "Basilica di San Lorenzo Maggiore", language: "it" },
  { ja: "サンタ・マリア・マッジョーレ教会堂", original: "Basilica di Santa Maria Maggiore", language: "it" },
  { ja: "サンタ・サビーナ教会堂", original: "Basilica di Santa Sabina all'Aventino", language: "it" },
  { ja: "アゴラ", original: "Αρχαία Αγορά της Αθήνας", language: "el" },
  { ja: "トラヤヌス帝市場", original: "Mercati di Traiano", language: "it" },
  { ja: "マルケルス劇場", original: "Teatro di Marcello", language: "it" },
  { ja: "コンスタンティヌスのバシリカ", original: "Basilica di Massenzio", language: "it", aliases: ["コンスタンティヌスのバシリか"] },
  { ja: "カラカラ浴場", original: "Terme di Caracalla", language: "it" },
  { ja: "コロッセウム", original: "Colosseo", language: "it" },
  { ja: "トラヤヌスの記念円柱", original: "Colonna Traiana", language: "it" },
  { ja: "セプティミウス・セウェルスの凱旋門", original: "Arco di Settimio Severo", language: "it" },
  { ja: "ティトゥスの凱旋門", original: "Arco di Tito", language: "it" },
  { ja: "アッタロスのストア", original: "Στοά του Αττάλου", language: "el" },
  { ja: "エピダウロスの劇場", original: "Θέατρο της Επιδαύρου", language: "el" },
  { ja: "アテネのアクロポリス", original: "Ακρόπολη Αθηνών", language: "el" },
  { ja: "プロピュライア", original: "Προπύλαια", language: "el" },
  { ja: "エレクテイオン", original: "Ἐρέχθειον", language: "el" },
  { ja: "カサ・ミラ", original: "Casa Milà", language: "ca" },
  { ja: "サンスーシ宮殿", original: "Schloss Sanssouci", language: "de" },
  { ja: "テンピオ・マラテスティアーノ聖堂", original: "Tempio Malatestiano", language: "it" },
  { ja: "リヴァプール大聖堂", original: "Liverpool Cathedral", language: "en" },
  { ja: "ヴィラ・マダマ", original: "Villa Madama", language: "it" },
  { ja: "ローマのオーダー", original: "Roman orders", language: "en" },
  { ja: "古代ギリシャ建築三種のオーダー", original: "Greek orders", language: "en" },
  { ja: "コンス神殿", original: "Temple of Khonsu", language: "en" },
  { ja: "ハトシェプスト女王葬祭神殿", original: "Mortuary Temple of Hatshepsut", language: "en" },
  { ja: "メントゥホテップ2世葬祭神殿", original: "Mortuary Temple of Mentuhotep II", language: "en" },
  { ja: "ギザの3大ピラミッド", original: "Pyramids of Giza", language: "en" },
  { ja: "ギザのマスタバ", original: "Mastaba", language: "en" },
  { ja: "ペルセポリス", original: "Persepolis", language: "en" },
  { ja: "バベルの塔", original: "Tower of Babel", language: "en" },
  { ja: "ウルのジッグラト", original: "Ziggurat of Ur", language: "en" },
  { ja: "アンコール・ワット", original: "Angkor Wat", language: "en" },
  { ja: "ルーブル美術館", original: "Musée du Louvre", language: "fr" },
  { ja: "テート・モダン", original: "Tate Modern", language: "en" },
  { ja: "直島コンテンポラリーアートミュージアム", original: "Benesse House Museum", language: "en" },
  { ja: "グーリー自邸", original: "Gehry Residence", language: "en" },
  { ja: "つくばセンタービル", original: "Tsukuba Center Building", language: "en" },
  { ja: "コアのあるH氏の住まい", original: "H House with a Core", language: "en" },
  { ja: "バングラディッシュ国会議場", original: "Jatiya Sangsad Bhaban", language: "en" },
  { ja: "カステルヴェッキオ美術館", original: "Museo di Castelvecchio", language: "it" },
  { ja: "セイナッツァロ村役場", original: "Säynätsalo Town Hall", language: "en" },
  { ja: "東京カテドラルマリア大聖堂", original: "St. Mary's Cathedral, Tokyo", language: "en" },
  { ja: "クレディ空港TWAターミナルビル", original: "TWA Flight Center", language: "en" },
  { ja: "リーダーズダイジェスト東京支社", original: "Reader's Digest Tokyo Office", language: "en" },
  { ja: "パレスサイドビル", original: "Palace Side Building", language: "en" },
  { ja: "レヴァーハウス", original: "Lever House", language: "en" },
  { ja: "甲子園ホテル", original: "Koshien Hotel", language: "en" },
  { ja: "東京帝国ホテル", original: "Imperial Hotel, Tokyo", language: "en" },
  { ja: "同潤会アパート", original: "Dojunkai Apartments", language: "en" },
  { ja: "東京海上ビル", original: "Tokyo Marine Building", language: "en" },
  { ja: "丸の内ビル", original: "Marunouchi Building", language: "en" },
  { ja: "ニコライ堂", original: "Tokyo Resurrection Cathedral", language: "en" },
  { ja: "グラバー邸", original: "Glover Residence", language: "en" },
  { ja: "バルセロナ・パビリオン", original: "Barcelona Pavilion", language: "en" },
  { ja: "レイクショア・ドライブ・アパートメント", original: "Lake Shore Drive Apartments", language: "en" },
  { ja: "ファンズワース邸", original: "Farnsworth House", language: "en" },
  { ja: "ラ・トゥーレットの修道院", original: "Couvent de la Tourette", language: "fr" },
  { ja: "プラン・ヴォワザン", original: "Plan Voisin", language: "fr" },
  { ja: "マルセイユのユニテ・ダビタシオン", original: "Unité d'habitation de Marseille", language: "fr" },
  { ja: "ドミノ・システム", original: "Maison Dom-Ino", language: "fr" },
  { ja: "AEGタービン工場", original: "AEG-Turbinenfabrik", language: "de" },
  { ja: "ケルン博モデル工場", original: "Model Factory, Werkbund Exhibition Cologne", language: "en" },
  { ja: "落水荘・カウフマン邸", original: "Fallingwater", language: "en" },
  { ja: "ジョンソン・ワックス本社", original: "S. C. Johnson Wax Headquarters", language: "en" },
  { ja: "ウィンズロー邸", original: "Winslow House", language: "en" },
  { ja: "ロビー邸", original: "Frederick C. Robie House", language: "en" },
  { ja: "クライスラー・ビル", original: "Chrysler Building", language: "en" },
  { ja: "バターシー発電所", original: "Battersea Power Station", language: "en" },
  { ja: "クライスラー・ビルのエントランス・ホール", original: "Chrysler Building lobby", language: "en" },
  { ja: "マレ＝ステヴァンの住宅", original: "Maison Mallet-Stevens", language: "fr" },
  { ja: "エスプリ・ヌーヴォー館", original: "Pavillon de l'Esprit Nouveau", language: "fr" },
  { ja: "ボン・マルシェ百貨店館", original: "Le Bon Marché", language: "fr" },
  { ja: "カフェ・デ・ユニ", original: "Café de Unie", language: "nl" },
  { ja: "ヴィラ・ヘニー", original: "Villa Henny", language: "nl" },
  { ja: "シュレーダー邸", original: "Rietveld Schröder House", language: "nl" },
  { ja: "レーニン研究所計画案", original: "Lenin Institute", language: "en" },
  { ja: "第三インターナショナル記念塔計画案", original: "Monument to the Third International", language: "en" },
  { ja: "ベルリン大劇場", original: "Großes Schauspielhaus", language: "de" },
  { ja: "チリ・ハウス", original: "Chilehaus", language: "de" },
  { ja: "ガラスの家", original: "Glashaus", language: "de", aliases: ["ガラスの家 Glaspavillon"] },
  { ja: "第2モール邸", original: "Second Mohr House", language: "en" },
  { ja: "カールスプラッツ駅舎", original: "Karlsplatz Stadtbahnstation", language: "de" },
  { ja: "ゼツェッシオン館", original: "Secessionsgebäude", language: "de" },
  { ja: "カタルーニャ音楽堂", original: "Palau de la Música Catalana", language: "ca" },
  { ja: "ベーレンス自邸", original: "Haus Behrens", language: "de" },
  { ja: "サグラダ・ファミリア", original: "Basílica de la Sagrada Família", language: "ca" },
  { ja: "エルヴィラ写真工房", original: "Atelier Elvira", language: "de" },
  { ja: "カステル・ベランジュ", original: "Castel Béranger", language: "fr" },
  { ja: "ムーア・クラッグ", original: "Moor Crag", language: "en" },
  { ja: "スタジオ・ハウス", original: "Kate Greenaway's House and Studio", language: "en" },
  { ja: "ブラックウェルホール", original: "Blackwell, The Arts & Crafts House", language: "en" },
  { ja: "スタンデン", original: "Standen House", language: "en" },
  { ja: "セント・パンクラス駅", original: "St Pancras railway station", language: "en" },
  { ja: "コールブルックデール橋", original: "The Iron Bridge", language: "en" },

  { ja: "フィリッポ・ブルネレスキ", original: "Filippo Brunelleschi", language: "it" },
  { ja: "アンドレーア・パッラーディオ", original: "Andrea Palladio", language: "it", aliases: ["パッラーディオ"] },
  { ja: "レオン・バッティスタ・アルベルティ", original: "Leon Battista Alberti", language: "it" },
  { ja: "フランチェスコ・ボッロミーニ", original: "Francesco Borromini", language: "it" },
  { ja: "オットー・ワーグナー", original: "Otto Wagner", language: "de" },
  { ja: "ミース・ファン・デル・ローエ", original: "Ludwig Mies van der Rohe", language: "de" },
  { ja: "ルイス・カーン", original: "Louis I. Kahn", language: "en" },
  { ja: "アドルフ・ロース", original: "Adolf Loos", language: "de" },
  { ja: "ヴァルター・グロピウス", original: "Walter Gropius", language: "de" },
  { ja: "フランク・ロイド・ライト", original: "Frank Lloyd Wright", language: "en" },
  { ja: "ル・コルビュジエ", original: "Le Corbusier", language: "fr" },
  { ja: "ミケランジェロ", original: "Michelangelo Buonarroti", language: "it" },
  { ja: "アントニオ・サンテリア", original: "Antonio Sant'Elia", language: "it" },
  { ja: "アルヴァ・アアルト", original: "Alvar Aalto", language: "en" },
  { ja: "アントニ・ガウディ", original: "Antoni Gaudí", language: "ca" },
  { ja: "アントニオ・ダ・サンガッロ・イル・ジョヴァネ", original: "Antonio da Sangallo il Giovane", language: "it" },
  { ja: "アントニン・レーモンド", original: "Antonin Raymond", language: "en" },
  { ja: "アンドレ・ル・ノートル", original: "André Le Nôtre", language: "fr" },
  { ja: "アンリ・ラブルースト", original: "Henri Labrouste", language: "fr" },
  { ja: "イクティノス", original: "Ictinus", language: "el" },
  { ja: "イシドロス・ミレトス", original: "Isidore of Miletus", language: "el" },
  { ja: "イニゴ・ジョーンズ", original: "Inigo Jones", language: "en" },
  { ja: "イワン・レオニドフ", original: "Ivan Leonidov", language: "en" },
  { ja: "ウィトルウィウス", original: "Marcus Vitruvius Pollio", language: "la" },
  { ja: "ウィリアム・ヴァン・アレン", original: "William Van Alen", language: "en" },
  { ja: "ウィリアム・チェンバーズ", original: "William Chambers", language: "en" },
  { ja: "ウラジーミル・タトリン", original: "Vladimir Tatlin", language: "en" },
  { ja: "エーリヒ・メンデルゾーン", original: "Erich Mendelsohn", language: "de" },
  { ja: "エーロ・サーリネン", original: "Eero Saarinen", language: "en" },
  { ja: "エクトール・ギマール", original: "Hector Guimard", language: "fr" },
  { ja: "エティエンヌ＝ルイ・ブーレー", original: "Étienne-Louis Boullée", language: "fr" },
  { ja: "エリアス・ホル", original: "Elias Holl", language: "de" },
  { ja: "エル・リシツキー", original: "El Lissitzky", language: "en" },
  { ja: "オーガスタス・ピュージン", original: "Augustus Pugin", language: "en" },
  { ja: "カール・ゴットハルト・ラングハンス", original: "Carl Gotthard Langhans", language: "de" },
  { ja: "カール・フリードリヒ・シンケル", original: "Karl Friedrich Schinkel", language: "de" },
  { ja: "カルロ・スカルパ", original: "Carlo Scarpa", language: "it" },
  { ja: "カルロ・マデルノ", original: "Carlo Maderno", language: "it" },
  { ja: "ギュスターヴ・エッフェル", original: "Gustave Eiffel", language: "fr" },
  { ja: "クリストファー・レン", original: "Christopher Wren", language: "en" },
  { ja: "クロード＝ニコラ・ルドゥー", original: "Claude-Nicolas Ledoux", language: "fr" },
  { ja: "ゴットフリート・ゼンパー", original: "Gottfried Semper", language: "de" },
  { ja: "サー・ジョン・ソーン", original: "Sir John Soane", language: "en" },
  { ja: "ジェームズ・ギブス", original: "James Gibbs", language: "en" },
  { ja: "ジャック＝ジェルマン・スフロ", original: "Jacques-Germain Soufflot", language: "fr" },
  { ja: "シャルル・ガルニエ", original: "Charles Garnier", language: "fr" },
  { ja: "ジャン＝フランソワ・シャルグラン", original: "Jean-François Chalgrin", language: "fr" },
  { ja: "ジャン・ロレンツォ・ベルニーニ", original: "Gian Lorenzo Bernini", language: "it" },
  { ja: "ジュール・アルドゥアン＝マンサール", original: "Jules Hardouin-Mansart", language: "fr" },
  { ja: "ジュリオ・ロマーノ", original: "Giulio Romano", language: "it" },
  { ja: "ジョージ・ギルバート・スコット", original: "George Gilbert Scott", language: "en" },
  { ja: "ジョセフ・パクストン", original: "Joseph Paxton", language: "en" },
  { ja: "ジョン・ヴァンブラ", original: "John Vanbrugh", language: "en" },
  { ja: "ジョン・ナッシュ", original: "John Nash", language: "en" },
  { ja: "ドナト・ブラマンテ", original: "Donato Bramante", language: "it" },
  { ja: "バルタザール・ノイマン", original: "Balthasar Neumann", language: "de" },
  { ja: "ハンス・ペルツィヒ", original: "Hans Poelzig", language: "de" },
  { ja: "ピエール＝アレクサンドル・ヴィニョン", original: "Pierre-Alexandre Vignon", language: "fr" },
  { ja: "ピエール・レスコー", original: "Pierre Lescot", language: "fr" },
  { ja: "フアン・デ・エレーラ", original: "Juan de Herrera", language: "es" },
  { ja: "フアン・バウティスタ・デ・トレド", original: "Juan Bautista de Toledo", language: "es" },
  { ja: "フィリップ・ウェブ", original: "Philip Webb", language: "en" },
  { ja: "フランク・O・ゲーリー", original: "Frank O. Gehry", language: "en" },
  { ja: "ブルーノ・タウト", original: "Bruno Taut", language: "de" },
  { ja: "ペーター・ベーレンス", original: "Peter Behrens", language: "de" },
  { ja: "ヘリット・トーマス・リートフェルト", original: "Gerrit Thomas Rietveld", language: "nl" },
  { ja: "ヘルツォーク＆ド・ムーロン", original: "Herzog & de Meuron", language: "de" },
  { ja: "ヤン・ブラジェイ・サンティーニ＝アイヘル", original: "Jan Blažej Santini-Aichel", language: "cs" },
  { ja: "ヨーゼフ・ホフマン", original: "Josef Hoffmann", language: "de" },
  { ja: "ヨーゼフ・マリア・オルブリッヒ", original: "Joseph Maria Olbrich", language: "de" },
  { ja: "ヨーン・ウツソン", original: "Jørn Utzon", language: "da" },
  { ja: "A・ダービー", original: "Abraham Darby", language: "en", aliases: ["A·ダービー"] },
  { ja: "C・F・A・ヴォイジー", original: "Charles Francis Annesley Voysey", language: "en" },
  { ja: "G・G・スコット", original: "George Gilbert Scott", language: "en" },
  { ja: "I・M・ペイ", original: "I. M. Pei", language: "en" },
  { ja: "J・F・ヘーガー", original: "Fritz Höger", language: "de", aliases: ["J・F・へーガー"] },
  { ja: "J・J・P・アウト", original: "J. J. P. Oud", language: "nl" },
  { ja: "L・H・ボワロー", original: "Louis-Charles Boileau", language: "fr" },
  { ja: "M・H・ベイリー・スコット", original: "M. H. Baillie Scott", language: "en" },
  { ja: "R・マレ＝ステヴァン", original: "Robert Mallet-Stevens", language: "fr" },
  { ja: "SOM（スキッドモア・オーウィングズ・アンド・メリル）", original: "Skidmore, Owings & Merrill", language: "en" },
  { ja: "T・F・プリチャード", original: "Thomas Farnolls Pritchard", language: "en", aliases: ["T·F·プリチャード"] },
  { ja: "T・J・ウォートルス", original: "Thomas James Waters", language: "en", aliases: ["T·J·ウォートルス", "トーマス・J・ウォートルス"] },
  { ja: "アウグスト・エンデル", original: "August Endell", language: "de" },
  { ja: "アッタロス2世", original: "Attalus II Philadelphus", language: "el" },
  { ja: "アドルフ・マイヤー", original: "Adolf Meyer", language: "de" },
  { ja: "ウィリアム・モリス", original: "William Morris", language: "en" },
  { ja: "エリアス・デレハム", original: "Elias of Dereham", language: "en" },
  { ja: "カリクラテス", original: "Callicrates", language: "el" },
  { ja: "ゲルハルト・フォン・リーレ", original: "Gerhard von Rile", language: "de" },
  { ja: "サン＝ベルナール", original: "Bernard of Clairvaux", language: "fr" },
  { ja: "ジョヴァンニ・バッティスタ・アルベルティ", original: "Giovanni Battista Alberti", language: "it" },
  { ja: "ジョサイア・コンドル", original: "Josiah Conder", language: "en" },
  { ja: "センムト", original: "Senenmut", language: "en" },
  { ja: "ハイメ・ファブラ", original: "Jaume Fabre", language: "ca" },
  { ja: "バスケトゥス", original: "Buscheto", language: "it" },
  { ja: "ライナルドゥス", original: "Rainaldo", language: "it" },
  { ja: "プティジャン神父", original: "Bernard Petitjean", language: "fr" },
  { ja: "フランシスコ・デ・エレーラ（子）", original: "Francisco de Herrera the Younger", language: "es" },
  { ja: "フランソワ・ド・キュヴィリエ", original: "François de Cuvilliés", language: "fr" },
  { ja: "フリードリヒ・フォン・ゲルトナー", original: "Friedrich von Gärtner", language: "de" },
  { ja: "ペイディアス", original: "Phidias", language: "el" },
  { ja: "ペリクレス", original: "Pericles", language: "el" },
  { ja: "ポリュクレイトス", original: "Polykleitos", language: "el" },
  { ja: "ムネシクレス", original: "Mnesicles", language: "el" },
  { ja: "ルイ・ル・ヴォー", original: "Louis Le Vau", language: "fr" },
  { ja: "ロベール・ド・リュザルシュ", original: "Robert de Luzarches", language: "fr" },
  { ja: "ルイス・サリヴァン", original: "Louis Sullivan", language: "en" },
  { ja: "ロバート・ヴェンチューリ", original: "Robert Venturi", language: "en" },
  { ja: "チャールズ・ムーア", original: "Charles Moore", language: "en" },
  { ja: "ケネス・フランプトン", original: "Kenneth Frampton", language: "en" },
  { ja: "アレグザンダー・ツォニス", original: "Alexander Tzonis", language: "en" },
  { ja: "リアーヌ・ルフェーヴル", original: "Liane Lefaivre", language: "en" },
  { ja: "バルクリシュナ・ドーシ", original: "Balkrishna Doshi", language: "en" },

  { ja: "ゴシック建築", original: "Gothic architecture", language: "en" },
  { ja: "ロマネスク建築", original: "Romanesque architecture", language: "en" },
  { ja: "ビザンティン建築", original: "Byzantine architecture", language: "en" },
  { ja: "ルネサンス建築", original: "Renaissance architecture", language: "en" },
  { ja: "マニエリスム", original: "Manierismo", language: "it" },
  { ja: "バロック建築", original: "Baroque architecture", language: "en" },
  { ja: "新古典主義建築", original: "Neoclassical architecture", language: "en" },
  { ja: "アール・ヌーヴォー", original: "Art Nouveau", language: "fr" },
  { ja: "アール・デコ", original: "Art déco", language: "fr" },
  { ja: "ウィーン分離派", original: "Wiener Secession", language: "de" },
  { ja: "バウハウス", original: "Bauhaus", language: "de" },
  { ja: "デ・ステイル", original: "De Stijl", language: "nl" },
  { ja: "ロシア構成主義", original: "Russian Constructivism", language: "en" },
  { ja: "インターナショナル・スタイル", original: "International Style", language: "en" },
  { ja: "ハイテク建築", original: "High-tech architecture", language: "en" },
  { ja: "ポストモダニズム", original: "Postmodernism", language: "en" },
  { ja: "メタボリズム", original: "Metabolism", language: "en" },
  { ja: "アーツ・アンド・クラフツ運動", original: "Arts and Crafts movement", language: "en" },
  { ja: "アール・デコ様式", original: "Art déco", language: "fr" },
  { ja: "インターナショナル・スタイル（国際様式）", original: "International Style", language: "en" },
  { ja: "ウィーン・ゼツェッシオン（分離派）", original: "Wiener Secession", language: "de" },
  { ja: "カロリング朝建築", original: "Carolingian architecture", language: "en" },
  { ja: "ギリシア建築", original: "Greek architecture", language: "en" },
  { ja: "クイーン・アン様式", original: "Queen Anne style", language: "en" },
  { ja: "コロニアル・スタイル", original: "Colonial style", language: "en" },
  { ja: "コロニアル建築", original: "Colonial architecture", language: "en" },
  { ja: "ドイツ表現主義", original: "German Expressionism", language: "en" },
  { ja: "ネオ・バロック様式", original: "Neo-Baroque", language: "en" },
  { ja: "ネオ・ルネサンス様式（ゴシックとクラシックの折衷）", original: "Neo-Renaissance", language: "en" },
  { ja: "プレーリースタイル", original: "Prairie School", language: "en", aliases: ["プレーリースタイル（草原様式）", "プレーリースタイル（有機的建築）"] },
  { ja: "ポストモダン", original: "Postmodernism", language: "en", aliases: ["ポストモダン建築"] },
  { ja: "メソポタミア建築", original: "Mesopotamian architecture", language: "en" },
  { ja: "モダニズム", original: "Modernism", language: "en", aliases: ["モダニズム（有機的建築）", "モダニズム・地域主義", "モダニズム・機能主義"] },
  { ja: "モダニズムデザイン・表現主義", original: "Modernist Expressionism", language: "en" },
  { ja: "ルネサンス様式", original: "Renaissance style", language: "en" },
  { ja: "産業革命期の鉄とガラス建築", original: "iron and glass architecture", language: "en" },
  { ja: "初期キリスト教建築", original: "Early Christian architecture", language: "en" },
  { ja: "古代エジプト建築", original: "Ancient Egyptian architecture", language: "en" },
  { ja: "古代ペルシア建築", original: "Ancient Persian architecture", language: "en" },
  { ja: "古代ローマ建築", original: "Ancient Roman architecture", language: "en" },
  { ja: "西洋風レンガ造り", original: "Western-style brick construction", language: "en" },
  { ja: "西洋建築（ネオ・ルネサンス様式）", original: "Neo-Renaissance architecture", language: "en" },
  { ja: "ペンデンティブ", original: "pendentive", language: "en" },
  { ja: "カプセル", original: "capsule", language: "en" },
  { ja: "コア", original: "core", language: "en", aliases: ["RCコア", "SRCコア"] },
  { ja: "リブ・ヴォールト", original: "rib vault", language: "en" },
  { ja: "ヴォールト", original: "vault", language: "en" },
  { ja: "ゴシック", original: "Gothic", language: "en", aliases: ["ゴシック様式"] },
  { ja: "フライング・バットレス", original: "flying buttress", language: "en" },
  { ja: "ロココ", original: "Rococo", language: "fr" },
  { ja: "ルネサンス", original: "Renaissance", language: "it" },
  { ja: "ローマ建築", original: "Roman architecture", language: "en" },
  { ja: "ロマネスク", original: "Romanesque", language: "en" },
  { ja: "ドーム", original: "dome", language: "en", aliases: ["ドーム構造"] },
  { ja: "ローマン・コンクリート", original: "Roman concrete", language: "en" },
  { ja: "オーセンティシティ", original: "authenticity", language: "en" },
  { ja: "アダプティブ・リユース", original: "adaptive reuse", language: "en" },
  { ja: "ビザンチン", original: "Byzantine", language: "en", aliases: ["ビザンチン建築"] },
  { ja: "カテドラル", original: "cathedral", language: "en" },
  { ja: "オーダー", original: "order", language: "en" },
  { ja: "トラス", original: "truss", language: "en" },
  { ja: "ディテール", original: "detail", language: "en" },
  { ja: "ゾーニング", original: "zoning", language: "en" },
  { ja: "パノプティコン", original: "Panopticon", language: "en" },
  { ja: "ヒッポダモス", original: "Hippodamus", language: "el" },
  { ja: "トリフォリウム", original: "triforium", language: "la" },
  { ja: "トロッケン・モンタージュ・バウ", original: "Trockenmontagebau", language: "de" },
  { ja: "トウーゲントハット邸", original: "Villa Tugendhat", language: "de", aliases: ["トウーゲントハット"] },
  { ja: "デール・エル・メディナ", original: "Deir el-Medina", language: "en" },
  { ja: "トプカプ宮殿", original: "Topkapı Sarayı", language: "tr", aliases: ["トプカプ"] },
  { ja: "バザール", original: "bazaar", language: "en" },
  { ja: "バジリカ", original: "basilica", language: "la", aliases: ["バシリカ"] },
  { ja: "リングシュトラーセ", original: "Ringstraße", language: "de" },
  { ja: "レイヨナン", original: "Rayonnant", language: "fr" },
  { ja: "鉄筋コンクリート構造", original: "reinforced concrete structure", language: "en" },
  { ja: "ヴィスタ", original: "vista", language: "en" },
  { ja: "フランス王立図書館", original: "Bibliothèque nationale de France", language: "fr" },
  { ja: "ハドリアヌス", original: "Hadrian", language: "la" },
  { ja: "フランツ・ヨーゼフ", original: "Franz Joseph I", language: "de" },
  { ja: "パラーディオ", original: "Andrea Palladio", language: "it" },
  { ja: "ブルネッレスキ", original: "Filippo Brunelleschi", language: "it" },
  { ja: "ブーレー", original: "Étienne-Louis Boullée", language: "fr" },
  { ja: "ベンサム", original: "Jeremy Bentham", language: "en" },
  { ja: "ラファエロ・サンティ", original: "Raffaello Sanzio", language: "it" },
  { ja: "ロバート・スマーク", original: "Robert Smirke", language: "en" },
  { ja: "レム・クールハウス", original: "Rem Koolhaas", language: "nl" },
];

const normalize = (value: string) => value.normalize("NFKC").replace(/\s+/g, "").replace(/[・·.]/g, "").replace(/[＝=]/g, "=").trim();

const lookup = new Map<string, OriginalLanguageTerm>();
for (const term of terms) {
  lookup.set(normalize(term.ja), term);
  for (const alias of term.aliases ?? []) lookup.set(normalize(alias), term);
}

// A small number of imported Anki titles contain OCR spacing or character
// substitutions. Keep them as input aliases, but always display the clean
// canonical Japanese entry from the term list above.
const importedTitleAliases: Record<string, string> = {
  "サー・ジョン・ソーン自邸（現サー・ジョン・ソーンズ博物館）": "サー・ジョン・ソーン自邸",
  "サント·ジュヌヴィエーヴ教会堂": "サント＝ジュヌヴィエーヴ聖堂",
  "サン·カルロ·アッレ·ファット 口.ファンタ一ネ教会堂": "サン・カルロ・アッレ・クワトロ・フォンターネ聖堂",
  "サン·フェルナンド施療院正面": "サン・フェルナンド施療院",
  "ザンクト·ヨ八ネス·ネポムク教会堂": "ザンクト・ヨハネス・ネポムク教会堂",
  "オテル·ド·スーピーズ「夏の間」": "オテル・ド・スービーズ「夏の間」",
  "ブレニム宫": "ブレナム宮殿",
  "セント·マーティン=インザ=フィールズ救会堂": "セント・マーティン＝イン＝ザ＝フィールズ教会堂",
  "ヴェルサイユ宮": "ヴェルサイユ宮殿",
  "サン.アンドレア·アル·クリナー レ教会堂": "サン・アンドレア・アル・クイリナーレ教会堂",
  "サン·カルロ·アッレ·ファット 口.ファンタ一ネ教会堂ド一ム": "サン・カルロ・アッレ・クワトロ・フォンターネ聖堂",
  "サラマン力大学図書館正面": "サラマンカ大学図書館正面",
  "アネの城館主屋中央入口": "アネの城館",
  "ブロワ城フランソワ1世の翼屋": "ブロワ城",
  "ルーヴル宫方形中庭西南隅": "ルーヴル宮",
  "グィラ·ロトンダ": "ヴィラ・ロトンダ",
  "サンタ·マリア·デル·ポポロ教会堂": "サンタ・マリア・デル・ポポロ教会",
  "サンタ·マリア·人ヴェッラ教会堂ファサード": "サンタ・マリア・ノヴェッラ教会堂ファサード",
  "パラッツォ·ルチェラ イ": "パラッツォ・ルチェッライ",
  "フィレンツェのサンタ マリア デル フォオーレ大聖堂": "フィレンツェのサンタ・マリア・デル・フィオーレ大聖堂",
  "ヴェズレのラ マドレーヌ教会堂": "ヴェズレーのラ・マドレーヌ教会堂",
  "トタヤヌスの記念円柱": "トラヤヌスの記念円柱",
  "セプティミウス・セウィルスの凱旋門": "セプティミウス・セウェルスの凱旋門",
  "ハトシェポスト女王葬祭神殿とメントゥホテップ2世葬祭神殿": "ハトシェプスト女王葬祭神殿",
};
for (const [alias, canonical] of Object.entries(importedTitleAliases)) {
  const target = lookup.get(normalize(canonical));
  if (target) lookup.set(normalize(alias), target);
}

export function getOriginalLanguageTerm(term: string): OriginalLanguageTerm | undefined {
  return lookup.get(normalize(term));
}

export function findOriginalLanguageTermsInText(text: string): OriginalLanguageTerm[] {
  const found = new Set<OriginalLanguageTerm>();
  for (const term of terms) {
    if ([term.ja, ...(term.aliases ?? [])].some((candidate) => text.includes(candidate))) {
      found.add(term);
    }
  }
  return [...found].sort((a, b) => a.ja.localeCompare(b.ja, "ja"));
}

export const ORIGINAL_LANGUAGE_TERMS = terms;
