export type PlanningExamRef = {
  year: number;
  exam: "専門1" | "専門2-2";
  question: string;
  subQuestion?: string;
};

export type PlanningEssayConcept = {
  id: string;
  termJa: string;
  termZh: string;
  category: "space" | "design" | "city" | "society" | "technology";
  definitionZh: string;
  definitionJa: string;
  visualCuesZh: string[];
  visualCuesJa: string[];
  mechanismZh: string;
  mechanismJa: string;
  contrasts: string[];
  examRefs: PlanningExamRef[];
  image?: string;
  imageNumber?: string;
  correctFor2015?: boolean;
};

export type PlanningEssayQuestion = {
  id: string;
  fileName: string;
  ref: PlanningExamRef;
  titleZh: string;
  titleJa: string;
  kind: "concept" | "case-reading" | "comparison" | "spatial-analysis";
  requirementZh: string;
  requirementJa: string;
  concepts: string[];
  cases: string[];
  answerFrameworkZh: string[];
  answerFrameworkJa: string[];
};

export type PlanningEssayDetailBlock = {
  id: string;
  titleZh: string;
  titleJa: string;
  promptZh: string;
  promptJa: string;
  keyPointsZh: string[];
  keyPointsJa: string[];
  image?: string;
  sourceStatus?: "verified" | "public-source-redacted";
};

export const PLANNING_ESSAY_CONCEPTS: PlanningEssayConcept[] = [
  {
    id: "universal-space",
    termJa: "ユニヴァーサル・スペース",
    termZh: "通用空间",
    category: "space",
    definitionZh: "不预先固定用途，以均质结构、设备和连续大空间容纳未来变化的空间观念。",
    definitionJa: "用途を固定せず、均質な構造・設備・連続空間によって将来の変更を受け止める空間概念。",
    visualCuesZh: ["大面积均质网格", "少量固定核心", "空间内部几乎没有永久分隔"],
    visualCuesJa: ["広い均質グリッド", "少数の固定コア", "恒久間仕切りの少ない内部"],
    mechanismZh: "将承重与主要设备集中或规则化，使非固定区域能够通过家具和轻隔断反复重组。",
    mechanismJa: "構造と主要設備を集中・規則化し、家具や軽量間仕切りで非固定領域を反復して組み替える。",
    contrasts: ["servant-space", "universal-design", "free-plan"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5", subQuestion: "図(4)" }, { year: 2019, exam: "専門2-2", question: "1" }],
    image: "/past-exams/2015年度_建築専門1+2_公開版_2062812099756437504_4aa2fdcf9adb.jpg",
    imageNumber: "4",
    correctFor2015: true,
  },
  {
    id: "universal-design",
    termJa: "ユニヴァーサル・デザイン",
    termZh: "通用设计",
    category: "society",
    definitionZh: "从设计之初就让年龄、能力和背景不同的尽可能多的人都能公平、安全、容易地使用环境。",
    definitionJa: "設計当初から、年齢・能力・背景の異なるできるだけ多くの人が公平・安全・容易に利用できる環境を目指す。",
    visualCuesZh: ["无障碍连续通行", "多种感知渠道", "操作与尺度照顾不同使用者"],
    visualCuesJa: ["段差のない連続動線", "複数の知覚手段", "多様な利用者に対応する操作・寸法"],
    mechanismZh: "通过公平使用、灵活性、简单直观、可感知信息、容错、低体力负担和适当尺度七项原则降低排除。",
    mechanismJa: "公平性、柔軟性、単純性、知覚可能な情報、失敗への寛容、少ない身体負担、適切な寸法という七原則で排除を減らす。",
    contrasts: ["universal-space", "barrier-free"],
    examRefs: [{ year: 2014, exam: "専門2-2", question: "2" }, { year: 2015, exam: "専門1", question: "5" }],
  },
  {
    id: "five-points",
    termJa: "近代建築の五原則",
    termZh: "现代建筑五原则",
    category: "design",
    definitionZh: "勒·柯布西耶将柱网结构带来的建筑自由概括为底层架空、屋顶花园、自由平面、横向长窗和自由立面。",
    definitionJa: "ル・コルビュジエが柱梁構造による自由を、ピロティ、屋上庭園、自由な平面、水平連続窓、自由な立面として整理した原則。",
    visualCuesZh: ["底层柱网架空", "横向连续窗", "屋顶花园或自由平面"],
    visualCuesJa: ["ピロティの柱列", "水平連続窓", "屋上庭園または自由な平面"],
    mechanismZh: "柱梁框架减少承重墙，使平面和立面摆脱结构墙约束。",
    mechanismJa: "柱梁架構が耐力壁を減らし、平面と立面を構造壁の制約から解放する。",
    contrasts: ["free-plan", "organic-architecture", "brise-soleil"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5", subQuestion: "図(1)" }],
    image: "/past-exams/2015年度_建築専門1+2_公開版_2062812099756437504_13cdb2b1f6ce.jpg",
    imageNumber: "1",
    correctFor2015: true,
  },
  {
    id: "brise-soleil",
    termJa: "ブリーズ・ソレイユ",
    termZh: "建筑遮阳构件",
    category: "technology",
    definitionZh: "设置在外墙开口外侧、用于遮挡高角度直射日光并控制室内热负荷与眩光的固定或可动构件。",
    definitionJa: "開口外部に設け、主に高角度の直達日射を遮り、熱負荷とグレアを制御する固定・可動の日除け。",
    visualCuesZh: ["外墙外凸水平板", "重复格栅", "与太阳方向对应"],
    visualCuesJa: ["外壁から張り出す水平板", "反復するルーバー", "日射方位への対応"],
    mechanismZh: "在太阳辐射到达玻璃前将其遮断，同时允许视线、散射光和通风。",
    mechanismJa: "日射がガラスへ到達する前に遮断しながら、視線・天空光・通風を確保する。",
    contrasts: ["five-points", "curtain-wall"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5" }],
  },
  {
    id: "modulor",
    termJa: "モデュロール",
    termZh: "模度体系",
    category: "design",
    definitionZh: "勒·柯布西耶以人体尺度、黄金比和数列建立的尺寸协调系统。",
    definitionJa: "ル・コルビュジエが人体寸法、黄金比、数列を結び付けた寸法調整体系。",
    visualCuesZh: ["人体比例图", "连续比例数列", "建筑尺寸与身体动作对应"],
    visualCuesJa: ["人体比例図", "連続する比例数列", "建築寸法と身体動作の対応"],
    mechanismZh: "以人体为尺寸起点，通过比例序列协调房间、构件和家具的尺度。",
    mechanismJa: "人体を寸法の起点とし、比例数列で室・部材・家具の寸法を調整する。",
    contrasts: ["universal-design", "minimum-dwelling"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5" }],
  },
  {
    id: "metabolism",
    termJa: "メタボリズム",
    termZh: "新陈代谢派",
    category: "technology",
    definitionZh: "把建筑和城市理解为可生长、替换和更新的生命系统的日本战后建筑思想。",
    definitionJa: "建築と都市を成長・交換・更新可能な生命システムとして捉える戦後日本の建築思想。",
    visualCuesZh: ["永久核心与可替换单元", "巨构架", "表现生长或增殖"],
    visualCuesJa: ["恒久コアと交換可能な単位", "メガストラクチャー", "成長・増殖の表現"],
    mechanismZh: "将寿命不同的结构、设备和居住单元分层，使部分能够在整体存续时更新。",
    mechanismJa: "寿命の異なる構造・設備・居住単位を分層し、全体を残しながら部分を更新する。",
    contrasts: ["organic-architecture", "universal-space"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5" }, { year: 2019, exam: "専門2-2", question: "1" }],
  },
  {
    id: "garden-city",
    termJa: "田園都市",
    termZh: "田园城市",
    category: "city",
    definitionZh: "霍华德提出的以绿带限制城市规模、结合城市就业与乡村环境并追求自立的规划模型。",
    definitionJa: "ハワードが提唱した、グリーンベルトで規模を限定し、都市の雇用と農村環境を結び付ける自立的都市モデル。",
    visualCuesZh: ["中心城市与卫星城市", "外围绿带", "居住、就业与农地组合"],
    visualCuesJa: ["中心都市と衛星都市", "外周グリーンベルト", "居住・就業・農地の組合せ"],
    mechanismZh: "通过土地共有、规模控制和轨道联系抑制无序扩张，并让生活与就业在城市单位内平衡。",
    mechanismJa: "土地共有、規模制御、鉄道連絡によって無秩序な拡大を抑え、生活と就業を都市単位内で均衡させる。",
    contrasts: ["city-image", "neighborhood-unit"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5" }],
  },
  {
    id: "dymaxion",
    termJa: "ダイマキシオン",
    termZh: "Dymaxion体系",
    category: "technology",
    definitionZh: "巴克敏斯特·富勒以最少资源获得最大性能、强调轻量化、工业生产和可运输性的设计思想。",
    definitionJa: "バックミンスター・フラーが、最小資源で最大性能を得る軽量化・工業生産・可搬性を追求した設計思想。",
    visualCuesZh: ["中央桅杆", "放射状构件或拉索", "轻量预制并悬挂的构成"],
    visualCuesJa: ["中央マスト", "放射状部材・張力材", "軽量プレファブの吊り構成"],
    mechanismZh: "以中央受力系统、张力构件和工业化零件减少材料、自重与现场施工。",
    mechanismJa: "中央支持、張力材、工業化部品によって材料・自重・現場施工を減らす。",
    contrasts: ["tensegrity", "metabolism", "minimum-dwelling"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5", subQuestion: "図(5)" }, { year: 2019, exam: "専門2-2", question: "1" }],
    image: "/past-exams/2015年度_建築専門1+2_公開版_2062812099756437504_8d73f5313b37.jpg",
    imageNumber: "5",
    correctFor2015: true,
  },
  {
    id: "servant-space",
    termJa: "サーヴァント・スペース",
    termZh: "服务空间",
    category: "space",
    definitionZh: "路易·康用于区分主要使用空间与支撑其运行的交通、设备、卫生和储藏空间的概念。",
    definitionJa: "ルイス・カーンが、主要な使用空間と、それを支える動線・設備・衛生・収納空間を区別した概念。",
    visualCuesZh: ["服务核心集中", "主次空间形态不同", "设备和交通形成厚实边缘"],
    visualCuesJa: ["サービスコアの集中", "主従空間の形態差", "設備・動線による厚い周縁"],
    mechanismZh: "把固定且技术密集的功能集中，使主要空间获得完整尺度与明确秩序。",
    mechanismJa: "固定的で技術密度の高い機能を集中させ、主要空間にまとまりと明快な秩序を与える。",
    contrasts: ["universal-space", "free-plan"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5" }, { year: 2019, exam: "専門2-2", question: "1" }],
  },
  {
    id: "organic-architecture",
    termJa: "有機的建築",
    termZh: "有机建筑",
    category: "design",
    definitionZh: "以部分与整体、建筑与场地、结构与材料形成内在统一为目标的建筑思想。",
    definitionJa: "部分と全体、建築と敷地、構造と材料の内的な統一を目指す建築思想。",
    visualCuesZh: ["以壁炉或生活中心展开", "平面与地形相互嵌合", "空间连续而非机械网格"],
    visualCuesJa: ["暖炉・生活中心からの展開", "平面と地形のかみ合わせ", "機械的グリッドではない空間連続"],
    mechanismZh: "让形态从生活、结构、材料和环境条件共同生长，而不是把独立形式附加到场地。",
    mechanismJa: "独立した形を敷地へ置くのではなく、生活・構造・材料・環境条件から形態を成長させる。",
    contrasts: ["metabolism", "five-points", "universal-space"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5", subQuestion: "図(3)" }, { year: 2019, exam: "専門2-2", question: "1" }],
    image: "/past-exams/2015年度_建築専門1+2_公開版_2062812099756437504_85e1d76b5d02.jpg",
    imageNumber: "3",
    correctFor2015: true,
  },
  {
    id: "phenomenal-transparency",
    termJa: "虚の透明性",
    termZh: "现象透明性",
    category: "space",
    definitionZh: "并非材料透明，而是多个空间层次或秩序在视觉上同时被理解的知觉性透明。",
    definitionJa: "材料の透過性ではなく、複数の空間層・秩序が視覚的に同時理解される知覚的な透明性。",
    visualCuesZh: ["空间层叠", "多个秩序互相穿插", "可同时读取前后关系"],
    visualCuesJa: ["空間層の重なり", "複数秩序の交差", "前後関係の同時読解"],
    mechanismZh: "通过错位、重叠和连续界面，让观察者同时感知多个空间归属。",
    mechanismJa: "ずれ、重なり、連続面によって複数の空間的帰属を同時に知覚させる。",
    contrasts: ["literal-transparency", "universal-space"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5" }],
  },
  {
    id: "discontinuous-unity",
    termJa: "不連続統一体",
    termZh: "不连续统一体",
    category: "design",
    definitionZh: "槙文彦用于说明相对独立的建筑或空间单元通过关系和秩序形成整体的集合形态概念。",
    definitionJa: "槇文彦が、相対的に独立した建築・空間単位が関係と秩序によって全体をつくる集合形態を示した概念。",
    visualCuesZh: ["分散单体", "单体之间保留间隙", "通过路径、地形或共同尺度形成整体"],
    visualCuesJa: ["分散した単体", "単体間の余白", "経路・地形・共通尺度による全体化"],
    mechanismZh: "不消除单元独立性，而以连续路径、重复规则和公共空间建立群体秩序。",
    mechanismJa: "単位の独立性を消さず、連続経路、反復規則、共用空間で群としての秩序をつくる。",
    contrasts: ["organic-architecture", "semilattice"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5" }],
  },
  {
    id: "minimum-dwelling",
    termJa: "立体最小限住宅",
    termZh: "立体最小限住宅",
    category: "space",
    definitionZh: "在极小占地中把生活功能沿垂直方向压缩、叠合的都市住宅类型。",
    definitionJa: "極小の敷地で生活機能を垂直方向に圧縮・積層する都市住宅類型。",
    visualCuesZh: ["极小基底", "多层垂直叠合", "楼梯成为主要空间组织"],
    visualCuesJa: ["極小の建築面積", "多層の垂直積層", "階段が主な空間構成"],
    mechanismZh: "以垂直移动替代水平面积，把不同生活行为按层组织。",
    mechanismJa: "水平面積を垂直移動で補い、生活行為を階ごとに編成する。",
    contrasts: ["modulor", "dymaxion"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5" }],
  },
  {
    id: "common-space",
    termJa: "コモン・スペース",
    termZh: "共同空间",
    category: "society",
    definitionZh: "由特定居住者或成员共同使用并通过持续关系形成归属感的共享空间。",
    definitionJa: "特定の居住者・構成員が共同利用し、継続的な関係によって帰属意識を形成する共用空間。",
    visualCuesZh: ["使用者群体可识别", "位于私人领域之间", "支持停留和共同活动"],
    visualCuesJa: ["利用者集団が特定可能", "私的領域の間に位置", "滞在・共同活動を支援"],
    mechanismZh: "以共同管理和反复使用建立半公共领域，增强邻里联系。",
    mechanismJa: "共同管理と反復利用によって半公共領域をつくり、近隣関係を支える。",
    contrasts: ["public-space", "servant-space"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5" }, { year: 2019, exam: "専門2-2", question: "1" }],
  },
  {
    id: "public-space",
    termJa: "パブリック・スペース",
    termZh: "公共空间",
    category: "society",
    definitionZh: "原则上向不特定多数人开放、支持城市公共活动与相遇的空间。",
    definitionJa: "原則として不特定多数に開かれ、都市の公共活動と出会いを支える空間。",
    visualCuesZh: ["不限定使用者", "与街道连续", "承担通行、停留或集会"],
    visualCuesJa: ["利用者を限定しない", "街路との連続", "通行・滞在・集会を受容"],
    mechanismZh: "通过开放访问和公共规则，让不同群体在同一空间共存。",
    mechanismJa: "開かれたアクセスと公共的ルールにより、異なる集団を同一空間に共存させる。",
    contrasts: ["common-space"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5" }, { year: 2019, exam: "専門2-2", question: "1" }],
  },
  {
    id: "semilattice",
    termJa: "セミ・ラティス",
    termZh: "半格子结构",
    category: "city",
    definitionZh: "亚历山大用于描述现实城市中不同活动集合相互重叠、而非像树状结构彼此排他的关系模型。",
    definitionJa: "アレグザンダーが、現実都市の活動集合が相互に重なり、ツリーのように排他的でない関係を示したモデル。",
    visualCuesZh: ["多个关系网重叠", "一个节点属于多个集合", "非单一层级树"],
    visualCuesJa: ["複数ネットワークの重なり", "一つの要素が複数集合に所属", "単一階層ツリーではない"],
    mechanismZh: "允许功能、群体和路径交叉共享，形成复杂但具有活力的城市关系。",
    mechanismJa: "機能・集団・経路の交差と共有を許し、複雑で活力ある都市関係をつくる。",
    contrasts: ["garden-city", "discontinuous-unity"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5" }],
  },
  {
    id: "city-image",
    termJa: "都市のイメージ",
    termZh: "城市意象",
    category: "city",
    definitionZh: "凯文·林奇关于居民如何借助路径、边界、区域、节点和地标认知并记忆城市的理论。",
    definitionJa: "ケヴィン・リンチが、パス、エッジ、ディストリクト、ノード、ランドマークによる都市の認知と記憶を説明した理論。",
    visualCuesZh: ["认知地图", "路径与边界", "节点和地标突出"],
    visualCuesJa: ["認知地図", "パスとエッジ", "ノードとランドマークの強調"],
    mechanismZh: "清晰且具有差异的城市要素提高可识别性，使人能够定位、组织路线和形成共同印象。",
    mechanismJa: "明瞭で差異のある都市要素がイメージアビリティを高め、定位・経路編成・共有イメージを支える。",
    contrasts: ["garden-city", "semilattice"],
    examRefs: [{ year: 2015, exam: "専門1", question: "5", subQuestion: "図(2)" }, { year: 2017, exam: "専門2-2", question: "1" }],
    image: "/past-exams/2015年度_建築専門1+2_公開版_2062812099756437504_15842824b39b.jpg",
    imageNumber: "2",
    correctFor2015: true,
  },
  {
    id: "open-school",
    termJa: "開かれた学校",
    termZh: "开放学校",
    category: "society",
    definitionZh: "让教学空间适应多样学习方式，并在适当管理下向地域社会开放设施的学校计划思想。",
    definitionJa: "多様な学習形態に対応する空間と、適切な管理の下で地域へ施設を開くことを扱う学校計画思想。",
    visualCuesZh: ["教室与开放空间连续", "多目的学习区", "地域使用与学校动线可分离"],
    visualCuesJa: ["教室とオープンスペースの連続", "多目的学習領域", "地域利用と学校動線の分離"],
    mechanismZh: "通过可变边界和共享空间支持统一、小组和个别学习，同时设置管理边界处理噪声与安全。",
    mechanismJa: "可変境界と共用空間で一斉・小集団・個別学習を支え、管理境界で音と安全の課題を扱う。",
    contrasts: ["universal-space"],
    examRefs: [{ year: 2014, exam: "専門2-2", question: "1" }, { year: 2017, exam: "専門2-2", question: "2" }],
  },
  {
    id: "small-unit-care",
    termJa: "小単位のユニットケア",
    termZh: "小单元照护",
    category: "society",
    definitionZh: "把少量居住者的个室与共同生活空间组成可辨识生活单元，并由固定照护团队支持日常生活的方式。",
    definitionJa: "少人数の個室と共同生活空間を認識しやすい生活単位にまとめ、固定的なケアチームが日常生活を支える方式。",
    visualCuesZh: ["少量个室围绕起居餐厨", "短而清晰的生活动线", "照护据点邻近共同空间"],
    visualCuesJa: ["少数個室が居間・食堂を囲む", "短く明快な生活動線", "共用空間に近いケア拠点"],
    mechanismZh: "缩短个室、共同生活空间和照护据点之间的步数，支持方向感、交往、观察与及时响应。",
    mechanismJa: "個室・共同生活空間・ケア拠点間のステップを短くし、見当識、交流、見守り、迅速な対応を支える。",
    contrasts: ["common-space"],
    examRefs: [{ year: 2023, exam: "専門2-2", question: "2" }],
  },
  {
    id: "space-graph",
    termJa: "空間グラフとステップ数",
    termZh: "空间图与步数",
    category: "space",
    definitionZh: "把房间视为节点、直接连通关系视为边，并用距起点的步数比较空间深度与中心性的分析方法。",
    definitionJa: "室をノード、直接接続をエッジとし、起点からのステップ数で空間の深さと中心性を比較する分析方法。",
    visualCuesZh: ["房间节点", "门连接形成边", "从外部或照护站标注step 0"],
    visualCuesJa: ["室を表すノード", "扉接続を表すエッジ", "外部・ケア拠点をstep 0に設定"],
    mechanismZh: "把平面连接关系转成可比较的数值证据，再用深浅、分支和中心性解释生活与管理差异。",
    mechanismJa: "平面の接続関係を比較可能な証拠へ変換し、深さ・分岐・中心性から生活と管理の差を説明する。",
    contrasts: ["small-unit-care"],
    examRefs: [{ year: 2015, exam: "専門1", question: "10" }, { year: 2023, exam: "専門2-2", question: "2" }],
  },
  {
    id: "architecture-without-architects",
    termJa: "『建築家なしの建築』",
    termZh: "《没有建筑师的建筑》",
    category: "society",
    definitionZh: "伯纳德·鲁道夫斯基通过世界各地的匿名建造，重新评价由气候、材料、生活习惯和共同体经验长期塑造的乡土建筑。",
    definitionJa: "バーナード・ルドフスキーが世界各地の無名の建築を示し、気候・材料・生活慣習・共同体の経験が育てたヴァナキュラー建築を再評価した著作。",
    visualCuesZh: ["无署名的传统聚落", "地方材料与气候适应", "生活经验积累形成的类型"],
    visualCuesJa: ["作者不詳の伝統集落", "地域材料と気候への適応", "生活経験から生まれた類型"],
    mechanismZh: "不以建筑师的形式创造为中心，而从反复试错和集体经验中读取环境适应与社会组织。",
    mechanismJa: "建築家の造形ではなく、反復的な試行錯誤と集合的経験から環境適応と社会構成を読む。",
    contrasts: ["pattern-language", "organic-architecture"],
    examRefs: [{ year: 2017, exam: "専門2-2", question: "1" }],
  },
  {
    id: "death-life-great-american-cities",
    termJa: "『アメリカ大都市の死と生』",
    termZh: "《美国大城市的死与生》",
    category: "city",
    definitionZh: "简·雅各布斯批判自上而下的现代主义城市更新，并以混合用途、短街区、不同年代建筑和足够密度解释城市多样性。",
    definitionJa: "ジェイン・ジェイコブズが上意下達の近代都市更新を批判し、用途混合、短い街区、年代の異なる建物、十分な密度から都市の多様性を論じた著作。",
    visualCuesZh: ["街道上的眼睛", "短街区和多路径", "不同时间与用途的人群共存"],
    visualCuesJa: ["ストリートの目", "短い街区と複数経路", "時間・用途の異なる人々の共存"],
    mechanismZh: "多样用途和连续活动提高街道使用频率，通过自然监视、偶遇和细粒度更新维持安全与活力。",
    mechanismJa: "多様な用途と連続的活動が街路利用を増やし、自然監視、出会い、細粒度の更新によって安全と活力を支える。",
    contrasts: ["garden-city", "city-image"],
    examRefs: [{ year: 2017, exam: "専門2-2", question: "1" }],
  },
  {
    id: "learning-from-las-vegas",
    termJa: "『ラスベガス』",
    termZh: "《向拉斯维加斯学习》",
    category: "design",
    definitionZh: "文丘里、斯科特·布朗和艾泽努尔从拉斯维加斯商业街研究汽车尺度下的标志、象征和大众传播，并区分“鸭子”与“装饰棚屋”。",
    definitionJa: "ヴェンチューリ、スコット・ブラウン、アイゼナワーがラスベガスの商業ストリップから、自動車尺度のサイン、象徴、大衆的コミュニケーションを読み、「ダック」と「装飾された小屋」を区別した著作。",
    visualCuesZh: ["汽车视点的商业带", "巨大标志先于建筑被识别", "鸭子与装饰棚屋"],
    visualCuesJa: ["自動車視点の商業ストリップ", "建築より先に読まれる巨大サイン", "ダックと装飾された小屋"],
    mechanismZh: "把建筑形式与传达意义的符号分开，说明普通建筑如何借标志在高速移动环境中被理解。",
    mechanismJa: "建築形態と意味を伝える記号を分け、普通の建物がサインによって高速移動環境で理解される仕組みを示す。",
    contrasts: ["city-image", "five-points"],
    examRefs: [{ year: 2017, exam: "専門2-2", question: "1" }],
  },
  {
    id: "pattern-language",
    termJa: "『パタン・ランゲージ』",
    termZh: "《模式语言》",
    category: "design",
    definitionZh: "克里斯托弗·亚历山大等人把城市、建筑和构造中反复出现的问题及其解决关系整理成253个可组合的模式。",
    definitionJa: "クリストファー・アレグザンダーらが、都市・建築・構法で反復する問題と解決関係を253の組合せ可能なパタンとして整理した著作。",
    visualCuesZh: ["从城市到构件的多尺度编号", "情境—问题—解决关系", "多个模式组成生成网络"],
    visualCuesJa: ["都市から部材までの多尺度番号", "文脈・問題・解決の関係", "複数パタンによる生成ネットワーク"],
    mechanismZh: "使用者和设计者从不同尺度选择相互支持的模式，以共享语言逐步生成具有整体性的环境。",
    mechanismJa: "利用者と設計者が異なる尺度の相互に支え合うパタンを選び、共有言語によって全体性のある環境を段階的に生成する。",
    contrasts: ["semilattice", "architecture-without-architects"],
    examRefs: [{ year: 2017, exam: "専門2-2", question: "1" }],
  },
  {
    id: "bim",
    termJa: "BIM",
    termZh: "建筑信息模型（BIM）",
    category: "technology",
    definitionZh: "以包含构件属性和相互关系的数字建筑模型，在设计、施工与运维阶段共享和协调信息的方法。",
    definitionJa: "部材属性と相互関係を持つデジタル建築モデルを用い、設計・施工・維持管理の情報を共有・調整する方法。",
    visualCuesZh: ["三维构件带属性", "图纸和数量由同一模型生成", "跨专业信息协调"],
    visualCuesJa: ["属性を持つ三次元部材", "同一モデルから図面・数量を生成", "分野横断の情報調整"],
    mechanismZh: "把几何、性能、数量和时间等数据关联到构件，使模型变更能够同步反映到多种成果物。",
    mechanismJa: "形状、性能、数量、時間などのデータを部材へ関連付け、モデル変更を複数の成果物へ同期させる。",
    contrasts: ["cam"],
    examRefs: [{ year: 2019, exam: "専門2-2", question: "1" }],
  },
  {
    id: "cam",
    termJa: "CAM",
    termZh: "计算机辅助制造（CAM）",
    category: "technology",
    definitionZh: "把数字设计数据转换为加工路径和机器指令，用于控制数控设备、机器人或其他制造过程的方法。",
    definitionJa: "デジタル設計データを加工経路と機械命令へ変換し、NC工作機械、ロボットなどの製造工程を制御する方法。",
    visualCuesZh: ["数字模型转加工路径", "数控机床或机器人", "面向生产和构件制造"],
    visualCuesJa: ["デジタルモデルから加工経路へ", "NC工作機械・ロボット", "生産・部材製作を目的とする"],
    mechanismZh: "将设计几何转译成可执行的生产信息，提高复杂构件制造的一致性和自动化程度。",
    mechanismJa: "設計形状を実行可能な生産情報へ翻訳し、複雑な部材製作の一貫性と自動化を高める。",
    contrasts: ["bim"],
    examRefs: [{ year: 2019, exam: "専門2-2", question: "1" }],
  },
  {
    id: "tensegrity",
    termJa: "テンセグリティ",
    termZh: "张拉整体结构",
    category: "technology",
    definitionZh: "由连续的张力网络与彼此不直接接触的离散受压构件共同维持稳定的结构原理。",
    definitionJa: "連続する引張材のネットワークと、互いに直接接触しない不連続な圧縮材によって安定する構造原理。",
    visualCuesZh: ["受压杆彼此分离", "连续拉索网络", "轻量自平衡结构"],
    visualCuesJa: ["圧縮材が相互に非接触", "連続する張力ネットワーク", "軽量な自己釣合い構造"],
    mechanismZh: "张力系统持续约束受压构件，使内部预应力形成整体稳定，而不依赖传统连续受压框架。",
    mechanismJa: "張力系が圧縮材を常時拘束し、内部のプレストレスで全体を安定させ、連続した圧縮架構に依存しない。",
    contrasts: ["dymaxion"],
    examRefs: [{ year: 2019, exam: "専門2-2", question: "1" }],
  },
];

export const PLANNING_ESSAY_QUESTIONS: PlanningEssayQuestion[] = [
  { id: "2013-s1-q3", fileName: "2013_専門1_建筑计划_Q3.md", ref: { year: 2013, exam: "専門1", question: "3" }, titleZh: "尺寸设定与空间类型比较", titleJa: "寸法設定と空間類型の比較", kind: "comparison", requirementZh: "根据使用条件说明尺寸依据，并比较住宅、住宿与商业／文化空间。", requirementJa: "利用条件から寸法根拠を説明し、住宅・宿泊・商業文化空間を比較する。", concepts: [], cases: ["会议室", "4床病房", "阶梯室型／片廊下型", "酒店／和风旅馆", "公共图书馆／超市"], answerFrameworkZh: ["先声明使用人数或行为条件", "给出空间关系或尺寸", "解释对使用者产生的作用", "指出比较对象的根本差异"], answerFrameworkJa: ["利用人数・行為条件", "空間関係・寸法", "利用者への効果", "比較対象との根本差"] },
  { id: "2014-s1-q4", fileName: "2014_専門1_建筑计划_Q4.md", ref: { year: 2014, exam: "専門1", question: "4" }, titleZh: "战时标准住宅平面的生活逻辑", titleJa: "戦時標準住宅平面の生活論理", kind: "case-reading", requirementZh: "解释土间兼玄关炊事场，以及6畳与3畳前后配置的理由。", requirementJa: "土間兼玄関・炊事場と、六畳・三畳の前後配置の理由を説明する。", concepts: [], cases: ["1943临时日本标准规格住宅"], answerFrameworkZh: ["从当时设备与施工条件开始", "说明土间承担的生活行为", "说明房间等级与接客关系", "回到战时最小住宅背景"], answerFrameworkJa: ["当時の設備・施工条件", "土間の生活行為", "室の格式と接客関係", "戦時最小住宅の背景"] },
  { id: "2015-s1-q5", fileName: "2015_専門1_建筑计划_Q5.md", ref: { year: 2015, exam: "専門1", question: "5" }, titleZh: "图像识别建筑概念并作200字解释", titleJa: "図像から建築概念を識別し200字で解説", kind: "concept", requirementZh: "五图任选三，选择最相关用语并分别写约200字。", requirementJa: "五図から三つを選び、最も関連する用語と約200字の解説を書く。", concepts: ["five-points", "city-image", "organic-architecture", "universal-space", "dymaxion"], cases: ["萨伏伊别墅", "波士顿认知地图", "有机住宅平面", "均质大空间", "4D Tower"], answerFrameworkZh: ["提出者／时代", "一句话定义", "空间或结构机制", "指出图中可见证据"], answerFrameworkJa: ["提唱者・時代", "一文定義", "空間・構造メカニズム", "図中の視覚的根拠"] },
  { id: "2015-s1-q9", fileName: "2015_専門1_建筑计划_Q9.md", ref: { year: 2015, exam: "専門1", question: "9" }, titleZh: "旧丸大楼与新宿三井大楼办公平面比较", titleJa: "旧丸ビルと新宿三井ビルの基準階比較", kind: "comparison", requirementZh: "分别说明两种平面的特征与劳动环境依据，再解释技术背景。", requirementJa: "両平面の特徴と労働環境上の理由を述べ、新しい平面を可能にした技術背景を説明する。", concepts: [], cases: ["旧丸ビル", "新宿三井ビル"], answerFrameworkZh: ["读取进深、采光面与核心", "说明自然采光通风需求", "说明空调、人工照明与电梯技术", "形成新旧对照"], answerFrameworkJa: ["奥行・採光面・コア", "自然採光・換気", "空調・人工照明・エレベータ技術", "新旧の対照"] },
  { id: "2015-s1-q10", fileName: "2015_専門1_建筑计划_Q10.md", ref: { year: 2015, exam: "専門1", question: "10" }, titleZh: "特养空间图与空间深度比较", titleJa: "特養の空間グラフと深さの比較", kind: "spatial-analysis", requirementZh: "将两平面转成节点图，并引用步数解释空间构成差异。", requirementJa: "二平面をノードグラフへ変換し、ステップ数を用いて空間構成の差を説明する。", concepts: ["space-graph"], cases: ["两座特別養護老人ホーム"], answerFrameworkZh: ["只提取题目指定房间", "门的直接连接才构成边", "从外部标注步数", "用数值解释空间层级"], answerFrameworkJa: ["指定室のみ抽出", "扉の直接接続をエッジ化", "外部からステップ付与", "数値で領域構成を説明"] },
  { id: "2015-s1-q11", fileName: "2015_専門1_建筑计划_Q11.md", ref: { year: 2015, exam: "専門1", question: "11" }, titleZh: "大高正人的四个集合住宅", titleJa: "大高正人が関わった四つの集合住宅", kind: "case-reading", requirementZh: "分别在300字以内说明四个项目的建筑特征。", requirementJa: "四事例の建築的特徴を各300字以内で述べる。", concepts: [], cases: ["阿佐谷住宅", "晴海高层公寓", "坂出人工土地", "广岛基町高层住宅"], answerFrameworkZh: ["项目背景与住宅类型", "住栋和交通组织", "公共空间机制", "该项目的计划学意义"], answerFrameworkJa: ["背景・住宅類型", "住棟・アクセス構成", "共用空間の仕組み", "計画学的意義"] },
  { id: "2018-s1-q4", fileName: "2018_専門1_建筑计划_Q4.md", ref: { year: 2018, exam: "専門1", question: "4" }, titleZh: "四个图示对象的计划意图", titleJa: "四つの図示対象の計画意図", kind: "case-reading", requirementZh: "从图面说明四个建筑／布局的计划意图，各约150字。", requirementJa: "図から四つの建築・配置の計画意図を各150字程度で説明する。", concepts: [], cases: ["蓬皮杜中心", "柏林音乐厅", "办公布局", "虎之门医院"], answerFrameworkZh: ["先确认图的空间类型", "指出主导结构或动线", "说明使用与环境效果", "以计划意图收束"], answerFrameworkJa: ["空間類型の同定", "主な構造・動線", "利用・環境への効果", "計画意図で結ぶ"] },
  { id: "2014-s22-q1", fileName: "2014_専門2-2_建筑计划_Q6.md", ref: { year: 2014, exam: "専門2-2", question: "1" }, titleZh: "开放学校的两个视点", titleJa: "開かれた学校の二つの視点", kind: "concept", requirementZh: "从教育活动与地域开放两条轴说明图示小学，并分别写问题点。", requirementJa: "教育活動と地域開放の二視点から図示小学校を説明し、それぞれの問題点を書く。", concepts: ["open-school"], cases: ["图示小学校"], answerFrameworkZh: ["提出一条开放视点", "以图中空间关系证明", "说明教育或地域收益", "写噪声、管理或安全代价"], answerFrameworkJa: ["開放の視点", "図中の空間的根拠", "教育・地域への効果", "音・管理・安全の代償"] },
  { id: "2014-s22-q2", fileName: "2014_専門2-2_建筑计划_Q7.md", ref: { year: 2014, exam: "専門2-2", question: "2" }, titleZh: "Universal Design定义与七原则", titleJa: "ユニバーサルデザインの定義と七原則", kind: "concept", requirementZh: "100字说明定义并完整列举七原则。", requirementJa: "100字で定義し、七原則をすべて列挙する。", concepts: ["universal-design"], cases: [], answerFrameworkZh: ["Ronald Mace与设计之初", "尽可能多的人公平使用", "七原则完整列举", "不写成仅针对障碍者的补救"], answerFrameworkJa: ["ロナルド・メイスと設計当初", "できるだけ多くの人の公平利用", "七原則", "障害者専用の事後対応と区別"] },
  { id: "2014-s22-q3", fileName: "2014_専門2-2_建筑计划_Q8.md", ref: { year: 2014, exam: "専門2-2", question: "3" }, titleZh: "超高层集合住宅的居住问题", titleJa: "超高層集合住宅の居住上の問題", kind: "comparison", requirementZh: "在300字以内写出具体问题及其因果机制。", requirementJa: "具体的な問題と因果関係を300字以内で説明する。", concepts: [], cases: ["超高层集合住宅"], answerFrameworkZh: ["选择儿童、高龄者或日常外出视角", "高度导致电梯依赖", "联系灾害、邻里或风环境", "避免只说‘太高’"], answerFrameworkJa: ["子ども・高齢者・外出の視点", "高さとエレベータ依存", "防災・近隣・風環境", "高さ自体を問題にしない"] },
  { id: "2016-s22-q2", fileName: "2016_専門2-2_建筑计划_Q7.md", ref: { year: 2016, exam: "専門2-2", question: "2" }, titleZh: "消防署与急救医院的选址", titleJa: "消防署・救急病院の立地", kind: "comparison", requirementZh: "论述选址标准及其在城市中的总体位置。", requirementJa: "立地基準と都市全体における配置位置を論じる。", concepts: [], cases: ["消防署", "急救医院"], answerFrameworkZh: ["响应时间是核心指标", "联系服务圈与需求重心", "接入主干道路并避开拥堵", "考虑灾害时冗余"], answerFrameworkJa: ["応答時間", "サービス圏と需要重心", "幹線道路と渋滞回避", "災害時の冗長性"] },
  { id: "2017-s22-q1", fileName: "2017_専門2-2_建筑计划_Q1.md", ref: { year: 2017, exam: "専門2-2", question: "1" }, titleZh: "五本建筑与城市理论著作", titleJa: "建築・都市理論の五著作", kind: "concept", requirementZh: "分别在300字内说明每本书的要点。", requirementJa: "各著作の要点を300字以内で説明する。", concepts: ["architecture-without-architects", "death-life-great-american-cities", "city-image", "learning-from-las-vegas", "pattern-language"], cases: ["Architecture Without Architects", "The Death and Life of Great American Cities", "The Image of the City", "Learning from Las Vegas", "A Pattern Language"], answerFrameworkZh: ["作者与问题意识", "核心概念", "观察或论证对象", "对空间计划的影响"], answerFrameworkJa: ["著者と問題意識", "中心概念", "観察・論証対象", "空間計画への影響"] },
  { id: "2017-s22-q2", fileName: "2017_専門2-2_建筑计划_Q2.md", ref: { year: 2017, exam: "専門2-2", question: "2" }, titleZh: "西户山小学改修前后", titleJa: "西戸山小学校の改修前後", kind: "comparison", requirementZh: "比较1950建成平面与1996改修平面，并说明学校计划思想变化。", requirementJa: "1950年建設時と1996年改修後の平面を比較し、学校計画思想の変化を説明する。", concepts: ["open-school"], cases: ["西户山小学"], answerFrameworkZh: ["确认片廊下标准校舍", "比较教室、走廊与开放空间", "联系教学方式变化", "写噪声与管理代价"], answerFrameworkJa: ["片廊下型標準校舎", "教室・廊下・オープンスペース", "教育方法の変化", "音・管理の課題"] },
  { id: "2018-s22-q1", fileName: "2018_専門2-2_建筑计划_Q1.md", ref: { year: 2018, exam: "専門2-2", question: "1" }, titleZh: "Lighthouse International视觉障碍环境", titleJa: "Lighthouse Internationalの視覚障害者環境", kind: "case-reading", requirementZh: "逐图定位并列举弱视与视觉障碍者可使用的环境和标识设计。", requirementJa: "各写真を位置付け、弱視・視覚障害者のための環境・サイン計画を列挙する。", concepts: ["universal-design"], cases: ["Lighthouse International纽约总部"], answerFrameworkZh: ["只写照片中可见事实", "对象—信息渠道—效果", "视觉与触觉信息并列", "替代门牌可用声音提示"], answerFrameworkJa: ["写真で確認できる事実", "対象・情報手段・効果", "視覚・触覚情報", "音声による代替"] },
  { id: "2019-s22-q1", fileName: "2019_専門2-2_建筑计划_Q1.md", ref: { year: 2019, exam: "専門2-2", question: "1" }, titleZh: "五组建筑概念差异", titleJa: "五組の建築概念の相違", kind: "concept", requirementZh: "每组在5行内同时定义两端并指出根本差异。", requirementJa: "各組について両概念を定義し、根本的な差を5行以内で説明する。", concepts: ["universal-space", "servant-space", "bim", "cam", "dymaxion", "tensegrity", "metabolism", "organic-architecture", "public-space", "common-space"], cases: [], answerFrameworkZh: ["概念A定义", "概念B定义", "比较组织方式或技术", "一句话明确区别"], answerFrameworkJa: ["概念Aの定義", "概念Bの定義", "構成・技術の比較", "差を一文で明示"] },
  { id: "2019-s22-q4", fileName: "2019_専門2-2_建筑计划_Q4.md", ref: { year: 2019, exam: "専門2-2", question: "4" }, titleZh: "鸟羽海之博物馆与丰岛美术馆", titleJa: "鳥羽市立海の博物館と豊島美術館", kind: "case-reading", requirementZh: "从空间、设计、结构和细部说明两座建筑。", requirementJa: "空間・デザイン・構造・ディテールから二建築を説明する。", concepts: ["organic-architecture"], cases: ["鸟羽市立海之博物馆展示栋", "丰岛美术馆"], answerFrameworkZh: ["识别主空间形态", "说明结构如何实现形态", "描述光与材料细部", "评价身体体验"], answerFrameworkJa: ["主空間形態", "形態を支える構造", "光・材料・ディテール", "身体的体験"] },
  { id: "2020-s22-q1", fileName: "2020_専門2-2_建筑计划_Q1.md", ref: { year: 2020, exam: "専門2-2", question: "1" }, titleZh: "こもれび之家与旧宫前小学", titleJa: "こもれびの家と旧宮前小学校", kind: "case-reading", requirementZh: "分别以建筑计划视角写两案例约10行。", requirementJa: "二事例を建築計画学的視点から各10行程度で説明する。", concepts: ["small-unit-care", "open-school"], cases: ["こもれび之家", "旧宫前小学"], answerFrameworkZh: ["识别主要生活／学习单位", "连接个室、共同空间与外部", "说明观察或教学运营", "写开放带来的管理课题"], answerFrameworkJa: ["生活・学習単位", "個室・共用・外部の接続", "見守り・教育運営", "開放性の管理課題"] },
  { id: "2023-s22-q2", fileName: "2023_専門2-2_建筑计划_Q2.md", ref: { year: 2023, exam: "専門2-2", question: "2" }, titleZh: "两座特养的空间图与Unit Care", titleJa: "二つの特養の空間グラフとユニットケア", kind: "spatial-analysis", requirementZh: "从外部与HS两个起点重画节点图，用步数解释照护意义。", requirementJa: "外部とHSを起点にグラフを描き、ステップ数からケア上の意味を説明する。", concepts: ["space-graph", "small-unit-care"], cases: ["东京老人院", "とかみ共生苑"], answerFrameworkZh: ["按指定房间建立图", "分别以外部和HS为step 0", "引用具体步数差", "联系方向感、交往与见守"], answerFrameworkJa: ["指定室のグラフ化", "外部・HSをstep 0", "具体的ステップ差", "見当識・交流・見守り"] },
  { id: "2023-s22-q4", fileName: "2023_専門2-2_建筑计划_Q4.md", ref: { year: 2023, exam: "専門2-2", question: "4" }, titleZh: "京町家、Shop House与Insula", titleJa: "京町家・ショップハウス・インスラ", kind: "comparison", requirementZh: "用平面草图、城市条件与气候解释三种城市住宅。", requirementJa: "平面スケッチ、都市条件、気候から三つの都市住宅を説明・比較する。", concepts: [], cases: ["京町家", "东南亚Shop House", "古罗马Insula"], answerFrameworkZh: ["画出临街—通庭—居室—后部", "联系狭长城市地块", "比较骑楼、中庭与层数", "用气候和居住单位解释差异"], answerFrameworkJa: ["街路・通り庭・居室・後部", "細長い都市敷地", "騎楼・中庭・階数", "気候・居住単位の差"] },
  { id: "2024-s22-q1", fileName: "2024_専門2-2_建筑计划_Q1.md", ref: { year: 2024, exam: "専門2-2", question: "1" }, titleZh: "战前战后的东京公共集合住宅", titleJa: "戦前・戦後の東京の公的集合住宅", kind: "comparison", requirementZh: "把四图关联成战前／战后两组，在20行内进行对比。", requirementJa: "四図を戦前・戦後の二組として関連付け、20行以内で対比する。", concepts: [], cases: ["战前城市型公共住宅", "战后开放团地", "51C型住户"], answerFrameworkZh: ["先把配置与住户配成两组", "比较城市肌理与平行住栋", "比较生活近代化与食寝分离", "指出公共供给改善居住的连续性"], answerFrameworkJa: ["配置・住戸を二組化", "都市組織・平行住棟", "生活近代化・食寝分離", "公的供給の連続性"] },
  { id: "2025-s22-q1", fileName: "2025_専門2-2_建筑计划_Q1.md", ref: { year: 2025, exam: "専門2-2", question: "1" }, titleZh: "病室与美术馆的平面比较", titleJa: "病室と美術館の平面比較", kind: "comparison", requirementZh: "分别参照标准方案，说明另一病室与十和田美术馆的计划特征。", requirementJa: "標準案を参照し、別形式の病室と十和田市現代美術館の計画的特徴を説明する。", concepts: [], cases: ["东京临海医院", "西神户医疗中心", "世田谷美术馆", "十和田市现代美术馆"], answerFrameworkZh: ["先明确参照方案", "用同一组比较轴读两者", "说明空间收益", "补充护理或运营代价"], answerFrameworkJa: ["参照案の明示", "共通比較軸", "空間的効果", "看護・運営上の代償"] },
  { id: "2026-s22-q1", fileName: "2026_専門2-2_建筑计划_Q1.md", ref: { year: 2026, exam: "専門2-2", question: "1" }, titleZh: "三座建筑任选二进行计划分析", titleJa: "三建築から二つを選ぶ計画分析", kind: "case-reading", requirementZh: "从晴海、日野图书馆、Eveline Lowe小学中任选两项，各写约10行。", requirementJa: "晴海、日野図書館、イブリン・ロウ小学校から二つを選び、各10行程度で説明する。", concepts: ["open-school"], cases: ["晴海高层公寓", "日野市立中央图书馆", "Eveline Lowe小学"], answerFrameworkZh: ["从题图提取稳定关系", "说明主要空间与动线机制", "写使用或运营收益", "补充限制并作计划评价"], answerFrameworkJa: ["図から安定した関係を抽出", "空間・動線メカニズム", "利用・運営への効果", "制約と計画評価"] },
];

export const PLANNING_ESSAY_EXCLUDED_NUMERIC = [
  "2016 専門2-2 Q1：郊外大型店舗の駐車場規模",
  "2018 専門2-2 Q2：都心オフィスの最適プロポーション",
  "2019 専門2-2 Q2：家具工場の線形計画",
  "2020 専門2-2 Q2：待ち行列理論",
  "2022 専門2-2 Q2：公共施設数の費用最適化",
  "2024 専門2-2 Q2：施設分布関数の数理分析",
  "2025 専門2-2 Q2：住宅の空間グラフ・平均ステップ数・中心性",
  "2026 専門2-2 Q2：エレベータ運行モデル",
] as const;

export const PLANNING_ESSAY_SOURCE_LIMITS: Record<string, { zh: string; ja: string }> = {
  "2018-s22-q1": {
    zh: "东京大学公开版保留Photo 1、Photo 2和Fig.3，但Photo 3–6及定位用Fig.1/2已被版权占位图替换，因此无法可靠恢复全部“照片—图中字母”对应。",
    ja: "東京大学公開版ではPhoto 1、Photo 2、Fig.3のみ確認でき、Photo 3–6と位置同定用Fig.1/2は著作権上のプレースホルダーに置換されているため、全ての写真・記号対応を復元できない。",
  },
};

export const PLANNING_ESSAY_DETAIL_BLOCKS: Record<string, PlanningEssayDetailBlock[]> = {
  "2013-s1-q3": [
    {
      id: "dimensions-meeting-room",
      titleZh: "(1)-① 8人会议室与家具尺寸",
      titleJa: "(1)-① 8人用会議室と家具寸法",
      promptZh: "先声明会议形式与通行条件，再给出一组相互吻合的房间、桌椅尺寸。",
      promptJa: "会議形式と通行条件を先に設定し、室・机・椅子の整合する寸法を示す。",
      keyPointsZh: ["示例条件：长桌两侧各3人、端部各1人", "桌面约2400×1200mm，高度约700–720mm；座面高约420–450mm", "桌边每人约600mm，并在椅后预留约900mm拉椅与通行", "因此可取约4200×3600mm的房间；数字必须由人数、动作和通行反推"],
      keyPointsJa: ["条件例：長辺各3人、短辺各1人の対面会議", "机約2400×1200mm、高さ700–720mm、座面高420–450mm", "一人当たり机縁約600mm、椅子後方に引き代・通行約900mm", "室は約4200×3600mmとし、人数・動作・通行から寸法を説明する"],
    },
    {
      id: "dimensions-four-bed-room",
      titleZh: "(1)-② 4床病房尺寸与层高",
      titleJa: "(1)-② 4床病室の寸法と天井高",
      promptZh: "以护理、移床、床边操作、采光通风和患者停留为条件，而不是孤立背一个面积数字。",
      promptJa: "看護、ベッド移動、ベッドサイド作業、採光・換気、患者滞在を条件として寸法を決める。",
      keyPointsZh: ["示例方案：约6400×5400mm、约34.5㎡，作为说明尺寸推导的一个可行设定", "床之间及主要护理侧保证约900mm级操作宽度，入口应允许病床转运", "床头设备、收纳、洗面与窗边个人领域不能侵占护理通道", "层高可取约2600mm，并从设备、采光、压迫感和维护说明依据"],
      keyPointsJa: ["設定例：約6400×5400mm、約34.5㎡を一つの成立案とする", "ベッド間・主要看護側に約900mm級の作業幅を確保し、入口はベッド搬送に対応", "枕元設備、収納、洗面、窓際の個人領域が看護動線を侵食しない", "天井高約2600mmとし、設備、採光、圧迫感、維持管理から根拠を述べる"],
    },
    {
      id: "comparison-staircase-access-balcony",
      titleZh: "(2) 阶梯室型／片廊下型的社区差异",
      titleJa: "(2) 階段室型／片廊下型のコミュニティ差",
      promptZh: "只选择一个最根本差异：共同交通空间服务多少住户，以及接触范围如何形成。",
      promptJa: "共用動線が何戸を結び、接触範囲をどう形成するかという一点に絞る。",
      keyPointsZh: ["阶梯室型：一个楼梯服务少量住户，成员范围小而稳定", "片廊下型：长廊联系较多住户，偶遇机会多但领域归属较弱", "不要把‘交流多’写成绝对优点；同时评价经过、噪声、私密和监视感"],
      keyPointsJa: ["階段室型：一つの階段が少数住戸を結び、成員が限定され安定する", "片廊下型：長い共用廊下が多数住戸を結び、接触機会は増すが領域帰属は弱い", "交流量だけで評価せず、通過、騒音、プライバシー、監視感も書く"],
    },
    {
      id: "comparison-hotel-ryokan-library-market",
      titleZh: "(3)(4) 住宿差异与选择式空间的相似性",
      titleJa: "(3)(4) 宿泊形式の差と選択型空間の類似",
      promptZh: "分别完成‘酒店／和风旅馆的差异’与‘图书馆／超市的相似’两种比较动作。",
      promptJa: "ホテル／旅館の相違と、図書館／スーパーの類似という二つの比較を分けて答える。",
      keyPointsZh: ["酒店：客房功能相对固定、自包含，公共服务与客房交通分离", "和风旅馆：同一和室随用餐、起居、铺被转换，玄关脱鞋、浴场和仲居服务形成连续体验", "图书馆与超市都把大量对象按类别开放陈列，让使用者自行浏览、比较、选择", "两者都依赖货架／书架、标识、回游路径和出口处的借还／结算，但停留时间与安静要求不同"],
      keyPointsJa: ["ホテル：客室機能が固定的・自己完結的で、共用サービスと客室動線を分離", "旅館：同じ和室を食事・団らん・就寝へ転換し、脱履、浴場、仲居サービスが連続", "図書館とスーパーはいずれも多数の対象を分類・開架し、利用者が閲覧・比較・選択する", "書架・棚、サイン、回遊経路、出口の貸出・精算が共通するが、滞在時間と静粛性は異なる"],
    },
  ],
  "2018-s22-q1": [
    {
      id: "photo-1",
      titleZh: "Photo 1：Independent Living Services接待区",
      titleJa: "Photo 1：Independent Living Services受付",
      promptZh: "公开图可确认接待柜台及其前方通道；Fig.中的字母位置因公开版Fig.1/2缺图而不能核定。",
      promptJa: "公開写真から受付カウンターと前面通路は確認できるが、公開版Fig.1/2欠落のため図中記号は確定できない。",
      keyPointsZh: ["墙面名称采用深色大字与浅色背景，便于弱视者辨认", "顶灯连续且照度较均匀，有助于定位接待位置", "地面以色块／明度差形成路径提示", "柜台向通道凸出，边缘和转角需要用对比与圆角避免碰撞"],
      keyPointsJa: ["壁面名称を濃色大文字・明るい背景で表示し弱視者が識別しやすい", "連続した天井照明で受付位置を把握しやすい", "床の色・明度差が経路の手掛かりになる", "通路へ張り出すカウンター端部はコントラストと角処理が重要"],
      image: "/past-exams/2018年度_建築専門2-2_公開版_2062812160888414208_6da9beb87b52.jpg",
      sourceStatus: "verified",
    },
    {
      id: "photo-2",
      titleZh: "Photo 2：建筑主入口",
      titleJa: "Photo 2：建物主入口",
      promptZh: "可识别为玻璃自动门入口；具体Fig.1字母位置因公开版轴测图缺失而不能核定。",
      promptJa: "ガラス自動扉の主入口と判断できるが、公開版アクソメ欠落のためFig.1の記号は確定できない。",
      keyPointsZh: ["自动滑门减少寻找把手和开门操作负担", "玻璃上连续圆点提高透明门的可见性并提示门面位置", "入口标志大、明暗对比强，便于远距离识别", "门前地垫和地面变化可作为脚下触感与入口边界提示"],
      keyPointsJa: ["自動引戸により取手探索と開閉操作の負担を減らす", "ガラス面の連続ドットが透明扉の存在と位置を示す", "大きく高コントラストなロゴで遠方から入口を識別できる", "玄関マットと床仕上げの変化が足裏の手掛かりと境界になる"],
      image: "/past-exams/2018年度_建築専門2-2_公開版_2062812160888414208_ee01d1b74e4d.jpg",
      sourceStatus: "verified",
    },
    {
      id: "photo-3-6",
      titleZh: "Photo 3–6：公开版不可恢复",
      titleJa: "Photo 3–6：公開版では復元不能",
      promptZh: "这些照片在公开版中被“个人提供照片”占位图替换，不能可靠描述位置或具体措施。",
      promptJa: "公開版では「個人提供写真」のプレースホルダーへ置換され、位置・具体的工夫を信頼して記述できない。",
      keyPointsZh: ["不得用一般无障碍知识冒充照片中的可见事实", "若取得考试当日原图，应按‘Photo—Fig字母—构件—信息渠道—效果’补录", "当前题卡保留缺口说明，防止生成虚假对应"],
      keyPointsJa: ["一般的なバリアフリー知識を写真の事実として代用しない", "原図入手時はPhoto・Fig記号・部位・情報手段・効果の順で追記", "虚偽の対応を防ぐため欠落状態を明示する"],
      sourceStatus: "public-source-redacted",
    },
    {
      id: "fig-3-sign",
      titleZh: "Fig.3：触觉与高对比门牌",
      titleJa: "Fig.3：触覚・高コントラストサイン",
      promptZh: "这一图在公开版中保留，可直接列举标识设计。",
      promptJa: "公開版で確認できるため、サインの工夫を直接列挙できる。",
      keyPointsZh: ["黑底白色大字形成高明度对比", "文字信息简洁、字号大，方便近距离读取", "下部倾斜面便于手触，包含触觉文字／点字信息", "除门牌外可用感应语音播报或电子信标传达房间名称"],
      keyPointsJa: ["黒地に白の大文字で高い明度差を確保", "情報を簡潔にし、近距離で読みやすい文字寸法", "下部の傾斜面を触りやすくし、触知文字・点字を併記", "サイン以外にはセンサー音声案内や電子ビーコンで室名を伝達"],
      image: "/past-exams/2018年度_建築専門2-2_公開版_2062812160888414208_4626606d88ef.jpg",
      sourceStatus: "verified",
    },
  ],
  "2024-s22-q1": [
    {
      id: "figure-a",
      titleZh: "Fig.A：战前城市地块型配置",
      titleJa: "Fig.A：戦前の都市敷地型配置",
      promptZh: "建筑顺应狭长、不规则的既有城市地块与道路组织，不采用统一南向平行排列。",
      promptJa: "細長く不整形な既成市街地の敷地・道路に応答し、均一な南面平行配置ではない。",
      keyPointsZh: ["住栋方向和长度多样", "道路与小型外部空间嵌入住栋之间", "体现战前公的住宅仍与既有城市肌理紧密结合"],
      keyPointsJa: ["住棟方位・長さが多様", "道路と小規模外部空間が住棟間へ入り込む", "戦前の公的住宅が既成市街地組織と密接に結び付く"],
      image: "/past-exams/2024年度_建築専門2-2_公開版_2062812379948527616_9e843430955f.jpg",
      sourceStatus: "verified",
    },
    {
      id: "figure-b",
      titleZh: "Fig.B：战后团地式平行住栋配置",
      titleJa: "Fig.B：戦後団地の平行住棟配置",
      promptZh: "标准化板状住栋以采光、通风和建设效率为依据，规则地配置在开放用地中。",
      promptJa: "標準化された板状住棟を、日照・通風・建設効率に基づきオープンな敷地へ規則配置する。",
      keyPointsZh: ["住栋间距和朝向较统一", "建筑脱离沿街围合，置于连续开放空间中", "适合战后大量、标准化公共住宅供给"],
      keyPointsJa: ["住棟間隔・方位が比較的均一", "沿道囲みから離れ、連続オープンスペース内に配置", "戦後の大量・標準化された公共住宅供給に適する"],
      image: "/past-exams/2024年度_建築専門2-2_公開版_2062812379948527616_9968abfb823e.jpg",
      sourceStatus: "verified",
    },
    {
      id: "figure-c",
      titleZh: "Fig.C：战前阶梯室型住户",
      titleJa: "Fig.C：戦前の階段室型住戸",
      promptZh: "由共同楼梯直接进入少量住户，房间功能尚未按DK与就寝关系明确标准化。",
      promptJa: "共用階段から少数住戸へ直接入り、室用途はDKと就寝関係によって明確に標準化されていない。",
      keyPointsZh: ["共同楼梯服务少量住户", "紧凑配置厕所、炊事与榻榻米房间", "房间之间具有连续使用和用途转换的传统住宅特征"],
      keyPointsJa: ["共用階段が少数住戸を担当", "便所・炊事・畳室をコンパクトに配置", "室の連続利用・用途転換という伝統住宅的性格"],
      image: "/past-exams/2024年度_建築専門2-2_公開版_2062812379948527616_132b55042bcb.jpg",
      sourceStatus: "verified",
    },
    {
      id: "figure-d",
      titleZh: "Fig.D：战后51C型标准住户",
      titleJa: "Fig.D：戦後の51C型標準住戸",
      promptZh: "两室与DK明确组织，体现以居住调查为基础的食寝分离和战后标准化住宅计划。",
      promptJa: "二室とDKを明確に構成し、住み方調査に基づく食寝分離と戦後標準設計を示す。",
      keyPointsZh: ["DK把进餐从榻榻米就寝室中分离", "两居室与收纳支持家庭成员的就寝分离", "厕所、炊事、收纳被标准化；早期方案通常不设完整浴室", "Fig.A＋C构成战前组，Fig.B＋D构成战后组"],
      keyPointsJa: ["DKにより食事を畳の就寝室から分離", "二居室と収納が家族の就寝分離を支える", "便所・炊事・収納を標準化し、初期案は完全な浴室を持たない", "Fig.A＋Cが戦前、Fig.B＋Dが戦後の組"],
      image: "/past-exams/2024年度_建築専門2-2_公開版_2062812379948527616_f5ae35a03a26.jpg",
      sourceStatus: "verified",
    },
  ],
};
