/**
 * Question Store — Read-Only TypeScript Layer
 * ============================================
 * Reads data/questions.json (generated by scripts/generate-questions.py).
 * Provides type-safe query functions for the optimized question pool.
 */

import fs from "fs";
import path from "path";

// ============================================================================
// Types
// ============================================================================

export interface QuestionOption {
  label: string;   // e.g. "A."
  text: string;    // e.g. "パンテオン"
}

export interface QuestionData {
  prompt: string;
  options: string[];       // ["A. ...", "B. ...", ...]
  correctIndex: number;
  answerExplanation: string;
}

export interface QuestionValidation {
  issues: string[];
  optLog: string[];
}

export interface QuestionTraceability {
  originalSource: string;
  originalField: string;
  extractedFacts: string[];
  blueprint: string;
  blueprintOccurrences: Array<{
    year: number;
    category: string;
    questionNumber: string;
    originalForm: string;
  }>;
  confidence: string;
}

export interface GeneratedQuestion {
  id: string;
  subject: "history" | "planning" | "environment" | "construction";
  blueprintId: string;
  question: QuestionData;
  distractorRationale: Record<string, string>;
  validation: QuestionValidation;
  qualityScore: number;
  qualityPassed: boolean;
  traceability: QuestionTraceability;
}

interface QuestionStore {
  version: number;
  generatedAt: string;
  totalQuestions: number;
  averageQuality: number;
  rejectedCount: number;
  questions: GeneratedQuestion[];
}

// ============================================================================
// Load
// ============================================================================

let _store: QuestionStore | null = null;

function loadStore(): QuestionStore {
  if (_store) return _store;
  const p = path.resolve(process.cwd(), "data/questions.json");
  _store = JSON.parse(fs.readFileSync(p, "utf-8")) as QuestionStore;
  return _store;
}

// ============================================================================
// Query API
// ============================================================================

/** All quality-passed questions */
export function getAllQuestions(): GeneratedQuestion[] {
  return loadStore().questions.filter((q) => q.qualityPassed);
}

/** Questions by subject */
export function getQuestionsBySubject(subject: string): GeneratedQuestion[] {
  return getAllQuestions().filter((q) => q.subject === subject);
}

/** Questions by blueprint */
export function getQuestionsByBlueprint(blueprintId: string): GeneratedQuestion[] {
  return getAllQuestions().filter((q) => q.blueprintId === blueprintId);
}

/** Get a sample of N questions */
export function sampleQuestions(n: number, subject?: string): GeneratedQuestion[] {
  const pool = subject ? getQuestionsBySubject(subject) : getAllQuestions();
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(n, pool.length));
}

/** Stats */
export function getQuestionStats() {
  const all = getAllQuestions();
  const bySubject: Record<string, number> = {};
  const byBlueprint: Record<string, number> = {};
  const byQuality: Record<string, number> = {};

  for (const q of all) {
    bySubject[q.subject] = (bySubject[q.subject] || 0) + 1;
    byBlueprint[q.blueprintId] = (byBlueprint[q.blueprintId] || 0) + 1;
    const bucket = `${Math.floor(q.qualityScore / 10) * 10}-${Math.floor(q.qualityScore / 10) * 10 + 9}`;
    byQuality[bucket] = (byQuality[bucket] || 0) + 1;
  }

  return {
    total: all.length,
    rejected: loadStore().rejectedCount,
    averageQuality: loadStore().averageQuality,
    generatedAt: loadStore().generatedAt,
    bySubject,
    byBlueprint,
    byQuality,
  };
}
