import type { LocalizedReviewItemCopy, ReviewItem, ReviewItemSource } from "./review-items";

type ReviewItemWithJapanese = ReviewItem & { ja: LocalizedReviewItemCopy };

const notionPages = {
  history: "https://app.notion.com/p/3a4e961e469080ec8171fe62817a7047",
  construction: "https://app.notion.com/p/3a4e961e4690805a9386ee00567913f0",
};

const environmentPdf = (page: number): ReviewItemSource => ({
  kind: "pdf",
  label: `環工近期錯題整理 P${page}`,
  fileName: "环境工学.pdf",
  pages: [page],
});

const environmentMap: ReviewItemSource = {
  kind: "site",
  label: "環工記憶マップ",
  href: "/environment-memory",
};

const constructionNotion: ReviewItemSource = {
  kind: "notion",
  label: "近期錯題：建築構法",
  href: notionPages.construction,
};

const historyNotion: ReviewItemSource = {
  kind: "notion",
  label: "近期錯題：建築史",
  href: notionPages.history,
};

const additions: ReviewItemWithJapanese[] = [
  {
    id: "environment-material-conductivity",
    subject: "environment",
    topic: "傳熱",
    title: "材料熱傳導率的量級",
    taskType: "numeric",
    priority: "core",
    years: [],
    prompt: "空氣、玻璃、木材、混凝土、鋼、鋁的熱傳導率量級如何排列？",
    minimumAnswer: "約為空氣 0.022 < 玻璃 0.6 ≈ 木材 0.1–0.2 < 混凝土 1.6 << 鋼 50 < 鋁 200 W/(m·K)。重點是金屬遠高於非金屬，空氣最低。",
    sources: [environmentPdf(1), environmentMap],
    keywords: ["熱伝導率", "λ", "空気", "鋼", "アルミ"],
    ja: { topic: "伝熱", title: "材料の熱伝導率の桁", prompt: "空気・ガラス・木材・コンクリート・鋼・アルミの熱伝導率を小さい順に並べる。", minimumAnswer: "概ね空気0.022 < 木材0.1〜0.2 < ガラス0.6 < コンクリート1.6 << 鋼50 < アルミ200 W/(m・K)。金属は非常に大きく、空気は小さい。" },
  },
  {
    id: "environment-continuity-dynamic-pressure",
    subject: "environment",
    topic: "流體",
    title: "連續方程與動壓",
    taskType: "formula",
    priority: "core",
    years: [],
    prompt: "不可壓縮流的連續方程與動壓公式分別是什麼？",
    minimumAnswer: "連續方程 A₁v₁=A₂v₂；動壓 q=ρv²/2。截面縮小時速度增大，動壓隨速度平方增大。",
    sources: [environmentPdf(1), environmentMap],
    keywords: ["連続の式", "動圧", "A v", "ρv²/2"],
    ja: { topic: "流体", title: "連続の式と動圧", prompt: "非圧縮流体の連続の式と動圧の式を答える。", minimumAnswer: "A₁v₁=A₂v₂、動圧q=ρv²/2。断面が小さくなると流速が増し、動圧は流速の2乗で増える。" },
  },
  {
    id: "environment-wall-thermal-resistance",
    subject: "environment",
    topic: "傳熱",
    title: "牆體總熱阻與傳熱量",
    taskType: "calculation",
    priority: "core",
    years: [],
    prompt: "單層牆含內外表面熱阻時，總熱阻與熱流密度如何寫？",
    minimumAnswer: "Rtotal=1/αi+d/λ+1/αo，熱流密度 q=ΔT/Rtotal；多層牆把各層 d/λ 依序相加。",
    sources: [environmentPdf(1), environmentPdf(2), environmentMap],
    keywords: ["熱抵抗", "熱貫流率", "d/λ", "表面熱伝達"],
    ja: { topic: "伝熱", title: "壁体の総合熱抵抗と熱流", prompt: "内外表面熱抵抗を含む単層壁の総合熱抵抗と熱流密度を示す。", minimumAnswer: "Rtotal=1/αi+d/λ+1/αo、q=ΔT/Rtotal。多層壁は各層のd/λを加算する。" },
  },
  {
    id: "environment-ventilation-generation",
    subject: "environment",
    topic: "換氣",
    title: "污染物發生量法的必要換氣量",
    taskType: "formula",
    priority: "core",
    years: [],
    prompt: "已知污染物發生量與室內外容許濃度時，必要換氣量如何求？",
    minimumAnswer: "穩態質量平衡為 Q=G/(Ci−Co)。濃度要用相同體積比單位；人數增加時先把每人發生量乘以人數。",
    sources: [environmentPdf(1), environmentPdf(2), environmentMap],
    keywords: ["必要換気量", "CO2", "G/(Ci-Co)", "質量収支"],
    ja: { topic: "換気", title: "汚染物発生量による必要換気量", prompt: "汚染物発生量と室内外許容濃度から必要換気量を求める式は何か。", minimumAnswer: "定常物質収支よりQ=G/(Ci−Co)。濃度単位をそろえ、人数分の発生量を合計する。" },
  },
  {
    id: "environment-beer-lambert",
    subject: "environment",
    topic: "採光",
    title: "Beer–Lambert 衰減",
    taskType: "formula",
    priority: "support",
    years: [],
    prompt: "吸收介質中光強隨厚度如何衰減？",
    minimumAnswer: "I=I₀e^(−αd)。吸收係數 α 或厚度 d 增加，透射光按指數衰減，而不是線性下降。",
    sources: [environmentPdf(1), environmentPdf(2), environmentMap],
    keywords: ["Beer-Lambert", "透過率", "指数減衰", "αd"],
    ja: { topic: "採光", title: "Beer–Lambertの減衰", prompt: "吸収媒体内の光強度は厚さに対してどう減衰するか。", minimumAnswer: "I=I₀e^(−αd)。吸収係数または厚さが増すと、透過光は指数関数的に減衰する。" },
  },
  {
    id: "environment-daylight-types",
    subject: "environment",
    topic: "採光",
    title: "直射、天空與反射日光",
    taskType: "comparison",
    priority: "support",
    years: [],
    prompt: "直射日光、天空光與反射日光分別從哪裡到達室內？",
    minimumAnswer: "直射日光直接來自太陽；天空光是大氣散射後由天空到達；反射日光是先被地面或周邊建築反射後再進入。",
    sources: [environmentPdf(1), environmentMap],
    keywords: ["直射日光", "天空光", "反射光", "昼光"],
    ja: { topic: "採光", title: "直射日光・天空光・反射日光", prompt: "三つの昼光成分はどこから室内へ届くか。", minimumAnswer: "直射日光は太陽から直接、天空光は大気で散乱して天空から、反射日光は地面や周辺建物で反射して届く。" },
  },
  {
    id: "environment-munsell-system",
    subject: "environment",
    topic: "色彩",
    title: "Munsell 三屬性",
    taskType: "concept",
    priority: "core",
    years: [],
    prompt: "Munsell 表色系的三個屬性是什麼？例如 5YR 3.5/4 如何讀？",
    minimumAnswer: "三屬性為色相、明度、彩度。5YR 3.5/4 表示色相 5YR、明度 3.5、彩度 4；彩度 0 為無彩色。",
    sources: [environmentPdf(1), environmentMap],
    keywords: ["マンセル", "色相", "明度", "彩度"],
    ja: { topic: "色彩", title: "マンセルの三属性", prompt: "マンセル表色系の三属性と、5YR 3.5/4の読み方を答える。", minimumAnswer: "色相・明度・彩度。5YRが色相、3.5が明度、4が彩度で、彩度0は無彩色。" },
  },
  {
    id: "environment-sound-speed-octave",
    subject: "environment",
    topic: "音響",
    title: "聲速、波長與 octave",
    taskType: "formula",
    priority: "support",
    years: [],
    prompt: "聲速、頻率、波長的關係是什麼？一個 octave 代表什麼？",
    minimumAnswer: "c=fλ，常溫空氣中 c≈331+0.6θ m/s；升高一個 octave 表示頻率加倍，降低一個 octave 表示頻率減半。",
    sources: [environmentPdf(1), environmentMap],
    keywords: ["音速", "波長", "周波数", "オクターブ"],
    ja: { topic: "音響", title: "音速・波長・オクターブ", prompt: "音速・周波数・波長の関係と、1オクターブの意味を答える。", minimumAnswer: "c=fλ、常温空気中ではc≈331+0.6θ m/s。1オクターブ上は周波数2倍、下は1/2。" },
  },
  {
    id: "environment-sound-audible-effects",
    subject: "environment",
    topic: "音響",
    title: "可聽範圍、masking 與 cocktail party",
    taskType: "comparison",
    priority: "core",
    years: [],
    prompt: "可聽頻率範圍是多少？masking 與 cocktail party effect 如何區分？",
    minimumAnswer: "可聽範圍約 20 Hz–20 kHz。masking 是一個聲音使另一聲音變得難以聽見；cocktail party effect 是在多聲源中選擇性注意並聽取目標聲音。",
    sources: [environmentPdf(2), environmentMap],
    keywords: ["可聴周波数", "マスキング", "カクテルパーティー"],
    ja: { topic: "音響", title: "可聴域・マスキング・カクテルパーティー", prompt: "可聴周波数帯と二つの聴覚現象を区別する。", minimumAnswer: "可聴域は約20 Hz〜20 kHz。マスキングは別音を聞こえにくくする現象、カクテルパーティー効果は多声源から目的音を選択して聞く現象。" },
  },
  {
    id: "environment-echo-types",
    subject: "environment",
    topic: "音響",
    title: "鳴龍、flutter echo 與 booming",
    taskType: "comparison",
    priority: "support",
    years: [],
    prompt: "三種特殊音響現象各由什麼反射條件造成？",
    minimumAnswer: "鳴龍是特定天花等曲面下拍手聲形成的多重反射；flutter echo 是平行反射面間的快速往返反射；booming 是低頻在室內共振而被異常放大。",
    sources: [environmentPdf(2), environmentMap],
    keywords: ["鳴き竜", "flutter echo", "booming", "反射"],
    ja: { topic: "音響", title: "鳴き竜・フラッターエコー・ブーミング", prompt: "三つの特殊な音響現象を反射・共振条件から区別する。", minimumAnswer: "鳴き竜は特定天井下の多重反射、フラッターエコーは平行面間の往復反射、ブーミングは低音域の室共振による異常増幅。" },
  },
  {
    id: "environment-radiation-exchange",
    subject: "environment",
    topic: "傳熱",
    title: "兩表面間的放射換熱",
    taskType: "formula",
    priority: "core",
    years: [],
    prompt: "兩表面間淨放射換熱的溫度項與放射率如何進入公式？",
    minimumAnswer: "淨交換量與 σ(T₁⁴−T₂⁴) 成正比；灰體表面的等效放射率由兩表面放射率與幾何形態係數共同決定。溫度必須用 K。",
    sources: [environmentPdf(2), environmentMap],
    keywords: ["放射熱交換", "T⁴", "放射率", "形態係数"],
    ja: { topic: "伝熱", title: "二面間の放射熱交換", prompt: "二面間の正味放射熱交換で温度と放射率はどう効くか。", minimumAnswer: "正味交換量はσ(T₁⁴−T₂⁴)に比例し、灰色面の有効放射率は両面の放射率と形態係数で決まる。温度はKを使う。" },
  },
  {
    id: "environment-wind-ventilation",
    subject: "environment",
    topic: "換氣",
    title: "風壓換氣的公式鏈",
    taskType: "calculation",
    priority: "core",
    years: [],
    prompt: "從風壓係數到兩開口有效面積，再到換氣量的公式鏈是什麼？",
    minimumAnswer: "先由 Δp=(Cp1−Cp2)ρv²/2 求壓差；兩開口串聯時 Ae=A1A2/√(A1²+A2²)；最後 Q=αAe√(2Δp/ρ)。",
    sources: [environmentPdf(2), environmentMap],
    keywords: ["風力換気", "風圧係数", "有効開口面積", "Δp"],
    ja: { topic: "換気", title: "風力換気の式の流れ", prompt: "風圧係数から有効開口面積と換気量までの式をつなげる。", minimumAnswer: "Δp=(Cp1−Cp2)ρv²/2、直列二開口ではAe=A1A2/√(A1²+A2²)、Q=αAe√(2Δp/ρ)。" },
  },
  {
    id: "environment-glass-types",
    subject: "environment",
    topic: "材料・外皮",
    title: "四種玻璃的差別",
    taskType: "comparison",
    priority: "core",
    years: [],
    prompt: "複層、Low-E 複層、熱線吸收、熱線反射玻璃的構造或作用有何不同？",
    minimumAnswer: "複層玻璃以中空層提高隔熱；Low-E 在玻璃面設低放射膜以抑制輻射換熱；熱線吸收玻璃把日射能量吸收為熱；熱線反射玻璃以表面膜反射日射。",
    sources: [environmentPdf(2), environmentMap],
    keywords: ["複層ガラス", "Low-E", "熱線吸収", "熱線反射"],
    ja: { topic: "材料・外皮", title: "四種類のガラス", prompt: "複層・Low-E複層・熱線吸収・熱線反射ガラスを区別する。", minimumAnswer: "複層は中空層で断熱、Low-Eは低放射膜で放射熱移動を抑制、熱線吸収は日射を熱として吸収、熱線反射は表面膜で日射を反射する。" },
  },
  {
    id: "environment-vapor-permeance",
    subject: "environment",
    topic: "濕氣",
    title: "透濕率與透濕阻抗",
    taskType: "formula",
    priority: "support",
    years: [],
    prompt: "透濕率與透濕阻抗是什麼關係？數值大代表什麼？",
    minimumAnswer: "透濕阻抗是透濕率的倒數。透濕率大表示水蒸氣容易通過；透濕阻抗大表示材料較能阻擋水蒸氣。",
    sources: [environmentPdf(3), environmentMap],
    keywords: ["透湿率", "透湿抵抗", "水蒸気"],
    ja: { topic: "湿気", title: "透湿率と透湿抵抗", prompt: "透湿率と透湿抵抗の関係、および数値が大きいときの意味を答える。", minimumAnswer: "透湿抵抗は透湿率の逆数。透湿率が大きいほど水蒸気を通しやすく、透湿抵抗が大きいほど通しにくい。" },
  },
  {
    id: "environment-degree-day",
    subject: "environment",
    topic: "空調負荷",
    title: "degree day",
    taskType: "concept",
    priority: "support",
    years: [],
    prompt: "degree day 如何把室外溫度與時間合成為氣候／負荷指標？",
    minimumAnswer: "以基準溫度與每日平均室外溫度之差，對需要供暖或制冷的日子累加；同時反映溫差大小與持續天數。",
    sources: [environmentPdf(3), environmentMap],
    keywords: ["degree day", "デグリーデー", "暖房負荷", "気候"],
    ja: { topic: "空調負荷", title: "デグリーデー", prompt: "外気温と時間をどう一つの気候・負荷指標にするか。", minimumAnswer: "基準温度と日平均外気温との差を、暖冷房が必要な日にわたり積算し、温度差と継続日数を同時に表す。" },
  },
  {
    id: "environment-double-skin",
    subject: "environment",
    topic: "外皮",
    title: "double-skin facade",
    taskType: "concept",
    priority: "support",
    years: [],
    prompt: "雙層外皮的基本構成與主要環境作用是什麼？",
    minimumAnswer: "內外兩層立面之間形成可通風的空腔，可配合遮陽排走日射熱、改善冬季保溫與自然通風；效果取決於季節控制與開口。",
    sources: [environmentPdf(3), environmentMap],
    keywords: ["ダブルスキン", "通気層", "日射遮蔽", "外皮"],
    ja: { topic: "外皮", title: "ダブルスキンファサード", prompt: "基本構成と主な環境効果を答える。", minimumAnswer: "内外二層の外皮間に通気可能な空間を設け、日射熱排出・冬季保温・自然換気を助ける。効果は季節ごとの開口制御に依存する。" },
  },
  {
    id: "environment-mechanical-ventilation-types",
    subject: "environment",
    topic: "換氣",
    title: "三種機械換氣方式",
    taskType: "comparison",
    priority: "core",
    years: [],
    prompt: "第一、第二、第三種機械換氣的送風與排風分別是機械還是自然？",
    minimumAnswer: "第一種：機械送風＋機械排風；第二種：機械送風＋自然排風，室內偏正壓；第三種：自然送風＋機械排風，室內偏負壓。",
    sources: [environmentPdf(3), environmentMap],
    keywords: ["第一種換気", "第二種換気", "第三種換気", "正圧", "負圧"],
    ja: { topic: "換気", title: "三つの機械換気方式", prompt: "第1・第2・第3種換気の給気と排気を機械／自然で区別する。", minimumAnswer: "第1種は機械給気＋機械排気、第2種は機械給気＋自然排気で正圧、第3種は自然給気＋機械排気で負圧になりやすい。" },
  },
  {
    id: "environment-room-index",
    subject: "environment",
    topic: "照明",
    title: "室指數",
    taskType: "formula",
    priority: "support",
    years: [],
    prompt: "矩形房間的室指數 K 如何由長、寬與燈具計算高度表示？",
    minimumAnswer: "K=LW/[Hm(L+W)]。L、W 為房間長寬，Hm 為燈具至工作面的高度；房間越寬大、燈具相對越低，K 越大。",
    sources: [environmentPdf(3), environmentMap],
    keywords: ["室指数", "照明率", "Hm", "K"],
    ja: { topic: "照明", title: "室指数", prompt: "矩形室の室指数Kを長さ・幅・作業面上高さで示す。", minimumAnswer: "K=LW/[Hm(L+W)]。L・Wは室の長さと幅、Hmは器具から作業面までの高さ。" },
  },
  {
    id: "environment-fan-coil-multizone",
    subject: "environment",
    topic: "空調",
    title: "fan-coil 與 multi-zone unit",
    taskType: "comparison",
    priority: "support",
    years: [],
    prompt: "fan-coil unit 與 multi-zone unit 分別在末端如何調節房間或區域負荷？",
    minimumAnswer: "fan-coil 在各室以盤管與風機處理室內回風，常由中央供冷熱水；multi-zone 在中央空調機內先製作冷、熱風，再按各 zone 混合後分送。",
    sources: [environmentPdf(3), environmentMap],
    keywords: ["ファンコイル", "マルチゾーン", "空調方式", "zone"],
    ja: { topic: "空調", title: "ファンコイルとマルチゾーンユニット", prompt: "二方式は末端・中央でどのように室やゾーンの負荷を調整するか。", minimumAnswer: "ファンコイルは各室のコイルとファンで主に中央供給の冷温水を利用する。マルチゾーンは中央機で冷温風を作り、ゾーンごとに混合して送る。" },
  },
  {
    id: "environment-weber-fechner",
    subject: "environment",
    topic: "感覺",
    title: "Weber–Fechner 法則",
    taskType: "concept",
    priority: "support",
    years: [],
    prompt: "Weber–Fechner 法則如何描述刺激量與感覺量？",
    minimumAnswer: "感覺量大致與刺激量的對數成正比：刺激按倍數增加時，主觀感受近似按等差增加；dB 標度就是典型應用。",
    sources: [environmentPdf(3), environmentMap],
    keywords: ["Weber-Fechner", "感覚量", "刺激量", "対数"],
    ja: { topic: "感覚", title: "ウェーバー・フェヒナーの法則", prompt: "刺激量と感覚量の関係を答える。", minimumAnswer: "感覚量は刺激量の対数にほぼ比例する。刺激が倍率で増えると、主観的感覚は等差的に増える。" },
  },
  {
    id: "environment-wall-transmission-loss",
    subject: "environment",
    topic: "音響",
    title: "單層牆的質量則",
    taskType: "formula",
    priority: "core",
    years: [],
    prompt: "單層均質牆的透過損失與面密度、頻率有什麼關係？倍增時約增加多少？",
    minimumAnswer: "質量則近似 TL=20log₁₀(mf)−C；面密度 m 或頻率 f 加倍，透過損失約增加 6 dB，但 coincidence 頻帶附近會偏離。",
    sources: [environmentPdf(3), environmentMap],
    keywords: ["質量則", "透過損失", "面密度", "coincidence"],
    ja: { topic: "音響", title: "単層壁の質量則", prompt: "透過損失は面密度・周波数とどう関係し、2倍で何dB増えるか。", minimumAnswer: "TL≈20log₁₀(mf)−C。面密度mまたは周波数fが2倍になると約6 dB増えるが、コインシデンス帯では外れる。" },
  },
  {
    id: "construction-keraba-mullion",
    subject: "construction",
    topic: "部位名稱",
    title: "けらば 與 mullion",
    taskType: "comparison",
    priority: "core",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "けらば 和 curtain wall 的 mullion 分別位於哪裡？",
    minimumAnswer: "けらば 是切妻屋頂在妻側的斜向屋面端部；mullion（方立）是幕牆或窗牆中的垂直分格、支承構件。",
    sources: [constructionNotion],
    keywords: ["けらば", "マリオン", "方立", "切妻"],
    ja: { topic: "部位名称", title: "けらばとマリオン", prompt: "それぞれ建物のどこにある部位か。", minimumAnswer: "けらばは切妻屋根の妻側にある斜めの屋根端部。マリオンはカーテンウォールや窓の鉛直方向の区画・支持材。" },
  },
  {
    id: "construction-kanawa-kendon",
    subject: "construction",
    topic: "木造・建具",
    title: "金輪継ぎ 與 ケンドン式",
    taskType: "comparison",
    priority: "support",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "金輪継ぎ是什麼接合？ケンドン式又如何把板或建具裝入？",
    minimumAnswer: "金輪継ぎ是將兩根木材端部互相嵌合並以栓固定的強固長向接合；ケンドン式是先把構件上提插入上槽，再落入下槽固定。",
    sources: [constructionNotion],
    keywords: ["金輪継ぎ", "ケンドン式", "継手", "落とし込み"],
    ja: { topic: "木造・建具", title: "金輪継ぎとケンドン式", prompt: "金輪継ぎの接合と、ケンドン式の建て込み方を説明する。", minimumAnswer: "金輪継ぎは材端を相互にかみ合わせ栓で固定する強固な継手。ケンドン式は上溝へ持ち上げて差し込み、下溝へ落として納める。" },
  },
  {
    id: "construction-kyoro-orioki",
    subject: "construction",
    topic: "木造屋架",
    title: "京呂組 vs 折置組",
    taskType: "comparison",
    priority: "core",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "京呂組與折置組在柱頂、軒桁、小屋梁的上下順序有何不同？",
    minimumAnswer: "京呂組：柱頂先放軒桁，再把小屋梁架在軒桁上；折置組：小屋梁直接置於柱頂，再在其上放軒桁。",
    sources: [constructionNotion],
    keywords: ["京呂組", "折置組", "軒桁", "小屋梁"],
    ja: { topic: "木造小屋組", title: "京呂組と折置組", prompt: "柱頂・軒桁・小屋梁の上下順序を比較する。", minimumAnswer: "京呂組は柱上に軒桁、その上に小屋梁。折置組は柱頂に小屋梁を直接載せ、その上に軒桁を渡す。" },
  },
  {
    id: "construction-stair-stringers",
    subject: "construction",
    topic: "樓梯",
    title: "側桁階段 vs ささら桁階段",
    taskType: "comparison",
    priority: "support",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "側桁與ささら桁分別如何支承踏板？",
    minimumAnswer: "側桁階段由踏板兩側的直線桁材承托或夾持踏板；ささら桁階段的桁材上緣按級高切成鋸齒狀，踏板直接坐在齒形上。",
    sources: [constructionNotion],
    keywords: ["側桁階段", "ささら桁", "段板", "階段"],
    ja: { topic: "階段", title: "側桁階段とささら桁階段", prompt: "二つの桁は段板をどのように支持するか。", minimumAnswer: "側桁は段板両側の直線材で支持・挟み込む。ささら桁は上端を段状に刻み、その上へ段板を載せる。" },
  },
  {
    id: "construction-hanegi",
    subject: "construction",
    topic: "木造屋架",
    title: "桔木（はねぎ）",
    taskType: "concept",
    priority: "support",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "桔木設在哪裡，利用什麼原理支撐深屋簷？",
    minimumAnswer: "設於小屋裏，外端托住屋簷，內端由屋架或重物壓住，以槓桿原理抵抗深簷向下彎曲。",
    sources: [constructionNotion],
    keywords: ["桔木", "はねぎ", "軒", "てこ"],
    ja: { topic: "木造小屋組", title: "桔木（はねぎ）", prompt: "どこに設け、どの原理で深い軒を支えるか。", minimumAnswer: "小屋裏に設け、外端で軒を支え、内端を小屋組や重しで押さえて、てこの原理で深い軒を支持する。" },
  },
  {
    id: "construction-plate-load-test",
    subject: "construction",
    topic: "地基",
    title: "平板載荷試驗",
    taskType: "process",
    priority: "core",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "平板載荷試驗在哪個深度進行、量測什麼、用來判斷什麼？",
    minimumAnswer: "在基礎底面深度設置小型載荷板，逐級加載並量測沉降；由荷重—沉降關係判斷地基承載力與沉降特性。",
    sources: [constructionNotion],
    keywords: ["平板載荷試験", "地耐力", "沈下", "載荷板"],
    ja: { topic: "地盤", title: "平板載荷試験", prompt: "試験位置・測定量・判定対象を答える。", minimumAnswer: "基礎底面深さに小型載荷板を置き、段階載荷して沈下量を測定し、荷重−沈下関係から地盤支持力と沈下特性を判定する。" },
  },
  {
    id: "construction-wood-failure",
    subject: "construction",
    topic: "木材",
    title: "割裂 vs めり込み",
    taskType: "comparison",
    priority: "core",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "木材的割裂與めり込み各由哪個方向、哪種力造成？",
    minimumAnswer: "割裂是裂縫沿纖維方向擴展、木材被劈開；めり込み是纖維垂直方向受局部壓縮，使接觸表面凹陷。",
    sources: [constructionNotion],
    keywords: ["割裂", "めり込み", "繊維方向", "局部圧縮"],
    ja: { topic: "木材", title: "割裂とめり込み", prompt: "繊維方向と作用力から二現象を区別する。", minimumAnswer: "割裂は繊維方向へ裂け目が進み材が割れる現象。めり込みは繊維直角方向の局部圧縮で接触面がへこむ現象。" },
  },
  {
    id: "construction-yielding",
    subject: "construction",
    topic: "鋼材",
    title: "降伏現象",
    taskType: "concept",
    priority: "core",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "材料進入降伏後，應力與應變如何變化？",
    minimumAnswer: "應力達到一定值後，即使應力不再明顯增加，塑性應變仍持續增加；軟鋼拉伸試驗會出現明顯降伏段。",
    sources: [constructionNotion],
    keywords: ["降伏", "塑性ひずみ", "応力ひずみ", "軟鋼"],
    ja: { topic: "鋼材", title: "降伏現象", prompt: "降伏後の応力とひずみはどう変化するか。", minimumAnswer: "応力が一定値に達すると、応力がほぼ増えなくても塑性ひずみが増加する。軟鋼の引張試験では明瞭な降伏棚が現れる。" },
  },
  {
    id: "construction-board-layouts",
    subject: "construction",
    topic: "板材接合",
    title: "千鳥、さね、はぎ",
    taskType: "comparison",
    priority: "support",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "千鳥配置、さね 與 はぎ 分別描述什麼？",
    minimumAnswer: "千鳥是把相鄰接縫錯開排列；さね 是板邊細長的凸舌；はぎ 是把多塊板邊以舌槽等方式接合成較寬板面的做法。",
    sources: [constructionNotion],
    keywords: ["千鳥", "さね", "はぎ", "板接ぎ"],
    ja: { topic: "板材接合", title: "千鳥・さね・はぎ", prompt: "三語が示す配置・部位・接合法を区別する。", minimumAnswer: "千鳥は継目を互い違いに配置すること。さねは板端の細長い凸部。はぎは板同士をさね等で接ぎ、幅広い面を作る方法。" },
  },
  {
    id: "construction-osb-lsb",
    subject: "construction",
    topic: "木質材料",
    title: "OSB vs LSB",
    taskType: "comparison",
    priority: "support",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "OSB 與 LSB 的原料形狀和排列方式有何不同？",
    minimumAnswer: "OSB 以較薄的木刨片／strand 定向分層後膠壓成板；LSB 使用較長、較厚的 strand 定向膠合，通常形成更厚的結構板或構件。",
    sources: [constructionNotion],
    keywords: ["OSB", "LSB", "strand", "木質材料"],
    ja: { topic: "木質材料", title: "OSBとLSB", prompt: "原料ストランドの形状と配向から区別する。", minimumAnswer: "OSBは比較的薄いストランドを方向づけて層状に圧着した板。LSBはより長く厚いストランドを配向接着し、厚い構造用材とする。" },
  },
  {
    id: "construction-fire-layers",
    subject: "construction",
    topic: "木造防火",
    title: "燃えしろ層 vs 燃え止まり層",
    taskType: "comparison",
    priority: "core",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "兩種木造耐火設計層各自如何保護核心承重部分？",
    minimumAnswer: "燃えしろ層預留可炭化的外層，火災後仍以剩餘有效截面承重；燃え止まり層在外層後設難燃／不燃層，延緩或阻止火焰繼續進入核心。",
    sources: [constructionNotion],
    keywords: ["燃えしろ", "燃え止まり", "炭化", "木造耐火"],
    ja: { topic: "木造防火", title: "燃えしろ層と燃え止まり層", prompt: "二つの層は荷重支持部をどう守るか。", minimumAnswer: "燃えしろ層は炭化を見込む外層を確保し、残存断面で支持する。燃え止まり層は難燃・不燃層で火炎の進展を遅らせ、主要部を守る。" },
  },
  {
    id: "construction-clearances",
    subject: "construction",
    topic: "接合細部",
    title: "edge clearance vs face clearance",
    taskType: "comparison",
    priority: "support",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "edge clearance 與 face clearance 分別是哪個方向的淨距？",
    minimumAnswer: "edge clearance 是緊固件或構件到板材邊緣的平面內淨距；face clearance 是構件表面／面材之間沿厚度或面外方向保留的淨空。",
    sources: [constructionNotion],
    keywords: ["edge clearance", "face clearance", "縁端距離", "クリアランス"],
    ja: { topic: "接合詳細", title: "エッジクリアランスとフェイスクリアランス", prompt: "二つのクリアランスの方向を区別する。", minimumAnswer: "edge clearanceは金物等から材縁までの面内の空き、face clearanceは材面間・厚さ方向に確保する面外の空き。" },
  },
  {
    id: "construction-truss-types",
    subject: "construction",
    topic: "桁架",
    title: "king-post 與 queen-post truss",
    taskType: "comparison",
    priority: "support",
    years: [2013, 2014, 2015, 2024, 2025],
    prompt: "真束小屋組與對束小屋組最容易由哪個構件數量辨認？適用跨度如何？",
    minimumAnswer: "king-post／真束桁架中央有一根豎直杆；queen-post／對束桁架中央有兩根豎直杆，通常能處理較大的跨度。",
    sources: [constructionNotion],
    keywords: ["king post", "queen post", "真束", "対束", "トラス"],
    ja: { topic: "トラス", title: "キングポストとクイーンポスト", prompt: "鉛直材の本数と適用スパンから区別する。", minimumAnswer: "キングポスト（真束）は中央鉛直材1本、クイーンポスト（対束）は2本で、一般に後者がより大きなスパンに対応する。" },
  },
  {
    id: "history-joan",
    subject: "history",
    topic: "日本建築",
    title: "如庵",
    taskType: "concept",
    priority: "core",
    years: [2013],
    prompt: "如庵與哪位茶人、哪個時代相連？最小辨識線索是什麼？",
    minimumAnswer: "織田有楽（有楽斎）所作，17 世紀初的茶室；二畳半台目、斜置炉與有楽窗是重要辨識線索。",
    sources: [historyNotion],
    keywords: ["如庵", "織田有楽", "茶室", "有楽窓"],
    ja: { topic: "日本建築", title: "如庵", prompt: "茶人・時代・最小識別要素を答える。", minimumAnswer: "織田有楽（有楽斎）による17世紀初頭の茶室。二畳半台目、斜めに切った炉、有楽窓が識別点。" },
  },
  {
    id: "history-laurentian-library",
    subject: "history",
    topic: "文藝復興",
    title: "勞倫齊阿納圖書館",
    taskType: "image",
    priority: "core",
    years: [2013],
    prompt: "勞倫齊阿納圖書館的建築師、時代與前室最具辨識度的空間操作是什麼？",
    minimumAnswer: "Michelangelo，16 世紀；前室以巨大的中央階梯侵入狹長空間，牆面柱、窗等古典要素被反常壓縮和錯置，呈現 Mannerism。",
    sources: [historyNotion],
    keywords: ["ラウレンツィアーナ図書館", "ミケランジェロ", "マニエリスム", "階段"],
    ja: { topic: "ルネサンス", title: "ラウレンツィアーナ図書館", prompt: "設計者・時代・玄関前室の特徴を答える。", minimumAnswer: "ミケランジェロ、16世紀。巨大な中央階段が前室へ迫り出し、古典要素を圧縮・転倒させたマニエリスム的空間。" },
  },
  {
    id: "history-oxford-natural-history",
    subject: "history",
    topic: "19 世紀英國",
    title: "牛津大學自然史博物館",
    taskType: "image",
    priority: "support",
    years: [2013],
    prompt: "這座博物館與哪位理論家、哪個運動背景相連？材料表現有何特徵？",
    minimumAnswer: "與 John Ruskin 的思想及 Gothic Revival 相連；外部採哥德式石作，內部以鐵與玻璃覆蓋中央庭院，將工業材料與中世形式結合。",
    sources: [historyNotion],
    keywords: ["オックスフォード自然史博物館", "ラスキン", "ゴシック・リヴァイヴァル", "鉄とガラス"],
    ja: { topic: "19世紀イギリス", title: "オックスフォード大学自然史博物館", prompt: "思想家・運動背景・材料表現を答える。", minimumAnswer: "ジョン・ラスキンの思想とゴシック・リヴァイヴァルに関連し、石造ゴシック外観と鉄・ガラスの中庭屋根を組み合わせる。" },
  },
  {
    id: "history-pantheon-paris",
    subject: "history",
    topic: "新古典主義",
    title: "巴黎先賢祠（Panthéon）",
    taskType: "concept",
    priority: "core",
    years: [2013],
    prompt: "巴黎先賢祠的建築師、時代與三種被融合的建築理想是什麼？",
    minimumAnswer: "Jacques-Germain Soufflot，18 世紀；試圖融合希臘的莊嚴、羅馬的宏偉與哥德建築的輕快結構。",
    sources: [historyNotion],
    keywords: ["パンテオン", "スフロ", "新古典主義", "ゴシック"],
    ja: { topic: "新古典主義", title: "パリのパンテオン", prompt: "設計者・時代・統合しようとした三つの建築的理想を答える。", minimumAnswer: "スフロ、18世紀。ギリシアの壮麗さ、ローマの偉大さ、ゴシックの軽快さを統合しようとした。" },
  },
  {
    id: "history-sant-ivo",
    subject: "history",
    topic: "巴洛克",
    title: "Sant'Ivo alla Sapienza",
    taskType: "image",
    priority: "core",
    years: [2013],
    prompt: "Sant'Ivo 的建築師、時代與平面／穹頂的核心辨識特徵是什麼？",
    minimumAnswer: "Francesco Borromini，17 世紀巴洛克；凹凸交替的星形／六瓣幾何平面向上延伸為動態穹頂與螺旋燈塔。",
    sources: [historyNotion],
    keywords: ["サンティーヴォ", "ボッロミーニ", "バロック", "星型平面"],
    ja: { topic: "バロック", title: "サンティーヴォ・アッラ・サピエンツァ", prompt: "設計者・時代・平面／ドームの識別点を答える。", minimumAnswer: "ボッロミーニ、17世紀バロック。凹凸が交替する星形・六葉形平面が動的なドームと螺旋状ランタンへ続く。" },
  },
  {
    id: "history-saint-jean-montmartre",
    subject: "history",
    topic: "近代法國",
    title: "Saint-Jean-de-Montmartre",
    taskType: "image",
    priority: "support",
    years: [2013],
    prompt: "這座教堂的建築師、時代與構造史意義是什麼？",
    minimumAnswer: "Anatole de Baudot，19 世紀末至 20 世紀初；以 Anatole de Baudot 的系統早期運用鋼筋混凝土，被視為法國最早的 RC 教堂之一。",
    sources: [historyNotion],
    keywords: ["サン＝ジャン・ド・モンマルトル", "アナトール・ド・ボド", "鉄筋コンクリート", "教会"],
    ja: { topic: "近代フランス", title: "サン＝ジャン・ド・モンマルトル教会", prompt: "設計者・時代・構造史上の意義を答える。", minimumAnswer: "アナトール・ド・ボド、19世紀末〜20世紀初頭。初期鉄筋コンクリートを用いたフランス最初期の教会の一つ。" },
  },
  {
    id: "history-liverpool-cathedral",
    subject: "history",
    topic: "近代英國",
    title: "利物浦大教堂",
    taskType: "image",
    priority: "support",
    years: [2013],
    prompt: "利物浦大教堂的建築師、時代與空間風格線索是什麼？",
    minimumAnswer: "Giles Gilbert Scott，20 世紀；以巨大的哥德復興式拱券、塔樓與縱向大空間形成紀念性。",
    sources: [historyNotion],
    keywords: ["リヴァプール大聖堂", "G.G.スコット", "ゴシック・リヴァイヴァル", "大空間"],
    ja: { topic: "近代イギリス", title: "リヴァプール大聖堂", prompt: "設計者・時代・空間様式の手掛かりを答える。", minimumAnswer: "G.G.スコット、20世紀。巨大なゴシック・リヴァイヴァルのアーチ、塔、長大な内部空間が特徴。" },
  },
  {
    id: "history-santa-maria-novella",
    subject: "history",
    topic: "文藝復興",
    title: "Santa Maria Novella 正面",
    taskType: "image",
    priority: "core",
    years: [2013],
    prompt: "正面改修者、時代，以及如何把既有哥德教堂整合成古典構圖？",
    minimumAnswer: "Leon Battista Alberti，15 世紀；以方形、圓形與比例網格統一既有哥德正面，並用兩側渦卷銜接高低屋頂。",
    sources: [historyNotion],
    keywords: ["サンタ・マリア・ノヴェッラ", "アルベルティ", "ルネサンス", "渦巻"],
    ja: { topic: "ルネサンス", title: "サンタ・マリア・ノヴェッラ正面", prompt: "改修者・時代・既存ゴシックを古典構図へ統合した方法を答える。", minimumAnswer: "アルベルティ、15世紀。正方形・円・比例グリッドで正面を統一し、両側の渦巻で高低差をつないだ。" },
  },
  {
    id: "history-hagia-sophia",
    subject: "history",
    topic: "拜占庭",
    title: "Hagia Sophia 與 pendentive",
    taskType: "concept",
    priority: "core",
    years: [2013],
    prompt: "pendentive 解決了什麼幾何／構造轉換？Hagia Sophia 是哪個世紀？",
    minimumAnswer: "pendentive 是方形平面四角向圓形穹頂過渡的三角曲面，把穹頂荷重導向四個支點；Hagia Sophia 建於 6 世紀。",
    sources: [historyNotion],
    keywords: ["ハギア・ソフィア", "ペンデンティブ", "ビザンティン", "ドーム"],
    ja: { topic: "ビザンティン", title: "ハギア・ソフィアとペンデンティブ", prompt: "ペンデンティブが解決する幾何・構造変換と建設世紀を答える。", minimumAnswer: "正方形平面の四隅から円形ドームへ移る三角曲面で、荷重を四支点へ導く。ハギア・ソフィアは6世紀。" },
  },
  {
    id: "history-sainte-chapelle",
    subject: "history",
    topic: "哥德",
    title: "Sainte-Chapelle 與 Rayonnant",
    taskType: "image",
    priority: "core",
    years: [2013],
    prompt: "Sainte-Chapelle 屬於哪種哥德風格？名稱來自哪種窗飾特徵？",
    minimumAnswer: "13 世紀 Rayonnant（輻射式）哥德；窗的 tracery 像陽光般由中心向外放射，牆體被大片彩色玻璃取代。",
    sources: [historyNotion],
    keywords: ["サント＝シャペル", "Rayonnant", "トレーサリー", "ゴシック"],
    ja: { topic: "ゴシック", title: "サント＝シャペルとレイヨナン式", prompt: "様式・世紀・名称の由来となる窓飾りを答える。", minimumAnswer: "13世紀のレイヨナン式ゴシック。トレーサリーが中心から光線状に放射し、壁面を大きなステンドグラスへ変える。" },
  },
  {
    id: "history-aachen-palatine",
    subject: "history",
    topic: "加洛林",
    title: "Aachen Palatine Chapel",
    taskType: "concept",
    priority: "core",
    years: [2013],
    prompt: "Aachen 宮廷禮拜堂與哪位統治者、哪個世紀相連？平面的核心形式是什麼？",
    minimumAnswer: "Charlemagne（查理曼），9 世紀初；中央八角形空間外圍環繞多邊形回廊，是 Carolingian 對 Ravenna 集中式教堂的再詮釋。",
    sources: [historyNotion],
    keywords: ["エクス・ラ・シャペル", "シャルルマーニュ", "カロリング", "八角形"],
    ja: { topic: "カロリング", title: "アーヘン宮廷礼拝堂", prompt: "統治者・世紀・中心平面形式を答える。", minimumAnswer: "シャルルマーニュ、9世紀初頭。中央八角形空間を多角形の周歩廊が囲む集中式礼拝堂。" },
  },
];

export const RECENT_REVIEW_ITEMS: ReviewItem[] = additions.map(({ ja, ...item }) => {
  void ja;
  return item;
});

export const RECENT_REVIEW_ITEM_JA: Record<string, LocalizedReviewItemCopy> = Object.fromEntries(
  additions.map((item) => [item.id, item.ja]),
);
