import type { LocalizedText } from "@/types/history-topic";

type EnglishLocalizedText = LocalizedText & { en?: string };

const l = (ja: string, zh: string, en?: string): EnglishLocalizedText => ({ ja, zh, ...(en ? { en } : {}) });

export interface StyleTransition {
  from: string;
  fromIds?: string[];
  to: string;
  relation: "evolution" | "influence" | "reaction" | "synthesis" | "exchange";
  cause: LocalizedText;
  inherited: LocalizedText[];
  changed: LocalizedText[];
}

export interface StyleComparisonGroup {
  id: string;
  title: LocalizedText;
  description: LocalizedText;
  cardIds: string[];
  axes: { label: LocalizedText; values: Record<string, LocalizedText> }[];
  confusion: LocalizedText[];
}

export const STYLE_TRANSITIONS: StyleTransition[] = [
  { from:"style-wayo", to:"style-shinden", relation:"evolution", cause:l("寺院で日本化した木造技術と平安貴族の儀礼・生活が住宅形式へ展開。","日本化木构技术与平安贵族礼仪生活结合并发展为住宅形式。","Japanese timber techniques developed in Buddhist temples were adapted to the rituals and domestic life of the Heian aristocracy."), inherited:[l("木造軸組と深い軒","木构架与深远屋檐","Post-and-beam timber framing and deep eaves")], changed:[l("複数殿舎と庭園を渡殿で結ぶ開放的構成","以渡殿连接多座殿舍与庭园的开放布局","An open residential composition linking multiple pavilions and gardens with covered corridors")] },
  { from:"style-shinden", to:"style-shoin", relation:"evolution", cause:l("武家の対面儀礼、常設の室内機能、畳敷きの普及。","武家会面礼仪、固定室内功能与榻榻米铺设普及。","Samurai reception rituals, permanent interior functions, and the widespread use of tatami required more fixed domestic rooms."), inherited:[l("主室を中心とする序列","以主室为核心的等级秩序","A hierarchy organized around the principal room")], changed:[l("可動的な分隔から、襖・障子・床・棚をもつ固定室内へ","由临时分隔转向具有隔扇、障子、壁龛与棚的固定室内","From movable divisions to fixed interiors with fusuma, shoji, tokonoma alcoves, and built-in shelves")] },
  { from:"style-shoin", to:"style-sukiya", relation:"evolution", cause:l("茶の湯の美意識と、格式化した書院造への簡素化・非対称化。","茶道审美，以及对程式化书院造的简化与非对称化。","The aesthetics of tea ceremony encouraged a simplification and asymmetrical reinterpretation of formal Shoin-zukuri."), inherited:[l("畳、建具、座位による室内秩序","榻榻米、门窗与坐姿形成的室内秩序","An interior order based on tatami, joinery, and seated use")], changed:[l("細い部材、自然素材、不整形・非対称の構成","细构件、自然材料及不规则非对称构成","Slender members, natural materials, and irregular asymmetrical composition")] },
  { from:"style-wayo", fromIds:["style-wayo","style-daibutsuyo","style-zenshuyo"], to:"style-setchuyo", relation:"synthesis", cause:l("鎌倉期に伝来した大仏様・禅宗様を在来の和様へ選択的に導入。","镰仓时期把传入的大佛样、禅宗样选择性地融入既有和样。","Kamakura-period Daibutsuyo and Zenshuyo techniques were selectively incorporated into the established Wayō tradition."), inherited:[l("和様の平面と穏やかな外観","和样平面与平稳外观","Wayō planning and its restrained exterior character")], changed:[l("貫、挿肘木、詰組、扇垂木などを部分採用","局部采用贯、插肘木、诘组和扇椽等","Selective use of penetrating tie beams, inserted bracket arms, dense bracket complexes, and fan-shaped rafters")] },
  { from:"style-renaissance", to:"style-mannerism", relation:"evolution", cause:l("確立した古典規範を意図的に操作し、緊張と知的効果を追求。","有意识操控已经确立的古典规范，追求紧张感与智性效果。","Established classical norms were deliberately manipulated to produce tension, ambiguity, and intellectual effect."), inherited:[l("オーダーと古典語彙","柱式与古典语汇","The classical orders and Renaissance vocabulary")], changed:[l("尺度・位置・支持関係をずらし、曖昧さをつくる","错置尺度、位置与支撑关系，制造暧昧性","Displaced scale, position, and support relationships that create deliberate ambiguity")] },
  { from:"style-mannerism", to:"style-baroque", relation:"evolution", cause:l("対抗宗教改革と王権の表象が、より直接的な空間演出を要求。","反宗教改革与王权表现要求更直接的空间戏剧性。","The Counter-Reformation and royal representation demanded more direct and persuasive spatial drama."), inherited:[l("古典語彙の自由な操作","对古典语汇的自由操作","The free manipulation of classical vocabulary")], changed:[l("曲面、軸線、光、都市空間を統合した動的構成","整合曲面、轴线、光与城市空间的动态构成","Dynamic compositions integrating curved surfaces, axes, light, and urban space")] },
  { from:"style-baroque", to:"style-rococo", relation:"evolution", cause:l("宮廷儀礼の壮大さから、邸宅の親密なサロン文化へ重点が移行。","重心由宏大宫廷礼仪转向宅邸中亲密的沙龙文化。","Emphasis shifted from the grandeur of court ceremony to the intimate salon culture of aristocratic houses."), inherited:[l("建築・絵画・彫刻の統合","建筑、绘画与雕塑的整合","The integration of architecture, painting, and sculpture")], changed:[l("小規模室内、淡色、鏡、ロカイユ、非対称装飾","小尺度室内、淡色、镜面、贝壳纹与非对称装饰","Small-scale interiors, pale colors, mirrors, rocaille, and asymmetrical ornament")] },
  { from:"style-baroque", to:"style-neoclassical", relation:"reaction", cause:l("啓蒙思想と考古学が、バロック／ロココへの批判と古典の再評価を促進。","启蒙思想与考古学推动对巴洛克／洛可可的批评和对古典的重新评价。","Enlightenment thought and archaeology fostered criticism of Baroque and Rococo excess and a reassessment of classical antiquity."), inherited:[l("公共建築の記念性","公共建筑的纪念性","The monumentality of public architecture")], changed:[l("明快な幾何学、独立列柱、装飾の抑制","清晰几何、独立柱列与装饰克制","Clear geometry, free-standing colonnades, and restrained ornament")] },
  { from:"style-neoclassical", to:"style-historicism", relation:"evolution", cause:l("19世紀の国家形成、用途の多様化、考古学・建築教育が過去様式を選択可能な設計言語へ変えた。","19世纪国家形成、功能多样化以及考古与建筑教育，使历史样式成为可选择的设计语言。","Nineteenth-century nation building, diversified building programs, archaeology, and architectural education turned past styles into selectable design languages."), inherited:[l("歴史を権威と公共性の表象に用いる","以历史表现权威与公共性","The use of history to represent authority and public purpose")], changed:[l("古典だけでなくゴシック、ルネサンスなどを用途別に選択・混成","不只古典，也按功能选择或混合哥特、文艺复兴等样式","Selection and hybridization of Gothic, Renaissance, and other styles according to building type, rather than classicism alone")] },
  { from:"style-historicism", to:"movement-art-nouveau", relation:"reaction", cause:l("歴史様式の反復への批判と、鉄・ガラス・工芸を近代生活へ統合する要求。","对重复历史样式的批评，以及把铁、玻璃与工艺整合进现代生活的要求。","Criticism of repeated historical styles coincided with a demand to integrate iron, glass, and craft into modern life."), inherited:[l("建築・室内・装飾を総合する考え","整合建筑、室内与装饰的观念","The idea of integrating architecture, interiors, and ornament")], changed:[l("過去様式の引用から植物曲線、新材料、個別的造形へ","由引用历史样式转向植物曲线、新材料与个性化造型","A shift from historical quotation to vegetal curves, new materials, and individual formal expression")] },
  { from:"movement-art-nouveau", to:"movement-vienna-secession", relation:"evolution", cause:l("ウィーンの芸術家組織が曲線的な新芸術を幾何学化し、材料と機能へ接近させた。","维也纳艺术家组织把曲线性新艺术几何化，并使其接近材料与功能。","Vienna's artists' association geometrized curvilinear Art Nouveau and brought it closer to material discipline and function."), inherited:[l("建築・美術・工芸の統合","建筑、美术与工艺的整合","The integration of architecture, fine art, and craft")], changed:[l("植物曲線から幾何学的装飾と明快な面構成へ","由植物曲线转向几何装饰与清晰平面构成","From vegetal curves to geometric ornament and clear planar composition")] },
  { from:"movement-vienna-secession", to:"style-art-deco", relation:"influence", cause:l("幾何学化した装飾、工芸、都市消費文化が1920年代の装飾芸術へ接続。","几何化装饰、工艺与都市消费文化连接到1920年代装饰艺术。","Geometrized ornament, craft, and metropolitan consumer culture fed into the decorative arts of the 1920s."), inherited:[l("総合デザインと幾何学的装飾","总体设计与几何装饰","Total design and geometric ornament")], changed:[l("高級材料、機械時代の図像、階段状・放射状モチーフ","奢华材料、机器时代图像及阶梯、放射纹样","Luxurious materials, machine-age imagery, and stepped or radiating motifs")] },
  { from:"movement-bauhaus", to:"style-international", relation:"influence", cause:l("教育、出版、展覧会、亡命した設計者を通じて近代建築言語が国際化。","通过教育、出版、展览及流亡设计师，现代建筑语言走向国际化。","Education, publishing, exhibitions, and emigrant designers internationalized the language of modern architecture."), inherited:[l("標準化、機能、構造骨組み、装飾抑制","标准化、功能、结构框架与装饰克制","Standardization, function, structural frames, and the reduction of ornament")], changed:[l("地域的前衛から企業・公共建築の国際的共通語へ","由地域先锋转为企业和公共建筑的国际共同语言","From a regional avant-garde to an international common language for corporate and public architecture")] },
  { from:"movement-de-stijl", to:"style-international", relation:"influence", cause:l("直交する面と非対称な均衡が近代建築の抽象的空間構成へ影響。","正交平面与非对称平衡影响现代建筑抽象空间构成。","Orthogonal planes and asymmetrical balance informed the abstract spatial composition of modern architecture."), inherited:[l("水平・垂直、独立した面、抽象性","水平垂直、独立平面与抽象性","Horizontal and vertical elements, independent planes, and abstraction")], changed:[l("原色の造形実験から一般化された白色・ガラスの建築語彙へ","由原色造型实验转向普遍化的白色与玻璃建筑语汇","From experiments with primary colors to a generalized architectural vocabulary of white surfaces and glass")] },
  { from:"movement-de-stijl", to:"movement-bauhaus", relation:"exchange", cause:l("ファン・ドゥースブルフのワイマールでの活動などを通じ、色彩・抽象構成・家具・建築教育が相互に刺激し合った。","通过范·杜斯堡在魏玛等地的活动，色彩、抽象构成、家具与建筑教育相互产生刺激。","Theo van Doesburg's activity in Weimar and related exchanges connected color, abstract composition, furniture, and architectural education."), inherited:[l("芸術・家具・建築を横断する総合的実験","跨越艺术、家具与建筑的综合实验","Integrated experiments across art, furniture, and architecture")], changed:[l("デ・ステイルの抽象原理とバウハウスの工房・生産教育が異なる形で展開","风格派抽象原理与包豪斯工坊生产教育以不同方式展开","De Stijl's abstract principles and the Bauhaus's workshop and production pedagogy developed in distinct ways")] },
  { from:"movement-constructivism", to:"style-high-tech", relation:"influence", cause:l("工業部材、動的構成、設備や構造の可視化が戦後の技術表現に再評価された。","工业构件、动态构成及结构设备可视化在战后技术表现中被重新评价。","Industrial components, dynamic composition, and the visibility of services and structure were reassessed in postwar technological expression."), inherited:[l("構造・生産・機能を造形化する姿勢","把结构、生产与功能转化为造型的态度","The impulse to turn structure, production, and function into form")], changed:[l("革命的計画案から実用的な大スパン・設備外部化へ","由革命性方案转向实用大跨度与设备外置","From revolutionary projects to practical long spans and externally expressed services")] },
  { from:"movement-modernism", to:"movement-metabolism", relation:"evolution", cause:l("戦後日本の急速な都市化に対し、固定的な建築を成長・交換可能なシステムへ拡張。","面对战后日本快速城市化，把固定建筑扩展为可成长、可替换的系统。","Rapid postwar urbanization in Japan expanded fixed architecture into systems capable of growth and replacement."), inherited:[l("工業化、標準化、都市と建築の統合","工业化、标准化及城市建筑整合","Industrialization, standardization, and the integration of city and architecture")], changed:[l("恒久的基盤と交換可能単位、メガストラクチャー","永久基础设施、可替换单元与巨型结构","Permanent infrastructure, replaceable units, and megastructure")] },
  { from:"movement-modernism", to:"movement-critical-regionalism", relation:"influence", cause:l("普遍的近代技術を保ちながら、場所・気候・材料・身体経験を回復する批判。","在保留现代普遍技术的同时，恢复场所、气候、材料与身体经验的批判。","A critique that retained universal modern technology while recovering place, climate, material, and bodily experience."), inherited:[l("近代的構法と抽象性","现代构法与抽象性","Modern construction methods and abstraction")], changed:[l("地域条件による批判的調整と触覚的な場所経験","依据地域条件进行批判性调整并强调触觉性场所经验","Critical adjustment to regional conditions and tactile experience of place")] },
  { from:"style-international", to:"movement-postmodernism", relation:"reaction", cause:l("画一化した国際様式と大規模都市更新への批判。","对趋同的国际风格和大规模都市更新的批评。","A critique of the homogenized International Style and large-scale urban renewal."), inherited:[l("近代的構造と都市プログラム","现代结构与都市功能","Modern structure and urban program")], changed:[l("歴史的引用、記号、文脈、多義性の回復","恢复历史引用、符号、语境与多义性","The return of historical quotation, signs, context, and multiple meanings")] },
];

const axisEn = (ja:string, zh:string, en:string, values:Record<string,[string,string,string]>) => ({ label:l(ja,zh,en), values:Object.fromEntries(Object.entries(values).map(([id,v])=>[id,l(v[0],v[1],v[2])])) });

export const STYLE_COMPARISON_GROUPS: StyleComparisonGroup[] = [
  { id:"japanese-buddhist", title:l("和様・大仏様・禅宗様・折衷様","和样・大佛样・禅宗样・折衷样","Wayō, Daibutsuyō, Zenshuyō, and Setchūyō"), description:l("中世寺院建築で最も混同しやすい構法と細部を比較。","比较中世寺院建筑中最容易混淆的构造与细部。","Comparison of the structural systems and details most frequently confused in medieval Japanese Buddhist architecture."), cardIds:["style-wayo","style-daibutsuyo","style-zenshuyo","style-setchuyo"], axes:[
    axisEn("成立","形成","Formation and context",{"style-wayo":["大陸系寺院建築の日本化","大陆寺院建筑的日本化","The Japanese adaptation of continental Buddhist temple architecture"],"style-daibutsuyo":["重源による東大寺復興と宋代技術","重源重建东大寺与宋代技术","Chogen's reconstruction of Todai-ji and Song-dynasty construction techniques"],"style-zenshuyo":["禅宗寺院制度と宋元建築の受容","禅宗寺院制度与宋元建筑传入","Zen monastic institutions and the reception of Song-Yuan architecture"],"style-setchuyo":["三様式の選択的併用","三种样式的选择性并用","Selective combination of the three styles"]}),
    axisEn("構造","结构","Structural system",{"style-wayo":["長押、柱上中心の疎組","长押、以柱顶为主的疏组","Nageshi tie beams and sparse, column-centered bracket sets"],"style-daibutsuyo":["貫、挿肘木、構造の露出","贯、插肘木与结构外露","Penetrating tie beams, inserted bracket arms, and exposed structure"],"style-zenshuyo":["貫、詰組、扇垂木、礎盤","贯、诘组、扇椽与础盘","Penetrating tie beams, dense brackets, fan-shaped rafters, and column bases"],"style-setchuyo":["和様を基調に新様式細部を採用","以和样为基础采用新样式细部","Wayō planning enriched with selected details from the newer styles"]}),
    axisEn("識別","识别","Identification",{"style-wayo":["穏やかな屋根、疎組、水平性","平缓屋顶、疏组与水平感","Gentle roofs, sparse brackets, and strong horizontality"],"style-daibutsuyo":["太い構材、挿肘木、貫","粗大构件、插肘木与贯","Heavy members, inserted bracket arms, and penetrating tie beams"],"style-zenshuyo":["花頭窓、詰組、扇垂木","花头窗、诘组与扇椽","Katōmado cusped windows, dense brackets, and fan-shaped rafters"],"style-setchuyo":["一棟に複数様式の細部","一栋建筑混合多种样式细部","Details from more than one style within a single building"]})
  ], confusion:[l("大仏様と禅宗様はともに貫を用いる。識別は挿肘木か、詰組・扇垂木かを見る。","大佛样与禅宗样都使用贯；应观察是插肘木，还是诘组、扇椽。","Both Daibutsuyō and Zenshuyō use penetrating tie beams (nuki). Distinguish them by inserted bracket arms in Daibutsuyō versus dense bracket complexes and fan-shaped rafters in Zenshuyō.") ] },
  { id:"shrine-archaic", title:l("神明造・大社造・住吉造","神明造・大社造・住吉造","Shinmei-zukuri, Taisha-zukuri, and Sumiyoshi-zukuri"), description:l("古式を伝える三形式を入口方向、平面、屋根で比較。","从入口方向、平面和屋顶比较三种古式神社形式。","Comparison of three archaic shrine forms by entrance orientation, plan, and roof."), cardIds:["style-shinmei","style-taisha","style-sumiyoshi"], axes:[
    axisEn("入口と屋根","入口与屋顶","Entrance and roof",{"style-shinmei":["切妻・平入","切妻・平入","Gabled roof with the entrance on the eave side (hirairi)"],"style-taisha":["切妻・妻入","切妻・妻入","Gabled roof with the entrance on the gable side (tsumairi)"],"style-sumiyoshi":["切妻・妻入","切妻・妻入","Gabled roof with the entrance on the gable side (tsumairi)"]}),
    axisEn("平面","平面","Plan",{"style-shinmei":["単純な一室、高床、棟持柱","单室、高床与栋持柱","A simple single room, raised floor, and ridge-supporting posts"],"style-taisha":["心御柱をもつ高床本殿","具有心御柱的高床本殿","A raised-floor honden with a central sacred pillar (shin no mihashira)"],"style-sumiyoshi":["桁行四間・梁間二間、前後二室","面阔四间、进深二间、前后两室","Four bays by two bays, divided into elongated front and rear rooms"]}),
    axisEn("代表","代表","Representative example",{"style-shinmei":["伊勢神宮正殿","伊势神宫正殿","Main Sanctuary of Ise Jingu"],"style-taisha":["出雲大社本殿","出云大社本殿","Main Sanctuary of Izumo Taisha"],"style-sumiyoshi":["住吉大社本殿","住吉大社本殿","Main Sanctuary of Sumiyoshi Taisha"]})
  ], confusion:[l("大社造と住吉造はいずれも妻入だが、心御柱と一室的構成か、細長い前後二室かで区別する。","大社造和住吉造都是妻入；区别在于心御柱和单室性，或狭长的前后两室。","Both Taisha-zukuri and Sumiyoshi-zukuri are tsumairi forms. Distinguish the former's central sacred pillar and single-room tendency from the latter's long plan divided into front and rear rooms.") ] },
  { id:"shrine-common", title:l("春日造・流造","春日造・流造","Kasuga-zukuri and Nagare-zukuri"), description:l("本殿正面の向きと前庇のつくり方を比較。","比较本殿正面方向与前庇的形成方式。","Comparison of honden entrance orientation and the formation of the front canopy."), cardIds:["style-kasuga","style-nagare"], axes:[
    axisEn("基本形式","基本形式","Basic form",{"style-kasuga":["切妻・妻入、正面に庇","切妻・妻入，正面加庇","Gabled, gable-entry form (tsumairi) with a front canopy"],"style-nagare":["切妻・平入、前流れを延長","切妻・平入，延长前坡","Gabled, eave-entry form (hirairi) with an extended front roof slope"]}),
    axisEn("外観","外观","Exterior character",{"style-kasuga":["妻面が正面、反りのある小社殿","山墙面为正面、屋顶起翘的小型社殿","A compact shrine with a gable façade and a gently curved roof"],"style-nagare":["長い前流れと非対称な屋根断面","长前坡与不对称屋顶剖面","A long front roof slope and an asymmetrical roof section"]})
  ], confusion:[l("どちらも正面庇をもつが、妻入か平入かを最初に確認する。","两者都有前庇，首先确认是妻入还是平入。","Both have a front canopy; first determine whether the entrance is on the gable side (tsumairi) or the eave side (hirairi).") ] },
  { id:"residential", title:l("寝殿造・書院造・数寄屋造","寝殿造・书院造・数寄屋造","Shinden-zukuri, Shoin-zukuri, and Sukiya-zukuri"), description:l("貴族住宅から武家儀礼、茶の湯空間への変化。","从贵族住宅到武家礼仪和茶道空间的变化。","The evolution from aristocratic residence through samurai ceremony to tea-oriented space."), cardIds:["style-shinden","style-shoin","style-sukiya"], axes:[
    axisEn("社会背景","社会背景","Social context",{"style-shinden":["平安貴族の儀礼と生活","平安贵族礼仪与生活","Heian aristocratic ceremony and domestic life"],"style-shoin":["武家の対面儀礼と室内秩序","武家会面礼仪与室内秩序","Samurai reception rituals and a fixed interior order"],"style-sukiya":["茶の湯と簡素・自然の美意識","茶道与简素自然审美","Tea ceremony and an aesthetic of simplicity and naturalness"]}),
    axisEn("空間","空间","Spatial organization",{"style-shinden":["殿舎・渡殿・庭園の開放的構成","殿舍、渡殿与庭园的开放布局","An open composition of pavilions, covered corridors, and gardens"],"style-shoin":["畳割、襖、床・棚・付書院","榻榻米模数、隔扇、壁龛、棚与付书院","Tatami modules, fusuma, a tokonoma, shelves, and a tsuke-shoin"],"style-sukiya":["小規模、非対称、庭との繊細な連続","小尺度、非对称及与庭园的细腻连续","Small scale, asymmetry, and a subtle continuity with the garden"]})
  ], confusion:[l("数寄屋造は書院造を単純に否定したのではなく、その室内要素を細く軽く再解釈した。","数寄屋造并非简单否定书院造，而是把其室内要素重新解释得更轻巧。","Sukiya-zukuri did not simply reject Shoin-zukuri; it reinterpreted its interior elements with lighter, more delicate proportions.") ] },
  { id:"western-classical", title:l("ルネサンス・マニエリスム・バロック・ロココ","文艺复兴・手法主义・巴洛克・洛可可","Renaissance, Mannerism, Baroque, and Rococo"), description:l("古典規範の確立、操作、劇化、室内化という変化を比較。","比较古典规范从确立、操控、戏剧化到室内化的变化。","Comparison of the establishment, manipulation, dramatization, and interiorization of classical norms."), cardIds:["style-renaissance","style-mannerism","style-baroque","style-rococo"], axes:[
    axisEn("古典規範","古典规范","Classical norms",{"style-renaissance":["比例と幾何学で再構成","以比例与几何重构","Reconstructed through proportion and geometry"],"style-mannerism":["規則を意図的にずらす","有意识错置规则","Rules deliberately displaced"],"style-baroque":["曲線・光・軸線で動的に展開","以曲线、光与轴线动态展开","Dynamically developed through curves, light, and axes"],"style-rococo":["室内表皮と装飾へ軽快に展開","轻快地转向室内表皮与装饰","Lightly developed into interior surfaces and ornament"]}),
    axisEn("主要空間","主要空间","Principal space",{"style-renaissance":["明快な集中式・軸線・対称","清晰的集中式、轴线与对称","Clear centralized plans, axes, and symmetry"],"style-mannerism":["曖昧で緊張した構成","暧昧而紧张的构成","Ambiguous and tense compositions"],"style-baroque":["連続する演出的空間と都市軸","连续戏剧性空间与城市轴线","Continuous theatrical spaces and urban axes"],"style-rococo":["親密なサロンと楕円形室内","亲密沙龙与椭圆室内","Intimate salons and oval interiors"]})
  ], confusion:[l("ロココはバロック後期と連続するが、主眼は巨大な都市・宗教空間より邸宅内部にある。","洛可可与晚期巴洛克连续，但重点由宏大城市宗教空间转向宅邸内部。","Rococo continues late Baroque, but it focuses on the interior of aristocratic houses rather than monumental urban and religious space.") ] },
  { id:"revival", title:l("新古典主義・歴史主義","新古典主义・历史主义","Neoclassicism and Historicism"), description:l("古典を規範とする態度と、複数の過去様式を選択する態度を比較。","比较以古典为规范与选择多种历史样式的两种态度。","Comparison of classicism as a normative ideal with the selective use of multiple past styles."), cardIds:["style-neoclassical","style-historicism"], axes:[
    axisEn("歴史の扱い","历史的使用","Use of history",{"style-neoclassical":["ギリシア・ローマを普遍的規範として再構成","把希腊罗马重构为普遍规范","Greek and Roman antiquity reconstructed as universal norms"],"style-historicism":["用途・国家・宗教に応じて複数様式を選択・混成","按功能、国家与宗教选择或混合多种样式","Multiple styles selected or combined for program, nation, and religion"]}),
    axisEn("背景","背景","Context",{"style-neoclassical":["啓蒙思想、考古学、革命、公共性","启蒙思想、考古学、革命与公共性","Enlightenment thought, archaeology, revolution, and public purpose"],"style-historicism":["国家形成、都市拡大、建築教育、用途分化","国家形成、城市扩张、建筑教育与功能分化","Nation building, urban expansion, architectural education, and specialized programs"]}),
    axisEn("識別","识别","Identification",{"style-neoclassical":["明快な幾何学、神殿正面、装飾抑制","清晰几何、神庙正面与装饰克制","Clear geometry, temple fronts, and restrained ornament"],"style-historicism":["ネオ・ゴシック、ネオ・ルネサンス、折衷立面","新哥特、新文艺复兴与折衷立面","Neo-Gothic and Neo-Renaissance elements or eclectic façades"]})
  ], confusion:[l("新古典主義も歴史を参照するが、歴史主義より対象を古典へ限定し、規範性を強く主張する。","新古典主义同样参照历史，但对象更集中于古典，并更强调规范性。","Neoclassicism also refers to history, but restricts its reference to antiquity and asserts a stronger normative ideal than Historicism.") ] },
  { id:"decorative-modern", title:l("アール・ヌーヴォー・分離派・アール・デコ","新艺术・维也纳分离派・装饰艺术","Art Nouveau, Vienna Secession, and Art Deco"), description:l("装飾を否定せずに近代化した三つの異なる方向。","三种不否定装饰而实现现代化的不同方向。","Three distinct paths to modernity that retained ornament."), cardIds:["movement-art-nouveau","movement-vienna-secession","style-art-deco"], axes:[
    axisEn("造形","造型","Form",{"movement-art-nouveau":["植物的曲線と連続する線","植物曲线与连续线条","Vegetal curves and continuous line"],"movement-vienna-secession":["幾何学化した装飾と平面","几何化装饰与平面","Geometrized ornament and planar composition"],"style-art-deco":["階段、放射、ジグザグ、流線形","阶梯、放射、锯齿与流线","Stepped, radiating, zigzag, and streamlined motifs"]}),
    axisEn("社会背景","社会背景","Social context",{"movement-art-nouveau":["新中産階級、工芸、新材料","新中产、工艺与新材料","New middle classes, craft, and new materials"],"movement-vienna-secession":["保守的芸術制度からの離脱","脱离保守艺术制度","Break with conservative art institutions"],"style-art-deco":["1920年代の消費文化、高層建築、交通","1920年代消费文化、高层建筑与交通","1920s consumer culture, high-rise construction, and transport"]}),
    axisEn("主要対象","主要对象","Principal commissions",{"movement-art-nouveau":["住宅、店舗、地下鉄、家具","住宅、商店、地铁与家具","Houses, shops, metro entrances, and furniture"],"movement-vienna-secession":["展示館、住宅、都市交通、工芸","展馆、住宅、城市交通与工艺","Exhibition buildings, houses, urban transport, and craft"],"style-art-deco":["高層、劇場、商業、交通機関","高层、剧院、商业与交通设施","High-rises, theatres, commercial buildings, and transport facilities"]})
  ], confusion:[l("三者は装飾を用いるが、自然曲線、幾何学化、機械時代の図像という順に識別する。","三者都使用装饰，可依次从自然曲线、几何化、机器时代图像加以识别。","All use ornament: distinguish vegetal curves, geometric abstraction, and machine-age imagery.") ] },
  { id:"modern-language", title:l("モダニズム・国際様式・ポストモダン","现代主义・国际风格・后现代","Modernism, the International Style, and Postmodernism"), description:l("運動、普及した造形言語、それへの批判を区別。","区分思想运动、普及后的造型语言及其批判。","Distinguishes the movement, its widely disseminated formal language, and its critique."), cardIds:["movement-modernism","style-international","movement-postmodernism"], axes:[
    axisEn("位置づけ","定位","Position",{"movement-modernism":["工業社会へ対応する広い思想・運動","回应工业社会的广泛思想与运动","A broad movement responding to industrial society"],"style-international":["展覧会・企業・戦後建設で普及した造形言語","经展览、企业与战后建设普及的造型语言","A formal language disseminated through exhibitions, corporations, and postwar building"],"movement-postmodernism":["近代主義の単一性への批判運動","对现代主义单一性的批判运动","A critique of modernism's singularity"]}),
    axisEn("表現","表达","Expression",{"movement-modernism":["機能、構造、標準化、自由な平面","功能、结构、标准化与自由平面","Function, structure, standardization, and free plan"],"style-international":["直方体、グリッド、ガラス外皮、装飾抑制","长方体、网格、玻璃表皮与装饰克制","Rectilinear volumes, grids, glass skins, and reduced ornament"],"movement-postmodernism":["歴史引用、記号、文脈、多義性","历史引用、符号、语境与多义性","Historical quotation, signs, context, and multiple meanings"]})
  ], confusion:[l("国際様式はモダニズム全体と同義ではなく、その一部を形式的特徴として整理・普及した概念。","国际风格不等于全部现代主义，而是把其中一部分整理为形式特征并加以传播的概念。","The International Style is not synonymous with all Modernism; it systematized and disseminated one part of it as formal characteristics.") ] },
  { id:"avant-garde", title:l("バウハウス・デ・ステイル・ロシア構成主義","包豪斯・风格派・俄国构成主义","Bauhaus, De Stijl, and Russian Constructivism"), description:l("同時代の前衛を教育、抽象造形、革命的生産の違いから比較。","从教育、抽象造型和革命性生产比较同时代先锋。","Comparison of contemporaneous avant-gardes through education, abstract form, and revolutionary production."), cardIds:["movement-bauhaus","movement-de-stijl","movement-constructivism"], axes:[
    axisEn("中心課題","核心问题","Central concern",{"movement-bauhaus":["芸術・工芸・建築教育と工業生産の統合","整合艺术、工艺、建筑教育与工业生产","Integration of art, craft, architectural education, and industrial production"],"movement-de-stijl":["普遍的な抽象造形秩序","普遍抽象造型秩序","A universal order of abstract form"],"movement-constructivism":["革命後社会の生産・集団生活・宣伝","革命后社会的生产、集体生活与宣传","Production, collective life, and propaganda in post-revolutionary society"]}),
    axisEn("造形","造型","Form",{"movement-bauhaus":["機能、標準化、工房実験","功能、标准化与工坊实验","Function, standardization, and workshop experimentation"],"movement-de-stijl":["水平垂直、三原色、非対称均衡","水平垂直、三原色与非对称平衡","Horizontal and vertical lines, primary colors, and asymmetrical balance"],"movement-constructivism":["斜線、片持ち、交差体、工業材料","斜线、悬挑、交叉体与工业材料","Diagonals, cantilevers, intersecting volumes, and industrial materials"]}),
    axisEn("性格","性质","Character",{"movement-bauhaus":["学校・教育制度でもある","同时也是学校与教育制度","A school and educational institution"],"movement-de-stijl":["雑誌を核とする芸術運動","以杂志为核心的艺术运动","An artistic movement organized around a journal"],"movement-constructivism":["革命と結びつく前衛運動","与革命结合的先锋运动","An avant-garde linked to revolution"]})
  ], confusion:[l("三者は相互交流したが同一運動ではない。バウハウスは学校、デ・ステイルは抽象造形運動、構成主義は革命後社会の生産志向が核。","三者相互交流但并非同一运动；包豪斯是学校，风格派以抽象造型为核心，构成主义面向革命后社会生产。","They exchanged ideas but were not one movement: Bauhaus was a school, De Stijl an abstract-form movement, and Constructivism oriented toward post-revolutionary production.") ] },
  { id:"after-modern", title:l("モダニズム・メタボリズム・批判的地域主義","现代主义・新陈代谢派・批判地域主义","Modernism, Metabolism, and Critical Regionalism"), description:l("近代主義を継承しながら、成長する都市と地域性へ応答した二方向。","比较继承现代主义后，回应城市成长与地域性的两种方向。","Two directions that extended Modernism while responding to growing cities and regional conditions."), cardIds:["movement-modernism","movement-metabolism","movement-critical-regionalism"], axes:[
    axisEn("近代主義への態度","对现代主义的态度","Attitude to Modernism",{"movement-modernism":["普遍的機能・構造・標準化を構築","建立普遍功能、结构与标准化","Establishes universal function, structure, and standardization"],"movement-metabolism":["工業化を成長・交換システムへ拡張","把工业化扩展为成长与替换系统","Extends industrialization into systems of growth and replacement"],"movement-critical-regionalism":["普遍技術を地域条件で批判的に調整","以地域条件批判性调整普遍技术","Critically adjusts universal technology to regional conditions"]}),
    axisEn("主要スケール","主要尺度","Principal scale",{"movement-modernism":["住宅から都市まで","从住宅至城市","From dwelling to city"],"movement-metabolism":["都市、メガストラクチャー、カプセル","城市、巨构与胶囊","City, megastructure, and capsule"],"movement-critical-regionalism":["敷地、地形、材料、身体経験","场地、地形、材料与身体经验","Site, topography, material, and bodily experience"]}),
    axisEn("時間観","时间观","View of time",{"movement-modernism":["合理的に計画された完成形","理性规划的完成形","A rationally planned finished form"],"movement-metabolism":["成長・交換・更新","成长、替换与更新","Growth, replacement, and renewal"],"movement-critical-regionalism":["気候・文化・場所の持続","气候、文化与场所延续","Continuity of climate, culture, and place"]})
  ], confusion:[l("批判的地域主義は伝統様式の外観模倣ではなく、近代技術を地域条件で批判的に濾過する立場。","批判地域主义不是模仿传统外观，而是以地域条件批判性过滤现代技术。","Critical Regionalism does not imitate traditional appearances; it critically filters modern technology through regional conditions.") ] }
];
