// ============================================================
// 时间轴数据：中央脊椎 + 上下分支
// ============================================================

export interface TimelineNode {
  id: string;
  year: string;          // 绝对年份（显示在中央轴线上）
  century: string;       // 世纪标签
  centuryZh: string;
  centuryEn: string;
  // 表层标签（上方：西洋建筑史）
  westernLabel: string;
  westernLabelZh: string;
  westernLabelEn: string;
  westernTags: string[];
  westernTagsZh: string[];
  westernTagsEn: string[];
  // 表层标签（下方：日本建筑史）
  eastAsianLabel: string;
  eastAsianLabelZh: string;
  eastAsianLabelEn: string;
  eastAsianTags: string[];
  eastAsianTagsZh: string[];
  eastAsianTagsEn: string[];
  // 地域标签（用于比较表格表头，替代硬编码的"西方"/"东亚"）
  westernRegionLabel: string;
  westernRegionLabelZh: string;
  westernRegionLabelEn: string;
  easternRegionLabel: string;
  easternRegionLabelZh: string;
  easternRegionLabelEn: string;
  // 里层数据
  macroTendency: string;
  macroTendencyZh: string;
  macroTendencyEn: string;
  westernDetail: string;
  westernDetailZh: string;
  westernDetailEn: string;
  eastAsianDetail: string;
  eastAsianDetailZh: string;
  eastAsianDetailEn: string;
  // 深度对比表格
  comparison: {
    dimension: string;
    dimensionZh: string;
    dimensionEn: string;
    western: string;
    westernZh: string;
    westernEn: string;
    eastAsian: string;
    eastAsianZh: string;
    eastAsianEn: string;
  }[];
  // 底部补充
  footnote: string;
  footnoteZh: string;
  footnoteEn: string;
  // 关联学习卡片
  relatedCardIds?: string[];
  // 补充定位（可选：仅用于说明传播关系或防止误解）
  supplementaryNote?: string;
  supplementaryNoteZh?: string;
  supplementaryNoteEn?: string;
  // 考试关键词（该时代最应记忆的建筑/技术/样式，3–5项）
  examKeywords: string[];
  examKeywordsZh: string[];
  examKeywordsEn: string[];
  /** Region-tagged content for the comparison modules.  Do not infer regions from display text. */
  trends?: TimelineRegionalText[];
  examKeywordEntries?: TimelineKeyword[];
  /** Stable building ids from the normalized architecture database. */
  buildingIds?: string[];
}

export type TimelineRegion = "western" | "japan";

export interface TimelineRegionalText {
  region: TimelineRegion;
  ja: string;
  zh: string;
  en?: string;
}

export interface TimelineKeyword extends TimelineRegionalText {
  type: "building" | "style" | "structure" | "spatial-form" | "religion" | "ideology";
}

export const TIMELINE_DATA: TimelineNode[] = [
  // ==================== 古代 ====================
  {
    id: "ancient-3000bce",
    year: "3000 BCE",
    century: "30th Century BCE",
    centuryZh: "公元前30世纪",
    centuryEn: "30th century BCE",
    westernLabel: "メソポタミア文明",
    westernLabelZh: "美索不达米亚文明",
    westernLabelEn: "Mesopotamian civilization",
    westernTags: ["ジッグラト", "日乾煉瓦"],
    westernTagsZh: ["塔庙", "日晒砖"],
    westernTagsEn: ["Ziggurat", "Sun-dried brick"],
    eastAsianLabel: "縄文集落",
    eastAsianLabelZh: "绳文聚落",
    eastAsianLabelEn: "Jōmon settlements",
    eastAsianTags: ["竪穴住居", "掘立柱建物"],
    eastAsianTagsZh: ["竖穴住居", "掘立柱建物"],
    eastAsianTagsEn: ["Pit dwellings", "Post-in-ground buildings"],
    westernRegionLabel: "メソポタミア",
    westernRegionLabelZh: "美索不达米亚",
    westernRegionLabelEn: "Mesopotamia",
    easternRegionLabel: "日本列島（縄文）",
    easternRegionLabelZh: "日本列岛（绳文）",
    easternRegionLabelEn: "Japanese archipelago (Jōmon)",
    macroTendency: "メソポタミア：灌漑農業を基盤として都市国家が成立し、宗教・政治の中心となる大規模建築が出現した。この大河流域文明は、広域の交易ネットワークと文字行政によって支えられていた。日本列島：縄文時代の定住集落が発達し、竪穴住居を中心とする共同生活が営まれた。両者の社会規模・技術基盤・建築需要の差は、地理的条件と農耕・文明化の時間差に起因する。",
    macroTendencyZh: "美索不达米亚：以灌溉农业为基础，城市国家成立，作为宗教与政治中心的大型建筑出现。此大河流域文明由广域贸易网络与文字行政支撑。日本列岛：绳文时代定居聚落发展，营建以竖穴住居为中心的共同生活。两者的社会规模、技术基础与建筑需求差异，缘于地理条件与农耕文明化的时间差。",
    macroTendencyEn: "Mesopotamia: city-states emerged from irrigated agriculture, together with large buildings that became religious and political centers. This river-valley civilization was sustained by wide trading networks and written administration. Japanese archipelago: settled Jōmon communities developed around pit dwellings. Differences in social scale, technical foundations, and architectural demand arose from geography and the differing timing of agriculture and urban civilization.",
    westernDetail: "シュメール文明がウル・ジッグラトを建設。日乾煉瓦による階段ピラミッドは神と人間を結ぶ「天の階段」としての意味を持つ。",
    westernDetailZh: "苏美尔文明建造乌尔大塔庙。日晒砖阶梯金字塔具有连接神与人的「天之阶梯」之意。",
    westernDetailEn: "Sumerian civilization built the Ziggurat of Ur. Its stepped pyramid of sun-dried brick signified a \"stairway to heaven\" linking gods and people.",
    eastAsianDetail: "日本列島では縄文時代の竪穴住居を中心とする定住集落が展開した。三内丸山遺跡（青森）では大型掘立柱建物や祭祀施設が確認されており、縄文社会の複雑性を示す。環濠集落は後の弥生時代に顕著となる。",
    eastAsianDetailZh: "日本列岛绳文时代发展出以竖穴住居为主的定居聚落。三内丸山遗址（青森）确认有大型掘立柱建筑和祭祀设施，显示绳文社会的复杂性。环壕聚落在之后的弥生时代更为显著。",
    eastAsianDetailEn: "In the Japanese archipelago, settled Jōmon communities developed around pit dwellings. At the Sannai-Maruyama site in Aomori, large post-in-ground buildings and ritual facilities demonstrate the complexity of Jōmon society. Moated settlements became more prominent in the later Yayoi period.",
    comparison: [
      { dimension: "政治と社会組織", dimensionZh: "政治与社会组织", dimensionEn: "Political and social organization", western: "灌漑農業を基盤とする都市国家（神殿を中心とする神権政治）。文字と行政制度が成立。", westernZh: "以灌溉农业为基础的城市国家（以神殿为中心的神权政治）。文字与行政制度已成立。", westernEn: "City-states based on irrigated agriculture, with temple-centered theocracy. Writing and administration emerged.", eastAsian: "狩猟・採集・初期農耕を基盤とする定住集落（共同生活を基本とする集落共同体）。", eastAsianZh: "以狩猎、采集和初期农耕为基础的定居聚落（以共同生活为基本的聚落共同体）。", eastAsianEn: "Settled communities based on hunting, gathering, and early agriculture, organized around collective life." },
      { dimension: "集落・都市形態", dimensionZh: "聚落／城市形态", dimensionEn: "Settlement and urban form", western: "城壁で囲まれた計画的都市。神殿・宮殿・穀物倉庫が都市の中核をなす。", westernZh: "以城墙围绕的计划性城市。神殿、宫殿与谷物仓库构成城市核心。", westernEn: "Planned walled cities whose cores comprised temples, palaces, and granaries.", eastAsian: "河川沿いの自然発生的集落。竪穴住居を中心とする散在的な配置。", eastAsianZh: "沿河川自然发生的聚落。以竖穴住居为中心的分散布局。", eastAsianEn: "Organic riverside settlements with dispersed arrangements centered on pit dwellings." },
      { dimension: "主要な建築需要", dimensionZh: "主要建筑需求", dimensionEn: "Principal architectural needs", western: "宗教儀礼、穀物貯蔵と再分配、行政、防衛。", westernZh: "宗教仪礼、谷物储藏与再分配、行政、防御。", westernEn: "Religious rites, grain storage and redistribution, administration, and defense.", eastAsian: "居住、共同祭祀、食料貯蔵。", eastAsianZh: "居住、共同祭祀、食物储藏。", eastAsianEn: "Housing, communal rites, and food storage." },
      { dimension: "建築類型", dimensionZh: "建筑类型", dimensionEn: "Building types", western: "ジッグラト（階段ピラミッド型神殿）、宮殿、城壁、穀物倉庫。", westernZh: "塔庙（阶梯金字塔型神殿）、宫殿、城墙、谷物仓库。", westernEn: "Ziggurats (stepped pyramid temples), palaces, city walls, and granaries.", eastAsian: "竪穴住居、掘立柱建物、貯蔵穴。", eastAsianZh: "竖穴住居、掘立柱建物、储藏穴。", eastAsianEn: "Pit dwellings, post-in-ground buildings, and storage pits." },
      { dimension: "構造と材料", dimensionZh: "构造与材料", dimensionEn: "Structure and materials", western: "日乾煉瓦（土レンガ）・焼成煉瓦・石灰岩。日乾煉瓦は入手容易だが耐久性に限界。", westernZh: "日晒砖（土砖）·烧制砖·石灰岩。日晒砖易获取但耐久性有限。", westernEn: "Sun-dried mud brick, fired brick, and limestone. Sun-dried brick was readily available but had limited durability.", eastAsian: "木材・土・草（植物性材料）。湿潤気候に適し、更新・建替えが容易。", eastAsianZh: "木材·土·草（植物性材料）。适应湿润气候，易于更新重建。", eastAsianEn: "Timber, earth, and grass or other plant materials, suited to a humid climate and easy to renew or rebuild." },
      { dimension: "建築の社会的役割", dimensionZh: "建筑的社会角色", dimensionEn: "Social role of architecture", western: "神権政治と都市国家の統治を支える宗教的・行政的中心。", westernZh: "支撑神权政治与城市国家统治的宗教与行政中心。", westernEn: "Religious and administrative centers supporting theocracy and the governance of city-states.", eastAsian: "共同体の共同生活・祭祀を支える居住と集会的機能。", eastAsianZh: "支撑共同体共同生活与祭祀的居住与集会功能。", eastAsianEn: "Residential and gathering functions supporting communal life and rites." },
    ],
    footnote: "メソポタミアの建築技術はエジプトやギリシアにも影響した。一方、日本列島では縄文時代の植物性材料による建築が、後の木造建築文化の深層を形成した。両者の建築差は地理的・技術的伝播条件の違いに起因し、単純な技術水準の比較はできない。",
    footnoteZh: "美索不达米亚建筑技术影响了埃及和希腊。另一方面，日本列岛绳文时代的植物性材料建筑形成了后来木造建筑文化的深层基础。两者的建筑差异源于地理与技术传播条件的不同，不能简单比较技术水平。",
    footnoteEn: "Mesopotamian building techniques influenced Egypt and Greece. In contrast, Jōmon architecture of plant-based materials formed a deep foundation for later Japanese timber culture. Their differences reflect geography and conditions of technical transmission, not a simple hierarchy of technical level.",
    supplementaryNote: "同時期の中国大陸では黄河・長江流域で農耕集落（仰韶文化・河姆渡文化等）が発達していた。メソポタミアは大河の灌漑農業と広域交易ネットワークによって早期に都市化したが、日本列島は島嶼環境の中で狩猟採集を基盤とする定住文化を長期にわたり発展させた。両者は異なる生態的・地理的条件のもとで異なる社会形成の道筋をたどった。",
    supplementaryNoteZh: "同一时期，中国大陆在黄河、长江流域已发展农耕聚落（仰韶文化、河姆渡文化等）。美索不达米亚因大河流域灌溉农业与广域贸易网络而早期城市化，日本列岛则在岛屿环境中，以狩猎采集为基盘长期发展定居文化。两者在不同生态与地理条件下，经历了不同的社会形成路径。",
    supplementaryNoteEn: "At the same time, farming settlements developed in the Yellow and Yangtze river basins of the Chinese mainland, including the Yangshao and Hemudu cultures. Mesopotamia urbanized early through river irrigation and broad trade networks, whereas the Japanese archipelago sustained settlement cultures based on hunting and gathering over a long period within an island environment. They followed different paths of social formation under different ecological and geographic conditions.",
    examKeywords: ["ジッグラト", "日乾煉瓦", "竪穴住居", "掘立柱建物"],
    examKeywordsZh: ["塔庙", "日晒砖", "竖穴住居", "掘立柱建物"],
    examKeywordsEn: ["Ziggurat", "Sun-dried brick", "Pit dwelling", "Post-in-ground building"],
    relatedCardIds: ["style-mesopotamian", "type-pit-dwelling", "type-moated-settlement", "type-hottate-bashira"],
  },
  {
    id: "ancient-2500bce",
    year: "2500 BCE",
    century: "25th Century BCE",
    centuryZh: "公元前25世纪",
    centuryEn: "25th century BCE",
    westernLabel: "エジプト・ピラミッド",
    westernLabelZh: "埃及金字塔",
    westernLabelEn: "Egyptian pyramids",
    westernTags: ["ギザ", "石灰岩", "ピラミッド"],
    westernTagsZh: ["吉萨", "石灰岩", "金字塔"],
    westernTagsEn: ["Giza", "Limestone", "Pyramid"],
    eastAsianLabel: "縄文時代（中〜後期）",
    eastAsianLabelZh: "绳文时代（中～后期）",
    eastAsianLabelEn: "Jōmon period (middle to late)",
    eastAsianTags: ["三内丸山遺跡", "大型掘立柱建物"],
    eastAsianTagsZh: ["三内丸山遗址", "大型掘立柱建物"],
    eastAsianTagsEn: ["Sannai-Maruyama site", "Large post-in-ground buildings"],
    westernRegionLabel: "エジプト",
    westernRegionLabelZh: "埃及",
    westernRegionLabelEn: "Egypt",
    easternRegionLabel: "日本列島（縄文）",
    easternRegionLabelZh: "日本列岛（绳文）",
    easternRegionLabelEn: "Japanese archipelago (Jōmon)",
    macroTendency: "エジプト：ナイル川の灌漑農業と強力な神権的王権のもと、王の死後世界と来世を象徴する巨大な石造建造物が出現。ピラミッドは中央集権的国家体制と宗教的世界観の産物。日本列島：縄文社会の成熟に伴い、大型掘立柱建物や祭祀施設を伴う大規模集落が形成された。両者の社会規模と建築表現の差は、統一王権の成立時期と利用可能な資源・技術伝播経路の違いに起因する。",
    macroTendencyZh: "埃及：在尼罗河灌溉农业与强有力神权王权下，象征法老死后世界与来世的巨大石造建筑出现。金字塔是中央集权国家体制与宗教世界观的产物。日本列岛：随绳文社会成熟，形成伴有大型掘立柱建物和祭祀设施的大规模聚落。两者的社会规模与建筑表现差异，缘于统一王权成立时期不同，以及可利用资源与技术传播路径的差异。",
    macroTendencyEn: "Egypt: under Nile irrigation and a powerful sacral kingship, immense stone monuments symbolizing the king's afterlife emerged. Pyramids were products of a centralized state and religious worldview. Japanese archipelago: as Jōmon society matured, large settlements with post-in-ground buildings and ritual facilities formed. Differences in social scale and architectural expression reflect the timing of unified kingship, available resources, and routes of technical transmission.",
    westernDetail: "クフ王ピラミッド（高さ約146m、底辺約230m）は古代世界の七不思議の一つ。高度な数学・天文学・工学技術を実証した。石材の運搬方法については諸説ある。",
    westernDetailZh: "胡夫金字塔（高约146m，底边约230m）为古代世界七大奇迹之一。实证了高度的数学、天文学和工程技术。石材搬运方法有诸种说法。",
    westernDetailEn: "The Pyramid of Khufu, about 146 m high with a base of about 230 m, is one of the Seven Wonders of the Ancient World. It demonstrates advanced mathematics, astronomy, and engineering; methods of transporting its stone remain debated.",
    eastAsianDetail: "三内丸山遺跡（青森、約3900〜2200 BCE）では、長さ約32mの大型掘立柱建物や多数の竪穴住居が確認されている。縄文社会が大規模な建造物を作りうる組織力を有していたことを示す。",
    eastAsianDetailZh: "三内丸山遗址（青森，约3900～2200 BCE）确认有长约32m的大型掘立柱建物和大量竖穴住居。显示绳文社会具备建造大规模建筑的组组织能力。",
    eastAsianDetailEn: "At Sannai-Maruyama in Aomori, dated roughly 3900–2200 BCE, a large post-in-ground building about 32 m long and many pit dwellings have been identified. They show that Jōmon society had the organizational capacity to construct large buildings.",
    comparison: [
      { dimension: "政治と社会組織", dimensionZh: "政治与社会组织", dimensionEn: "Political and social organization", western: "神権的王権による中央集権国家。王（ファラオ）が宗教的・政治的権力を独占。", westernZh: "神权王权的中央集权国家。法老独占宗教与政治权力。", westernEn: "A centralized state under sacral kingship, in which the king (pharaoh) monopolized religious and political power.", eastAsian: "集落単位の共同体。階層化の兆しはあるが、統一的な政治権力は未成立。", eastAsianZh: "以聚落为单位的共同体。虽有阶层化萌芽，但统一政治权力尚未成立。", eastAsianEn: "Settlement-based communities. Social stratification had begun, but unified political authority had not yet formed." },
      { dimension: "集落・都市形態", dimensionZh: "聚落／城市形态", dimensionEn: "Settlement and urban form", western: "ナイル川沿いの計画的な都市とピラミッド複合体。労働力と資源の全国的動員。", westernZh: "沿尼罗河的计划性城市与金字塔复合体。劳动力和资源的全国性动员。", westernEn: "Planned Nile-side cities and pyramid complexes, backed by nationwide mobilization of labor and resources.", eastAsian: "河川沿いの大規模集落。三内丸山遺跡は約1500年間継続した定住的拠点。", eastAsianZh: "沿河川的大规模聚落。三内丸山遗址为持续约1500年的定居性据点。", eastAsianEn: "Large riverside settlements; Sannai-Maruyama was a settled center that continued for about 1,500 years." },
      { dimension: "主要な建築需要", dimensionZh: "主要建筑需求", dimensionEn: "Principal architectural needs", western: "王墓・葬祭、来世信仰の永続的表現、国家的威信。", westernZh: "王墓与葬祭、来世信仰的永续表达、国家威信。", westernEn: "Royal tombs and funerary rites, enduring expressions of belief in the afterlife, and national prestige.", eastAsian: "居住、共同祭祀、食料加工・貯蔵、集会。", eastAsianZh: "居住、共同祭祀、食物加工与储藏、集会。", eastAsianEn: "Housing, communal rites, food processing and storage, and gathering." },
      { dimension: "建築類型", dimensionZh: "建筑类型", dimensionEn: "Building types", western: "ピラミッド（王墓）、葬祭殿、スフィンクス。", westernZh: "金字塔（王墓）、葬祭殿、狮身人面像。", westernEn: "Pyramids (royal tombs), mortuary temples, and sphinxes.", eastAsian: "大型掘立柱建物、竪穴住居、祭祀施設、貯蔵穴。", eastAsianZh: "大型掘立柱建物、竖穴住居、祭祀设施、储藏穴。", eastAsianEn: "Large post-in-ground buildings, pit dwellings, ritual facilities, and storage pits." },
      { dimension: "構造と材料", dimensionZh: "构造与材料", dimensionEn: "Structure and materials", western: "石灰岩・花崗岩の切石積み。高度な幾何学・天文学・石工技術。", westernZh: "石灰岩·花岗岩切石堆砌。高度几何学、天文学与石工技术。", westernEn: "Ashlar masonry of limestone and granite, requiring advanced geometry, astronomy, and stoneworking.", eastAsian: "木材（クリ材等）・土・草。木造掘立柱による大規模構築物。", eastAsianZh: "木材（栗木等）·土·草。以木造掘立柱建造大规模构筑物。", eastAsianEn: "Timber such as chestnut, earth, and grass; large timber structures using post-in-ground construction." },
      { dimension: "建築の社会的役割", dimensionZh: "建筑的社会角色", dimensionEn: "Social role of architecture", western: "王権の永続性と宗教的世界観を可視化し、全国的な労働編成を実現する国家事業。", westernZh: "将王权的永续性与宗教世界观可视化，实现全国性劳动组织的国家事业。", westernEn: "A state undertaking that made the permanence of royal power and a religious worldview visible while organizing labor nationwide.", eastAsian: "共同体の結束と祭祀を支える共同的建造物。集団の組織力を示す。", eastAsianZh: "支撑共同体团结与祭祀的共有建造物。显示集团的组织力。", eastAsianEn: "A shared construction supporting community cohesion and ritual, and demonstrating the group's organizational capacity." },
    ],
    footnote: "ピラミッドの設計には高度な幾何学と天文学の知識が必要で、石材運搬にナイル川の水運を利用した。日本列島の縄文集落は、森林資源を活用した木造建築文化を長期にわたり発展させ、それが後の日本建築の基層となった。",
    footnoteZh: "金字塔设计需要高度几何学和天文学知识，利用尼罗河水运搬运石材。日本列岛绳文集落长期发展活用森林资源的木造建筑文化，成为日后日本建筑的基底层。",
    footnoteEn: "Pyramid design required advanced knowledge of geometry and astronomy, and Nile transport was used for stone. Jōmon settlements in the Japanese archipelago developed a long-lived timber culture using forest resources, which became a foundation of later Japanese architecture.",
    supplementaryNote: "同時期の中国大陸では龍山文化が発達し、夯土による城壁を持つ集落（城子崖遺跡等）が出現していた。エジプトはナイル川の安定した氾濫と灌漑農業を基盤に早期に統一国家を形成したが、日本列島は島嶼環境の中で集落単位の社会を長期にわたり持続させた。両者の差は地理的条件と農耕・文明化の時間差に起因し、異なる社会形成過程として理解すべきである。",
    supplementaryNoteZh: "同一时期，中国大陆龙山文化发展，出现夯土城墙聚落（城子崖遗址等）。埃及以尼罗河稳定的泛滥与灌溉农业为基盘，早期形成统一国家，而日本列岛在岛屿环境中长期持续以聚落为单位的社会。两者差异缘于地理条件与农耕文明化的时间差，应理解为不同的社会形成过程。",
    supplementaryNoteEn: "At the same time, the Longshan culture developed on the Chinese mainland and settlements with rammed-earth walls, such as Chengziya, appeared. Egypt formed a unified state early through the Nile's dependable flood regime and irrigated agriculture, while the Japanese archipelago maintained settlement-based societies for a long time in an island environment. Their differences arise from geography and the differing timing of agriculture and civilization, and should be understood as distinct processes of social formation.",
    examKeywords: ["クフ王ピラミッド", "ギザの三大ピラミッド", "三内丸山遺跡", "大型掘立柱建物"],
    examKeywordsZh: ["胡夫金字塔", "吉萨三大金字塔", "三内丸山遗址", "大型掘立柱建物"],
    examKeywordsEn: ["Pyramid of Khufu", "Three Pyramids of Giza", "Sannai-Maruyama site", "Large post-in-ground building"],
    relatedCardIds: ["style-ancient-egyptian"],
  },
  {
    id: "ancient-5c-bce",
    year: "500 BCE",
    footnoteEn: "The Greek orders—Doric, Ionic, and Corinthian—became the basic system of Western architecture. Yayoi-period construction formed a technical foundation for later Japanese architecture. Their differing forms reflect differences in political scale, urbanization, and building needs rather than a hierarchy of technical achievement.",
    supplementaryNoteEn: "At the same time, the Chinese mainland was in the Spring and Autumn and Warring States periods, when iron tools, rammed-earth construction, and roof tiles were highly developed. Wet-rice cultivation reached Japan from the continent via the Korean Peninsula. The Greek world was highly urbanized through Mediterranean trade and colonial networks, whereas the Japanese archipelago was forming an agrarian society under different geographic conditions and timelines of technological transmission; the two should not be reduced to a simple advanced-versus-backward comparison.",
    examKeywordsEn: ["Parthenon", "Doric/Ionic/Corinthian orders", "Yoshinogari site", "Moated settlement", "Raised-floor granary"],
    centuryEn: "5th Century BCE",
    westernLabelEn: "Golden Age of Greek Architecture",
    westernTagsEn: ["Parthenon", "Doric order", "Marble"],
    eastAsianLabelEn: "Yayoi period",
    eastAsianTagsEn: ["Wet-rice cultivation", "Moated settlements"],
    westernRegionLabelEn: "Greek world",
    easternRegionLabelEn: "Japanese archipelago (Yayoi)",
    macroTendencyEn: "Greek world: a columnar system based on human proportions was established, and temple architecture became the religious and political center of the polis. Technology and ideas circulated among city-states through Mediterranean trade and colonial networks. Japanese archipelago: wet-rice cultivation introduced from the continent expanded agrarian society and enlarged settled communities. Moated and hilltop settlements formed across the islands, though their political scale and urbanization differed greatly from those of the Greek world.",
    westernDetailEn: "The Parthenon (447–432 BCE) represents the high point of the Doric order, with optical refinements such as entasis and adjusted column spacing. Ionic and Corinthian orders developed alongside it. Greek stone and marble were obtained through extensive Mediterranean trade networks.",
    eastAsianDetailEn: "The introduction of wet-rice cultivation during the Yayoi period enlarged settled communities. Defensive moated settlements formed in many areas, with post-in-ground buildings and raised-floor granaries arranged within them; the Yoshinogari site in Saga is a representative example. Wet-rice farming and metal tools reached the Japanese archipelago from the continent in stages via the Korean Peninsula.",
    century: "5th Century BCE",
    centuryZh: "公元前5世纪",
    westernLabel: "ギリシア建築の黄金期",
    westernLabelZh: "希腊建筑黄金期",
    westernTags: ["パルテノン", "ドリス式", "大理石"],
    westernTagsZh: ["帕特农", "多立克柱式", "大理石"],
    eastAsianLabel: "弥生時代",
    eastAsianLabelZh: "弥生时代",
    eastAsianTags: ["水田稲作", "環濠集落"],
    eastAsianTagsZh: ["水田稻作", "环壕聚落"],
    westernRegionLabel: "ギリシア世界",
    westernRegionLabelZh: "希腊世界",
    easternRegionLabel: "日本列島（弥生）",
    easternRegionLabelZh: "日本列岛（弥生）",
    macroTendency: "ギリシア世界：人体比例に基づくオーダー体系が確立され、神殿建築がポリスの宗教的・政治的中心となった。各ポリスは地中海全域の交易・植民ネットワークを通じて技術と思想を共有していた。日本列島：大陸から水田稲作技術が伝来して農耕社会が拡大し、定住集落の規模が増大。環濠集落や高地性集落が各地に形成されたが、両地域の政治規模と都市化の段階は大きく異なっていた。",
    macroTendencyZh: "希腊世界：基于人体比例的柱式体系确立，神殿建筑成为城邦的宗教与政治中心。各城邦通过地中海全域的贸易与殖民网络共享技术与思想。日本列岛：大陆水田稻作技术传入使农耕社会扩大，定居聚落规模增长。环壕聚落与高地性聚落在各地形成，但两地政治规模与城市化阶段差异显著。",
    westernDetail: "パルテノン神殿（447-432 BCE）はドリス式の最高到達点。エンタシスや柱間調整による視覚的補正が施された。イオニア式・コリント式も並行して発展した。ギリシアの石材・大理石は地中海の広域交易ネットワークによって調達された。",
    westernDetailZh: "帕特农神殿（447-432 BCE）为多立克柱式最高成就。施以卷杀和柱间距调整的视觉矫正。爱奥尼式与科林斯式也并行发展。希腊石材与大理石通过地中海广域贸易网络获取。",
    eastAsianDetail: "弥生時代の水田稲作技術の導入により定住集落が拡大。環濠集落（防御的機能を持つ）が各地に形成され、集落内部に掘立柱建物や高床倉庫が計画的に配置された。佐賀県吉野ヶ里遺跡はその代表例。日本列島では大陸から朝鮮半島を経由して水田稲作と金属器が段階的に伝播した。",
    eastAsianDetailZh: "弥生时代水田稻作技术传入使定居聚落扩大。环壕聚落（具防御功能）在各地形成，聚落内部掘立柱建物与高床仓库经规划配置。佐贺县吉野里遗址为其代表例。日本列岛经朝鲜半岛从大陆阶段性传入水田稻作与金属器。",
    comparison: [
      { dimension: "政治と社会組織", dimensionZh: "政治与社会组织", dimensionEn: "Political and social organization", western: "ポリス（都市国家）・市民共同体。地中海の交易・植民ネットワークで技術と思想を共有。", westernZh: "城邦（城市国家）·市民共同体。通过地中海贸易殖民网络共享技术与思想。", westernEn: "Polis (city-state) and civic community; technology and ideas were shared through Mediterranean trade and colonial networks.", eastAsian: "地域首長を中心とする農耕共同体。集団間の競合と統合が進む段階。", eastAsianZh: "以地域首长为中心的农耕共同体。集团间竞争与统合进展中的阶段。", eastAsianEn: "Agrarian communities centered on regional chiefs, in a stage of growing competition and integration among groups." },
      { dimension: "集落・都市形態", dimensionZh: "聚落／城市形态", dimensionEn: "Settlement and urban form", western: "アゴラ（広場）と神殿を核とするポリス。石造の公共建築が都市景観を構成。", westernZh: "以广场和神殿为核心的城邦。石造公共建筑构成城市景观。", westernEn: "Polis centered on the agora and temples, where stone public buildings shaped the urban landscape.", eastAsian: "環濠集落・高地性集落。堀と土塁で囲まれた防御的集落が地域拠点。", eastAsianZh: "环壕聚落·高地性聚落。壕沟与土垒围合的防御性聚落为地域据点。", eastAsianEn: "Moated and hilltop settlements; defensive communities enclosed by ditches and earthworks served as regional centers." },
      { dimension: "主要な建築需要", dimensionZh: "主要建筑需求", dimensionEn: "Principal architectural needs", western: "祭祀、市民集会、体育競技、政治討論。", westernZh: "祭祀、市民集会、体育竞技、政治讨论。", westernEn: "Rituals, civic assemblies, athletic contests, and political debate.", eastAsian: "防御、穀物貯蔵、居住、共同祭祀。", eastAsianZh: "防御、谷物储藏、居住、共同祭祀。", eastAsianEn: "Defense, grain storage, housing, and communal rites." },
      { dimension: "建築類型", dimensionZh: "建筑类型", dimensionEn: "Building types", western: "石造神殿、ストア（列柱廊）、劇場、競技場。", westernZh: "石造神殿、柱廊、剧场、竞技场。", westernEn: "Stone temples, stoas (colonnades), theaters, and athletic grounds.", eastAsian: "掘立柱建物、高床倉庫、竪穴住居、環濠集落。", eastAsianZh: "掘立柱建物、高床仓库、竖穴住居、环壕聚落。", eastAsianEn: "Post-in-ground buildings, raised-floor granaries, pit dwellings, and moated settlements." },
      { dimension: "構造と材料", dimensionZh: "构造与材料", dimensionEn: "Structure and materials", western: "大理石・石灰岩の柱梁構造。オーダーによる比例体系。", westernZh: "大理石·石灰岩柱梁构造。以柱式体系规整比例。", westernEn: "Marble and limestone post-and-lintel construction, proportioned through the architectural orders.", eastAsian: "木材・土・草（植物性材料）。木造軸組の原型。", eastAsianZh: "木材·土·草（植物性材料）。木造框架的原型。", eastAsianEn: "Timber, earth, and grass (plant-based materials); an early prototype of timber framing." },
      { dimension: "建築の社会的役割", dimensionZh: "建筑的社会角色", dimensionEn: "Social role of architecture", western: "ポリスの宗教的・政治的中心としての公共建築。", westernZh: "作为城邦宗教与政治中心的公共建筑。", westernEn: "Public architecture as the religious and political center of the polis.", eastAsian: "共同体の統合と防衛、首長権力の表現。", eastAsianZh: "共同体的统合与防御、首长权力的表现。", eastAsianEn: "Integration and defense of the community, and an expression of chiefly authority." },
    ],
    footnote: "ギリシアのオーダー（ドリス・イオニア・コリント）は西洋建築の基本体系となった。弥生時代の建築は後の日本建築の技術的基盤を形成。両者の建築形態の差は「技術の高低」ではなく、政治規模・都市化段階・建築需要の違いによる。",
    footnoteZh: "希腊柱式（多立克·爱奥尼·科林斯）成为西方建筑的基本体系。弥生时代建筑形成了日后日本建筑的技术基础。两者的建筑形态差异并非「技术高低」，而是源于政治规模、城市化阶段与建筑需求的不同。",
    supplementaryNote: "同時期の中国大陸では春秋・戦国時代にあたり、鉄器・夯土技術や瓦が高度に発達していた。水田稲作技術は大陸から朝鮮半島を経由して日本列島に伝来した。ギリシア世界は地中海全域の交易・植民ネットワークを通じて高度に都市化していたが、日本列島は異なる地理的条件と技術伝播の時間差の中で農耕社会を形成していた段階であり、単純な先進・後進の比較はできない。",
    supplementaryNoteZh: "同一时期，中国大陆处于春秋战国时代，铁器、夯土技术和瓦已高度发达。水田稻作技术从大陆经朝鲜半岛传入日本列岛。希腊世界通过地中海全域的贸易殖民网络已高度城市化，而日本列岛在不同的地理条件与技术传播时间差中，正处于农耕社会形成阶段，不能简单以先进或落后进行比较。",
    examKeywords: ["パルテノン神殿", "ドリス式/イオニア式/コリント式", "吉野ヶ里遺跡", "環濠集落", "高床倉庫"],
    examKeywordsZh: ["帕特农神殿", "多立克式/爱奥尼式/科林斯式", "吉野里遗址", "环壕聚落", "高床仓库"],
    relatedCardIds: ["style-greek", "style-ancient-persian"],
  },
  {
    id: "ancient-1c-ce",
    year: "100 CE",
    centuryEn: "1st–2nd Century CE", westernLabelEn: "Peak of Roman architecture", westernTagsEn: ["Pantheon", "Concrete", "Dome"], eastAsianLabelEn: "Yayoi to Kofun period", eastAsianTagsEn: ["Yoshinogari site", "Keyhole tombs"], westernRegionLabelEn: "Roman Empire", easternRegionLabelEn: "Japanese archipelago (Yayoi to Kofun)",
    macroTendencyEn: "Roman Empire: structural systems using concrete, arches, vaults, and domes developed, supporting large buildings for imperial governance and urban public life. Japanese archipelago: as agrarian society expanded and regional chiefs rose, moated settlements, chiefly residences, and keyhole tombs developed as works of community integration and political expression.",
    westernDetailEn: "The Roman Empire covered the Mediterranean, with urban networks, law, administration, and commerce across its provinces. The Pantheon (118–128, under Hadrian) achieved a dome about 43.3 m in diameter, a high point of Roman concrete using pozzolana. The Colosseum (72–80), seating about 50,000, served public entertainment and imperial rule.",
    eastAsianDetailEn: "With settled wet-rice cultivation, agrarian society expanded across Japan and regional chiefs grew stronger. Yoshinogari in Saga was one of the largest Yayoi moated settlements, with post-in-ground buildings, raised-floor granaries, and ritual facilities laid out in a planned arrangement. From the mid-third century, keyhole tombs appeared, accompanied by large earthworks and wider political alliances.",
    footnoteEn: "Roman concrete was a hydraulic cement mixed with volcanic ash (pozzolana), central to Roman construction. Japan's post-in-ground timber construction adapted to a humid climate and abundant forest resources; its premise of renewal and rebuilding differs fundamentally from stone construction.",
    supplementaryNoteEn: "On the Chinese mainland, the Han Empire had developed large palaces and tombs using timber, tiles, and brick. Japan was still forming a unified state under different conditions of political scale, urbanization, and technical transmission; this difference should be understood as distinct social formation, not simply as advancement or backwardness.",
    examKeywordsEn: ["Pantheon", "Roman concrete", "Colosseum", "Keyhole tomb", "Yoshinogari site"],
    century: "1st–2nd Century CE",
    centuryZh: "公元1-2世纪",
    westernLabel: "ローマ建築の頂点",
    westernLabelZh: "罗马建筑的顶点",
    westernTags: ["パンテオン", "コンクリート", "ドーム"],
    westernTagsZh: ["万神殿", "混凝土", "穹顶"],
    eastAsianLabel: "弥生〜古墳時代",
    eastAsianLabelZh: "弥生～古坟时代",
    eastAsianTags: ["吉野ヶ里遺跡", "前方後円墳"],
    eastAsianTagsZh: ["吉野里遗址", "前方后圆坟"],
    westernRegionLabel: "ローマ帝国",
    westernRegionLabelZh: "罗马帝国",
    easternRegionLabel: "日本列島（弥生〜古墳）",
    easternRegionLabelZh: "日本列岛（弥生～古坟）",
    macroTendency: "ローマ帝国：コンクリート、アーチ、ヴォールト、ドームを用いた構造体系が発達し、帝国統治と都市公共生活を支える大規模建築が整備された。日本列島：農耕社会の拡大と地域首長の台頭に伴い、環濠集落、首長居館、前方後円墳など、共同体統合と権力表現に関わる建築・土木が発達した。",
    macroTendencyZh: "罗马帝国：混凝土、拱券、穹顶等结构体系发达，支撑帝国统治与城市公共生活的大规模建筑得以整备。日本列岛：伴随农耕社会扩大与地域首长兴起，环壕聚落、首长居馆和前方后圆坟等涉及共同体统合与权力表现的建筑与土木工程发达。",
    westernDetail: "ローマ帝国は地中海全域を覆う広域帝国であり、属州を含む都市ネットワークと法・行政・商業の制度が整備されていた。パンテオン（118-128年、ハドリアヌス帝期）は直径約43.3mのドームを実現し、ローマン・コンクリート（ポゾラーナ使用）の技術的到達点。コロッセウム（72-80年）は約5万人を収容し、公共娯楽と帝国統治の装置として機能した。",
    westernDetailZh: "罗马帝国是覆盖地中海全域的广域帝国，属州在内的城市网络与法律、行政、商业制度已完备。万神殿（118-128年，哈德良帝期）实现直径约43.3m穹顶，为罗马混凝土（使用火山灰）最高技术成就。斗兽场（72-80年）容纳约5万人，作为公共娱乐与帝国统治的装置发挥功能。",
    eastAsianDetail: "日本列島では水田稲作の定着により農耕社会が拡大し、各地で地域首長の勢力が強まっていた。吉野ヶ里遺跡（佐賀）は弥生時代最大級の環濠集落で、掘立柱建物・高床倉庫や祭祀施設が計画的に配置された。3世紀中頃から前方後円墳が出現し、大規模な土木工事と広域の政治連合が進展した。",
    eastAsianDetailZh: "日本列岛因水田稻作定居，农耕社会扩大，各地地域首长势力增强。吉野里遗址（佐贺）为弥生时代最大级环壕聚落，掘立柱建物、高床仓库和祭祀设施经规划配置。3世纪中期起前方后圆坟出现，大规模土木工程与广域政治联合进展。",
    comparison: [
      { dimension: "政治と社会組織", dimensionZh: "政治与社会组织", dimensionEn: "Political and social organization", western: "広域帝国と都市行政が成立し、法・商業・公共サービスを支える制度が発達した。", westernZh: "广域帝国与城市行政成立，法律、商业和公共服务制度发达。", westernEn: "A wide-ranging empire and urban administration, with institutions supporting law, commerce, and public services.", eastAsian: "地域首長の勢力が拡大し、複数の集団が統合されながら初期国家形成へ向かった。", eastAsianZh: "地域首长势力扩大，多个集团整合中走向初期国家形成。", eastAsianEn: "Regional chiefs gained power as multiple groups integrated toward early state formation." },
      { dimension: "集落・都市形態", dimensionZh: "聚落／城市形态", dimensionEn: "Settlement and urban form", western: "道路、上下水道、フォルム（広場）などを備えた都市ネットワーク。", westernZh: "具有道路、上下水道和广场等的城市网络。", westernEn: "Urban networks with roads, water and drainage systems, and forums.", eastAsian: "環濠集落、農耕集落、首長居館を中心とする地域的な拠点。", eastAsianZh: "以环壕聚落、农耕聚落和首长居馆为中心的地域性据点。", eastAsianEn: "Regional centers based on moated settlements, farming villages, and chiefly residences." },
      { dimension: "主要な建築需要", dimensionZh: "主要建筑需求", dimensionEn: "Principal architectural needs", western: "行政、裁判、交易、娯楽、浴場、宗教儀礼。", westernZh: "行政、裁判、交易、娱乐、浴场、宗教仪礼。", westernEn: "Administration, courts, trade, entertainment, baths, and religious rites.", eastAsian: "防御、穀物貯蔵、共同生活、祭祀、首長権力の表現。", eastAsianZh: "防御、谷物储藏、共同生活、祭祀、首长权力的表现。", eastAsianEn: "Defense, grain storage, communal life, ritual, and expression of chiefly authority." },
      { dimension: "建築類型", dimensionZh: "建筑类型", dimensionEn: "Building types", western: "神殿、バシリカ、公共浴場、円形闘技場、劇場。", westernZh: "神殿、巴西利卡、公共浴场、圆形斗兽场、剧场。", westernEn: "Temples, basilicas, public baths, amphitheaters, and theaters.", eastAsian: "環濠集落、掘立柱建物、高床倉庫、首長居館、前方後円墳。", eastAsianZh: "环壕聚落、掘立柱建物、高床仓库、首长居馆、前方后圆坟。", eastAsianEn: "Moated settlements, post-in-ground buildings, raised-floor granaries, chiefly residences, and keyhole tombs." },
      { dimension: "構造と材料", dimensionZh: "构造与材料", dimensionEn: "Structure and materials", western: "ローマン・コンクリート、アーチ、ヴォールト、ドーム、石・煉瓦。", westernZh: "罗马混凝土、拱券、穹顶、石·砖。", westernEn: "Roman concrete, arches, vaults, domes, stone, and brick.", eastAsian: "木造掘立柱構造、草葺・板葺屋根、土壁。", eastAsianZh: "木造掘立柱构造、草葺·板葺屋顶、土墙。", eastAsianEn: "Timber post-in-ground construction, thatched or board roofs, and earthen walls." },
      { dimension: "建築の社会的役割", dimensionZh: "建筑的社会角色", dimensionEn: "Social role of architecture", western: "都市公共生活と帝国統治を支える装置。", westernZh: "支撑都市公共生活与帝国统治的装置。", westernEn: "An instrument supporting urban public life and imperial governance.", eastAsian: "共同体統合と首長権力を可視化する装置。", eastAsianZh: "使共同体统合与首长权力可视化的装置。", eastAsianEn: "An instrument making community integration and chiefly authority visible." },
    ],
    footnote: "ローマン・コンクリートは火山灰（ポゾラーナ）を混ぜた水硬性セメントで、ローマ建築技術の核心。日本列島の木造掘立柱は、湿潤な気候と入手容易な森林資源に適応した構法であり、更新・建替えを前提とする点で石造建築とは根本的に建物観が異なる。",
    footnoteZh: "罗马混凝土是混入火山灰的水硬性水泥，为罗马建筑技术核心。日本列岛的木造掘立柱是适应湿润气候与丰富森林资源的构法，以更新与重建为前提，在建筑观上与石造建筑根本不同。",
    supplementaryNote: "同時期の中国大陸では漢帝国が成立し、木造・瓦・煉瓦による大規模宮殿建築や墳墓が発達していた。一方、日本列島では統一国家形成の途中にあり、地中海世界とは政治規模・都市化・技術伝播の条件が異なっていた。したがって、この差は単純な先進・後進ではなく、異なる社会形成過程として理解する必要がある。",
    supplementaryNoteZh: "同一时期，中国大陆已形成汉帝国，以木造·瓦·砖建造的大规模宫殿建筑与坟墓已经发达。而日本列岛仍处于统一国家形成途中，与地中海世界在政治规模、城市化程度和技术传播条件上不同。因此，这种差异不能简单理解为先进或落后，而应视为不同的社会形成过程。",
    examKeywords: ["パンテオン", "ローマン・コンクリート", "コロッセウム", "前方後円墳", "吉野ヶ里遺跡"],
    examKeywordsZh: ["万神殿", "罗马混凝土", "斗兽场", "前方后圆坟", "吉野里遗址"],
    relatedCardIds: ["style-roman", "type-pit-dwelling", "type-moated-settlement"],
  },
  {
    id: "4c-6c",
    year: "500 CE",
    century: "4th–6th Century CE",
    centuryZh: "4–6世纪",
    centuryEn: "4th–6th century CE",
    westernLabel: "ビザンツ建築の興隆",
    westernLabelZh: "拜占庭建筑的兴隆",
    westernLabelEn: "Rise of Byzantine architecture",
    westernTags: ["ハギア・ソフィア", "ペンデンティブ", "モザイク"],
    westernTagsZh: ["圣索菲亚", "帆拱", "镶嵌画"],
    westernTagsEn: ["Hagia Sophia", "Pendentive", "Mosaic"],
    eastAsianLabel: "飛鳥時代",
    eastAsianLabelZh: "飞鸟时代",
    eastAsianLabelEn: "Asuka period",
    eastAsianTags: ["飛鳥寺", "仏教建築の始まり"],
    eastAsianTagsZh: ["飞鸟寺", "佛教建筑开端"],
    eastAsianTagsEn: ["Asuka-dera", "Beginnings of Buddhist architecture"],
    westernRegionLabel: "ビザンツ帝国",
    westernRegionLabelZh: "拜占庭帝国",
    westernRegionLabelEn: "Byzantine Empire",
    easternRegionLabel: "日本列島（飛鳥）",
    easternRegionLabelZh: "日本列岛（飞鸟）",
    easternRegionLabelEn: "Japanese archipelago (Asuka)",
    macroTendency: "ビザンツ帝国：ローマ建築の技術を継承しつつ、ペンデンティブによるドーム架構が発展。キリスト教典礼に適合した集中式空間が追求された。日本列島：仏教伝来に伴い、中国大陸・朝鮮半島から寺院建築技術が体系的に伝えられ、日本最古の本格的仏教建築が建設された。両地域とも外来の宗教と建築技術を在来の伝統と融合させた点で共通するが、既存の建築技術の蓄積段階が異なっていた。",
    macroTendencyZh: "拜占庭帝国：继承罗马建筑技术同时，帆拱穹顶构架得到发展。追求适应基督教礼仪的集中式空间。日本列岛：随佛教传入，中国大陆·朝鲜半岛的寺院建筑技术被系统性传入，日本最古老的正规佛教建筑开始建造。两地均以外来宗教与建筑技术融合于本地传统，但既有建筑技术积累的阶段不同。",
    macroTendencyEn: "The Byzantine Empire developed pendentive domes while inheriting Roman building technology and pursuing centralized spaces suited to Christian liturgy. In the Japanese archipelago, Buddhist temple technology arrived systematically from the Chinese mainland and Korean Peninsula, enabling Japan's first formal Buddhist buildings. Both regions integrated imported religion and construction with local traditions, but from different technical foundations.",
    westernDetail: "ハギア・ソフィア（532-537年）はペンデンティブで正方形平面に大ドームを架構。主ドーム直径約31m、高さ約55.6m。ビザンツ建築の最高傑作とされる。サン・ヴィターレ聖堂（ラヴェンナ、6世紀）は八角形集中堂形式。",
    westernDetailZh: "圣索菲亚（532-537年）以帆拱在正方形平面上架设大穹顶。主穹顶直径约31m，高约55.6m。被视为拜占庭建筑最高杰作。圣维塔莱教堂（拉文纳，6世纪）为八角形集中式。",
    westernDetailEn: "Hagia Sophia (532–537) uses pendentives to support a great dome over a square plan; its main dome is about 31 m in diameter and 55.6 m high. It is a masterpiece of Byzantine architecture. San Vitale in Ravenna is a sixth-century octagonal centralized church.",
    eastAsianDetail: "飛鳥寺（6世紀末、蘇我馬子により建立）は日本最古の本格的仏教寺院。伽藍配置は四天王寺式（塔・金堂・講堂が一直線）とされる。中国南北朝時代の建築様式を基礎とし、朝鮮半島（百済）経由で技術が伝来した。",
    eastAsianDetailZh: "飞鸟寺（6世纪末，苏我马子建立）为日本最古老的正规佛教寺院。伽蓝配置为四天王寺式（塔·金堂·讲堂一直线排列）。以中国南北朝时代建筑样式为基础，经朝鲜半岛（百济）传来技术。",
    eastAsianDetailEn: "Asuka-dera, founded by Soga no Umako in the late sixth century, was Japan's earliest formal Buddhist temple. Its compound followed the Shitennō-ji arrangement, with pagoda, main hall, and lecture hall aligned on an axis. Technology arrived via Baekje, based on architecture of China's Northern and Southern Dynasties.",
    comparison: [
      { dimension: "政治と社会組織", dimensionZh: "政治与社会组织", dimensionEn: "Political and social organization", western: "ローマ帝国の東半分を継承するキリスト教帝国。皇帝が教会と国家の双方を統括。", westernZh: "继承罗马帝国东半部的基督教帝国。皇帝统括教会与国家双方。", westernEn: "A Christian empire inheriting the eastern half of Rome, with the emperor directing both church and state.", eastAsian: "豪族（蘇我氏等）を中心とする連合政権。仏教受容をめぐる政治的対立を経て国家宗教として受容。", eastAsianZh: "以豪族（苏我氏等）为中心的联合政权。经由围绕佛教接受的政争后作为国家宗教接受。", eastAsianEn: "A coalition government centered on powerful clans such as the Soga; Buddhism became a state religion after political conflict over its acceptance." },
      { dimension: "集落・都市形態", dimensionZh: "聚落／城市形态", dimensionEn: "Settlement and urban form", western: "コンスタンティノポリスを首都とする大都市文明。ローマ以来の都市インフラを継承。", westernZh: "以君士坦丁堡为首都的大都市文明。继承罗马以来的城市基础设施。", westernEn: "A metropolitan civilization centered on Constantinople and inheriting Roman urban infrastructure.", eastAsian: "宮都（飛鳥）を中心とする拠点形成段階。本格的な都城（藤原京）は7世紀末を待つ。", eastAsianZh: "以宮都（飞鸟）为中心的据点形成阶段。正式都城（藤原京）有待7世纪末。", eastAsianEn: "A stage of nodal formation around the court center of Asuka; the formal Fujiwara capital came only in the late seventh century." },
      { dimension: "宗教と建築", dimensionZh: "宗教与建筑", dimensionEn: "Religion and architecture", western: "キリスト教の帝国国教化と典礼空間。バシリカ式と集中式の二大系譜。", westernZh: "基督教帝国国教化与礼仪空间。巴西利卡式与集中式两大谱系。", westernEn: "Christianity as imperial religion and its liturgical spaces: basilican and centralized traditions.", eastAsian: "仏教の公的受容と伽藍建築の導入。塔・金堂・講堂を中核とする伽藍配置。", eastAsianZh: "佛教的官方接受与伽蓝建筑引入。以塔·金堂·讲堂为核心的伽蓝配置。", eastAsianEn: "Official acceptance of Buddhism and temple compounds organized around pagoda, main hall, and lecture hall." },
      { dimension: "構造と材料", dimensionZh: "构造与材料", dimensionEn: "Structure and materials", western: "石造・煉瓦造を基本とし、ペンデンティブ（三角穹隅）により方形平面にドームを架構。", westernZh: "以石造·砖造为基础，以帆拱（三角穹隅）在方形平面上架设穹顶。", westernEn: "Stone and brick construction, with pendentives supporting domes over square plans.", eastAsian: "大陸から木造軸組・瓦葺き技術を導入。在来の掘立柱から礎石建物への転換期。", eastAsianZh: "从大陆引入木造框架·瓦葺技术。从传统掘立柱向础石建物的转换期。", eastAsianEn: "Introduction of continental timber framing and tile roofing; a transition from post-in-ground to foundation-stone buildings." },
      { dimension: "技術伝播の経路", dimensionZh: "技术传播路径", dimensionEn: "Routes of technical transmission", western: "ローマ→ビザンツの技術継承と典礼空間への応用変容。", westernZh: "罗马→拜占庭的技术继承与向礼仪空间的应用变容。", westernEn: "Inheritance of Roman technology in Byzantium and its transformation for liturgical space.", eastAsian: "中国南北朝→朝鮮半島（百済）→日本への段階的技術移転。渡来人の役割が大きい。", eastAsianZh: "中国南北朝→朝鲜半岛（百济）→日本的阶段性技术转移。渡来人作用重大。", eastAsianEn: "Stepwise transfer from China's Northern and Southern Dynasties through Baekje to Japan, with immigrants playing a major role." },
    ],
    footnote: "仏教建築は中国→朝鮮半島（百済）→日本と伝播し、各地域で様式が変容した。飛鳥寺の工匠の一部は百済からの渡来人と考えられている。",
    footnoteZh: "佛教建筑经中国→朝鲜半岛（百济）→日本传播，各样式在各地域发生变容。飞鸟寺的部分工匠被认为是百济渡来人。",
    footnoteEn: "Buddhist architecture spread from China through Baekje to Japan, changing in each region. Some craftspeople at Asuka-dera are thought to have immigrated from Baekje.",
    supplementaryNote: "西ヨーロッパでは西ローマ帝国滅亡（476年）後、古代都市が衰退し建築活動が縮小した。ビザンツ帝国は旧ローマ帝国の東半分として大規模建設を継続。日本列島は飛鳥時代に入り、中国大陸・朝鮮半島から仏教とともに寺院建築技術を初めて体系的に受容した。この時期の日欧の建築差は、技術伝播の到達時期の違いによるものであり、社会形成の優劣ではない。",
    supplementaryNoteZh: "西欧在西罗马帝国灭亡（476年）后，古代城市衰退，建筑活动缩小。拜占庭帝国作为旧罗马帝国东半部，继续大规模建设。日本列岛进入飞鸟时代，首次系统性地从中国大陆与朝鲜半岛接受佛教及寺院建筑技术。此时期日欧建筑差异源于技术传播到达时间的先后，而非社会形成的优劣。",
    supplementaryNoteEn: "After the fall of the Western Roman Empire in 476, western European cities and building activity declined, while Byzantium continued large-scale construction. In the Asuka period Japan first received Buddhist temple technology systematically from the Chinese mainland and Korean Peninsula. These differences reflect the timing of technical transmission, not social superiority.",
    examKeywords: ["ハギア・ソフィア", "ペンデンティブ", "飛鳥寺", "四天王寺式伽藍配置", "サン・ヴィターレ"],
    examKeywordsZh: ["圣索菲亚", "帆拱", "飞鸟寺", "四天王寺式伽蓝配置", "圣维塔莱"],
    examKeywordsEn: ["Hagia Sophia", "Pendentive", "Asuka-dera", "Shitennō-ji compound layout", "San Vitale"],
    relatedCardIds: ["style-byzantine", "style-early-christian", "style-asuka"],
  },
  {
    id: "7c-8c",
    year: "750 CE",
    century: "8th–9th Century CE",
    centuryZh: "8–9世纪",
    centuryEn: "8th–9th century CE",
    westernLabel: "カロリング朝ルネサンス",
    westernLabelZh: "加洛林文艺复兴",
    westernLabelEn: "Carolingian Renaissance",
    westernTags: ["バシリカ", "アーヘン宮廷礼拝堂"],
    westernTagsZh: ["巴西利卡", "亚琛宫廷礼拜堂"],
    westernTagsEn: ["Basilica", "Palatine Chapel at Aachen"],
    eastAsianLabel: "奈良時代",
    eastAsianLabelZh: "奈良时代",
    eastAsianLabelEn: "Nara period",
    eastAsianTags: ["唐招提寺", "東大寺", "大仏建立"],
    eastAsianTagsZh: ["唐招提寺", "東大寺", "大佛建造"],
    eastAsianTagsEn: ["Tōshōdai-ji", "Tōdai-ji", "Construction of the Great Buddha"],
    westernRegionLabel: "フランク王国（西欧）",
    westernRegionLabelZh: "法兰克王国（西欧）",
    westernRegionLabelEn: "Frankish kingdom (Western Europe)",
    easternRegionLabel: "日本列島（奈良）",
    easternRegionLabelZh: "日本列岛（奈良）",
    easternRegionLabelEn: "Japanese archipelago (Nara)",
    macroTendency: "フランク王国：ローマ建築様式の復興とキリスト教建築の整備が進められた。カロリング朝ルネサンスは西欧中世建築の起点となる。日本列島：唐の建築様式を全面的に導入し、都城制・寺院建築・官衙建築の体系が整備され、日本建築の基盤が形成された。",
    macroTendencyZh: "法兰克王国：罗马建筑样式复兴与基督教建筑整备取得进展。加洛林文艺复兴成为西欧中世纪建筑的起点。日本列岛：全面引入唐代建筑样式，都城制·寺院建筑·官衙建筑体系得到整备，形成日本建筑的基础。",
    macroTendencyEn: "The Frankish kingdom revived Roman forms and organized Christian architecture; the Carolingian Renaissance became a starting point for medieval Western European building. Japan comprehensively adopted Tang forms, establishing systems for capitals, temples, and government buildings that formed a basis for Japanese architecture.",
    westernDetail: "アーヘン宮廷礼拝堂（792-805年頃、オド・フォン・メッツ設計）はカロリング朝ルネサンスの代表作。中央八角形平面にドームを持ち、ビザンツ建築（サン・ヴィターレ）の影響を受けた。フランク王国はローマの権威を継承した。",
    westernDetailZh: "亚琛宫廷礼拜堂（约792-805年，奥多设计）为加洛林文艺复兴代表作。中央八角形平面带穹顶，受拜占庭建筑（圣维塔莱）影响。法兰克王国继承了罗马的权威。",
    westernDetailEn: "The Palatine Chapel at Aachen, designed by Odo of Metz around 792–805, is a key Carolingian work. Its domed central octagon was influenced by San Vitale and expressed Frankish succession to Roman authority.",
    eastAsianDetail: "唐招提寺金堂（759年頃）は鑑真和上が唐代の建築様式を忠実に再現。東大寺は752年に大仏開眼。平城京は唐の長安をモデルとした条坊制都城。奈良時代には国分寺・国分尼寺が全国に建立された。",
    eastAsianDetailZh: "唐招提寺金堂（759年左右）忠实再现鉴真和尚从唐带回的建筑样式。东大寺752年大佛开眼。平城京以唐长安为蓝本的条坊制都城。奈良时代在全国建立国分寺·国分尼寺。",
    eastAsianDetailEn: "The main hall of Tōshōdai-ji, around 759, reproduced Tang forms brought by the monk Ganjin. Tōdai-ji's Great Buddha was consecrated in 752. Heijō-kyō followed the grid of Tang Chang'an, while provincial monasteries and nunneries were established nationwide.",
    comparison: [
      { dimension: "建築様式の由来", dimensionZh: "建筑样式的由来", dimensionEn: "Origins of architectural style", western: "古代ローマ＋ビザンツの影響", westernZh: "古罗马＋拜占庭的影响", westernEn: "Ancient Roman and Byzantine influence", eastAsian: "唐（中国）建築様式の本格的導入", eastAsianZh: "唐（中国）建筑样式的正式引入", eastAsianEn: "Full introduction of Tang Chinese architectural forms" },
      { dimension: "都城計画", dimensionZh: "都城规划", dimensionEn: "Capital planning", western: "帝都アーヘン（ローマの伝統を継承）", westernZh: "帝都亚琛（继承罗马传统）", westernEn: "Imperial Aachen, inheriting Roman traditions", eastAsian: "条坊制による平城京（唐の長安を模範）", eastAsianZh: "条坊制平城京（以唐长安为范本）", eastAsianEn: "Grid-planned Heijō-kyō modeled on Tang Chang'an" },
      { dimension: "建築の制度化", dimensionZh: "建筑的制度化", dimensionEn: "Institutionalization of building", western: "修道院建築の整備（ベネディクト会）", westernZh: "修道院建筑整备（本笃会）", westernEn: "Development of Benedictine monastic architecture", eastAsian: "国分寺・国分尼寺の全国建立", eastAsianZh: "国分寺·国分尼寺全国建立", eastAsianEn: "Nationwide establishment of provincial monasteries and nunneries" },
      { dimension: "技術伝播", dimensionZh: "技术传播", dimensionEn: "Technical transmission", western: "地中海世界からアルプス以北への技術移転", westernZh: "从地中海世界向阿尔卑斯以北的技术转移", westernEn: "Transfer from the Mediterranean world north of the Alps", eastAsian: "唐→朝鮮半島→日本への建築技術移転", eastAsianZh: "唐→朝鲜半岛→日本的建筑技术转移", eastAsianEn: "Transfer of architectural technology from Tang China through Korea to Japan" },
    ],
    footnote: "唐招提寺は鑑真和上が持ち帰った建築技術の実物証明。奈良時代の建築は中国唐代の影響を色濃く残す。アーヘン宮廷礼拝堂は現存するカロリング朝最大の建築。",
    footnoteZh: "唐招提寺是鉴真和尚带回的建筑技术的实物证明。奈良时代建筑浓厚保留中国唐代影响。亚琛宫廷礼拜堂为现存加洛林朝最大建筑。",
    footnoteEn: "Tōshōdai-ji is material evidence of technology brought by Ganjin. Nara-period architecture strongly preserves Tang influence, while the Palatine Chapel is the largest surviving Carolingian building.",
    supplementaryNote: "イスラーム世界ではウマイヤ朝・アッバース朝のもとで独自のモスク建築が発展していた時期にあたる（ダマスカスの大モスク等）。",
    supplementaryNoteZh: "伊斯兰世界在伍麦叶朝·阿拔斯朝下，独自的清真寺建筑正在发展（大马士革大清真寺等）。",
    supplementaryNoteEn: "In the Islamic world, distinctive mosque architecture was developing under the Umayyad and Abbasid caliphates, including the Great Mosque of Damascus.",
    examKeywords: ["アーヘン宮廷礼拝堂", "唐招提寺金堂", "東大寺", "平城京・条坊制", "鑑真和上"],
    examKeywordsZh: ["亚琛宫廷礼拜堂", "唐招提寺金堂", "东大寺", "平城京·条坊制", "鉴真和尚"],
    examKeywordsEn: ["Palatine Chapel at Aachen", "Tōshōdai-ji Main Hall", "Tōdai-ji", "Heijō-kyō grid plan", "Ganjin"],
    relatedCardIds: ["style-carolingian", "style-wayo"],
  },
  {
    id: "9c-11c",
    year: "1000 CE",
    century: "9th–11th Century",
    centuryZh: "9-11世纪",
    centuryEn: "9th–11th century",
    westernLabel: "ロマネスク建築の発展",
    westernLabelZh: "罗曼式建筑的发展",
    westernLabelEn: "Development of Romanesque architecture",
    westernTags: ["シュパイヤー大聖堂", "バシリカ", "ヴォールト"],
    westernTagsZh: ["施派尔大教堂", "巴西利卡", "拱顶"],
    westernTagsEn: ["Speyer Cathedral", "Basilica", "Vault"],
    eastAsianLabel: "平安時代",
    eastAsianLabelZh: "平安时代",
    eastAsianLabelEn: "Heian period",
    eastAsianTags: ["平等院鳳凰堂", "寝殿造", "浄土教建築"],
    eastAsianTagsZh: ["平等院凤凰堂", "寝殿造", "净土教建筑"],
    eastAsianTagsEn: ["Byōdō-in Phoenix Hall", "Shinden-zukuri", "Pure Land architecture"],
    westernRegionLabel: "西欧（神聖ローマ帝国圏）",
    westernRegionLabelZh: "西欧（神圣罗马帝国圈）",
    westernRegionLabelEn: "Western Europe (Holy Roman Empire sphere)",
    easternRegionLabel: "日本列島（平安）",
    easternRegionLabelZh: "日本列岛（平安）",
    easternRegionLabelEn: "Japanese archipelago (Heian)",
    macroTendency: "西欧：ローマ建築の技術を基盤に教会建築が発展。分厚い壁体とヴォールト天井による重厚な石造空間が各地で建設された。日本列島：貴族文化の成熟に伴い寝殿造が確立。末法思想を背景に浄土教建築が発展し、庭園と一体化した優美な建築が生み出された。",
    macroTendencyZh: "西欧：以罗马建筑技术为基础发展教会建筑。以厚壁体和拱顶为特征的重厚石造空间在各地建造。日本列岛：随贵族文化成熟，寝殿造确立。以末法思想为背景，净土教建筑发展，产生与庭园一体的优美建筑。",
    macroTendencyEn: "In Western Europe, church architecture developed from Roman techniques, producing massive stone spaces with thick walls and vaults. In Japan, shinden-zukuri became established with aristocratic culture; Pure Land architecture developed amid beliefs in the latter days of the Dharma, creating graceful buildings integrated with gardens.",
    westernDetail: "シュパイヤー大聖堂（1030-1061年、神聖ローマ帝国）は身廊高さ約33mのロマネスク建築の最高到達点。厚い壁体で水平推力を処理。サンティアゴ・デ・コンポステーラ（スペイン）は巡礼路と結び付いた重要聖堂。",
    westernDetailZh: "施派尔大教堂（1030-1061年，神圣罗马帝国）为中殿高约33m的罗曼式建筑最高成就。以厚壁体处理水平推力。圣地亚哥·德·孔波斯特拉（西班牙）为与巡礼路联系的重要圣堂。",
    westernDetailEn: "Speyer Cathedral (1030–1061) is a high point of Romanesque architecture, with a nave about 33 m high and thick walls resisting horizontal thrust. Santiago de Compostela was an important pilgrimage church.",
    eastAsianDetail: "平等院鳳凰堂（1053年、藤原頼通建立）は浄土教建築の代表作。末法思想の下、阿弥陀信仰を建築と庭園で表現。寝殿造は貴族の生活様式を反映した建物配置を特徴とし、東三条殿などが知られる。",
    eastAsianDetailZh: "平等院凤凰堂（1053年，藤原赖通建立）为净土教建筑代表作。末法思想下以建筑与庭园表现阿弥陀信仰。寝殿造以反映贵族生活方式的建物配置为特征，东三条殿等较为人知。",
    eastAsianDetailEn: "Byōdō-in Phoenix Hall (1053), founded by Fujiwara no Yorimichi, is a major Pure Land building expressing Amida belief through architecture and garden. Shinden-zukuri arranged buildings around aristocratic life, as at Higashi Sanjō Palace.",
    comparison: [
      { dimension: "宗教と建築", dimensionZh: "宗教与建筑", dimensionEn: "Religion and architecture", western: "キリスト教会の権威と巡礼", westernZh: "基督教会的权威与巡礼", westernEn: "Church authority and pilgrimage", eastAsian: "末法思想・浄土信仰と極楽浄土の表現", eastAsianZh: "末法思想·净土信仰与极乐净土的表现", eastAsianEn: "Pure Land belief and the expression of paradise" },
      { dimension: "空間特性", dimensionZh: "空间特性", dimensionEn: "Spatial character", western: "暗く重厚な石造内部空間", westernZh: "暗而厚重的石造内部空间", westernEn: "Dark, massive stone interiors", eastAsian: "明るく開放的な木造空間（庭園との一体性）", eastAsianZh: "明亮开放的木造空间（与庭园的一体性）", eastAsianEn: "Bright, open timber spaces integrated with gardens" },
      { dimension: "構造", dimensionZh: "构造", dimensionEn: "Structure", western: "石造ヴォールト・分厚い壁体", westernZh: "石造拱顶·厚壁体", westernEn: "Stone vaults and thick walls", eastAsian: "木造軸組・寄棟造・檜皮葺", eastAsianZh: "木造框架·庑殿顶·桧皮葺", eastAsianEn: "Timber post-and-beam framing, hipped roofs, and cypress-bark roofing" },
      { dimension: "建築の平面", dimensionZh: "建筑平面", dimensionEn: "Building plan", western: "ラテン十字型バシリカ", westernZh: "拉丁十字巴西利卡", westernEn: "Latin-cross basilicas", eastAsian: "寝殿造（対称的配置）・阿弥陀堂（翼廊付き）", eastAsianZh: "寝殿造（对称配置）·阿弥陀堂（带翼廊）", eastAsianEn: "Shinden-zukuri with symmetrical layouts and Amida halls with wings" },
    ],
    footnote: "平安時代の日本建築は唐様式から和様式への変容が進み、独自の発展を遂げた。ロマネスクは地域により多様な表現がある。",
    footnoteZh: "平安时代日本建筑从唐样式向和样式转变，实现了独立发展。罗曼式因地域不同而有多种表现。",
    footnoteEn: "Heian-period Japanese architecture moved from Tang-derived forms toward Wayō and developed independently. Romanesque architecture varied regionally.",
      examKeywords: ["シュパイヤー大聖堂", "平等院鳳凰堂", "寝殿造", "浄土教建築", "末法思想"],
      examKeywordsZh: ["施派尔大教堂", "平等院凤凰堂", "寝殿造", "净土教建筑", "末法思想"],
      examKeywordsEn: ["Speyer Cathedral", "Byōdō-in Phoenix Hall", "Shinden-zukuri", "Pure Land architecture", "Latter Days of the Dharma"],
      relatedCardIds: ["style-romanesque", "style-shinden"],
      trends: [
        {
          region: "western",
          ja: "ローマ建築の技術を基盤に教会建築が発展。分厚い壁体とヴォールト天井による重厚な石造空間が各地に建設された。",
          zh: "以罗马建筑技术为基础，教会建筑发展；厚墙体与拱顶构成厚重的石造空间。",
          en: "Church architecture developed from Roman techniques, with thick walls and vaults creating massive stone spaces.",
        },
        {
          region: "japan",
          ja: "貴族文化の成熟に伴い寝殿造が確立。末法思想を背景に浄土教建築が発展し、庭園と一体化した優美な建築が生み出された。",
          zh: "随着贵族文化成熟，寝殿造确立；以末法思想为背景，净土教建筑发展，并形成与庭园一体化的优美建筑。",
          en: "As aristocratic culture matured, shinden-zukuri became established; Pure Land architecture developed and created graceful buildings integrated with gardens.",
        },
      ],
      examKeywordEntries: [
        { region: "western", type: "building", ja: "シュパイヤー大聖堂", zh: "施派尔大教堂", en: "Speyer Cathedral" },
        { region: "western", type: "style", ja: "ロマネスク建築", zh: "罗曼式建筑", en: "Romanesque architecture" },
        { region: "western", type: "structure", ja: "ヴォールト", zh: "拱顶", en: "Vault" },
        { region: "japan", type: "building", ja: "平等院鳳凰堂", zh: "平等院凤凰堂", en: "Byōdō-in Phoenix Hall" },
        { region: "japan", type: "spatial-form", ja: "寝殿造", zh: "寝殿造", en: "Shinden-zukuri" },
        { region: "japan", type: "religion", ja: "浄土教建築", zh: "净土教建筑", en: "Pure Land architecture" },
        { region: "japan", type: "ideology", ja: "末法思想", zh: "末法思想", en: "Latter Days of the Dharma" },
      ],
      buildingIds: [
        "building-81d00608e078",
        "building-c90fcc3d63b9",
        "building-34fb1bfbaad8",
        "building-supplemental-higashi-sanjo-dono",
      ],
    },
  {
    id: "12c-14c",
    year: "1200 CE",
    century: "12th–14th Century",
    centuryZh: "12-14世纪",
    centuryEn: "12th–14th century",
    westernLabel: "ゴシック建築の全盛",
    westernLabelZh: "哥特式建筑的全盛",
    westernLabelEn: "High Gothic architecture",
    westernTags: ["ノートル＝ダム", "フライング・バットレス", "ステンドグラス"],
    westernTagsZh: ["巴黎圣母院", "飞扶壁", "彩色玻璃"],
    westernTagsEn: ["Notre-Dame de Paris", "Flying buttress", "Stained glass"],
    eastAsianLabel: "鎌倉〜室町",
    eastAsianLabelZh: "镰仓～室町",
    eastAsianLabelEn: "Kamakura to Muromachi periods",
    eastAsianTags: ["大仏様", "禅宗様", "東大寺南大門"],
    eastAsianTagsZh: ["大佛样", "禅宗样", "东大寺南大门"],
    eastAsianTagsEn: ["Daibutsuyō", "Zenshūyō", "Tōdai-ji Great South Gate"],
    westernRegionLabel: "西欧（フランスを中心）",
    westernRegionLabelZh: "西欧（以法国为中心）",
    westernRegionLabelEn: "Western Europe (centered on France)",
    easternRegionLabel: "日本列島（鎌倉〜室町）",
    easternRegionLabelZh: "日本列岛（镰仓～室町）",
    easternRegionLabelEn: "Japanese archipelago (Kamakura–Muromachi)",
    macroTendency: "西欧（フランス）：フライング・バットレスにより壁面が解放され、光と高さを追求したゴシック建築が全盛を迎えた。「光の神学」が建築を方向づけた。日本列島：中国宋代の建築技術が導入され、大仏様・禅宗様が成立。木造技術の精緻化と様式の多様化が進んだ。",
    macroTendencyZh: "西欧（法国）：飞扶壁解放壁面，追求光与高度的哥特式建筑迎来全盛期。「光的神学」主导建筑方向。日本列岛：中国宋代建筑技术传入，大佛样·禅宗样成立。木造技术精细化与样式多样化取得进展。",
    macroTendencyEn: "In France, flying buttresses freed the walls and Gothic architecture reached its height in the pursuit of light and verticality, guided by a theology of light. In Japan, Song Chinese technology introduced Daibutsuyō and Zenshūyō, refining timber construction and diversifying styles.",
    westernDetail: "パリのノートル＝ダム（1163-1250年）は初期ゴシックの象徴。アミアン大聖堂（1220-1288年）は身廊高さ約42.3mで石造建築の最高到達点の一つ。サント・シャペル（1248年）はステンドグラスによる光の空間を極めた。",
    westernDetailZh: "巴黎圣母院（1163-1250年）为早期哥特式象征。亚眠大教堂（1220-1288年）中殿高约42.3m，为石造建筑最高成就之一。圣礼拜堂（1248年）以彩色玻璃将光之空间推向极致。",
    westernDetailEn: "Notre-Dame de Paris (1163–1250) symbolizes Early Gothic. Amiens Cathedral, with a nave about 42.3 m high, is a peak of stone building, while Sainte-Chapelle (1248) makes light through stained glass its defining space.",
    eastAsianDetail: "東大寺南大門（1203年）は重源が宋から伝えた大仏様の代表作。浄土寺浄土堂（1195年）は大仏様の集中堂形式。円覚寺舎利殿（1280年代）は禅宗様の代表的遺構。和様・大仏様・禅宗様の三様式が並立した。",
    eastAsianDetailZh: "东大寺南大门（1203年）为重源从宋传入的大佛样代表作。净土寺净土堂（1195年）为大佛样的集中式佛堂。圆觉寺舍利殿（1280年代）为禅宗样代表性遗构。和样·大佛样·禅宗样三样式并立。",
    eastAsianDetailEn: "Tōdai-ji's Great South Gate (1203) is a principal Daibutsuyō work brought from Song China by Chōgen. Jōdo-ji Jōdo Hall (1195) is a centralized Daibutsuyō hall, while Engaku-ji Shariden is a major Zenshūyō survivor. Wayō, Daibutsuyō, and Zenshūyō coexisted.",
    comparison: [
      { dimension: "建築の追求", dimensionZh: "建筑追求", dimensionEn: "Architectural pursuit", western: "光・高さ・石造の極限", westernZh: "光·高度·石造的极限", westernEn: "The limits of light, height, and stone building", eastAsian: "木造技術の精緻化と様式の多様化", eastAsianZh: "木造技术精细化与样式多样化", eastAsianEn: "Refinement of timber technology and diversification of styles" },
      { dimension: "技術革新", dimensionZh: "技术革新", dimensionEn: "Technical innovation", western: "フライング・バットレス＋尖頭アーチ＋リブ・ヴォールト", westernZh: "飞扶壁＋尖券＋肋架拱顶", westernEn: "Flying buttresses, pointed arches, and rib vaults", eastAsian: "大仏様（挿肘木・貫）＋禅宗様（扇垂木等）", eastAsianZh: "大佛样（插肘木·贯）＋禅宗样（扇椽等）", eastAsianEn: "Daibutsuyō with inserted bracket arms and tie beams; Zenshūyō with radial rafters" },
      { dimension: "思想背景", dimensionZh: "思想背景", dimensionEn: "Intellectual background", western: "光の神学（光＝神の顕現）＋都市の大聖堂建設競争", westernZh: "光的神学（光＝神的显现）＋城市大圣堂建设竞争", westernEn: "Theology of light and competition among cities to build cathedrals", eastAsian: "仏教建築の様式化＋中国建築技術の選択的導入", eastAsianZh: "佛教建筑的样式化＋中国建筑技术的选择性引入", eastAsianEn: "Stylistic development of Buddhist architecture and selective adoption of Chinese technology" },
      { dimension: "架構の原理", dimensionZh: "构架原理", dimensionEn: "Structural principle", western: "外部バットレスで横推力処理→壁の自由化", westernZh: "以外扶壁处理横推力→壁面自由化", westernEn: "External buttresses take horizontal thrust, freeing the walls", eastAsian: "軸組（柱・貫・肘木）で全体剛性→木造の自由度", eastAsianZh: "以框架（柱·贯·肘木）确保整体刚性→木造自由度", eastAsianEn: "Posts, tie beams, and bracket arms provide overall rigidity and timber flexibility" },
    ],
    footnote: "大仏様は中国宋代の建築技術を日本に導入したが、短期間で用いられなくなった。禅宗様は現代まで継続して用いられている。和様・大仏様・禅宗様の折衷が後の折衷様につながる。",
    footnoteZh: "大佛样将中国宋代建筑技术引入日本，但短期间即不再使用。禅宗样沿用至今。和样·大佛样·禅宗样的折衷连接后来的折衷样。",
    footnoteEn: "Daibutsuyō introduced Song Chinese technology but soon fell out of use. Zenshūyō continued into the present, while the synthesis of Wayō, Daibutsuyō, and Zenshūyō led to later eclectic styles.",
    examKeywords: ["ノートル＝ダム大聖堂", "フライング・バットレス", "東大寺南大門", "浄土寺浄土堂", "大仏様・禅宗様"],
    examKeywordsZh: ["巴黎圣母院", "飞扶壁", "东大寺南大门", "净土寺净土堂", "大佛样·禅宗样"],
    examKeywordsEn: ["Notre-Dame de Paris", "Flying buttress", "Tōdai-ji Great South Gate", "Jōdo-ji Jōdo Hall", "Daibutsuyō and Zenshūyō"],
    relatedCardIds: ["style-gothic", "style-daibutsuyo", "style-zenshuyo", "style-setchuyo"],
  },
  {
    id: "15c-16c",
    year: "1500 CE",
    centuryEn: "15th–16th century",
    westernLabelEn: "Renaissance architecture",
    westernTagsEn: ["Brunelleschi", "Tempietto", "Villa Rotonda"],
    eastAsianLabelEn: "Muromachi to Azuchi–Momoyama periods",
    eastAsianTagsEn: ["Shoin-zukuri", "Tea houses", "Jurakudai"],
    westernRegionLabelEn: "Italy (Western Europe)",
    easternRegionLabelEn: "Japanese archipelago (Muromachi–Momoyama)",
    macroTendencyEn: "Italy: the theoretical recovery of ancient Roman architecture systematized architecture as a learned discipline. Brunelleschi’s dome marked a technical breakthrough, and Palladio’s architectural books had wide influence. Japanese archipelago: as warrior culture matured, shoin-zukuri was established. The development of the tea ceremony produced the distinctive grass-hut tea house.",
    westernDetailEn: "Brunelleschi’s dome for Florence Cathedral (1420–1436) used a double-shell structure without full centering. Bramante’s Tempietto (1502) exemplifies Renaissance ideal proportion. Palladio’s Villa Rotonda (1567–1592) is a model of the symmetrical plan.",
    eastAsianDetailEn: "The Dōjinsai at Tōgudō, Ginkaku-ji (1486), is an early shoin-zukuri example, with a four-and-a-half-tatami study. Tea houses such as Jo-an and Taian created spaces calibrated to the seated eye, including features such as the nijiriguchi crawl-through entrance and tokonoma alcove. Jurakudai (1587), Toyotomi Hideyoshi’s administrative residence, combined castle and mansion architecture.",
    footnoteEn: "Renaissance architecture took ancient Roman architectural treatises, especially Vitruvius’s Ten Books on Architecture, as models. In Japan, shoin-zukuri and sukiya-zukuri became the two major currents of early modern architecture.",
    examKeywordsEn: ["Brunelleschi’s dome", "Tempietto", "Villa Rotonda", "Shoin-zukuri (Dōjinsai)", "Tea houses (Jo-an and Taian)"],
    century: "15th–16th Century",
    centuryZh: "15-16世纪",
    westernLabel: "ルネサンス建築",
    westernLabelZh: "文艺复兴建筑",
    westernTags: ["ブルネレスキ", "テンピエット", "パラーディオ"],
    westernTagsZh: ["布鲁内莱斯基", "坦比哀多", "帕拉第奥"],
    eastAsianLabel: "室町〜安土桃山",
    eastAsianLabelZh: "室町～安土桃山",
    eastAsianTags: ["書院造", "茶室", "聚楽第"],
    eastAsianTagsZh: ["书院造", "茶室", "聚乐第"],
    westernRegionLabel: "イタリア（西欧）",
    westernRegionLabelZh: "意大利（西欧）",
    easternRegionLabel: "日本列島（室町〜桃山）",
    easternRegionLabelZh: "日本列岛（室町～桃山）",
    macroTendency: "イタリア：古代ローマ建築の理論的復興が行われ、建築が学問として体系化された。ブルネレスキのドームは技術的飛躍を示し、パラーディオの建築書が広く影響を与えた。日本列島：武家文化の成熟に伴い書院造が確立。茶道の発展が草庵茶室という独自の建築を生み出した。",
    macroTendencyZh: "意大利：古罗马建筑的理论复兴得以展开，建筑作为学问被体系化。布鲁内莱斯基穹顶显示技术飞跃，帕拉第奥的建筑书产生广泛影响。日本列岛：随武家文化成熟，书院造确立。茶道发展创造出草庵茶室这一独特的建筑类型。",
    westernDetail: "ブルネレスキのサンタ・マリア・デル・フィオーレ大聖堂ドーム（1420-1436年）は二重殻構造で仮枠に頼らず架構。ブラマンテのテンピエット（1502年）はルネサンスの理想的比例を示す。パラーディオのヴィラ・ロトンダ（1567-92年）は対称的平面の模範。",
    westernDetailZh: "布鲁内莱斯基的圣母百花大教堂穹顶（1420-1436年）以双壳结构不依赖满堂脚手架架设。伯拉孟特的坦比哀多（1502年）显示文艺复兴的理想比例。帕拉第奥的维拉罗通达（1567-92年）为对称平面的范例。",
    eastAsianDetail: "慈照寺東求堂（1486年）の同仁斎は四畳半の書斎で書院造の初期例。茶室建築（如庵、待庵等）はにじり口や床の間など坐の視線で計算された空間を生み出した。聚楽第（1587年）は豊臣秀吉の政庁兼邸宅で、城郭と邸宅の複合的建築。",
    eastAsianDetailZh: "慈照寺东求堂（1486年）同仁斋为四叠半书房，为书院造早期实例。茶室建筑（如庵、待庵等）创造了躙口和床之间等以坐姿视线计算的空间。聚乐第（1587年）为丰臣秀吉的政厅兼邸宅，为城郭与邸宅的复合建筑。",
    comparison: [
      { dimension: "建築理論", dimensionZh: "建筑理论", dimensionEn: "Architectural theory", western: "建築書による理論的体系化（ヴィトルウィウス『建築書』再発見＋パラーディオ『建築四書』）", westernZh: "以建筑书进行理论体系化（维特鲁威《建筑书》再发现＋帕拉第奥《建筑四书》）", westernEn: "Theory systematized through architectural treatises", eastAsian: "口伝・実作による技術伝承＋木割書（『匠明』等）", eastAsianZh: "以口传·实作传承技术＋木割书（《匠明》等）", eastAsianEn: "Oral and practical transmission, including kiwari manuals" },
      { dimension: "空間構成", dimensionZh: "空间构成", dimensionEn: "Spatial composition", western: "幾何学的比例と遠近法に基づく空間", westernZh: "基于几何学比例与透视法的空间", westernEn: "Space based on geometric proportion and perspective.", eastAsian: "座の視線で計算された内部空間＋非対称の構成", eastAsianZh: "以坐姿视线计算的内部空间＋非对称构成", eastAsianEn: "Asymmetrical interior spaces calibrated to the seated viewpoint." },
      { dimension: "材料と構法", dimensionZh: "材料与构法", dimensionEn: "Materials and construction", western: "石造・組積造＋ドーム技術の革新", westernZh: "石造·组积造＋穹顶技术革新", westernEn: "Stone and masonry construction, with innovations in dome technology.", eastAsian: "木造軸組＋数寄屋の自由な平面構成", eastAsianZh: "木造框架＋数寄屋的自由平面构成", eastAsianEn: "Timber framing and the flexible plans of sukiya-zukuri." },
    ],
    footnote: "ルネサンス建築は古代ローマの建築書（ウィトルウィウス『建築十書』）を手本とした。日本では書院造と数寄屋造が近世建築の二大潮流を形成した。",
    footnoteZh: "文艺复兴建筑以古罗马建筑书（维特鲁威《建筑十书》）为范本。日本书院造与数寄屋造形成近世建筑的两大潮流。",
    examKeywords: ["ブルネレスキのドーム", "テンピエット", "ヴィラ・ロトンダ", "書院造（同仁斎）", "茶室（如庵・待庵）"],
    examKeywordsZh: ["布鲁内莱斯基穹顶", "坦比哀多", "维拉罗通达", "书院造（同仁斋）", "茶室（如庵·待庵）"],
    relatedCardIds: ["style-renaissance", "style-mannerism", "style-shoin", "style-sukiya"],
  },
  {
    id: "17c-18c",
    year: "1700 CE",
    centuryEn: "17th–18th century",
    westernLabelEn: "Baroque to Neoclassicism",
    westernTagsEn: ["Borromini", "Panthéon, Paris", "Neoclassicism"],
    eastAsianLabelEn: "Edo period",
    eastAsianTagsEn: ["Nikkō Tōshō-gū", "Katsura Imperial Villa", "Gongen-zukuri"],
    westernRegionLabelEn: "Western Europe (Italy and France)",
    easternRegionLabelEn: "Japanese archipelago (Edo)",
    macroTendencyEn: "Western Europe: architecture moved from Baroque’s dynamic, dramatic space toward Neoclassicism’s restrained rationality. In the eighteenth century, preservation debates began and Winckelmann’s doctrine of imitation of antiquity directed Neoclassicism. Japanese archipelago: under the Tokugawa shogunate, shrine-mausoleum architecture in the gongen-zukuri mode reached an ornamental peak, while sukiya-zukuri, exemplified by Katsura Imperial Villa, pursued a spare beauty.",
    westernDetailEn: "Borromini’s San Carlo alle Quattro Fontane (1638–1641) typifies Baroque dynamic space. Soufflot’s Panthéon in Paris (1758–1790) is a major Neoclassical work. In the later eighteenth century, architecture began to treat styles as historically relative.",
    eastAsianDetailEn: "Nikkō Tōshō-gū, rebuilt in 1636 under the third shogun Tokugawa Iemitsu, represents the apogee of gongen-zukuri; its Yōmeimon gate bears more than 150 carvings. Katsura Imperial Villa, dating to the mid-seventeenth century, is a leading sukiya-zukuri work, prized for its spare and refined spatial composition.",
    footnoteEn: "In eighteenth-century Europe, debate over architectural preservation and restoration became substantive, establishing an intellectual foundation for later conservation charters. The maturation of Japanese townspeople’s culture also influenced architecture.",
    examKeywordsEn: ["Borromini", "Soufflot’s Panthéon", "Nikkō Tōshō-gū", "Katsura Imperial Villa", "Gongen-zukuri and sukiya-zukuri"],
    century: "17th–18th Century",
    centuryZh: "17-18世纪",
    westernLabel: "バロック〜新古典主義",
    westernLabelZh: "巴洛克～新古典主义",
    westernTags: ["ボッロミーニ", "パンテオン（パリ）", "新古典主義"],
    westernTagsZh: ["波洛米尼", "先贤祠", "新古典主义"],
    eastAsianLabel: "江戸時代",
    eastAsianLabelZh: "江户时代",
    eastAsianTags: ["日光東照宮", "桂離宮", "権現造"],
    eastAsianTagsZh: ["日光东照宫", "桂离宫", "权现造"],
    westernRegionLabel: "西欧（イタリア・フランス）",
    westernRegionLabelZh: "西欧（意大利·法国）",
    easternRegionLabel: "日本列島（江戸）",
    easternRegionLabelZh: "日本列岛（江户）",
    macroTendency: "西欧：バロックの動的で劇的な空間から、新古典主義の静的な合理性へと展開。18世紀には建築保存の議論が始まり、ウィンケルマンの古代模倣論が新古典主義を方向づけた。日本列島：徳川幕府の下、霊廟建築（権現造）が装飾の極致に達する一方、桂離宮に代表される数寄屋造が簡素な美を追求した。",
    macroTendencyZh: "西欧：从巴洛克动态戏剧性空间向新古典主义静态合理性展开。18世纪建筑保存讨论开始，温克尔曼的古代模仿论主导新古典主义方向。日本列岛：德川幕府下，灵庙建筑（权现造）达到装饰极致，同时以桂离宫为代表的数寄屋造追求简素之美。",
    westernDetail: "ボッロミーニのサン・カルロ・アッラ・フォンターナ（1638-41年）はバロックの動的空間の典型。スフロのパンテオン（パリ、1758-1790年）は新古典主義の代表作。18世紀後半には建築における「様式の相対化」が始まった。",
    westernDetailZh: "波洛米尼的四泉圣卡洛（1638-41年）为巴洛克动态空间的典型。苏弗洛的先贤祠（巴黎，1758-1790年）为新古典主义代表作。18世纪后期建筑的「样式相对化」开始。",
    eastAsianDetail: "日光東照宮（1636年、三代将軍家光による造替）は権現造の極致で、陽明門には150体以上の彫刻が施された。桂離宮（17世紀中頃）は数寄屋造の代表作で、簡素で洗練された空間構成が高く評価されている。",
    eastAsianDetailZh: "日光东照宫（1636年，三代将军家光造替）为权现造极致，阳明门施以150体以上雕刻。桂离宫（17世纪中叶）为数寄屋造代表作，简素而洗练的空间构成获得高度评价。",
    comparison: [
      { dimension: "装飾の方向性", dimensionZh: "装饰的方向性", dimensionEn: "Direction of ornament", western: "バロックの動的装飾→新古典の幾何学的抑制", westernZh: "巴洛克动态装饰→新古典几何学的克制", westernEn: "Dynamic Baroque ornament shifting toward Neoclassical restraint", eastAsian: "権現造の極彩色装飾⇔数寄屋造の簡素の美（二極性）", eastAsianZh: "权现造极彩色装饰⇔数寄屋造简素之美（两极并存）", eastAsianEn: "Rich gongen-zukuri ornament alongside spare sukiya-zukuri beauty" },
      { dimension: "建築理論", dimensionZh: "建筑理论", dimensionEn: "Architectural theory", western: "建築書・美学論の出版が加速（ウィンケルマン、ラスキン等）", westernZh: "建筑书·美学论出版加速（温克尔曼、拉斯金等）", westernEn: "Architectural and aesthetic treatises proliferated, including work by Winckelmann and Ruskin.", eastAsian: "『匠明』等木割書の編纂＋和様の理論化", eastAsianZh: "《匠明》等木割书编纂＋和样理论化", eastAsianEn: "Compilation of kiwari manuals such as Shōmei and the theorization of Japanese-style architecture." },
      { dimension: "庭園と建築", dimensionZh: "庭园与建筑", dimensionEn: "Gardens and architecture", western: "幾何学式庭園（ヴェルサイユ）→風景式庭園（イギリス）", westernZh: "几何式庭园（凡尔赛）→风景式庭园（英国）", westernEn: "A shift from geometric gardens such as Versailles to English landscape gardens.", eastAsian: "回遊式庭園（桂離宮・栗林公園）→建築と庭園の一体化", eastAsianZh: "回游式庭园（桂离宫·栗林公园）→建筑与庭园的一体化", eastAsianEn: "Strolling gardens such as Katsura Imperial Villa and Ritsurin Garden integrated with architecture." },
    ],
    footnote: "18世紀のヨーロッパでは、建築の保存・修復に関する議論が本格化し、後の保存憲章の思想的基礎が形成された。日本では町人文化の成熟が建築にも影響を与えた。",
    footnoteZh: "18世纪欧洲，建筑保存修复的讨论正式化，为后来保存宪章奠定了思想基础。日本町人文化的成熟也影响了建筑。",
    examKeywords: ["ボッロミーニ", "スフロのパンテオン", "日光東照宮", "桂離宮", "権現造・数寄屋造"],
    examKeywordsZh: ["波洛米尼", "苏弗洛先贤祠", "日光东照宫", "桂离宫", "权现造·数寄屋造"],
    relatedCardIds: ["style-baroque", "style-rococo", "style-neoclassical", "style-gongen"],
  },
  {
    id: "19c",
    year: "1850 CE",
    centuryEn: "19th century",
    westernLabelEn: "Industrial Revolution and architectural transformation",
    westernTagsEn: ["Crystal Palace", "Iron and glass", "Art Nouveau"],
    eastAsianLabelEn: "Meiji Restoration",
    eastAsianTagsEn: ["Giyōfū architecture", "Rokumeikan", "Brick construction"],
    westernRegionLabelEn: "Western Europe (Britain, France, and Austria)",
    easternRegionLabelEn: "Japanese archipelago (Meiji)",
    macroTendencyEn: "Western Europe: the Industrial Revolution made iron and glass practical building materials and produced industrial architecture exemplified by the Crystal Palace. Art Nouveau introduced organic curves into architecture, while the Secession marked a transition toward Modernism. Japanese archipelago: the Meiji Restoration brought an active adoption of Western building technology, developing from giyōfū interpretations to fully fledged Western-style architecture.",
    westernDetailEn: "Joseph Paxton’s Crystal Palace (1851) enclosed about 70,000 square metres with an iron-and-glass system. The Eiffel Tower (1889) marked a high point of iron construction. Art Nouveau architects such as Victor Horta and Hector Guimard brought natural curves into architecture.",
    eastAsianDetailEn: "Ōura Cathedral, completed in 1864, is Japan’s oldest surviving church. The Rokumeikan, completed in 1883 to a design by Josiah Conder, was an early landmark of formal Western-style architecture. Giyōfū buildings, including Kaichi School, are distinctive interpretations of Western architecture by Japanese carpenters.",
    footnoteEn: "Under the ideal of wakon yōsai—Japanese spirit, Western technique—Meiji architecture sought to introduce Western technology while retaining Japanese tradition. Giyōfū architecture is a distinctive fusion of Japanese carpentry and Western design.",
    examKeywordsEn: ["Crystal Palace", "Eiffel Tower", "Ōura Cathedral", "Rokumeikan (Conder)", "Giyōfū architecture"],
    century: "19th Century",
    centuryZh: "19世纪",
    westernLabel: "産業革命と建築の変革",
    westernLabelZh: "产业革命与建筑变革",
    westernTags: ["水晶宮", "鉄とガラス", "アールヌーボー"],
    westernTagsZh: ["水晶宫", "铁与玻璃", "新艺术运动"],
    eastAsianLabel: "明治維新",
    eastAsianLabelZh: "明治维新",
    eastAsianTags: ["擬洋風建築", "鹿鳴館", "レンガ造"],
    eastAsianTagsZh: ["拟洋风建筑", "鹿鸣馆", "砖造"],
    westernRegionLabel: "西欧（英・仏・墺）",
    westernRegionLabelZh: "西欧（英·法·奥）",
    easternRegionLabel: "日本列島（明治）",
    easternRegionLabelZh: "日本列岛（明治）",
    macroTendency: "西欧：産業革命により鉄・ガラスが建築材料として実用化され、水晶宮に代表される産業建築が出現。アールヌーボーが自然の曲線を建築に導入し、セセッションがモダニズムへの過渡期を示した。日本列島：明治維新により西洋建築技術を積極的に導入。擬洋風建築から本格的な洋風建築へと展開した。",
    macroTendencyZh: "西欧：产业革命使铁·玻璃作为建筑材料得以实用化，以水晶宫为代表的产业建筑出现。新艺术运动将自然曲线引入建筑，分离派展示向现代主义的过渡。日本列岛：明治维新积极引入西洋建筑技术。从拟洋风建筑向正式洋风建筑展开。",
    westernDetail: "水晶宮（1851年、ジョセフ・パクストン設計）は鉄骨とガラスで約7万㎡を実現。エッフェル塔（1889年）は鉄骨構造の到達点。アールヌーボー（オルタ、ギマール等）は自然の曲線を建築に導入した。",
    westernDetailZh: "水晶宫（1851年，约瑟夫·帕克斯顿设计）以铁骨与玻璃实现约7万㎡。埃菲尔铁塔（1889年）为铁骨构造顶点。新艺术运动（奥塔、吉马尔等）将自然曲线引入建筑。",
    eastAsianDetail: "大浦天主堂（1864年竣工）は日本現存最古の教会堂。鹿鳴館（1883年竣工、コンドル設計）は本格的西洋建築の先駆け。擬洋風建築（開智学校等）は日本の大工が西洋建築を独自に解釈した興味深い事例である。",
    eastAsianDetailZh: "大浦天主堂（1864年竣工）为日本现存最古的教堂。鹿鸣馆（1883年竣工，康德尔设计）为正式西式建筑的先驱。拟洋风建筑（开智学校等）是日本传统工匠独立解释西洋建筑的趣味案例。",
    comparison: [
      { dimension: "建築材料", dimensionZh: "建造材料", dimensionEn: "Building materials", western: "鉄・ガラス・コンクリート（新材料の登場）", westernZh: "铁·玻璃·混凝土（新材料登场）", westernEn: "Iron, glass, and concrete as new materials", eastAsian: "レンガ・石造の導入＋在来の木造", eastAsianZh: "砖造·石造的引入＋传统木造", eastAsianEn: "Brick and stone construction alongside traditional timber" },
      { dimension: "建築思想", dimensionZh: "建筑思想", dimensionEn: "Architectural thought", western: "産業化と芸術の融合（アールヌーボー）＋合理主義", westernZh: "产业化与艺术融合（新艺术运动）＋合理主义", westernEn: "The union of industry and art in Art Nouveau, alongside rationalism.", eastAsian: "和魂洋才の理念（西洋技術＋日本の伝統）", eastAsianZh: "和魂洋才理念（西洋技术＋日本传统）", eastAsianEn: "Wakon yōsai: Western technology combined with Japanese tradition." },
      { dimension: "技術伝播の方向", dimensionZh: "技术传播方向", dimensionEn: "Direction of technical transmission", western: "西欧内部での技術革新と様式展開", westernZh: "西欧内部的技术革新与样式展开", westernEn: "Technical innovation and stylistic development within Western Europe.", eastAsian: "西欧→日本への建築技術・様式の移転", eastAsianZh: "西欧→日本的建筑技术·样式转移", eastAsianEn: "Transfer of Western architectural technology and styles to Japan." },
    ],
    footnote: "明治日本の建築は「和魂洋才」の理念の下、西洋技術を導入しつつ日本の伝統を保持しようとした。擬洋風建築は日本の大工技術と西洋デザインの融合の独自例。",
    footnoteZh: "明治日本建筑在「和魂洋才」理念下，引入西洋技术同时保持日本传统。拟洋风建筑为日本传统工匠技术与西洋设计融合的独特事例。",
    examKeywords: ["水晶宮", "エッフェル塔", "大浦天主堂", "鹿鳴館（コンドル）", "擬洋風建築"],
    examKeywordsZh: ["水晶宫", "埃菲尔铁塔", "大浦天主堂", "鹿鸣馆（康德尔）", "拟洋风建筑"],
    relatedCardIds: ["style-historicism", "style-industrial-iron-glass", "movement-arts-crafts", "style-giyofu", "style-teikan", "style-wayo-secchu", "style-queen-anne", "style-ryugu-mon", "style-obaku"],
  },
  {
    id: "20c-early",
    year: "1920 CE",
    centuryEn: "Early 20th century",
    westernLabelEn: "Birth of Modernist architecture",
    westernTagsEn: ["Le Corbusier", "Walter Gropius", "Bauhaus"],
    eastAsianLabelEn: "Taishō to early Shōwa periods",
    eastAsianTagsEn: ["Imperial Crown Style", "Dōjunkai apartments", "Great Kantō Earthquake"],
    westernRegionLabelEn: "Western Europe (especially Germany and France)",
    easternRegionLabelEn: "Japanese archipelago (Taishō to early Shōwa)",
    macroTendencyEn: "Western Europe: Le Corbusier’s Five Points of a New Architecture were established, and Mies’s maxim “less is more” became a Modernist watchword. The Bauhaus transformed architectural education. Japanese archipelago: the Great Kantō Earthquake of 1923 reshaped standards for earthquake resistance and fireproofing. Imperial Crown Style combined Japanese design motifs with modern structural frames.",
    westernDetailEn: "Le Corbusier’s Five Points are pilotis, the free plan, the free façade, horizontal ribbon windows, and the roof garden. Gropius’s Bauhaus building dates from 1926. Frank Lloyd Wright’s Fallingwater (1935–1939) is a major work of organic architecture.",
    eastAsianDetailEn: "Post-earthquake reconstruction after 1923 emphasized seismic resistance and fireproofing. From the late 1920s, Dōjunkai built reinforced-concrete apartment blocks throughout Japan, helping to disseminate modern urban housing. Imperial Crown Style, seen in works such as the Kanagawa Prefectural Government Building, paired modern structures with Japanese-style roofs.",
    footnoteEn: "Imperial Crown Style was Japan’s distinctive architectural expression of wakon yōsai—Japanese spirit, Western technique. After the Second World War, Modernism spread worldwide as the International Style.",
    examKeywordsEn: ["Five Points of a New Architecture", "Bauhaus", "Fallingwater", "Dōjunkai apartments", "Imperial Crown Style"],
    century: "Early 20th Century",
    centuryZh: "20世纪前半",
    westernLabel: "モダニズム建築の誕生",
    westernLabelZh: "现代主义建筑的诞生",
    westernTags: ["ル・コルビュジェ", "グロピウス", "バウハウス"],
    westernTagsZh: ["勒·柯布西耶", "格罗皮乌斯", "包豪斯"],
    eastAsianLabel: "大正〜昭和初期",
    eastAsianLabelZh: "大正～昭和初期",
    eastAsianTags: ["帝冠様式", "同潤会アパート", "関東大震災"],
    eastAsianTagsZh: ["帝冠样式", "同润会公寓", "关东大地震"],
    westernRegionLabel: "西欧（独・仏を中心）",
    westernRegionLabelZh: "西欧（以德·法为中心）",
    easternRegionLabel: "日本列島（大正〜昭和初期）",
    easternRegionLabelZh: "日本列岛（大正～昭和初期）",
    macroTendency: "西欧：近代建築の五原則（ル・コルビュジェ）が確立され、「less is more」（ミース）がモダニズムの標語となった。バウハウスが建築教育を革新。日本列島：関東大震災（1923年）が耐震・不燃化の建築基準を変革。帝冠様式が近代的躯体に和風の意匠を融合させた。",
    macroTendencyZh: "西欧：近代建筑五原则（柯布西耶）确立，「少即是多」（密斯）成为现代主义口号。包豪斯革新建筑教育。日本列岛：关东大地震（1923年）变革抗震·防火建筑基准。帝冠样式在现代结构上融合和风意匠。",
    westernDetail: "ル・コルビュジェの近代建築の五原則（ピロティ・自由な平面・自由な立面・水平連窓・屋上庭園）。グロピウスのバウハウス校舎（1926年）。落水荘（1935-39年、ライト）はオーガニック建築の代表作。",
    westernDetailZh: "柯布西耶近代建筑五原则（底层架空·自由平面·自由立面·横向长窗·屋顶花园）。格罗皮乌斯包豪斯校舍（1926年）。流水别墅（1935-39年，莱特）为有机建筑代表作。",
    eastAsianDetail: "関東大震災（1923年）後の復興で耐震・不燃化が重視された。同潤会は1920年代後半からRC造集合住宅を各地に建設し、近代的な都市住宅の普及に貢献した。帝冠様式（神奈川県庁舎等）は近代構造に和風屋根を組み合わせた。",
    eastAsianDetailZh: "关东大地震（1923年）后复兴重视抗震与防火。同润会从1920年代后半起建设RC造集合住宅，对近代都市住宅普及做出贡献。帝冠样式（神奈川县厅舍等）将近代结构与和风屋顶结合。",
    comparison: [
      { dimension: "建築原則・思想", dimensionZh: "建筑原则·思想", dimensionEn: "Architectural principles and thought", western: "近代建築の五原則＋合理主義＋工業化", westernZh: "近代建筑五原则＋合理主义＋工业化", westernEn: "Five Points, rationalism, and industrialization", eastAsian: "帝冠様式（和洋折衷）＋耐震構造への関心", eastAsianZh: "帝冠样式（和洋折衷）＋对抗震构造的关注", eastAsianEn: "Imperial Crown Style and earthquake-resistant construction" },
      { dimension: "社会背景", dimensionZh: "社会背景", dimensionEn: "Social context", western: "第一次大戦後の社会改革＋産業化・大量生産", westernZh: "一战后社会改革＋产业化·大量生产", westernEn: "Post-First World War social reform, industrialization, and mass production.", eastAsian: "震災復興＋近代化と伝統継承の両立模索", eastAsianZh: "震灾复兴＋近代化与传统继承并存的探索", eastAsianEn: "Earthquake reconstruction and efforts to reconcile modernization with tradition." },
      { dimension: "建築教育", dimensionZh: "建筑教育", dimensionEn: "Architectural education", western: "バウハウスによる工芸・芸術・建築の統合教育", westernZh: "包豪斯的工艺·艺术·建筑统合教育", westernEn: "Bauhaus integration of craft, art, and architectural education.", eastAsian: "東京美術学校・東京帝国大学での建築教育確立", eastAsianZh: "东京美术学校·东京帝国大学的建筑教育确立", eastAsianEn: "The establishment of architectural education at Tokyo Fine Arts School and Tokyo Imperial University." },
    ],
    footnote: "帝冠様式は「和魂洋才」の理念を建築で表現した日本の独自の様式。モダニズムは第二次大戦後に国際様式として世界的に普及した。",
    footnoteZh: "帝冠样式是以建筑表现「和魂洋才」理念的日本独有样式。现代主义在二战后作为国际样式在世界范围普及。",
    examKeywords: ["近代建築の五原則", "バウハウス", "落水荘", "同潤会アパート", "帝冠様式"],
    examKeywordsZh: ["近代建筑五原则", "包豪斯", "流水别墅", "同润会公寓", "帝冠样式"],
    relatedCardIds: ["movement-art-nouveau", "movement-vienna-secession", "movement-de-stijl", "movement-bauhaus", "movement-constructivism", "movement-modernism", "style-expressionism", "style-art-deco", "style-international", "architect-le-corbusier", "architect-walter-gropius"],
  },
  {
    id: "20c-late",
    year: "1960 CE",
    centuryEn: "Mid-to-late 20th century",
    westernLabelEn: "Maturation and diversification of Modernism",
    westernTagsEn: ["Unité d’Habitation", "High-tech architecture", "Adaptive reuse"],
    eastAsianLabelEn: "Postwar Japanese architecture",
    eastAsianTagsEn: ["Kenzo Tange", "Metabolism", "Yoyogi National Gymnasium"],
    westernRegionLabelEn: "Western Europe and the United States",
    easternRegionLabelEn: "Japanese archipelago (postwar)",
    macroTendencyEn: "Western Europe and the United States: Modernism diversified as high-tech architecture and Postmodernism emerged, while adaptive reuse of existing buildings became a new architectural concern. Japanese archipelago: Kenzo Tange brought Japanese modern architecture to international prominence. Metabolism attracted global attention as a distinctive movement that expressed urban growth and transformation through architecture.",
    westernDetailEn: "Le Corbusier’s Unité d’Habitation in Marseille (1947–1952) was conceived as a “vertical city.” Tate Modern in London (2000), by Herzog & de Meuron, is a prominent adaptive-reuse project that converted a power station into an art museum.",
    eastAsianDetailEn: "Kenzo Tange’s Yoyogi National Gymnasium (1964) is a masterpiece of suspended-roof construction. His St. Mary’s Cathedral, Tokyo (1964), uses a reinforced-concrete shell structure. Kisho Kurokawa’s Nakagin Capsule Tower (1972) was an experimental Metabolist work. Tadao Ando’s Azuma House in Sumiyoshi (1976) proposed an enclosed urban dwelling.",
    footnoteEn: "Metabolism was a postwar Japanese architectural movement that expressed urban growth and transformation through architecture. It was internationally acclaimed and is recognized as an architectural idea originating in Japan.",
    examKeywordsEn: ["Yoyogi National Gymnasium", "Nakagin Capsule Tower", "Metabolism", "Kenzo Tange", "Unité d’Habitation"],
    century: "Mid–Late 20th Century",
    centuryZh: "20世纪中后半",
    westernLabel: "モダニズムの成熟と多様化",
    westernLabelZh: "现代主义的成熟与多样化",
    westernTags: ["ユニテ・ダビタシオン", "ハイテク建築", "アダプティブ・リユース"],
    westernTagsZh: ["马赛公寓", "高技派建筑", "适应性再利用"],
    eastAsianLabel: "戦後日本の建築",
    eastAsianLabelZh: "战后日本建筑",
    eastAsianTags: ["丹下健三", "メタボリズム", "代々木競技場"],
    eastAsianTagsZh: ["丹下健三", "新陈代谢派", "代代木体育馆"],
    westernRegionLabel: "西欧・アメリカ",
    westernRegionLabelZh: "西欧·美国",
    easternRegionLabel: "日本列島（戦後）",
    easternRegionLabelZh: "日本列岛（战后）",
    macroTendency: "西欧・アメリカ：モダニズムが多様化し、ハイテク建築やポストモダンが登場。既存建築の再利用（アダプティブ・リユース）が新たな建築課題となる。日本列島：丹下健三が日本の近代建築を世界的な水準に引き上げた。メタボリズムが都市の成長・変容を建築で表現する独自の運動として国際的に注目された。",
    macroTendencyZh: "西欧·美国：现代主义多样化，高技派建筑和后现代登场。既有建筑的适应性再利用成为新建筑课题。日本列岛：丹下健三将日本近代建筑提升到世界水准。新陈代谢派作为以建筑表现都市成长变容的独立运动，受到国际关注。",
    westernDetail: "ル・コルビュジェのユニテ・ダビタシオン（マルセイユ、1947-52年）は「垂直の都市」。テート・モダン（ロンドン、2000年、ヘルツォーク＆ド・ムーロン）は発電所を美術館に転用したアダプティブ・リユースの代表的事例。",
    westernDetailZh: "柯布西耶的马赛公寓（1947-52年）为「垂直城市」。泰特现代美术馆（伦敦，2000年，赫尔佐格＆德梅隆）为发电站转用为美术馆的适应性再利用代表事例。",
    eastAsianDetail: "代々木競技場（1964年、丹下健三）は吊り屋根構造の傑作。東京カテドラル聖マリア大聖堂（1964年、丹下）はRC殻構造。中銀カプセルタワー（1972年、黒川紀章）はメタボリズム運動の実験作。住吉の長屋（1976年、安藤忠雄）は都市における閉じた住空間を提示した。",
    eastAsianDetailZh: "代代木体育馆（1964年，丹下健三）为悬垂结构杰作。东京圣玛利亚大教堂（1964年，丹下）为RC壳体结构。中银胶囊塔（1972年，黑川纪章）为新陈代谢运动实验作品。住吉长屋（1976年，安藤忠雄）提示了都市中闭合的居住空间。",
    comparison: [
      { dimension: "建築運動", dimensionZh: "建筑运动", dimensionEn: "Architectural movements", western: "ハイテク建築・ポストモダン・脱構築主義", westernZh: "高技派·后现代·解构主义", westernEn: "High-tech architecture, Postmodernism, and Deconstructivism", eastAsian: "メタボリズム＋丹下派＋安藤以降の個人作家", eastAsianZh: "新陈代谢派＋丹下派＋安藤以降的个体建筑师", eastAsianEn: "Metabolism, the Tange school, and individual architects" },
      { dimension: "代表的建築家", dimensionZh: "代表建筑家", dimensionEn: "Representative architects", western: "ル・コルビュジェ・ミース・カーン・ロジャース", westernZh: "柯布西耶·密斯·康·罗杰斯", westernEn: "Le Corbusier, Mies van der Rohe, Louis Kahn, and Richard Rogers.", eastAsian: "丹下健三・安藤忠雄・黒川紀章・磯崎新", eastAsianZh: "丹下健三·安藤忠雄·黑川纪章·矶崎新", eastAsianEn: "Kenzo Tange, Tadao Ando, Kisho Kurokawa, and Arata Isozaki." },
      { dimension: "テーマ", dimensionZh: "主题", dimensionEn: "Themes", western: "工業化と人間性の調和＋既存建築との対話", westernZh: "工业化与人性的调和＋与既有建筑的对话", westernEn: "Reconciling industrialization with human needs and engaging with existing buildings.", eastAsian: "都市の成長・変容の表現＋日本的空間の再解釈", eastAsianZh: "都市成长·变容的表现＋日本式空间的再解释", eastAsianEn: "Expressing urban growth and transformation while reinterpreting Japanese space." },
    ],
    footnote: "メタボリズムは日本の戦後建築運動で、都市の成長・変容を建築で表現した。国際的に高い評価を受け、日本発の建築思想として位置づけられる。",
    footnoteZh: "新陈代谢派为日本战后建筑运动，以建筑表现都市成长·变容。获得国际高度评价，被定位为日本发源的建筑思想。",
    examKeywords: ["代々木競技場", "中銀カプセルタワー", "メタボリズム", "丹下健三", "ユニテ・ダビタシオン"],
    examKeywordsZh: ["代代木体育馆", "中银胶囊塔", "新陈代谢派", "丹下健三", "马赛公寓"],
    relatedCardIds: ["movement-metabolism", "movement-postmodernism", "movement-critical-regionalism", "style-high-tech", "architect-kenzo-tange", "architect-tadao-ando", "architect-kisho-kurokawa"],
  },
];
