"use client";

import Link from "next/link";
import type { TimelineNode } from "@/lib/timeline-data";
import { UI, type TimelineLanguage } from "./timeline-i18n";

interface Building { id: string; nameJa: string; nameZh: string; nameEn: string; examCount: number; region: "western" | "japan" | "unassigned"; period: string; style: string; imageFile: string | null; }
export default function EraComparisonDetail({ node, lang, buildings }: { node: TimelineNode | null; lang: TimelineLanguage; buildings: Building[] }) {
  const labels = UI[lang];
  if (!node) return null;
  const pick = (row: (typeof node.comparison)[number], key: "dimension" | "western" | "eastAsian") => lang === "ja" ? row[key] : lang === "zh" ? row[`${key}Zh`] : row[`${key}En`];
  const region = (side: "western" | "japan") => side === "western" ? (lang === "ja" ? node.westernRegionLabel : lang === "zh" ? node.westernRegionLabelZh : node.westernRegionLabelEn) : (lang === "ja" ? node.easternRegionLabel : lang === "zh" ? node.easternRegionLabelZh : node.easternRegionLabelEn);
  const detail = (side: "western" | "japan") => side === "western" ? (lang === "ja" ? node.westernDetail : lang === "zh" ? node.westernDetailZh : node.westernDetailEn) : (lang === "ja" ? node.eastAsianDetail : lang === "zh" ? node.eastAsianDetailZh : node.eastAsianDetailEn);
  return <div className="space-y-6"><section><h3 className="mb-2 text-xs font-bold text-violet-700">{labels.details}</h3><p className="rounded-lg bg-violet-50 p-3 text-[11px] leading-relaxed text-gray-700">{lang === "ja" ? node.macroTendency : lang === "zh" ? node.macroTendencyZh : node.macroTendencyEn}</p></section>
    <section><h3 className="mb-2 text-xs font-bold text-violet-700">{labels.comparison}</h3><div className="overflow-x-auto rounded-lg border border-gray-200"><table className="w-full min-w-[560px] text-left text-[10px]"><thead className="bg-gray-50"><tr><th className="p-2">{labels.architecture}</th><th className="p-2 text-sky-700">{region("western")}</th><th className="p-2 text-amber-700">{region("japan")}</th></tr></thead><tbody>{node.comparison.map((row) => <tr key={row.dimensionEn} className="border-t"><th className="p-2 font-medium text-gray-700">{pick(row, "dimension")}</th><td className="p-2 leading-relaxed">{pick(row, "western")}</td><td className="p-2 leading-relaxed">{pick(row, "eastAsian")}</td></tr>)}</tbody></table></div></section>
    <section className="grid gap-3 md:grid-cols-2">{(["western", "japan"] as const).map((side) => <article key={side} className="rounded-lg border border-gray-200 p-3"><h3 className="mb-2 text-xs font-bold text-gray-800">{region(side)}</h3><p className="text-[11px] leading-relaxed text-gray-700">{detail(side)}</p></article>)}</section>
    <section><h3 className="mb-2 text-xs font-bold text-violet-700">{labels.buildings}</h3><div className="grid gap-2 sm:grid-cols-2">{buildings.filter((building) => building.region !== "unassigned").map((building) => { const name = lang === "en" ? building.nameEn : lang === "zh" ? building.nameZh : building.nameJa; return <Link key={building.id} href={`/history/buildings/${building.id}?from=timeline&era=${encodeURIComponent(node.id)}`} aria-label={`${name} — ${labels.details}`} className="group overflow-hidden rounded-lg border border-gray-200 transition hover:-translate-y-0.5 hover:border-violet-300 hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-500"><div className="aspect-video bg-gray-100">{building.imageFile ? <img src={`/architecture-images/${building.imageFile}`} alt={name} className="h-full w-full object-cover transition group-hover:scale-[1.02]" loading="lazy" /> : <div className="flex h-full items-center justify-center text-[10px] text-gray-400">{labels.imageUnavailable}</div>}</div><div className="p-2"><p className="text-[10px] font-medium text-gray-700 group-hover:text-violet-700">{name}</p>{building.period && <p className="mt-0.5 text-[9px] text-gray-400">{building.period}</p>}</div></Link>; })}</div>{buildings.length === 0 && <p className="rounded-lg border border-dashed p-3 text-[10px] text-gray-500">{labels.noBuildings}</p>}</section>
    <section><h3 className="mb-2 text-xs font-bold text-violet-700">{labels.notes}</h3><p className="rounded-lg bg-gray-50 p-3 text-[10px] italic text-gray-600">{lang === "ja" ? node.footnote : lang === "zh" ? node.footnoteZh : node.footnoteEn}</p></section>
  </div>;
}
