"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { SidebarLayout } from "@/components/layout";
import type { LightPracticeQuestion } from "@/lib/light-practice";
import type { KnowledgeCoverageItem, SubjectCoverageItem } from "@/lib/knowledge-coverage";
import type { AssessmentDraft } from "@/lib/assessment-drafts";

const notionSources = [
  { subject: "建筑史", title: "建築歴史カード（已完成）", status: "已接入", url: "https://app.notion.com/p/118e961e469080ff9a0bca950748804e" },
  { subject: "建筑计划", title: "建築計画（已整理）", status: "已接入", url: "https://app.notion.com/p/106e961e4690807b9036d31dccd62d28" },
  { subject: "建筑环境工学", title: "环境工学（已整理完）", status: "已接入", url: "https://app.notion.com/p/34be961e469080aea0bfd40049388b76" },
  { subject: "建筑构法", title: "建築構法（进行中）", status: "整理中", url: "https://app.notion.com/p/382e961e469080fa86c8c5836b44ed6b" },
];
const CANDIDATE_QUEUE_KEY = "assessment-candidate-queue-v1";

export default function AssessmentClient({ units, ankiCoverage, planningCoverage, environmentCoverage, constructionDrafts }: { units: LightPracticeQuestion[]; ankiCoverage: KnowledgeCoverageItem[]; planningCoverage: SubjectCoverageItem[]; environmentCoverage: SubjectCoverageItem[]; constructionDrafts: AssessmentDraft[] }) {
  const [subject, setSubject] = useState("全部");
  const [form, setForm] = useState("全部");
  const [query, setQuery] = useState("");
  const [candidateQueue, setCandidateQueue] = useState<string[]>([]);
  useEffect(() => {
    queueMicrotask(() => {
      try { setCandidateQueue(JSON.parse(window.localStorage.getItem(CANDIDATE_QUEUE_KEY) ?? "[]") as string[]); } catch { setCandidateQueue([]); }
    });
  }, []);
  const toggleCandidate = (id: string) => {
    const next = candidateQueue.includes(id) ? candidateQueue.filter((value) => value !== id) : [...candidateQueue, id];
    setCandidateQueue(next);
    window.localStorage.setItem(CANDIDATE_QUEUE_KEY, JSON.stringify(next));
  };
  const subjects = ["全部", ...new Set(units.map((unit) => unit.subject))];
  const forms = ["全部", ...new Set(units.map((unit) => unit.assessmentForm))];
  const visible = units.filter((unit) => (subject === "全部" || unit.subject === subject) && (form === "全部" || unit.assessmentForm === form) && `${unit.prompt} ${unit.answer}`.toLowerCase().includes(query.toLowerCase()));
  const counts = Object.fromEntries(subjects.slice(1).map((value) => [value, units.filter((unit) => unit.subject === value).length]));
  const ankiGaps = ankiCoverage.filter((item) => item.status === "只有记忆卡");
  const ankiCovered = ankiCoverage.length - ankiGaps.length;
  const planningGaps = planningCoverage.filter((item) => item.status === "只有知识材料");
  const environmentGaps = environmentCoverage.filter((item) => item.status === "只有知识材料");

  return <SidebarLayout><main className="min-h-full bg-slate-50 px-5 py-8 sm:px-8"><div className="mx-auto max-w-6xl">
    <header><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold tracking-[0.18em] text-cyan-700">可考查知识层</p><h1 className="mt-2 text-3xl font-bold text-slate-950">考查单元库</h1><p className="mt-3 max-w-3xl leading-7 text-slate-600">这里不是另一套笔记，而是连接真题、Notion 与 Anki 的中间层。当前题目全部来自拆分真题；以后生成的变式和模拟题会使用不同标签。</p></div><Link href="/assessment/drafts" className="rounded-2xl border border-cyan-200 bg-white px-4 py-3 text-right hover:border-fuchsia-300"><p className="text-xs text-slate-500">待出题候选</p><p className="mt-1 text-2xl font-bold text-cyan-700">{candidateQueue.length}</p><p className="mt-1 text-[11px] font-semibold text-fuchsia-700">进入出题工作台 →</p></Link></div></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(counts).map(([name, count]) => <div key={name} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-sm text-slate-500">{name === "建筑环境工学" ? "环境工学" : name}</p><p className="mt-2 text-2xl font-bold text-slate-900">{count}</p><p className="text-xs text-emerald-700">已核验真题小问</p></div>)}</section>
    <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-slate-900">知识来源覆盖</h2><p className="mt-1 text-sm text-slate-500">Notion 提供完整知识，Anki 提供记忆提取；未转换内容不会被标成真题。</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">Anki：350 条已审计卡片</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{notionSources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-100 bg-slate-50 p-3 hover:border-cyan-200"><div className="flex justify-between gap-3"><div><p className="text-xs text-slate-400">Notion · {source.subject}</p><p className="mt-1 text-sm font-semibold text-slate-800">{source.title}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[11px] ${source.status === "已接入" ? "bg-cyan-100 text-cyan-700" : "bg-amber-100 text-amber-700"}`}>{source.status}</span></div></a>)}</div></section>
    <section className="mt-8 rounded-3xl border border-amber-200 bg-amber-50/40 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold tracking-[0.16em] text-amber-700">ANKI → 考查形式</p><h2 className="mt-1 text-xl font-bold text-slate-900">建筑史记忆卡缺口队列</h2><p className="mt-2 text-sm text-slate-600">用卡片名称与真题小问题干、答案做保守的直接匹配；没有匹配到的只列为候选，不代表一定从未考过。</p></div><div className="flex gap-2 text-xs"><span className="rounded-full bg-emerald-100 px-3 py-1 text-emerald-700">已匹配 {ankiCovered}</span><span className="rounded-full bg-amber-100 px-3 py-1 text-amber-800">待转换 {ankiGaps.length}</span></div></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{ankiGaps.slice(0, 30).map((item) => { const queueId = `anki:${item.id}`; return <article key={item.id} className="rounded-xl border border-amber-100 bg-white p-3"><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-bold text-slate-800">{item.name}</h3>{item.needsReview && <span className="shrink-0 rounded bg-rose-50 px-1.5 py-0.5 text-[10px] text-rose-600">资料待核</span>}</div><p className="mt-1 text-[11px] text-slate-400">{item.deck.replace("东大建筑史::", "")}</p><div className="mt-3 flex flex-wrap gap-1">{item.suggestedForms.map((value) => <span key={value} className="rounded bg-cyan-50 px-2 py-1 text-[10px] text-cyan-700">可做：{value}</span>)}</div><button onClick={() => toggleCandidate(queueId)} className={`mt-3 rounded-full px-3 py-1 text-[11px] font-semibold ${candidateQueue.includes(queueId) ? "bg-emerald-100 text-emerald-700" : "border border-slate-200 text-slate-500"}`}>{candidateQueue.includes(queueId) ? "✓ 已纳入出题队列" : "+ 纳入出题队列"}</button></article>; })}</div>{ankiGaps.length > 30 && <p className="mt-4 text-center text-xs text-slate-400">先展示优先级较高的 30 项；完整队列保留在覆盖数据中。</p>}
    </section>
    <section className="mt-8 grid gap-5 lg:grid-cols-2">{[
      { title: "建筑计划知识卡缺口", note: "依据已审计的 337 张计划知识卡与 155 条真题关联。", gaps: planningGaps, total: planningCoverage.length, color: "violet" },
      { title: "环境工学公式缺口", note: "公式只在能直接匹配题干或答案时才算已有真题关联；主题年份仅作参考。", gaps: environmentGaps, total: environmentCoverage.length, color: "cyan" },
    ].map((section) => <div key={section.title} className="rounded-3xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">{section.title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{section.note}</p></div><span className="shrink-0 rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">{section.gaps.length} / {section.total} 待转换</span></div><div className="mt-4 space-y-2">{section.gaps.slice(0, 20).map((item) => { const queueId = `${item.subject}:${item.id}`; return <article key={item.id} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><div className="flex items-start justify-between gap-2"><div><h3 className="text-sm font-semibold text-slate-800">{item.name}</h3><p className="mt-1 text-[11px] text-slate-400">{item.group}{item.sourceYears?.length ? ` · 真题主题年份 ${item.sourceYears.join("/")}` : ""}</p></div><span className={`shrink-0 rounded px-2 py-1 text-[10px] ${section.color === "violet" ? "bg-violet-100 text-violet-700" : "bg-cyan-100 text-cyan-700"}`}>{item.suggestedForms[0]}</span></div><button onClick={() => toggleCandidate(queueId)} className={`mt-2 rounded-full px-3 py-1 text-[11px] font-semibold ${candidateQueue.includes(queueId) ? "bg-emerald-100 text-emerald-700" : "border border-slate-200 bg-white text-slate-500"}`}>{candidateQueue.includes(queueId) ? "✓ 已纳入出题队列" : "+ 纳入出题队列"}</button></article>; })}</div>{section.gaps.length > 20 && <p className="mt-3 text-center text-xs text-slate-400">显示前 20 项</p>}</div>)}
    </section>
    <section className="mt-8 rounded-3xl border border-orange-200 bg-orange-50/40 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold tracking-[0.16em] text-orange-700">构法真题 → 同型变式</p><h2 className="mt-1 text-xl font-bold text-slate-900">构法术语四选一候选</h2><p className="mt-2 text-sm text-slate-600">只使用已核对的短答案小问，把原来的术语填空改成四选一；图解、施工顺序和长论述不自动改写。</p></div><span className="rounded-full bg-white px-3 py-1 text-xs text-orange-700">{constructionDrafts.length} 个候选</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{constructionDrafts.slice(0, 30).map((draft) => { const queueId = draft.id; return <article key={draft.id} className="rounded-xl border border-orange-100 bg-white p-3"><h3 className="text-sm font-semibold text-slate-800">{draft.knowledgeName}</h3><p className="mt-2 text-[11px] text-slate-400">{draft.evidence}</p><button onClick={() => toggleCandidate(queueId)} className={`mt-3 rounded-full px-3 py-1 text-[11px] font-semibold ${candidateQueue.includes(queueId) ? "bg-emerald-100 text-emerald-700" : "border border-slate-200 text-slate-500"}`}>{candidateQueue.includes(queueId) ? "✓ 已纳入出题队列" : "+ 纳入出题队列"}</button></article>; })}</div>{constructionDrafts.length > 30 && <p className="mt-4 text-center text-xs text-slate-400">优先显示前 30 项</p>}</section>
    <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-xl font-bold text-slate-900">已建立的考查单元</h2><p className="mt-1 text-sm text-slate-500">来源标签固定为“真题”；题型与能力层级用于以后组卷。</p></div><Link href="/practice/light" className="rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white">进入轻量练习 →</Link></div>
      <div className="mt-4 flex flex-wrap gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索题干或答案" className="min-w-56 flex-1 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"/><select value={subject} onChange={(event) => setSubject(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm">{subjects.map((value) => <option key={value}>{value}</option>)}</select><select value={form} onChange={(event) => setForm(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm">{forms.map((value) => <option key={value}>{value}</option>)}</select></div>
      <p className="mt-3 text-xs text-slate-400">显示 {visible.length} / {units.length} 个单元</p><div className="mt-3 space-y-3">{visible.slice(0, 80).map((unit) => <article key={unit.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap gap-2 text-[11px]"><span className="rounded bg-emerald-100 px-2 py-1 font-semibold text-emerald-700">真题 · {unit.year}</span><span className="rounded bg-cyan-50 px-2 py-1 text-cyan-700">{unit.assessmentForm}</span><span className="rounded bg-violet-50 px-2 py-1 text-violet-700">{unit.skillLevel}</span><span className="px-1 py-1 text-slate-400">{unit.subject}</span></div><p className="mt-3 line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-slate-700">{unit.prompt}</p><details className="mt-3 text-sm"><summary className="cursor-pointer font-medium text-emerald-700">查看标准答案</summary><p className="mt-2 whitespace-pre-wrap rounded-xl bg-emerald-50 p-3 leading-6 text-slate-700">{unit.answer}</p></details></article>)}</div>{visible.length > 80 && <p className="mt-4 text-center text-sm text-slate-400">为保持页面轻量，当前显示前 80 项；可通过筛选缩小范围。</p>}
    </section>
  </div></main></SidebarLayout>;
}
