import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import LearningShell from "../../../_components/LearningShell";
import { getMechanicsQuestion, mechanicsQuestions } from "@/lib/structural-learning";

export function generateStaticParams() { return mechanicsQuestions.map((question) => ({ slug: question.slug })); }

export default async function JapaneseQuestionPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const question = getMechanicsQuestion(slug); if (!question) notFound();
  return <LearningShell locale="ja"><div className="min-h-full bg-[#f7f8f6] text-slate-900" lang="ja">
    <header className="sticky top-0 z-20 border-b border-slate-200/80 bg-[#f7f8f6]/90 px-4 py-3 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><div className="flex items-center gap-2 text-xs text-slate-500"><Link href="/structural-learning" className="hover:text-slate-950">構造力学</Link><span>/</span><span className="font-medium text-slate-800">問題 {question.number}</span></div><div className="flex rounded-xl border border-slate-200 bg-white p-1 text-xs font-semibold shadow-sm"><Link href={`/structural-learning/questions/${slug}`} className="rounded-lg px-3 py-1.5 text-slate-500 hover:bg-slate-100">中文解析</Link><span className="rounded-lg bg-slate-950 px-3 py-1.5 text-white">日本語</span></div></div></header>
    <main className="mx-auto max-w-6xl px-4 py-8 sm:px-8 sm:py-12">
      <section className="border-b border-slate-200 pb-10"><div className="flex flex-wrap items-center gap-3"><span className="font-mono text-sm font-semibold text-slate-400">QUESTION {question.number}</span><span className="rounded-full border border-slate-200 bg-white px-3 py-1 text-[11px] font-semibold text-slate-600">{question.scale}</span></div><h1 className="mt-5 text-3xl font-bold tracking-[-0.03em] text-slate-950 sm:text-5xl">{question.titleJa}</h1><p className="mt-3 text-sm text-slate-500 sm:text-base">{question.subtitleJa}</p><div className="mt-7 max-w-4xl border-l-2 border-slate-950 pl-5"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-400">この問題の本質</p><p className="mt-2 text-lg font-medium leading-8 text-slate-800">{question.coreQuestionJa}</p></div></section>
      <section className="py-10"><div className="mb-5"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400">01 · ORIGINAL QUESTION</p><h2 className="mt-2 text-2xl font-bold text-slate-950">原問題</h2></div><a href={question.originalImage} target="_blank" rel="noreferrer" className="block overflow-hidden rounded-3xl border border-slate-200 bg-white p-2"><Image src={question.originalImage} alt={`${question.titleJa}の原問題`} width={1429} height={2021} priority unoptimized className="h-auto w-full rounded-2xl" /></a></section>
      <section className="pb-12"><div className="mb-6"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400">02 · STEP-BY-STEP SOLUTION</p><h2 className="mt-2 text-2xl font-bold text-slate-950">設問ごとの解法</h2><p className="mt-3 text-sm leading-6 text-slate-500">判断の根拠、計算の流れ、試験答案に使える文章をまとめています。</p></div><div className="space-y-4">{question.subproblems.map((part, index) => <details key={part.id} open={index===0} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white"><summary className="flex cursor-pointer list-none items-center gap-4 px-5 py-5 sm:px-7"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-950 font-mono text-xs font-bold text-white">{part.id}</span><h3 className="min-w-0 flex-1 text-base font-bold text-slate-900 sm:text-lg">{part.titleJa}</h3><span className="text-xl text-slate-300 transition group-open:rotate-45">＋</span></summary><div className="border-t border-slate-100 px-5 py-6 sm:px-7 sm:py-8">
          <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">設問</p><p className="mt-2 text-sm leading-7 text-slate-700">{part.japanese.task}</p></div><div className="rounded-2xl bg-blue-50 p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-blue-600">解法の入口</p><p className="mt-2 text-sm leading-7 text-slate-700">{part.japanese.approach}</p></div></div>
          <div className="mt-6 rounded-2xl border border-slate-200 p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">計算式</p><div className="mt-3 space-y-3">{part.steps.filter(step=>step.formula).map(step => <div key={step.label} className="overflow-x-auto rounded-xl bg-slate-950 px-4 py-3 font-mono text-sm font-semibold leading-6 text-white">{step.formula}</div>)}</div></div>
          <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-emerald-700">答</p><p className="mt-2 text-sm font-bold leading-7">{part.japanese.answer}</p></div><div className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-violet-700">答案用の表現</p><p className="mt-2 text-sm leading-7 text-slate-700">{part.japanese.examText}</p></div></div>
        </div></details>)}</div></section>
    </main>
  </div></LearningShell>;
}
